### PR TITLE
tools: cosmetic changes (comments, typo, ...)

### PR DESCRIPTION
**Pull request by mcoolive**
- Add comments in CONTRIBUTING.md
- Fix a typo in the groupId of the reactor pom
- Add project and env info to the Maven poms

---
This change is [Reviewable](https://reviewable.io/reviews/criteo/biggraphite/182)

### CODE REVIEW

**Comment by dpanth3r** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/182#-:-KWpnImonkB7xRTi6x4v:bnfp4nl)*

**Comment by iksaif** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[pom.xml, line 41 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/182#-KWqgfLJgkMcu3GMyOCO:-KWqgfLK5U_5wbRNub73:b-hg4cnr) ([raw file](https://github.com/criteo/biggraphite/blob/2f4e2e28426e8613ea8747ef298e96e14ca22d91/pom.xml#L41)):*
> ```XML
>     <organization>
>       <name>Criteo</name>
>       <url>http://www.criteo.com</url>
> ```

https://github.com/criteo

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/182)*

**Comment by iksaif** [comment]
:lgtm_strong: 

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/182#-:-KWqgkJ-SxrNPUB2jLpX:b-uwkowd)*

**Comment by mcoolive** [comment]
*[pom.xml, line 41 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/182#-KWqgfLJgkMcu3GMyOCO:-KWsAkQr3UEgthwdJNUT:buu1afb) ([raw file](https://github.com/criteo/biggraphite/blob/2f4e2e28426e8613ea8747ef298e96e14ca22d91/pom.xml#L41)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> https://github.com/criteo
</details>
I amend my commit to include "https://github.com/criteo" as organization URL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/182)*

**Comment by mcoolive** [comment]
*[pom.xml, line 41 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/182#-KWqgfLJgkMcu3GMyOCO:-KWs_HQgLXWWP6Y_LIwO:b-896fix) ([raw file](https://github.com/criteo/biggraphite/blob/2f4e2e28426e8613ea8747ef298e96e14ca22d91/pom.xml#L41)):*
<details><summary><i>Previously, mcoolive (Cyril Martin) wrote…</i></summary>
> I amend my commit to include "https://github.com/criteo" as organization URL.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/182)*

**Pull request merged**
