### PR TITLE
Return current aggregates in Downsampler.feed

### PR DESCRIPTION
**Pull request by natbraun**
This change is [Reviewable](https://reviewable.io/reviews/criteo/biggraphite/66)

### CODE REVIEW

**Comment by unbrice** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[biggraphite/drivers/_downsampling.py, line 106 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/66#-KNl79B1IfPD_5e-fzBr:-KNl79B1IfPD_5e-fzBs:1110529159) ([raw file](https://github.com/criteo/biggraphite/blob/57d729567cb129f15adc87d7e6f3259a14451f22/biggraphite/drivers/_downsampling.py#L106)):*
>           precision: precision
probably precision should be retention as you are reimplementing stage.round_down, stage.epoch...

---

*[biggraphite/drivers/_downsampling.py, line 155 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/66#-KNl6s4k730BPoEl1-Vf:-KNl6s4k730BPoEl1-Vg:703267013) ([raw file](https://github.com/criteo/biggraphite/blob/57d729567cb129f15adc87d7e6f3259a14451f22/biggraphite/drivers/_downsampling.py#L155)):*
> ```Python
>         # Second, append current (not expired) points to the result.
>         not_expired = []
>         start_epoch = self._raw_timestamp // precision - (self._raw_capacity - 1)
> ```

I think "- raw_capacity" shuldn't  be here. Also see above comment on reimplementing stage.epoch()

---

*[biggraphite/drivers/_downsampling.py, line 162 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/66#-KNl6RigI8zSDmNT2bTV:-KNl6RigI8zSDmNT2bTW:1343975547) ([raw file](https://github.com/criteo/biggraphite/blob/57d729567cb129f15adc87d7e6f3259a14451f22/biggraphite/drivers/_downsampling.py#L162)):*
> ```Python
>                 not_expired.append((epoch * precision, self._values[index], False))
> 
>         return expired + not_expired
> ```

I suggest you make a new method returning current points: two smaller methods is better than one method with two results

---

*[biggraphite/drivers/_downsampling.py, line 219 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/66#-KNl7dEC_aNSh2jo6OqD:-KNl7dEDVO3bPRavc1D2:895060630) ([raw file](https://github.com/criteo/biggraphite/blob/57d729567cb129f15adc87d7e6f3259a14451f22/biggraphite/drivers/_downsampling.py#L219)):*
> ```Python
>             if expired:
>                 # Point is expired => update count of expired points.
>                 expired_count = len(result)
> ```

I'd expect expired_count += 1

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/66)*

**Comment by unbrice** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[tests/test_drivers_downsampling.py, line 101 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/66#-KNl8X4kLVoJF_AVvni7:-KNl8X4kLVoJF_AVvni8:1167354130) ([raw file](https://github.com/criteo/biggraphite/blob/57d729567cb129f15adc87d7e6f3259a14451f22/tests/test_drivers_downsampling.py#L101)):*
> ```Python
>         """Test feeding points out of order."""
>         points = [
>             (self.PRECISION ** 2 + 1, 42),  # Overrides next point once sorted.
> ```

Does this mean we'll do write 1 point more (30% more writes)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/66)*

**Comment by unbrice** [comment]
Mostly good to me :-) Thanks! Just a few more comments.

---

Review status: 1 of 2 files reviewed at latest revision, 11 unresolved discussions.

---

*[biggraphite/drivers/_downsampling.py, line 102 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/66#-KNlnQY6PauiMYva6RyJ:-KNlnPEy3TGp6iQOSD6w:1151590820) ([raw file](https://github.com/criteo/biggraphite/blob/75314654403db1986628bfd43f762508be0e9ae9/biggraphite/drivers/_downsampling.py#L102)):*
> raw points in raw buffer

just "raw points"

---

*[biggraphite/drivers/_downsampling.py, line 105 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/66#-KNlnY1s4KcSrIFPWH0I:-KNlnY1s4KcSrIFPWH0J:-1410952539) ([raw file](https://github.com/criteo/biggraphite/blob/75314654403db1986628bfd43f762508be0e9ae9/biggraphite/drivers/_downsampling.py#L105)):*
> ```Python
> 
>         Args:
>           precision: precision of the raw buffer in seconds.
> ```

I suggest passing a MetricMetadata

---

*[biggraphite/drivers/_downsampling.py, line 114 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/66#-KNlnxjtJCvWwZAcWop-:-KNlnxjupCdr1t94XuF1:-60621835) ([raw file](https://github.com/criteo/biggraphite/blob/75314654403db1986628bfd43f762508be0e9ae9/biggraphite/drivers/_downsampling.py#L114)):*
> ```Python
>             return []
> 
>         non_expired = []
> ```

I suggest result

---

*[biggraphite/drivers/_downsampling.py, line 115 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/66#-KNlniJetf2G5r7Jj6zx:-KNlniJetf2G5r7Jj6zy:-160375422) ([raw file](https://github.com/criteo/biggraphite/blob/75314654403db1986628bfd43f762508be0e9ae9/biggraphite/drivers/_downsampling.py#L115)):*
> ```Python
> 
>         non_expired = []
>         start_epoch = self._raw_timestamp // precision - (self._raw_capacity - 1)
> ```

if you pass in retention instead of precision, you'll be able to do retention[0].epoch

---

*[biggraphite/drivers/_downsampling.py, line 124 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/66#-KNloICYpLu6ZwhfNR0L:-KNloICYpLu6ZwhfNR0M:-1501134351) ([raw file](https://github.com/criteo/biggraphite/blob/75314654403db1986628bfd43f762508be0e9ae9/biggraphite/drivers/_downsampling.py#L124)):*
> ```Python
>         return non_expired
> 
>     def _get_expired_raw_points(self, points, precision):
> ```

I suggest _update_raw as it does more than getting data but instead updates the raw data

---

*[biggraphite/drivers/_downsampling.py, line 177 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/66#-KNlocNAG3254wLMHw-N:-KNlocNAG3254wLMHw-O:-994577487) ([raw file](https://github.com/criteo/biggraphite/blob/75314654403db1986628bfd43f762508be0e9ae9/biggraphite/drivers/_downsampling.py#L177)):*
> ```Python
>         return expired
> 
>     def _get_raw_points(self, points, precision):
> ```

Why did you rename it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/66#-:-KNlov6VlaC_iSc9aiKx:-2143240835)*

**Comment by iksaif** [comment]
ping ? I need this for https://github.com/criteo/biggraphite/pull/78

**Comment by natbraun** [comment]
Review status: 0 of 2 files reviewed at latest revision, 11 unresolved discussions.

---

*[biggraphite/drivers/_downsampling.py, line 102 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/66#-KNlnQY6PauiMYva6RyJ:-KPmENOK2FZDtzjH2lUc:b-896fix) ([raw file](https://github.com/criteo/biggraphite/blob/75314654403db1986628bfd43f762508be0e9ae9/biggraphite/drivers/_downsampling.py#L102)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> > raw points in raw buffer
> 
> just "raw points"
</details>
Done.

---

*[biggraphite/drivers/_downsampling.py, line 105 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/66#-KNlnY1s4KcSrIFPWH0I:-KNpju9zX8a9M3ASYqvQ:bpnn17x) ([raw file](https://github.com/criteo/biggraphite/blob/75314654403db1986628bfd43f762508be0e9ae9/biggraphite/drivers/_downsampling.py#L105)):*
> retention
I'll go with retention

---

*[biggraphite/drivers/_downsampling.py, line 114 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/66#-KNlnxjtJCvWwZAcWop-:-KPmEQD1x0sr4IoVknC4:b-896fix) ([raw file](https://github.com/criteo/biggraphite/blob/75314654403db1986628bfd43f762508be0e9ae9/biggraphite/drivers/_downsampling.py#L114)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> I suggest result
</details>
Done.

---

*[biggraphite/drivers/_downsampling.py, line 115 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/66#-KNlniJetf2G5r7Jj6zx:-KNpprh4Opy4SVNDRllg:b-896fix) ([raw file](https://github.com/criteo/biggraphite/blob/75314654403db1986628bfd43f762508be0e9ae9/biggraphite/drivers/_downsampling.py#L115)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> if you pass in retention instead of precision, you'll be able to do retention[0].epoch
</details>
Done.

---

*[biggraphite/drivers/_downsampling.py, line 124 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/66#-KNloICYpLu6ZwhfNR0L:-KPmEa9ntHoGXAaiqf0-:b-896fix) ([raw file](https://github.com/criteo/biggraphite/blob/75314654403db1986628bfd43f762508be0e9ae9/biggraphite/drivers/_downsampling.py#L124)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> I suggest _update_raw as it does more than getting data but instead updates the raw data
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/66)*

**Comment by iksaif** [comment]
Review status: 0 of 2 files reviewed at latest revision, 18 unresolved discussions.

---

*[biggraphite/drivers/_downsampling.py, line 104 \[r3\]](https://reviewable.io:443/reviews/criteo/biggraphite/66#-KPmvZwmt6Ff4V3ecqaT:-KPmvZwmt6Ff4V3ecqaU:bxtm4i7) ([raw file](https://github.com/criteo/biggraphite/blob/a3ad71e3cd3bef817f8ed8aca99a30071202b676/biggraphite/drivers/_downsampling.py#L104)):*
> ```Python
>         Args:
>           points: iterable of (timestamp, value).
>           rentention: Retention object.
> ```

typo: retention

---

*[biggraphite/drivers/_downsampling.py, line 165 \[r3\]](https://reviewable.io:443/reviews/criteo/biggraphite/66#-KPmx7WjKsf_Tub_C3p4:-KPmx7WjKsf_Tub_C3p5:b-k3un5a) ([raw file](https://github.com/criteo/biggraphite/blob/a3ad71e3cd3bef817f8ed8aca99a30071202b676/biggraphite/drivers/_downsampling.py#L165)):*
> ```Python
> 
>         result = []
>         stage_0 = retention[0]
> ```

this code isn't easy to read. please add a few comments.

---

*[biggraphite/drivers/_downsampling.py, line 190 \[r3\]](https://reviewable.io:443/reviews/criteo/biggraphite/66#-KPmy3o4gUcQgcLS14lA:-KPmy3o4gUcQgcLS14lB:bjxn40t) ([raw file](https://github.com/criteo/biggraphite/blob/a3ad71e3cd3bef817f8ed8aca99a30071202b676/biggraphite/drivers/_downsampling.py#L190)):*
> ```Python
>         return (expired, non_expired)
> 
>     def _coalesce(self, stage, metric_metadata, result, points):
> ```

_merge ?

---

*[biggraphite/drivers/_downsampling.py, line 237 \[r3\]](https://reviewable.io:443/reviews/criteo/biggraphite/66#-KPmxHpD2En4Zg3VJVuV:-KPmxHpD2En4Zg3VJVuW:b-k3un5a) ([raw file](https://github.com/criteo/biggraphite/blob/a3ad71e3cd3bef817f8ed8aca99a30071202b676/biggraphite/drivers/_downsampling.py#L237)):*
> ```Python
>         stage = stages[stage_index]
>         precision = stage.precision
> ```

this code isn't easy to read. please add a few comments.

---

*[biggraphite/drivers/_downsampling.py, line 253 \[r3\]](https://reviewable.io:443/reviews/criteo/biggraphite/66#-KPmxJKTTOgB5qUYMXr2:-KPmxJKTTOgB5qUYMXr3:b-k3un5a) ([raw file](https://github.com/criteo/biggraphite/blob/a3ad71e3cd3bef817f8ed8aca99a30071202b676/biggraphite/drivers/_downsampling.py#L253)):*
> ```Python
>             first_timestamp = first_step * precision
>             current_timestamp = first_timestamp
> ```

this code isn't easy to read. please add a few comments.

---

*[tests/test_drivers_downsampling.py, line 68 \[r3\]](https://reviewable.io:443/reviews/criteo/biggraphite/66#-KPmyZ7yMLMqBWUOo9aw:-KPmyZ7yMLMqBWUOo9ax:bju6xhz) ([raw file](https://github.com/criteo/biggraphite/blob/a3ad71e3cd3bef817f8ed8aca99a30071202b676/tests/test_drivers_downsampling.py#L68)):*
> ```Python
>         ]
>         result = self.ds.feed(self.metric, points)
>         print(self.ds._names_to_aggregates[self.METRIC_NAME]._values)
> ```

remove print()

---

*[tests/test_drivers_downsampling.py, line 97 \[r3\]](https://reviewable.io:443/reviews/criteo/biggraphite/66#-KPmylc9vsiTOLoHzF7j:-KPmylc9vsiTOLoHzF7k:b-3gtz1u) ([raw file](https://github.com/criteo/biggraphite/blob/a3ad71e3cd3bef817f8ed8aca99a30071202b676/tests/test_drivers_downsampling.py#L97)):*
> ```Python
>         ]
>         expected = expected_stage_0 + expected_stage_1
>         result = self.ds.feed(self.metric, points)
> ```

maybe call feed a second time here without adding new points, and a third time adding only one point.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/66)*

**Comment by natbraun** [comment]
Review status: 0 of 2 files reviewed at latest revision, 18 unresolved discussions.

---

*[biggraphite/drivers/_downsampling.py, line 104 \[r3\]](https://reviewable.io:443/reviews/criteo/biggraphite/66#-KPmvZwmt6Ff4V3ecqaT:-KPnFW6fn-qvIfCOm7Vb:b-896fix) ([raw file](https://github.com/criteo/biggraphite/blob/a3ad71e3cd3bef817f8ed8aca99a30071202b676/biggraphite/drivers/_downsampling.py#L104)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> typo: retention
</details>
Done.

---

*[biggraphite/drivers/_downsampling.py, line 165 \[r3\]](https://reviewable.io:443/reviews/criteo/biggraphite/66#-KPmx7WjKsf_Tub_C3p4:-KPnG8HVIkFfPsxku0nN:b-896fix) ([raw file](https://github.com/criteo/biggraphite/blob/a3ad71e3cd3bef817f8ed8aca99a30071202b676/biggraphite/drivers/_downsampling.py#L165)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> this code isn't easy to read. please add a few comments.
</details>
Done.

---

*[biggraphite/drivers/_downsampling.py, line 190 \[r3\]](https://reviewable.io:443/reviews/criteo/biggraphite/66#-KPmy3o4gUcQgcLS14lA:-KPnGK7Zh9fKXgl8ZD3E:b-896fix) ([raw file](https://github.com/criteo/biggraphite/blob/a3ad71e3cd3bef817f8ed8aca99a30071202b676/biggraphite/drivers/_downsampling.py#L190)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> _merge ?
</details>
Done.

---

*[biggraphite/drivers/_downsampling.py, line 237 \[r3\]](https://reviewable.io:443/reviews/criteo/biggraphite/66#-KPmxHpD2En4Zg3VJVuV:-KPnGqYrDKzZ87XChMUQ:b-896fix) ([raw file](https://github.com/criteo/biggraphite/blob/a3ad71e3cd3bef817f8ed8aca99a30071202b676/biggraphite/drivers/_downsampling.py#L237)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> this code isn't easy to read. please add a few comments.
</details>
Done.

---

*[biggraphite/drivers/_downsampling.py, line 253 \[r3\]](https://reviewable.io:443/reviews/criteo/biggraphite/66#-KPmxJKTTOgB5qUYMXr2:-KPnHewcG-aKo40e2lvA:b-896fix) ([raw file](https://github.com/criteo/biggraphite/blob/a3ad71e3cd3bef817f8ed8aca99a30071202b676/biggraphite/drivers/_downsampling.py#L253)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> this code isn't easy to read. please add a few comments.
</details>
Done.

---

*[tests/test_drivers_downsampling.py, line 68 \[r3\]](https://reviewable.io:443/reviews/criteo/biggraphite/66#-KPmyZ7yMLMqBWUOo9aw:-KPnIu1KUrPN7mpmQtLj:b-896fix) ([raw file](https://github.com/criteo/biggraphite/blob/a3ad71e3cd3bef817f8ed8aca99a30071202b676/tests/test_drivers_downsampling.py#L68)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> remove print()
</details>
Done.

---

*[tests/test_drivers_downsampling.py, line 97 \[r3\]](https://reviewable.io:443/reviews/criteo/biggraphite/66#-KPmylc9vsiTOLoHzF7j:-KPnItkeoe0shB71QR_7:b-896fix) ([raw file](https://github.com/criteo/biggraphite/blob/a3ad71e3cd3bef817f8ed8aca99a30071202b676/tests/test_drivers_downsampling.py#L97)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> maybe call feed a second time here without adding new points, and a third time adding only one point.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/66)*

**Comment by iksaif** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/66#-:-KPnTR3zZxdR47zBPtX1:bnfp4nl)*

**Pull request merged**
