### PR TITLE
Documents design

### PR DESCRIPTION
**Pull request by unbrice**
This proposes and documents new schemas for biggraphite.

---
This change is [Reviewable](https://reviewable.io/reviews/criteo/biggraphite/33)

### CODE REVIEW

**Comment by iksaif** [comment]
First round of comments. *not* on the design yet

<details><summary><i>Previously, coveralls wrote…</i></summary>
> 
> [Coverage Status](https://coveralls.io/builds/6495844)
> 
> Coverage increased (+0.3%) to 93.142% when pulling **6bb34c2ec88b9b00606418d5349f42af823bd14d on unbrice:wip** into **a71d8fcd34a282c1d76decf7c0b2092b3b2b38b2 on criteo:master**.
> 
</details>


---

Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[CONTRIBUTING.md, line 2 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/33#-KJg99ZwgPblxCfXL6Bx:-KJg99ZxiB0K9gWXy71U:37836832) ([raw file](https://github.com/criteo/biggraphite/blob/c66be891dc8d8d6d8df1237d2230847fae96fc9c/CONTRIBUTING.md#L2)):*
> ```Markdown
> # How to contribute to Ruby on Rails
> ```

ruby on rails ?

---

*[CONTRIBUTING.md, line 21 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/33#-KJgAqZ9la00efxchdYj:-KJgAqZ9la00efxchdYk:-1530565135) ([raw file](https://github.com/criteo/biggraphite/blob/c66be891dc8d8d6d8df1237d2230847fae96fc9c/CONTRIBUTING.md#L21)):*
> ```Markdown
> - This project follows (PEP 8)[https://www.python.org/dev/peps/pep-0008/]
>   and (PEP 257)[https://www.python.org/dev/peps/pep-0257/]
> - We intend by four space
> ```

indent

---

*[CONTRIBUTING.md, line 23 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/33#-KJgArpjl35uzT4qqGV5:-KJgArpjl35uzT4qqGV6:-1839709414) ([raw file](https://github.com/criteo/biggraphite/blob/c66be891dc8d8d6d8df1237d2230847fae96fc9c/CONTRIBUTING.md#L23)):*
> ```Markdown
> - We intend by four space
> - We only import modules (`from os import path as os_path` not `from os.path import join`).
> ```

say that one should run pylama ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/33#-:-KJgAjm7dO1TzYR3YCwH:-1266672145)*

**Comment by unbrice** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[CONTRIBUTING.md, line 2 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/33#-KJg99ZwgPblxCfXL6Bx:-KJkldzKaK5z5ilRNsED:1749860100) ([raw file](https://github.com/criteo/biggraphite/blob/c66be891dc8d8d6d8df1237d2230847fae96fc9c/CONTRIBUTING.md#L2)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> ruby on rails ?
</details>
:-P Done.

---

*[CONTRIBUTING.md, line 21 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/33#-KJgAqZ9la00efxchdYj:-KJkmdZsx_0To08MFLLZ:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/c66be891dc8d8d6d8df1237d2230847fae96fc9c/CONTRIBUTING.md#L21)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> indent
</details>
Done.

---

*[CONTRIBUTING.md, line 23 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/33#-KJgArpjl35uzT4qqGV5:-KJknq3h4P53Oxc1hRYH:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/c66be891dc8d8d6d8df1237d2230847fae96fc9c/CONTRIBUTING.md#L23)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> say that one should run pylama ?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/33)*

**Comment by iksaif** [comment]
Review status: 0 of 5 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[CASSANDRA_DESIGN.md, line 16 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/33#-KJl1gq2WhkgxReNDNA_:-KJl1gq2WhkgxReNDNAa:-847139483) ([raw file](https://github.com/criteo/biggraphite/blob/d20cefa8bfca362485ba3a7400bf42297b146377/CASSANDRA_DESIGN.md#L16)):*
> ```Markdown
> 
> ### Expiry of data
> We use counters, so we cannot use TTL. Also TTLs are only applied on compaction and finding proper compaction configuration not to waste place would be tricky.<br />
> ```

Why do we *have* to use counters ? Looking at https://docs.datastax.com/en/cql/3.1/cql/cql_using/use_counter_t.html counters seem complicated and rather new (and thus probably fragile). It also seem to be a sharded counter where broken replication could easily break stuff.

Compared to that, just write the same value to two cassandra nodes seems more robust (even if we waste some performances on the reading path).

Remember that we want to optimize the write path, the read path will be cached most of the time.

---

*[CASSANDRA_DESIGN.md, line 16 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/33#-KJl2U1ibdnjxCvjicag:-KJl2U1ibdnjxCvjicah:1199887340) ([raw file](https://github.com/criteo/biggraphite/blob/d20cefa8bfca362485ba3a7400bf42297b146377/CASSANDRA_DESIGN.md#L16)):*
> ```Markdown
> 
> ### Expiry of data
> We use counters, so we cannot use TTL. Also TTLs are only applied on compaction and finding proper compaction configuration not to waste place would be tricky.<br />
> ```

Why would compaction waste space ?

---

*[CASSANDRA_DESIGN.md, line 21 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/33#-KJl3XJg8ZhEcDCH2vE9:-KJl3XJg8ZhEcDCH2vEA:-1885055865) ([raw file](https://github.com/criteo/biggraphite/blob/d20cefa8bfca362485ba3a7400bf42297b146377/CASSANDRA_DESIGN.md#L21)):*
> ```Markdown
> 
> At any time we have 11 tables prefix, corresponding to 1 TTL: 4 days, 8 days, 16 days, ..., 2048 days.
> We write and read a timestamp in the table that best fit. If we assume there is about the same amount of data week-over-week, we store **50% more than instant deletion**.
> ```

So 50% more is basically also the worst case with compactions + ttl ?

---

*[biggraphite/driver/interface.py, line 27 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/33#-KJl3rF-1ezKxD1ZuTQO:-KJl3rF-1ezKxD1ZuTQP:-1987612466) ([raw file](https://github.com/criteo/biggraphite/blob/d20cefa8bfca362485ba3a7400bf42297b146377/biggraphite/driver/interface.py#L27)):*
> ```Python
> import abc
> 
> class Driver(object):
> ```

I'm generally fine with all this, it doesn't really belong here though 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/33)*

**Comment by unbrice** [comment]
Review status: 0 of 5 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[CASSANDRA_DESIGN.md, line 16 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/33#-KJl1gq2WhkgxReNDNA_:-KJug0f5KYbprAOlxKnN:-549748577) ([raw file](https://github.com/criteo/biggraphite/blob/d20cefa8bfca362485ba3a7400bf42297b146377/CASSANDRA_DESIGN.md#L16)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> Why do we *have* to use counters ? Looking at https://docs.datastax.com/en/cql/3.1/cql/cql_using/use_counter_t.html counters seem complicated and rather new (and thus probably fragile). It also seem to be a sharded counter where broken replication could easily break stuff.
> 
> Compared to that, just write the same value to two cassandra nodes seems more robust (even if we waste some performances on the reading path).
> 
> Remember that we want to optimize the write path, the read path will be cached most of the time.
</details>
Great question. Counters were already there in 0.8. [Since 2.1 it's no longer a sharded counter](http://www.datastax.com/dev/blog/whats-new-in-cassandra-2-1-a-better-implementation-of-counters). Now the node takes a local lock on the row and reads/add/write - with a cache. This is basically what we'd be implementing in Python, except I expect it to be faster in Java, we reuse code and avoid sharding by hand.

[These benchmarks](http://riptano.github.io/cassandra_performance/graph/graph.html?stats=6553.low_contention_no_cache_CL_quorum_3_28.json&metric=op_rate&operation=counterwrite&smoothing=1&xmin=0&xmax=140.03&ymin=0&ymax=51540.5) from [CASSANDRA-6553](https://issues.apache.org/jira/browse/CASSANDRA-6553) indicate that in case of low contention (10K counters in different partitions accessed by 50 threads) and with CL.quorum, authors were achieving 44k writes per second *without caching*.

So I expect performance to be many order of magnitudes above what we need. And it's very cheap to implement.

---

*[CASSANDRA_DESIGN.md, line 16 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/33#-KJl2U1ibdnjxCvjicag:-KJwnTgNj73UPxVgyivz:-1127533170) ([raw file](https://github.com/criteo/biggraphite/blob/d20cefa8bfca362485ba3a7400bf42297b146377/CASSANDRA_DESIGN.md#L16)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> Why would compaction waste space ?
</details>
[Because compaction with DTCS happens every so often](https://labs.spotify.com/2014/12/18/date-tiered-compaction/). After 4H for data written more than 1H ago, after 16H for >4H ago, after 3 days for >16H, 12D for >3D and so forth. Not only does old data remain for an extra time proportional to how long it has existed (as with proposal) but furthermore this behaves very poorly when TTL of different rows are different and interleaved in one SSTable as the "drop the sstable" idea described does not work.
Also we mix application of retention policies with SSTable compaction which makes all sort of tuning more complex.

---

*[CASSANDRA_DESIGN.md, line 21 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/33#-KJl3XJg8ZhEcDCH2vE9:-KJwr4Qcgu_ThjAY14yg:-1462734851) ([raw file](https://github.com/criteo/biggraphite/blob/d20cefa8bfca362485ba3a7400bf42297b146377/CASSANDRA_DESIGN.md#L21)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> So 50% more is basically also the worst case with compactions + ttl ?
</details>
My understanding is that compaction + TTL has a worst case of 300% with default min_threshold=4.

---

*[biggraphite/driver/interface.py, line 27 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/33#-KJl3rF-1ezKxD1ZuTQO:-KJwre7GnkE2KrlXnKnV:-241364814) ([raw file](https://github.com/criteo/biggraphite/blob/d20cefa8bfca362485ba3a7400bf42297b146377/biggraphite/driver/interface.py#L27)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> I'm generally fine with all this, it doesn't really belong here though 
</details>
ACK, will make it part of the driver refacto review.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/33)*

**Comment by iksaif** [comment]
Review status: 0 of 5 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[CASSANDRA_DESIGN.md, line 16 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/33#-KJl2U1ibdnjxCvjicag:-KK7lqD4Q1orjn18JlSS:970424995) ([raw file](https://github.com/criteo/biggraphite/blob/d20cefa8bfca362485ba3a7400bf42297b146377/CASSANDRA_DESIGN.md#L16)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> [Because compaction with DTCS happens every so often](https://labs.spotify.com/2014/12/18/date-tiered-compaction/). After 4H for data written more than 1H ago, after 16H for >4H ago, after 3 days for >16H, 12D for >3D and so forth. Not only does old data remain for an extra time proportional to how long it has existed (as with proposal) but furthermore this behaves very poorly when TTL of different rows are different and interleaved in one SSTable as the "drop the sstable" idea described does not work.
> Also we mix application of retention policies with SSTable compaction which makes all sort of tuning more complex.
</details>
That's with DateTieredCompactionStrategy, which isn't the default and that we may not want to use.
Other databases usually only have SizeTieredCompactionStrategy. Cassandra also have LeveledCompactionStrategy.

Also, as far as I know, these only affect minor compactions. Major compactions are still triggered periodically (a period which is probably between 1 and 7 days by default).

---

*[CASSANDRA_DESIGN.md, line 21 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/33#-KJl3XJg8ZhEcDCH2vE9:-KK7mutXKn6pr_TJQEtZ:1780260796) ([raw file](https://github.com/criteo/biggraphite/blob/d20cefa8bfca362485ba3a7400bf42297b146377/CASSANDRA_DESIGN.md#L21)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> My understanding is that compaction + TTL has a worst case of 300% with default min_threshold=4.
</details>
How do you get 300% ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/33)*

**Comment by unbrice** [comment]
Review status: 0 of 4 files reviewed at latest revision, 7 unresolved discussions.

---

*[CASSANDRA_DESIGN.md, line 16 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/33#-KJl2U1ibdnjxCvjicag:-KLpmpfRrc89RkvVvIeA:314253233) ([raw file](https://github.com/criteo/biggraphite/blob/d20cefa8bfca362485ba3a7400bf42297b146377/CASSANDRA_DESIGN.md#L16)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> That's with DateTieredCompactionStrategy, which isn't the default and that we may not want to use.
> Other databases usually only have SizeTieredCompactionStrategy. Cassandra also have LeveledCompactionStrategy.
> 
> Also, as far as I know, these only affect minor compactions. Major compactions are still triggered periodically (a period which is probably between 1 and 7 days by default).
</details>
Discussed IRL.

---

*[CASSANDRA_DESIGN.md, line 21 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/33#-KJl3XJg8ZhEcDCH2vE9:-KLpmst44IHMyjDsRsU6:160356787) ([raw file](https://github.com/criteo/biggraphite/blob/d20cefa8bfca362485ba3a7400bf42297b146377/CASSANDRA_DESIGN.md#L21)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> How do you get 300% ?
</details>
4-1

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/33)*

**Comment by unbrice** [comment]
Discussions have been had, let's turn this into a proper doc.

**Pull request closed without merging**
