### PR TITLE
import_whisper: Handle input directories not ending with /

### PR DESCRIPTION
**Pull request by unbrice**
This change is [Reviewable](https://reviewable.io/reviews/criteo/biggraphite/27)

### CODE REVIEW

**Comment by natbraun** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[biggraphite/cli/import_whisper.py, line 101 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/27#-KJBN4mvguxfRgVrpzkr:-KJBN4mvguxfRgVrpzks:-919959979) ([raw file](https://github.com/criteo/biggraphite/blob/91232c409fd849aa2c56e1bd10f98417f0d3ba78/biggraphite/cli/import_whisper.py#L101)):*
> ```Python
>         relative_path = os.path.relpath(path, self._opts.root_directory)
>         relative_path_noext = os.path.splitext(relative_path)[0]
>         metric_name = relative_path_noext.replace(os.path.sep, ".")
> ```

Please put this in a separate function and add tests & comments :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/27)*

**Comment by unbrice** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[biggraphite/cli/import_whisper.py, line 101 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/27#-KJBN4mvguxfRgVrpzkr:-KJBQtbumDr6U7xrfz4a:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/91232c409fd849aa2c56e1bd10f98417f0d3ba78/biggraphite/cli/import_whisper.py#L101)):*
<details><summary><i>Previously, natbraun (Nathaniel Braun) wrote…</i></summary>
> Please put this in a separate function and add tests & comments :)
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/27)*

**Comment by natbraun** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/27)*

**Comment by natbraun** [comment]
:lgtm:

<details><summary><i>Previously, coveralls wrote…</i></summary>
> 
> [Coverage Status](https://coveralls.io/builds/6418017)
> 
> Coverage increased (+0.02%) to 93.333% when pulling **91232c409fd849aa2c56e1bd10f98417f0d3ba78 on unbrice:master** into **9703bd08c2c2182821e131e69857c7b730f26e07 on criteo:master**.
> 
</details>


---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/27#-:-KJBReV--nN06QnFo9AA:1417088721)*

**Pull request merged**
