### PR TITLE
Clean Java code

### PR DESCRIPTION
**Pull request by mcoolive**
- Remove IDE configuration files (*.iml) and add them to .gitignore
- reindent POMs
- Add a parent relationship between POMs (to inherit project info)
- Add Maven properties to ensure resources are encoded in UTF8
(previously the build was platform dependent)
- Add maven-enforcer-plugin to check the maven and java versions
- Move up version of dependencies in the parent dependencyManagement
- Replace cassandra-driver by its shaded version (it embeds its own
version of Netty)
- Add explicit exclusions to prevent cassandra-driver to bring back
Netty (in particular if we use the shaded artifact ...) Needed to avoid
several versions of Netty (how shade plugin picks one is unspecified)
- Add junit test dependencies (it worked previously because
thrift-server:0.3.7 depends on it by mistake...)
- Fix paths of java code to match with package names
- Change package from "biggraphite" to "com.criteo.biggraphite"
- Clean unused imports
- Make internal methods private

---
This change is [Reviewable](https://reviewable.io/reviews/criteo/biggraphite/186)

### CODE REVIEW

**Comment by iksaif** [comment]
:lgtm:

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/186#-:-KXBR1iJD_x70LOo-MXf:bnfp4nl)*

**Comment by iksaif** [comment]
:lgtm_strong: (please rebase before merging)

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/186#-:-KXBR3xmbsKlwo2okuas:b-gzedae)*

**Comment by erebe** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[.gitignore, line 17 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/186#-KXBQrHBoXrwKO5CTzjg:-KXBQrHBoXrwKO5CTzjh:b61a76b) ([raw file](https://github.com/criteo/biggraphite/blob/d00056d63bbed5e04d96f1026373af1a4464aa16/.gitignore#L17)):*
> ```
> # IDEs
> .idea/
> *.iml
> ```

use  recursive patterns, so if you add some submodules it will sill ignore them
**/*.iml
**/*.idea

---

*[pom.xml, line 64 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/186#-KXBRiaN2N2ATagFpvkA:-KXBRiaN2N2ATagFpvkB:b8m72sl) ([raw file](https://github.com/criteo/biggraphite/blob/d00056d63bbed5e04d96f1026373af1a4464aa16/pom.xml#L64)):*
> ```XML
>             
> ```

I am not sure of it (you should look into the final jar) but it may be good to include. By default it is not included by cassandra as it is plateform dependent.

<dependency>
    <groupId>io.netty</groupId>
    <artifactId>netty-transport-native-epoll</artifactId>
    <version>4.1.6.Final</version>
</dependency>

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/186)*

**Comment by erebe** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[.gitignore, line 17 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/186#-KXBQrHBoXrwKO5CTzjg:-KXBS33MRxRSYS9AA2JL:b8qqtn8) ([raw file](https://github.com/criteo/biggraphite/blob/d00056d63bbed5e04d96f1026373af1a4464aa16/.gitignore#L17)):*
<details><summary><i>Previously, erebe (Erèbe - Romain Gerard) wrote…</i></summary>
> use  recursive patterns, so if you add some submodules it will sill ignore them
> **/*.iml
> **/*.idea
</details>
it is * */*.iml (without spaces) reviewable eats the double star

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/186)*

**Comment by erebe** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[.gitignore, line 17 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/186#-KXBQrHBoXrwKO5CTzjg:-KXBSUdWjJTB_HFqpn85:b-lmtxyh) ([raw file](https://github.com/criteo/biggraphite/blob/d00056d63bbed5e04d96f1026373af1a4464aa16/.gitignore#L17)):*
<details><summary><i>Previously, erebe (Erèbe - Romain Gerard) wrote…</i></summary>
> it is * */*.iml (without spaces) reviewable eats the double star
</details>
... this link 
http://stackoverflow.com/questions/17812717/correctly-ignore-all-files-recursively-under-a-specific-folder-except-for-a-spec

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/186)*

**Comment by erebe** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/186)*

**Comment by dpanth3r** [comment]
As a side note, I would suggest IDE/editor/environment-specific files should be filtered on your own global gitignore, and not inside the ones for every single project you contribute to.

**Comment by mcoolive** [comment]
*[.gitignore, line 17 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/186#-KXBQrHBoXrwKO5CTzjg:-KXGCwwIq6uIOIzfZUbl:bthrh3s) ([raw file](https://github.com/criteo/biggraphite/blob/ac7c9754952c8c61499620740a04d8a52d18b5bb/.gitignore#L17)):*
<details><summary><i>Previously, erebe (Erèbe - Romain Gerard) wrote…</i></summary>
> ... this link 
> http://stackoverflow.com/questions/17812717/correctly-ignore-all-files-recursively-under-a-specific-folder-except-for-a-spec
> 
</details>
Ok. I will amend my commit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/186)*

**Comment by mcoolive** [comment]
*[pom.xml, line 64 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/186#-KXBRiaN2N2ATagFpvkA:-KXGD9fBkEUGGxfqnSbx:bhixeoq) ([raw file](https://github.com/criteo/biggraphite/blob/ac7c9754952c8c61499620740a04d8a52d18b5bb/pom.xml#L64)):*
<details><summary><i>Previously, erebe (Erèbe - Romain Gerard) wrote…</i></summary>
> I am not sure of it (you should look into the final jar) but it may be good to include. By default it is not included by cassandra as it is plateform dependent.
> 
> <dependency>
>     <groupId>io.netty</groupId>
>     <artifactId>netty-transport-native-epoll</artifactId>
>     <version>4.1.6.Final</version>
> </dependency>
> 
</details>
Indeed, epoll is not shaded, but I don't excluded this one.
In other hand, epoll is an optional dependency: it is NOT used (nor before nor after). Maybe we should use it...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/186)*

**Pull request merged**
