### PR TITLE
Merge Metricbuffer and StageAggregate into MetricAggregate

### PR DESCRIPTION
**Pull request by natbraun**
This change is [Reviewable](https://reviewable.io/reviews/criteo/biggraphite/53)

### CODE REVIEW

**Comment by unbrice** [comment]
Review status: 0 of 2 files reviewed at latest revision, 7 unresolved discussions.

---

*[biggraphite/drivers/downsampling.py, line 26 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/53#-KNI9nr1nXNBmO62McOZ:-KNI9nr24rhfjs5BnBez:-1063430468) ([raw file](https://github.com/criteo/biggraphite/blob/89727f4435e12916f15c2536ebf31e5a35275a38/biggraphite/drivers/downsampling.py#L26)):*
> ```Python
> 
> 
> class MetricDownsampler(object):
> ```

this class can probably go away no? It's only a wrapper of MetricAggregates.

---

*[biggraphite/drivers/downsampling.py, line 90 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/53#-KNIA4V-iaBIPDYmXma1:-KNIA4V-iaBIPDYmXma2:-1477138188) ([raw file](https://github.com/criteo/biggraphite/blob/89727f4435e12916f15c2536ebf31e5a35275a38/biggraphite/drivers/downsampling.py#L90)):*
> ```Python
>     """Perform aggregation on metric data points."""
> 
>     RAW_CAPACITY = 10
> ```

DEFAULT_RAW_CAPACITY

---

*[biggraphite/drivers/downsampling.py, line 93 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/53#-KNIAEkplwSS4WO2ReMn:-KNIAEkplwSS4WO2ReMo:-250312516) ([raw file](https://github.com/criteo/biggraphite/blob/89727f4435e12916f15c2536ebf31e5a35275a38/biggraphite/drivers/downsampling.py#L93)):*
> ```Python
> 
>     __slots__ = (
>         "_raw_timestamp",
> ```

did you consider making this the first element of _timestamps?

---

*[biggraphite/drivers/downsampling.py, line 126 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/53#-KNIAhY_vQI7LUd8PfrC:-KNIAhY_vQI7LUd8PfrD:-1752212634) ([raw file](https://github.com/criteo/biggraphite/blob/89727f4435e12916f15c2536ebf31e5a35275a38/biggraphite/drivers/downsampling.py#L126)):*
> ```Python
>           The list of (timestamp, value) expired from the raw buffer.
>         """
>         res = []
> ```

I suggest renaming res into expired in this specific case as it's harder to remember what it returns

---

*[biggraphite/drivers/downsampling.py, line 128 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/53#-KNIAWhwzqx7ySruk1lE:-KNIAWhwzqx7ySruk1lF:2134357245) ([raw file](https://github.com/criteo/biggraphite/blob/89727f4435e12916f15c2536ebf31e5a35275a38/biggraphite/drivers/downsampling.py#L128)):*
> ```Python
>         res = []
>         for timestamp, value in datapoints:
>             if self._raw_timestamp == -1:
> ```

this can go out of the loop no?

---

*[biggraphite/drivers/downsampling.py, line 136 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/53#-KNIB8LlkxsYMG-UajCL:-KNIB8LlkxsYMG-UajCM:-297459116) ([raw file](https://github.com/criteo/biggraphite/blob/89727f4435e12916f15c2536ebf31e5a35275a38/biggraphite/drivers/downsampling.py#L136)):*
> ```Python
>                 start_epoch = current_epoch - (self._raw_capacity - 1)
>                 end_epoch = point_epoch - (self._raw_capacity - 1)
>                 for epoch in xrange(start_epoch, end_epoch):
> ```

if there were no point for a long while you will add the same point multiple times and be in O(time)

---

*[biggraphite/drivers/downsampling.py, line 141 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/53#-KNIAwV68ZX0cN-DA5lF:-KNIAwV68ZX0cN-DA5lG:1521658720) ([raw file](https://github.com/criteo/biggraphite/blob/89727f4435e12916f15c2536ebf31e5a35275a38/biggraphite/drivers/downsampling.py#L141)):*
> ```Python
>                         res.append((epoch * precision, self._values[index]))
>                     self._values[index] = _NaN
>                 self._raw_timestamp = point_epoch * precision
> ```

I think it's easier to read as ` accessor.round_down(timestamp, precision)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/53)*

**Comment by natbraun** [comment]
Review status: 0 of 2 files reviewed at latest revision, 7 unresolved discussions.

---

*[biggraphite/drivers/downsampling.py, line 26 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/53#-KNI9nr1nXNBmO62McOZ:-KNW6SQjGJ4duxD45a6m:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/89727f4435e12916f15c2536ebf31e5a35275a38/biggraphite/drivers/downsampling.py#L26)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> this class can probably go away no? It's only a wrapper of MetricAggregates.
</details>
Done.

---

*[biggraphite/drivers/downsampling.py, line 90 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/53#-KNIA4V-iaBIPDYmXma1:-KNW6k4EvLGQJlQpzVe0:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/89727f4435e12916f15c2536ebf31e5a35275a38/biggraphite/drivers/downsampling.py#L90)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> DEFAULT_RAW_CAPACITY
</details>
Done.

---

*[biggraphite/drivers/downsampling.py, line 93 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/53#-KNIAEkplwSS4WO2ReMn:-KNW6lJsohc90L5hrUzs:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/89727f4435e12916f15c2536ebf31e5a35275a38/biggraphite/drivers/downsampling.py#L93)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> did you consider making this the first element of _timestamps?
</details>
Done.

---

*[biggraphite/drivers/downsampling.py, line 126 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/53#-KNIAhY_vQI7LUd8PfrC:-KNW841x501Wi8m1otaJ:6180935) ([raw file](https://github.com/criteo/biggraphite/blob/89727f4435e12916f15c2536ebf31e5a35275a38/biggraphite/drivers/downsampling.py#L126)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> I suggest renaming res into expired in this specific case as it's harder to remember what it returns
</details>

Done.

---

*[biggraphite/drivers/downsampling.py, line 128 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/53#-KNIAWhwzqx7ySruk1lE:-KNW9iaMxn2ZEPYyYaKC:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/89727f4435e12916f15c2536ebf31e5a35275a38/biggraphite/drivers/downsampling.py#L128)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> this can go out of the loop no?
</details>
Done.

---

*[biggraphite/drivers/downsampling.py, line 136 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/53#-KNIB8LlkxsYMG-UajCL:-KNWAHgxzI-X32fL17vt:-326792516) ([raw file](https://github.com/criteo/biggraphite/blob/89727f4435e12916f15c2536ebf31e5a35275a38/biggraphite/drivers/downsampling.py#L136)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> if there were no point for a long while you will add the same point multiple times and be in O(time)
</details>
I agree. I'll add a TODO to fix this.

---

*[biggraphite/drivers/downsampling.py, line 141 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/53#-KNIAwV68ZX0cN-DA5lF:-KNWBHBYVHtqsxdhnPun:2087341419) ([raw file](https://github.com/criteo/biggraphite/blob/89727f4435e12916f15c2536ebf31e5a35275a38/biggraphite/drivers/downsampling.py#L141)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> I think it's easier to read as ` accessor.round_down(timestamp, precision)`
</details>
This is not round_down, it's really a division. Moreover, it'll require changing the code to use the accessor. I'll add a comment instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/53)*

**Comment by iksaif** [comment]
I have the feeling that this commit is really a regression for readability. Even if we merge the objects, can we keep the methods separate in order to keep them simple ?

---

Review status: 0 of 2 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/53#-:-KNWC02xsfdS1SlT45LG:-600260034)*

**Comment by natbraun** [comment]
I agree. I'll try to fix this. We cram many things together, that's why.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/53#-:-KNWCNkCmTDlyUphQQVw:-127425955)*

**Comment by iksaif** [comment]
Review status: 0 of 2 files reviewed at latest revision, 8 unresolved discussions.

---

*[biggraphite/drivers/downsampling.py, line 113 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/53#-KNWDCHovx1gQIMQqetA:-KNWDCHovx1gQIMQqetB:2122063965) ([raw file](https://github.com/criteo/biggraphite/blob/89727f4435e12916f15c2536ebf31e5a35275a38/biggraphite/drivers/downsampling.py#L113)):*
> ```Python
>         self._raw_capacity = raw_capacity
>         self._timestamps = array.array("i", [-1] * stages)
>         self._values = array.array("d", [_NaN] * (raw_capacity + stages))
> ```

please add comments about what all of these are and how they are being used 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/53)*

**Comment by natbraun** [comment]
Review status: 0 of 2 files reviewed at latest revision, 8 unresolved discussions.

---

*[biggraphite/drivers/downsampling.py, line 113 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/53#-KNWDCHovx1gQIMQqetA:-KNWEkl_UyZ-wBkcJQmA:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/89727f4435e12916f15c2536ebf31e5a35275a38/biggraphite/drivers/downsampling.py#L113)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> please add comments about what all of these are and how they are being used 
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/53)*

**Comment by unbrice** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[biggraphite/drivers/downsampling.py, line 128 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/53#-KNIAWhwzqx7ySruk1lE:-KNX6e_I1zQwafdtSkAU:-1477728242) ([raw file](https://github.com/criteo/biggraphite/blob/89727f4435e12916f15c2536ebf31e5a35275a38/biggraphite/drivers/downsampling.py#L128)):*
<details><summary><i>Previously, natbraun (Nathaniel Braun) wrote…</i></summary>
> Done.
</details>
Nope :sweat_smile: 

---

*[biggraphite/drivers/downsampling.py, line 136 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/53#-KNIB8LlkxsYMG-UajCL:-KNX6nuR1HJhzl4QegLm:1078198294) ([raw file](https://github.com/criteo/biggraphite/blob/89727f4435e12916f15c2536ebf31e5a35275a38/biggraphite/drivers/downsampling.py#L136)):*
<details><summary><i>Previously, natbraun (Nathaniel Braun) wrote…</i></summary>
> I agree. I'll add a TODO to fix this.
</details>
Please add TODO

---

*[biggraphite/drivers/downsampling.py, line 141 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/53#-KNIAwV68ZX0cN-DA5lF:-KNX6t6Go4M6MSzHNb4d:-313925006) ([raw file](https://github.com/criteo/biggraphite/blob/89727f4435e12916f15c2536ebf31e5a35275a38/biggraphite/drivers/downsampling.py#L141)):*
<details><summary><i>Previously, natbraun (Nathaniel Braun) wrote…</i></summary>
> This is not round_down, it's really a division. Moreover, it'll require changing the code to use the accessor. I'll add a comment instead.
</details>
Why wouldn't the code I proposed work?

---

*[biggraphite/drivers/downsampling.py, line 33 \[r4\]](https://reviewable.io:443/reviews/criteo/biggraphite/53#-KNX7BsFZsjdud2WnRKK:-KNX7BsFZsjdud2WnRKL:1607462689) ([raw file](https://github.com/criteo/biggraphite/blob/1226422cc7e49daf928abb2e3acb6941876b38b0/biggraphite/drivers/downsampling.py#L33)):*
> ```Python
>     slots = (
>         "_capacity",
>         "_metric_aggregates"
> ```

I suggest calling dicts "${KEY}_to_${VALUE}" like "_names_to_aggregates"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/53)*

**Comment by natbraun** [comment]
Review status: 1 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[biggraphite/drivers/downsampling.py, line 128 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/53#-KNIAWhwzqx7ySruk1lE:-KNXJEPS11FyNcUbekOl:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/89727f4435e12916f15c2536ebf31e5a35275a38/biggraphite/drivers/downsampling.py#L128)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> Nope :sweat_smile: 
</details>
Done.

---

*[biggraphite/drivers/downsampling.py, line 136 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/53#-KNIB8LlkxsYMG-UajCL:-KNXJJDpfnCjSoNP8WQX:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/89727f4435e12916f15c2536ebf31e5a35275a38/biggraphite/drivers/downsampling.py#L136)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> Please add TODO
</details>
Done.

---

*[biggraphite/drivers/downsampling.py, line 141 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/53#-KNIAwV68ZX0cN-DA5lF:-KNXKeEf67VqUEwm0TMl:1013543619) ([raw file](https://github.com/criteo/biggraphite/blob/89727f4435e12916f15c2536ebf31e5a35275a38/biggraphite/drivers/downsampling.py#L141)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> Why wouldn't the code I proposed work?
</details>
Where do I get the accessor from?

---

*[biggraphite/drivers/downsampling.py, line 33 \[r4\]](https://reviewable.io:443/reviews/criteo/biggraphite/53#-KNX7BsFZsjdud2WnRKK:-KNXJYZnKMwcWUeTqfZn:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/1226422cc7e49daf928abb2e3acb6941876b38b0/biggraphite/drivers/downsampling.py#L33)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> I suggest calling dicts "${KEY}_to_${VALUE}" like "_names_to_aggregates"
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/53)*

**Comment by unbrice** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[biggraphite/drivers/downsampling.py, line 141 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/53#-KNIAwV68ZX0cN-DA5lF:-KNXQts7zhpkvTVMl_Tq:772175300) ([raw file](https://github.com/criteo/biggraphite/blob/89727f4435e12916f15c2536ebf31e5a35275a38/biggraphite/drivers/downsampling.py#L141)):*
<details><summary><i>Previously, natbraun (Nathaniel Braun) wrote…</i></summary>
> Where do I get the accessor from?
</details>
Sorry, meant the accessor module not an instance of Accessor

---

*[biggraphite/drivers/downsampling.py, line 110 \[r5\]](https://reviewable.io:443/reviews/criteo/biggraphite/53#-KNXPG7P9by2Ry5sppBY:-KNXPG7P9by2Ry5sppBZ:-2019947790) ([raw file](https://github.com/criteo/biggraphite/blob/37e67fecdb7881db359aaec8fcc78825d24592bf/biggraphite/drivers/downsampling.py#L110)):*
> ```Python
>         """
>         if self._timestamps[0] == -1:
>             # There is no prior stage in the raw buffer.
> ```

Buffer is empty

---

*[biggraphite/drivers/downsampling.py, line 117 \[r5\]](https://reviewable.io:443/reviews/criteo/biggraphite/53#-KNXQAfuxZmwMU79InKU:-KNXQAfvod9Dvespw8jw:835329674) ([raw file](https://github.com/criteo/biggraphite/blob/37e67fecdb7881db359aaec8fcc78825d24592bf/biggraphite/drivers/downsampling.py#L117)):*
> ```Python
>             first_datapoint = datapoints[0]
>             first_timestamp = first_datapoint[0]
>             self._timestamps[0] = first_timestamp
> ```

Can you use a current_timestamp local variable or property?
```python
@property
def a(self):
   pass

@a.setter
def a(self, value):
  pass
```
https://docs.python.org/2/library/functions.html#property

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/53)*

**Comment by natbraun** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[biggraphite/drivers/downsampling.py, line 141 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/53#-KNIAwV68ZX0cN-DA5lF:-KNXULPyxB4gZ_ZP85S8:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/89727f4435e12916f15c2536ebf31e5a35275a38/biggraphite/drivers/downsampling.py#L141)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> Sorry, meant the accessor module not an instance of Accessor
</details>
Done.

---

*[biggraphite/drivers/downsampling.py, line 110 \[r5\]](https://reviewable.io:443/reviews/criteo/biggraphite/53#-KNXPG7P9by2Ry5sppBY:-KNXSoNzAvVPQvC4tNo7:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/37e67fecdb7881db359aaec8fcc78825d24592bf/biggraphite/drivers/downsampling.py#L110)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> Buffer is empty
</details>
Done.

---

*[biggraphite/drivers/downsampling.py, line 117 \[r5\]](https://reviewable.io:443/reviews/criteo/biggraphite/53#-KNXQAfuxZmwMU79InKU:-KNXTXRAQlSd4xfUKrW8:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/37e67fecdb7881db359aaec8fcc78825d24592bf/biggraphite/drivers/downsampling.py#L117)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> Can you use a current_timestamp local variable or property?
> ```python
> @property
> def a(self):
>    pass
> 
> @a.setter
> def a(self, value):
>   pass
> ```
> https://docs.python.org/2/library/functions.html#property
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/53)*

**Comment by unbrice** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[biggraphite/drivers/downsampling.py, line 130 \[r6\]](https://reviewable.io:443/reviews/criteo/biggraphite/53#-KNZdj7fKxJrD2uegGCz:-KNZdj7gZY0QLxi-6f1J:262164995) ([raw file](https://github.com/criteo/biggraphite/blob/e0e5f4d6534195d74d61da66f1c5a3cfc7ee1a97/biggraphite/drivers/downsampling.py#L130)):*
> ```Python
>                 # Expire only points currently in the raw buffer
>                 start_epoch = current_epoch - (self._raw_capacity - 1)
>                 end_epoch = min(point_epoch - self._raw_capacity, current_epoch)
> ```

Do you agree the following is the same? If so, I thik this one is more legible
```python
expired_len = min(self.raw_capacity, point_epoch-start_epoch)
end_epoch = start_epoch+expired_len
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/53)*

**Comment by unbrice** [comment]
:lgtm_strong: 

---

Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/53#-:-KNaM8I628By7fQd20BG:-1868698381)*

**Comment by iksaif** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/53)*

**Comment by iksaif** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/53#-:-KNaMdxmAfjyPpgPYVu5:1417088721)*

**Comment by natbraun** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[biggraphite/drivers/downsampling.py, line 130 \[r6\]](https://reviewable.io:443/reviews/criteo/biggraphite/53#-KNZdj7fKxJrD2uegGCz:-KNaPW4cUFM5OvvvICop:-1068046671) ([raw file](https://github.com/criteo/biggraphite/blob/e0e5f4d6534195d74d61da66f1c5a3cfc7ee1a97/biggraphite/drivers/downsampling.py#L130)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> Do you agree the following is the same? If so, I thik this one is more legible
> ```python
> expired_len = min(self.raw_capacity, point_epoch-start_epoch)
> end_epoch = start_epoch+expired_len
> ```
</details>
I agree. I'll make the change

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/53)*

**Comment by natbraun** [comment]
*[biggraphite/drivers/downsampling.py, line 130 \[r6\]](https://reviewable.io:443/reviews/criteo/biggraphite/53#-KNZdj7fKxJrD2uegGCz:-KNaQ3kd-qsjTfSdTz7x:-1846617084) ([raw file](https://github.com/criteo/biggraphite/blob/e0e5f4d6534195d74d61da66f1c5a3cfc7ee1a97/biggraphite/drivers/downsampling.py#L130)):*
<details><summary><i>Previously, natbraun (Nathaniel Braun) wrote…</i></summary>
> I agree. I'll make the change
</details>
Well, actually it's not the same. Here is what you wanted to say, I guess:

                start_epoch = current_epoch - (self._raw_capacity - 1)
                expired_count = min(point_epoch - current_epoch, self._raw_capacity)
                end_epoch = start_epoch + expired_count

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/53)*

**Pull request merged**
