### PR TITLE
Add a graphite finder

### PR DESCRIPTION
**Pull request by unbrice**
Also fixes small bugs and makes test faster.

There are no unit tests yet, but I wanted to get this out so as to help
sync'ing with the ongoing work on writing a real Finder.

I checked it worked by inserting points and viewing them in Graphite.

---
This change is [Reviewable](https://reviewable.io/reviews/criteo/biggraphite/7)

### CODE REVIEW

**Comment by unbrice** [comment]
+@iksaif  +@natbraun could you please review?

<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> #### Adds a graphite finder
> 
> Also fixes small bugs and makes test faster.
> 
> 
> 
> There are no unit tests yet, but I wanted to get this out so as to help
> 
> sync'ing with the ongoing work on writing a real Finder.
> 
> 
> 
> I checked it worked by inserting points and viewing them in Graphite.
> 
> 
> 
</details>


---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/7#-:-KI29uaG2olEugiaTzU9:-208667220)*

**Comment by iksaif** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[biggraphite/plugins/graphite.py, line 47 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/7#-KI2Aez2uJD_Giq0Q2lS:-KI2Aez2uJD_Giq0Q2lT:-28461905) ([raw file](https://github.com/criteo/biggraphite/blob/2dc710fcf22c156d80acc4f0b42589b7c33e15d1/biggraphite/plugins/graphite.py#L47)):*
> ```Python
> 
> class Reader(object):
> ```

Add some docstrings and tests please :)

---

*[biggraphite/plugins/graphite.py, line 90 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/7#-KI2AnbzSLN3a842mIFR:-KI2AnbzSLN3a842mIFS:-570818154) ([raw file](https://github.com/criteo/biggraphite/blob/2dc710fcf22c156d80acc4f0b42589b7c33e15d1/biggraphite/plugins/graphite.py#L90)):*
> ```Python
>             index = int(ts - start_time) // step
>             points[index] = point
>         print (start_time, end_time, step), points
> ```

remove print

---

*[biggraphite/plugins/graphite.py, line 96 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/7#-KI2Amb6c3NkCTbF6-1o:-KI2Amb6c3NkCTbF6-1p:-570818154) ([raw file](https://github.com/criteo/biggraphite/blob/2dc710fcf22c156d80acc4f0b42589b7c33e15d1/biggraphite/plugins/graphite.py#L96)):*
> ```Python
>         self.__refresh_metadata()
>         start, end, unused_step = self.__get_time_info(0, time.time())
>         print start, end
> ```

remove print

---

*[biggraphite/plugins/graphite.py, line 102 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/7#-KI2CyYmh9Ft3qgI_lvh:-KI2CyYmh9Ft3qgI_lvi:221478649) ([raw file](https://github.com/criteo/biggraphite/blob/2dc710fcf22c156d80acc4f0b42589b7c33e15d1/biggraphite/plugins/graphite.py#L102)):*
> ```Python
> class Finder(object):
> 
>     def __init__(self, directories=None, django_like_settings=None):
> ```

Can you explain why we need this django_like_settings ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/7)*

**Comment by natbraun** [comment]
Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[biggraphite/accessor.py, line 322 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/7#-KI2D2CWIwB1RGZciag8:-KI2D2CWIwB1RGZciag9:-661612625) ([raw file](https://github.com/criteo/biggraphite/blob/2dc710fcf22c156d80acc4f0b42589b7c33e15d1/biggraphite/accessor.py#L322)):*
> ```Python
>         self.__cluster = c_cluster.Cluster(
>             self.contact_points, self.port, executor_threads=executor_threads,
>         )
> ```

Why this comma?

---

*[biggraphite/plugins/graphite.py, line 37 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/7#-KI2DOqFFH-M6cBAcakz:-KI2DOqG7vJOghEGBdhw:-1742237621) ([raw file](https://github.com/criteo/biggraphite/blob/2dc710fcf22c156d80acc4f0b42589b7c33e15d1/biggraphite/plugins/graphite.py#L37)):*
> ```Python
>     """Configuration problems."""
> ```

divider?

---

*[biggraphite/plugins/graphite.py, line 119 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/7#-KI2E6UmT1dqmjfZY9iL:-KI2E6UmT1dqmjfZY9iM:1949258922) ([raw file](https://github.com/criteo/biggraphite/blob/2dc710fcf22c156d80acc4f0b42589b7c33e15d1/biggraphite/plugins/graphite.py#L119)):*
> ```Python
> 
>         self._accessor = accessor.Accessor(keyspace, contact_points, port)
>         self._accessor = accessor.Accessor(keyspace="biggraphite", contact_points=["localhost"],port=9042)
> ```

why instantiate twice?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/7)*

**Comment by iksaif** [comment]
Review status: 0 of 3 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[biggraphite/plugins/graphite.py, line 63 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/7#-KI2NGmD_neFEkWtaixM:-KI2NGmD_neFEkWtaixN:-256162407) ([raw file](https://github.com/criteo/biggraphite/blob/2dc710fcf22c156d80acc4f0b42589b7c33e15d1/biggraphite/plugins/graphite.py#L63)):*
> ```Python
>             step, retention = 1, 60
> 
>         oldest_timestamp = time.time() - retention
> ```

Is retention always in second ? for me it was step * retention = time

---

*[biggraphite/plugins/graphite.py, line 95 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/7#-KI2O8x1k6aQ_a90Izvm:-KI2O8x1k6aQ_a90Izvn:167453318) ([raw file](https://github.com/criteo/biggraphite/blob/2dc710fcf22c156d80acc4f0b42589b7c33e15d1/biggraphite/plugins/graphite.py#L95)):*
> ```Python
>     def get_intervals(self):
>         self.__refresh_metadata()
>         start, end, unused_step = self.__get_time_info(0, time.time())
> ```

Add a comment explaining why we return 0, time.time() instead of fetching the actual interval for this metric.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/7)*

**Comment by unbrice** [comment]
Review status: 0 of 3 files reviewed at latest revision, 9 unresolved discussions.

---

*[biggraphite/accessor.py, line 322 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/7#-KI2D2CWIwB1RGZciag8:-KI2Hzai6rRwsMWzFKSu:-2068099281) ([raw file](https://github.com/criteo/biggraphite/blob/2dc710fcf22c156d80acc4f0b42589b7c33e15d1/biggraphite/accessor.py#L322)):*
<details><summary><i>Previously, natbraun (Nathaniel Braun) wrote…</i></summary>
> Why this comma?
</details>
By anology with https://docs.python.org/dev/faq/design.html#why-does-python-allow-commas-at-the-end-of-lists-and-tuples

---

*[biggraphite/plugins/graphite.py, line 37 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/7#-KI2DOqFFH-M6cBAcakz:-KI2Pnx4I0ompBEoDZ07:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/2dc710fcf22c156d80acc4f0b42589b7c33e15d1/biggraphite/plugins/graphite.py#L37)):*
<details><summary><i>Previously, natbraun (Nathaniel Braun) wrote…</i></summary>
> divider?
</details>
Done.

---

*[biggraphite/plugins/graphite.py, line 47 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/7#-KI2Aez2uJD_Giq0Q2lS:-KI2PqCuSM-vv0s-BVLT:-93269251) ([raw file](https://github.com/criteo/biggraphite/blob/2dc710fcf22c156d80acc4f0b42589b7c33e15d1/biggraphite/plugins/graphite.py#L47)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> Add some docstrings and tests please :)
</details>
Done for docstrings, are you OK with tests being part of another review?

---

*[biggraphite/plugins/graphite.py, line 63 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/7#-KI2NGmD_neFEkWtaixM:-KI2QVh6b87JbymTu7gY:642279517) ([raw file](https://github.com/criteo/biggraphite/blob/2dc710fcf22c156d80acc4f0b42589b7c33e15d1/biggraphite/plugins/graphite.py#L63)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> Is retention always in second ? for me it was step * retention = time
</details>
Well spotted! Fixed.

---

*[biggraphite/plugins/graphite.py, line 90 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/7#-KI2AnbzSLN3a842mIFR:-KI2RU7yxOuVbuBPtRtH:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/2dc710fcf22c156d80acc4f0b42589b7c33e15d1/biggraphite/plugins/graphite.py#L90)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> remove print
</details>
Done.

---

*[biggraphite/plugins/graphite.py, line 95 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/7#-KI2O8x1k6aQ_a90Izvm:-KI2RoauOV9r6AC6qA1w:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/2dc710fcf22c156d80acc4f0b42589b7c33e15d1/biggraphite/plugins/graphite.py#L95)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> Add a comment explaining why we return 0, time.time() instead of fetching the actual interval for this metric.
</details>
Done.

---

*[biggraphite/plugins/graphite.py, line 96 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/7#-KI2Amb6c3NkCTbF6-1o:-KI2RUY_V_7vTXZX1Xn8:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/2dc710fcf22c156d80acc4f0b42589b7c33e15d1/biggraphite/plugins/graphite.py#L96)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> remove print
</details>
Done.

---

*[biggraphite/plugins/graphite.py, line 102 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/7#-KI2CyYmh9Ft3qgI_lvh:-KI2RuJW8vF6G9C3yZjw:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/2dc710fcf22c156d80acc4f0b42589b7c33e15d1/biggraphite/plugins/graphite.py#L102)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> Can you explain why we need this django_like_settings ?
</details>
Done.

---

*[biggraphite/plugins/graphite.py, line 119 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/7#-KI2E6UmT1dqmjfZY9iL:-KI2RvZcI9-tp2-LbyEW:2137780419) ([raw file](https://github.com/criteo/biggraphite/blob/2dc710fcf22c156d80acc4f0b42589b7c33e15d1/biggraphite/plugins/graphite.py#L119)):*
<details><summary><i>Previously, natbraun (Nathaniel Braun) wrote…</i></summary>
> why instantiate twice?
</details>
Done (I had pushed code without removing debug statements from Friday)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/7)*

**Comment by iksaif** [comment]
Review status: 0 of 3 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[biggraphite/plugins/graphite.py, line 47 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/7#-KI2Aez2uJD_Giq0Q2lS:-KI2Vultybmai-Q0dryq:-1612505075) ([raw file](https://github.com/criteo/biggraphite/blob/2dc710fcf22c156d80acc4f0b42589b7c33e15d1/biggraphite/plugins/graphite.py#L47)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> Done for docstrings, are you OK with tests being part of another review?
</details>
In general not really, but since it will probably unblock Nath it's probably better this way.

---

*[biggraphite/plugins/graphite.py, line 111 \[r3\]](https://reviewable.io:443/reviews/criteo/biggraphite/7#-KI2WRIEBPAR5Uv7WJFm:-KI2WRIEBPAR5Uv7WJFn:-838894606) ([raw file](https://github.com/criteo/biggraphite/blob/b27217135397abfa480bf21bc30356564d7ed327/biggraphite/plugins/graphite.py#L111)):*
> ```Python
>         self.__refresh_metadata()
>         # Call __get_time_info with the widest conceivable range will make it be
>         # shortened to the widest range available according to retention policy.
> ```

Add a TODO to remove that once we support multiple retention policies ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/7)*

**Comment by unbrice** [comment]
Review status: 0 of 3 files reviewed at latest revision, 9 unresolved discussions.

---

*[biggraphite/plugins/graphite.py, line 111 \[r3\]](https://reviewable.io:443/reviews/criteo/biggraphite/7#-KI2WRIEBPAR5Uv7WJFm:-KI2cJKgdDWP01PpFU6w:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/b27217135397abfa480bf21bc30356564d7ed327/biggraphite/plugins/graphite.py#L111)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> Add a TODO to remove that once we support multiple retention policies ?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/7)*

**Comment by iksaif** [comment]
:lgtm: (don't forget to write unit tests in the next review)

<details><summary><i>Previously, coveralls wrote…</i></summary>
> 
> [Coverage Status](https://coveralls.io/builds/6229126)
> 
> Coverage decreased (-9.3%) to 61.741% when pulling **873753be45220735e567ab54d0a271c94870b07f on unbrice:master** into **58e2eeed651391d2322338eb3c3b89360dadf20f on criteo:master**.
> 
</details>


---

Reviewed 2 of 3 files at r1, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/7#-:-KI3KWNiPr-TMA35r04m:-951619409)*

**Comment by natbraun** [comment]
Plesae put the commit message in the infinitive :), then :lgtm:

<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> :lgtm: (don't forget to write unit tests in the next review)
</details>


---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/7#-:-KI3MVviJPySIv03lErD:-1765082168)*

**Comment by natbraun** [comment]
:lgtm_strong: 

<details><summary><i>Previously, natbraun (Nathaniel Braun) wrote…</i></summary>
> Plesae put the commit message in the infinitive :), then :lgtm:
</details>


---

Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/7#-:-KI3RylCrmcCO-oSYzyf:-1868698381)*

**Comment by unbrice** [comment]
-@iksaif  as he's away until EOW

<details><summary><i>Previously, coveralls wrote…</i></summary>
> 
> [Coverage Status](https://coveralls.io/builds/6232466)
> 
> Coverage decreased (-9.08%) to 63.443% when pulling **873753be45220735e567ab54d0a271c94870b07f on unbrice:master** into **b34c3aa6565eca192be112d7d396bebf29978deb on criteo:master**.
> 
</details>


---

Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/7#-:-KI3UILNHbR8btTaB7YB:-533475289)*

**Pull request merged**
