### PR TITLE
import_whisper: add the ability to import downsampled points

### PR DESCRIPTION
**Pull request by iksaif**
This change is [Reviewable](https://reviewable.io/reviews/criteo/biggraphite/70)

### CODE REVIEW

**Comment by iksaif** [comment]
@natbraun 

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/70#-:-KNxKo57HROUlfUOpC4b:1966696412)*

**Comment by iksaif** [comment]
ping ?

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/70#-:-KOJM0Bx1r7sYzP-tpnZ:-1334481322)*

**Comment by iksaif** [comment]
reassigned to @unbrice

**Comment by wdauchy** [comment]
Review status: 0 of 6 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[biggraphite/accessor.py, line 82 \[r3\]](https://reviewable.io:443/reviews/criteo/biggraphite/70#-KOPzEyf0Xlys5DCrJOr:-KOPzEyf0Xlys5DCrJOs:b-t3q76o) ([raw file](https://github.com/criteo/biggraphite/blob/b4a4749618b0c865287f2ae0a1d8b8bef93dfbda/biggraphite/accessor.py#L82)):*
> ```Python
>     maximum = "max"
>     total = "sum"
>     average = "average"
> ```

already fixed in 396c46ba6f5fa95 (Fix carbon plugin "average" aggregation (#72))

---

*[biggraphite/accessor.py, line 84 \[r3\]](https://reviewable.io:443/reviews/criteo/biggraphite/70#-KOPzhXKsSVq6k2mOfJN:-KOPzhXL9Ky2cZpp6NhI:bdqoipy) ([raw file](https://github.com/criteo/biggraphite/blob/b4a4749618b0c865287f2ae0a1d8b8bef93dfbda/biggraphite/accessor.py#L84)):*
> ```Python
>     average = "average"
>     last = "last"
>     # TODO: Add avg_zero.
> ```

not really needed in this commit

---

*[biggraphite/test_utils.py, line 159 \[r3\]](https://reviewable.io:443/reviews/criteo/biggraphite/70#-KOQ-ZsRxkhHkIgX6Uis:-KOQ-ZsSAdH0LCHwpq_i:b-nvwm9l) ([raw file](https://github.com/criteo/biggraphite/blob/b4a4749618b0c865287f2ae0a1d8b8bef93dfbda/biggraphite/test_utils.py#L159)):*
> ```Python
>         for datapoint in datapoints:
>             timestamp = datapoint[0]
>             value = datapoint[1]
> ```

 I would rather use "(timestamp, value) = datapoint" notation but ok for me

---

*[biggraphite/drivers/cassandra.py, line 469 \[r3\]](https://reviewable.io:443/reviews/criteo/biggraphite/70#-KOQ2xSqA53Rsd_0bnOp:-KOQ2xSqA53Rsd_0bnOq:b77c1b5) ([raw file](https://github.com/criteo/biggraphite/blob/b4a4749618b0c865287f2ae0a1d8b8bef93dfbda/biggraphite/drivers/cassandra.py#L469)):*
> ```Python
>         # Separate raw and aggregated points.
>         for datapoint in datapoints:
>             if len(datapoint) == 4:
> ```

I a bit lost with this value but it must be because I lack of context

---

*[tests/test_accessor.py, line 91 \[r3\]](https://reviewable.io:443/reviews/criteo/biggraphite/70#-KOQ-rZRNIxieYgT6eRt:-KOQ-rZRNIxieYgT6eRu:beqha3v) ([raw file](https://github.com/criteo/biggraphite/blob/b4a4749618b0c865287f2ae0a1d8b8bef93dfbda/tests/test_accessor.py#L91)):*
> ```Python
>     def test_config_names(self):
>         self.assertEqual(
>             bg_accessor.Aggregator.from_carbon_name("average"),
> ```

good point, I forgot to double check tests in Brice's review

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/70)*

**Comment by wdauchy** [comment]
Reviewed 4 of 4 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/70)*

**Comment by unbrice** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[biggraphite/accessor.py, line 84 \[r3\]](https://reviewable.io:443/reviews/criteo/biggraphite/70#-KOPzhXKsSVq6k2mOfJN:-KOQ5h6AySjWAaWQ7Uv-:b-w3cnmh) ([raw file](https://github.com/criteo/biggraphite/blob/b4a4749618b0c865287f2ae0a1d8b8bef93dfbda/biggraphite/accessor.py#L84)):*
<details><summary><i>Previously, wdauchy (William Dauchy) wrote…</i></summary>
> not really needed in this commit
</details>
OTOH it's probably not worth doing another review just to add a TODO

---

*[biggraphite/test_utils.py, line 159 \[r3\]](https://reviewable.io:443/reviews/criteo/biggraphite/70#-KOQ-ZsRxkhHkIgX6Uis:-KOQ5yexnWuuYqSc83KR:b1q7gwk) ([raw file](https://github.com/criteo/biggraphite/blob/b4a4749618b0c865287f2ae0a1d8b8bef93dfbda/biggraphite/test_utils.py#L159)):*
<details><summary><i>Previously, wdauchy (William Dauchy) wrote…</i></summary>
>  I would rather use "(timestamp, value) = datapoint" notation but ok for me
</details>
this part of the change only makes the code more verbose

---

*[biggraphite/drivers/cassandra.py, line 469 \[r3\]](https://reviewable.io:443/reviews/criteo/biggraphite/70#-KOQ2xSqA53Rsd_0bnOp:-KOQ69xo3JZydguqaijM:b-plzsdc) ([raw file](https://github.com/criteo/biggraphite/blob/b4a4749618b0c865287f2ae0a1d8b8bef93dfbda/biggraphite/drivers/cassandra.py#L469)):*
<details><summary><i>Previously, wdauchy (William Dauchy) wrote…</i></summary>
> I a bit lost with this value but it must be because I lack of context
</details>
According to the pydoc datapoints contains tuples of length four. This looks like broken code: callee should be changing arguments so that they match insert_points_async, not the opposite. Also this will break TestAccessor...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/70)*

**Comment by unbrice** [comment]
Taking over as discussed.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/70#-:-KOQ7CTGm7c9Zcl4SrMA:bynuaa0)*

**Comment by unbrice** [comment]
This is superseded by #76

**Comment by iksaif** [comment]
This superseeds #76 

---

Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/70#-:-KPlYFl-WytwM4yZVvmf:bodcshm)*

**Comment by iksaif** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[biggraphite/accessor.py, line 82 \[r3\]](https://reviewable.io:443/reviews/criteo/biggraphite/70#-KOPzEyf0Xlys5DCrJOr:-KPlYPNeAdCiJGnfpeol:b-896fix) ([raw file](https://github.com/criteo/biggraphite/blob/b4a4749618b0c865287f2ae0a1d8b8bef93dfbda/biggraphite/accessor.py#L82)):*
<details><summary><i>Previously, wdauchy (William Dauchy) wrote…</i></summary>
> already fixed in 396c46ba6f5fa95 (Fix carbon plugin "average" aggregation (#72))
</details>
Done.

---

*[biggraphite/accessor.py, line 84 \[r3\]](https://reviewable.io:443/reviews/criteo/biggraphite/70#-KOPzhXKsSVq6k2mOfJN:-KPlYPuEzyRQiOgeSpkW:b-896fix) ([raw file](https://github.com/criteo/biggraphite/blob/b4a4749618b0c865287f2ae0a1d8b8bef93dfbda/biggraphite/accessor.py#L84)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> OTOH it's probably not worth doing another review just to add a TODO
</details>
Done.

---

*[biggraphite/drivers/cassandra.py, line 469 \[r3\]](https://reviewable.io:443/reviews/criteo/biggraphite/70#-KOQ2xSqA53Rsd_0bnOp:-KPlYR7nOUiEl95hrzpv:b-896fix) ([raw file](https://github.com/criteo/biggraphite/blob/b4a4749618b0c865287f2ae0a1d8b8bef93dfbda/biggraphite/drivers/cassandra.py#L469)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> According to the pydoc datapoints contains tuples of length four. This looks like broken code: callee should be changing arguments so that they match insert_points_async, not the opposite. Also this will break TestAccessor...
</details>
Done.

---

*[biggraphite/test_utils.py, line 159 \[r3\]](https://reviewable.io:443/reviews/criteo/biggraphite/70#-KOQ-ZsRxkhHkIgX6Uis:-KPlYS3FBZv2rsdIEKJB:b-896fix) ([raw file](https://github.com/criteo/biggraphite/blob/b4a4749618b0c865287f2ae0a1d8b8bef93dfbda/biggraphite/test_utils.py#L159)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> this part of the change only makes the code more verbose
</details>
Done.

---

*[tests/test_accessor.py, line 91 \[r3\]](https://reviewable.io:443/reviews/criteo/biggraphite/70#-KOQ-rZRNIxieYgT6eRt:-KPlYSyn9cZ-tq0ijyVx:b-896fix) ([raw file](https://github.com/criteo/biggraphite/blob/b4a4749618b0c865287f2ae0a1d8b8bef93dfbda/tests/test_accessor.py#L91)):*
<details><summary><i>Previously, wdauchy (William Dauchy) wrote…</i></summary>
> good point, I forgot to double check tests in Brice's review
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/70)*

**Comment by wdauchy** [comment]
:lgtm:

---

Reviewed 5 of 6 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/70#-:-KPm4FZlFKf7nwB88_lo:bnfp4nl)*

**Pull request merged**
