### PR TITLE
WIP Implement a new way to do disk cache

### PR DESCRIPTION
**Pull request by geobeau**
Attempt at improving disk cache and simplify the implementation.

### CODE REVIEW

**Comment by iksaif** [comment]
Note: if we finish re-writing the way metrics are globbed, the disk cache can go away because graphite-web will not need it anymore :)

**Comment by geobeau** [comment]
It's used by carbon. But we are investigating if we need something like this or not

**Comment by iksaif** [comment]
Carbon is not supposed to use the disk cache

**Comment by geobeau** [comment]
Because it's too slow? Goal would be to have a cache that survives the restart of a process

**Comment by iksaif** [comment]
Because it was too problematic (because of locking) and too slow (including the `has` function). The workaround was to make startup work without the cache and slowly create the metrics if necessary after startup (the rate is not configurable but could be, it also probably lacks back-pressure).

**Comment by geobeau** [comment]
Ok, thanks for the informations!

**Pull request closed without merging**
