### PR TITLE
Implement aggregation mechanism

### PR DESCRIPTION
**Pull request by natbraun**
@iksaif: I did something wrong, I'm sorry. So I'm creating this new PR.

---
This change is [Reviewable](https://reviewable.io/reviews/criteo/biggraphite/48)

### CODE REVIEW

**Comment by iksaif** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[biggraphite/drivers/aggregate.py, line 1 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/48#-KMxJJvRJ_U3cpl6L3RT:-KMxJJvS42X33-1mSWEC:-1810629391) ([raw file](https://github.com/criteo/biggraphite/blob/76fbec3fdcaedd34a9fef674cd07be7e83a93c70/biggraphite/drivers/aggregate.py#L1)):*
> ```Python
> #!/usr/bin/env python
> ```

could this be in downsampling.py ?

---

*[biggraphite/drivers/aggregate.py, line 72 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/48#-KMxJZQLvxDAE5X_51mg:-KMxJZQLvxDAE5X_51mh:-365969130) ([raw file](https://github.com/criteo/biggraphite/blob/76fbec3fdcaedd34a9fef674cd07be7e83a93c70/biggraphite/drivers/aggregate.py#L72)):*
> ```Python
>                 old_count = current_point[1]
>                 aggregated_value = self._aggregator.merge(old_value, old_count, value)
>                 res[-1] = (current_point[0], current_point[1] + 1, aggregated_value)
> ```

Will this really work if there are multiple points for the current epoch ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/48)*

**Comment by iksaif** [comment]
Review status: 0 of 2 files reviewed at latest revision, 7 unresolved discussions.

---

*[biggraphite/drivers/aggregate.py, line 54 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/48#-KMxKu4jzTjeof_JBnvO:-KMxKu4jzTjeof_JBnvP:1984050691) ([raw file](https://github.com/criteo/biggraphite/blob/76fbec3fdcaedd34a9fef674cd07be7e83a93c70/biggraphite/drivers/aggregate.py#L54)):*
> ```Python
> 
>         Returns:
>           Iterable of (timestamp, count, value).
> ```

Please use (timestamp, value, count, self.precision)

---

*[biggraphite/drivers/aggregate.py, line 68 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/48#-KMxLEI28EaUcxbAKLLh:-KMxLEI28EaUcxbAKLLi:-349763028) ([raw file](https://github.com/criteo/biggraphite/blob/76fbec3fdcaedd34a9fef674cd07be7e83a93c70/biggraphite/drivers/aggregate.py#L68)):*
> ```Python
>                 res[0] = (epoch, 1, value)
>             elif current_epoch == epoch:
>                 # point is in current epoch => aggregate
> ```

add a comment to explain what you're doing here

---

*[biggraphite/drivers/aggregate.py, line 72 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/48#-KMxJZQLvxDAE5X_51mg:-KMxL7eESjSaLAZEC8od:-1957616144) ([raw file](https://github.com/criteo/biggraphite/blob/76fbec3fdcaedd34a9fef674cd07be7e83a93c70/biggraphite/drivers/aggregate.py#L72)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> Will this really work if there are multiple points for the current epoch ?
</details>
yes it does

---

*[biggraphite/drivers/aggregate.py, line 103 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/48#-KMxLX-SVrel_KHbthZr:-KMxLX-SVrel_KHbthZs:-1238820230) ([raw file](https://github.com/criteo/biggraphite/blob/76fbec3fdcaedd34a9fef674cd07be7e83a93c70/biggraphite/drivers/aggregate.py#L103)):*
> ```Python
> 
>     __slots__ = (
>         "_stage",
> ```

stages

---

*[biggraphite/drivers/aggregate.py, line 124 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/48#-KMxLr21U6ia6M-j0tQd:-KMxLr21U6ia6M-j0tQe:653610098) ([raw file](https://github.com/criteo/biggraphite/blob/76fbec3fdcaedd34a9fef674cd07be7e83a93c70/biggraphite/drivers/aggregate.py#L124)):*
> ```Python
> 
>         Returns:
>           Iterable of iterables of (timestamp, value).
> ```

Return (timestamp, value, count, step)

---

*[biggraphite/drivers/aggregate.py, line 140 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/48#-KMxLtfizv3DzWIFnPtF:-KMxLtfizv3DzWIFnPtG:678021867) ([raw file](https://github.com/criteo/biggraphite/blob/76fbec3fdcaedd34a9fef674cd07be7e83a93c70/biggraphite/drivers/aggregate.py#L140)):*
> ```Python
> 
>         Returns:
>           Iterable of iterables of (timestamp, value).
> ```

same

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/48)*

**Comment by natbraun** [comment]
Review status: 0 of 2 files reviewed at latest revision, 7 unresolved discussions.

---

*[biggraphite/drivers/aggregate.py, line 1 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/48#-KMxJJvRJ_U3cpl6L3RT:-KMxPj4kEGZUztNgs5nT:676635175) ([raw file](https://github.com/criteo/biggraphite/blob/76fbec3fdcaedd34a9fef674cd07be7e83a93c70/biggraphite/drivers/aggregate.py#L1)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> could this be in downsampling.py ?
</details>
Done

---

*[biggraphite/drivers/aggregate.py, line 54 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/48#-KMxKu4jzTjeof_JBnvO:-KMxQrHs2nK3nz-T55WL:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/76fbec3fdcaedd34a9fef674cd07be7e83a93c70/biggraphite/drivers/aggregate.py#L54)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> Please use (timestamp, value, count, self.precision)
</details>
Done.

---

*[biggraphite/drivers/aggregate.py, line 68 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/48#-KMxLEI28EaUcxbAKLLh:-KMxQq9_fHiaVBmroTWy:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/76fbec3fdcaedd34a9fef674cd07be7e83a93c70/biggraphite/drivers/aggregate.py#L68)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> add a comment to explain what you're doing here
</details>
Done.

---

*[biggraphite/drivers/aggregate.py, line 72 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/48#-KMxJZQLvxDAE5X_51mg:-KMxRp6xTlPpiCIxIvxP:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/76fbec3fdcaedd34a9fef674cd07be7e83a93c70/biggraphite/drivers/aggregate.py#L72)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> yes it does
</details>
Done.

---

*[biggraphite/drivers/aggregate.py, line 103 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/48#-KMxLX-SVrel_KHbthZr:-KMxSDJirJ9EOxgoM9cw:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/76fbec3fdcaedd34a9fef674cd07be7e83a93c70/biggraphite/drivers/aggregate.py#L103)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> stages
</details>
Done.

---

*[biggraphite/drivers/aggregate.py, line 124 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/48#-KMxLr21U6ia6M-j0tQd:-KMxSNyEN8DEx9JQqweF:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/76fbec3fdcaedd34a9fef674cd07be7e83a93c70/biggraphite/drivers/aggregate.py#L124)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> Return (timestamp, value, count, step)
</details>
Done.

---

*[biggraphite/drivers/aggregate.py, line 140 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/48#-KMxLtfizv3DzWIFnPtF:-KMxSP58Y3ZZVMDc_3Mo:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/76fbec3fdcaedd34a9fef674cd07be7e83a93c70/biggraphite/drivers/aggregate.py#L140)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> same
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/48)*

**Comment by iksaif** [comment]
:lgtm_strong: 

---

Reviewed 2 of 4 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/48#-:-KMxb3m_nzgYss6tYv5x:-1868698381)*

**Pull request merged**
