### PR TITLE
accessor: add some sugar to Retention and Stage

### PR DESCRIPTION
**Pull request by iksaif**
This change is [Reviewable](https://reviewable.io/reviews/criteo/biggraphite/43)

### CODE REVIEW

**Comment by natbraun** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[biggraphite/accessor.py, line 289 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/43#-KM3dgu7VKcx5u3jpaPv:-KM3dgu7VKcx5u3jpaPw:-724433922) ([raw file](https://github.com/criteo/biggraphite/blob/a4b7c4e1338f259a0b3a9434593f8728d42a6283/biggraphite/accessor.py#L289)):*
> ```Python
>         """Round down a timestamp to a multiple of the precision."""
>         return round_up(timestamp, self.precision)
> ```

Doesn't this introduce an infinite loop? I'm confused...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/43)*

**Comment by iksaif** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[biggraphite/accessor.py, line 289 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/43#-KM3dgu7VKcx5u3jpaPv:-KM3eJb-qtk6EIU1kBlq:-1999309407) ([raw file](https://github.com/criteo/biggraphite/blob/a4b7c4e1338f259a0b3a9434593f8728d42a6283/biggraphite/accessor.py#L289)):*
<details><summary><i>Previously, natbraun (Nathaniel Braun) wrote…</i></summary>
> Doesn't this introduce an infinite loop? I'm confused...
</details>
it doesn't call 'self.round_up' it calls a normal function :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/43)*

**Comment by natbraun** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/43#-:-KM3fIUotjuryPgBrEAy:1417088721)*

**Comment by natbraun** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/43)*

**Comment by iksaif** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[biggraphite/accessor.py, line 289 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/43#-KM3dgu7VKcx5u3jpaPv:-KM3haXBhuV_T5jaVkqZ:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/a4b7c4e1338f259a0b3a9434593f8728d42a6283/biggraphite/accessor.py#L289)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> it doesn't call 'self.round_up' it calls a normal function :)
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/43)*

**Pull request merged**
