### PR TITLE
Add UUID to metrics

### PR DESCRIPTION
**Pull request by natbraun**
This change is [Reviewable](https://reviewable.io/reviews/criteo/biggraphite/113)

### CODE REVIEW

**Comment by iksaif** [comment]
Review status: 0 of 9 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[biggraphite/accessor.py, line 525 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/113#-KR9xKWi7VO5ZM9sb7xe:-KR9xKWi7VO5ZM9sb7xf:bnaoejt) ([raw file](https://github.com/criteo/biggraphite/blob/18ac371de77087fcb863d1a8d793db13c6e3f0e7/biggraphite/accessor.py#L525)):*
> ```Python
>         assert metadata, "Metric: metadata is None"
>         self.name = encode_metric_name(name)
>         self.id = id
> ```

What's the type of "id" ? Maybe it should be of type https://docs.python.org/2/library/uuid.html

---

*[biggraphite/accessor.py, line 539 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/113#-KR9xBxisG0EncHJ8gL1:-KR9xBxjhCGV_k2PQFzZ:b-jue2os) ([raw file](https://github.com/criteo/biggraphite/blob/18ac371de77087fcb863d1a8d793db13c6e3f0e7/biggraphite/accessor.py#L539)):*
> ```Python
>     def as_json(self):
>         """Serialize Metric into a JSON string for serialization."""
>         return str(self.id) + _ID_SEPARATOR + self.metadata.as_json()
> ```

This isn't really 'json' anymore. You probably want to do this in the cache anyway as this is really specific to the cache.

---

*[biggraphite/metadata_cache.py, line 156 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/113#-KR9x_elVpK4kg1VIRLJ:-KR9x_elVpK4kg1VIRLK:b-byeue7) ([raw file](https://github.com/criteo/biggraphite/blob/18ac371de77087fcb863d1a8d793db13c6e3f0e7/biggraphite/metadata_cache.py#L156)):*
> ```Python
>         with self.__env.begin(self.__metric_to_metadata_db, write=False) as txn:
>             id_metadata = txn.get(encoded_metric_name)
> ```

This function is becoming pretty big, we probably want to split it in multiple private functions. One for a valid hit, one for an invalid hit and one for a miss

---

*[biggraphite/test_utils.py, line 119 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/113#-KR9xubi7nkm6oPRTcxg:-KR9xubi7nkm6oPRTcxh:b-w3wuai) ([raw file](https://github.com/criteo/biggraphite/blob/18ac371de77087fcb863d1a8d793db13c6e3f0e7/biggraphite/test_utils.py#L119)):*
> ```Python
> def make_metric(name, metadata=None, **kwargs):
>     """Create a bg_accessor.Metric with specified metadata."""
>     id = uuid.uuid4()
> ```

why not a uuid5 based on the metric name ?

---

*[biggraphite/plugins/carbon.py, line 103 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/113#-KR9y5p28lS8_qYE5BCq:-KR9y5p28lS8_qYE5BCr:b-646q7h) ([raw file](https://github.com/criteo/biggraphite/blob/18ac371de77087fcb863d1a8d793db13c6e3f0e7/biggraphite/plugins/carbon.py#L103)):*
> ```Python
> 
>     def create(self, metric_name, retentions, xfilesfactor, aggregation_method):
>         id = uuid.uuid4()
> ```

This should be the responsibility of the accessor and not of the callers to generate the uuid

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/113)*

**Comment by natbraun** [comment]
Review status: 0 of 9 files reviewed at latest revision, 5 unresolved discussions.

---

*[biggraphite/accessor.py, line 525 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/113#-KR9xKWi7VO5ZM9sb7xe:-KRCwWvt0lfjNG7Q7qJ9:b-j6a49b) ([raw file](https://github.com/criteo/biggraphite/blob/18ac371de77087fcb863d1a8d793db13c6e3f0e7/biggraphite/accessor.py#L525)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> What's the type of "id" ? Maybe it should be of type https://docs.python.org/2/library/uuid.html
</details>
Yes, it's a UUID. However, I don't know how to enforce this in Python.

---

*[biggraphite/accessor.py, line 539 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/113#-KR9xBxisG0EncHJ8gL1:-KRD5GIMkX6nKkQiNPsf:b-896fix) ([raw file](https://github.com/criteo/biggraphite/blob/18ac371de77087fcb863d1a8d793db13c6e3f0e7/biggraphite/accessor.py#L539)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> This isn't really 'json' anymore. You probably want to do this in the cache anyway as this is really specific to the cache.
</details>
Done.

---

*[biggraphite/test_utils.py, line 119 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/113#-KR9xubi7nkm6oPRTcxg:-KRD5brOK0FNj4NtQnX5:b-acw3n) ([raw file](https://github.com/criteo/biggraphite/blob/18ac371de77087fcb863d1a8d793db13c6e3f0e7/biggraphite/test_utils.py#L119)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> why not a uuid5 based on the metric name ?
</details>
I followed the Python doc:
If all you want is a unique ID, you should probably call uuid1() or uuid4(). Note that uuid1() may compromise privacy since it creates a UUID containing the computer’s network address. uuid4() creates a random UUID.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/113)*

**Comment by iksaif** [comment]
:lgtm_strong: 

---

Review status: 0 of 9 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[biggraphite/accessor.py, line 525 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/113#-KR9xKWi7VO5ZM9sb7xe:-KRDjSTc28WbK1gxeuj7:b-nyuhon) ([raw file](https://github.com/criteo/biggraphite/blob/18ac371de77087fcb863d1a8d793db13c6e3f0e7/biggraphite/accessor.py#L525)):*
<details><summary><i>Previously, natbraun (Nathaniel Braun) wrote…</i></summary>
> Yes, it's a UUID. However, I don't know how to enforce this in Python.
</details>
forget that.

---

*[biggraphite/metadata_cache.py, line 159 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/113#-KRDmEYEFIroiKqy_415:-KRDmEYEFIroiKqy_416:bix8ga8) ([raw file](https://github.com/criteo/biggraphite/blob/0eb0f7e6746d8d65867b216e581a14d79b18cdaf/biggraphite/metadata_cache.py#L159)):*
> ```Python
>             id_metadata = txn.get(encoded_metric_name)
> 
>         if id_metadata:
> ```

if not id_metadata:
  return None

---

*[biggraphite/metadata_cache.py, line 190 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/113#-KRDm_2hvq5ay198aIiA:-KRDm_2hvq5ay198aIiB:b-cdfwyg) ([raw file](https://github.com/criteo/biggraphite/blob/0eb0f7e6746d8d65867b216e581a14d79b18cdaf/biggraphite/metadata_cache.py#L190)):*
> ```Python
>             with self.__accessor_lock:
>                 metric = self.__accessor.get_metric(metric_name)
>                 self._cache(metric)
> ```

shift to the left, no need for the lock

---

*[biggraphite/test_utils.py, line 119 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/113#-KR9xubi7nkm6oPRTcxg:-KRDkFpzaiDByFzz2e5u:bfetw05) ([raw file](https://github.com/criteo/biggraphite/blob/18ac371de77087fcb863d1a8d793db13c6e3f0e7/biggraphite/test_utils.py#L119)):*
<details><summary><i>Previously, natbraun (Nathaniel Braun) wrote…</i></summary>
> I followed the Python doc:
> If all you want is a unique ID, you should probably call uuid1() or uuid4(). Note that uuid1() may compromise privacy since it creates a UUID containing the computer’s network address. uuid4() creates a random UUID.
</details>
we don't need privacy and randomness. We need a unique identifier for each metric. And by using uuid5() we have some advantages (we don't need to synchronize creations for example).

---

*[biggraphite/drivers/cassandra.py, line 311 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/113#-KRDkoz9BTkM4WUz65Zz:-KRDkoz9BTkM4WUz65_-:b-uatgjm) ([raw file](https://github.com/criteo/biggraphite/blob/0eb0f7e6746d8d65867b216e581a14d79b18cdaf/biggraphite/drivers/cassandra.py#L311)):*
> ```Python
>     _DEFAULT_CASSANDRA_PORT = 9042
> 
>     _UUID_NAMESPACE = uuid.UUID('{00000000-1111-2222-3333-444444444444}')
> ```

maybe just put zero's everywhere.

---

*[biggraphite/drivers/memory.py, line 36 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/113#-KRDkuomqcqhWIhmEuhF:-KRDkuomqcqhWIhmEuhG:b3x71st) ([raw file](https://github.com/criteo/biggraphite/blob/0eb0f7e6746d8d65867b216e581a14d79b18cdaf/biggraphite/drivers/memory.py#L36)):*
> ```Python
>         'Row', ['time_start_ms', 'offset', 'value', 'count'])
> 
>     _UUID_NAMESPACE = uuid.UUID('{00000000-1111-2222-3333-444444444444}')
> ```

since it's both in cassandra and memory, it should probably be in accessor.py

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/113#-:-KREarMmo70r9iAsbWUS:b-uwkowd)*

**Comment by iksaif** [comment]
Reviewed 2 of 9 files at r1, 4 of 6 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/113)*

**Pull request merged**
