### PR TITLE
Add new double-write plugins

### PR DESCRIPTION
**Pull request by iksaif**
This change is [Reviewable](https://reviewable.io/reviews/criteo/biggraphite/114)

### CODE REVIEW

**Comment by natbraun** [comment]
Reviewed 4 of 5 files at r1.
Review status: 4 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[biggraphite/plugins/carbon.py, line 142 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/114#-KRE4oSS36WOF3F2Uf4U:-KRE4oSS36WOF3F2Uf4V:b-kbjknv) ([raw file](https://github.com/criteo/biggraphite/blob/946b3d9feddb769190dbe5516f79568daac7d667/biggraphite/plugins/carbon.py#L142)):*
> ```Python
>     metaclass.
> 
>     This class allow to use multiple existing database plugin at the same time.
> ```

small typos:
  - allows using
  - plugins

---

*[biggraphite/plugins/carbon.py, line 155 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/114#-KRE4xKmQUlqqZ-XK8fW:-KRE4xKmQUlqqZ-XK8fX:b-f5momr) ([raw file](https://github.com/criteo/biggraphite/blob/946b3d9feddb769190dbe5516f79568daac7d667/biggraphite/plugins/carbon.py#L155)):*
> ```Python
>         exists = False
>         for db in self._dbs:
>             exists |= db.exists(metric_name)
> ```

Why not return early? something like
return true if db.exists(metric_name)

---

*[biggraphite/plugins/carbon.py, line 155 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/114#-KRE50uYnh5LYrISTb4Q:-KRE50uYnh5LYrISTb4R:bocb3xe) ([raw file](https://github.com/criteo/biggraphite/blob/946b3d9feddb769190dbe5516f79568daac7d667/biggraphite/plugins/carbon.py#L155)):*
> b.exists(metric_name)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/114)*

**Comment by natbraun** [comment]
Reviewed 1 of 5 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/114)*

**Comment by natbraun** [comment]
:lgtm_strong: 

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/114#-:-KREA4NR-QnxevzY_0Kx:b-uwkowd)*

**Comment by iksaif** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[biggraphite/plugins/carbon.py, line 142 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/114#-KRE4oSS36WOF3F2Uf4U:-KRERJu275S7k_JrFCMU:b-896fix) ([raw file](https://github.com/criteo/biggraphite/blob/946b3d9feddb769190dbe5516f79568daac7d667/biggraphite/plugins/carbon.py#L142)):*
<details><summary><i>Previously, natbraun (Nathaniel Braun) wrote…</i></summary>
> small typos:
>   - allows using
>   - plugins
</details>
Done.

---

*[biggraphite/plugins/carbon.py, line 155 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/114#-KRE4xKmQUlqqZ-XK8fW:-KRERKq5_Cp1k3-UPGC_:b-jxcv72) ([raw file](https://github.com/criteo/biggraphite/blob/946b3d9feddb769190dbe5516f79568daac7d667/biggraphite/plugins/carbon.py#L155)):*
<details><summary><i>Previously, natbraun (Nathaniel Braun) wrote…</i></summary>
> Why not return early? something like
> return true if db.exists(metric_name)
> 
</details>
This way if it's missing in any of the DB we re-create it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/114)*

**Pull request merged**
