### PR TITLE
Bgutil daemon

### PR DESCRIPTION
**Pull request by erebe**
Work in-progress, leave feedback anyway

---
This change is [Reviewable](https://reviewable.io/reviews/criteo/biggraphite/195)

### CODE REVIEW

**Comment by iksaif** [comment]
Maybe add a unit test just to check that you can start. You'll probably need a method to stop/kill the threads.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[biggraphite/cli/command_daemon.py, line 126 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/195#-KXkz-LYPnOHS18CGWbP:-KXkz-LYPnOHS18CGWbQ:bnb8vfs) ([raw file](https://github.com/criteo/biggraphite/blob/c703fd992cf441abe36e05feb60ec8e43085e3b6/biggraphite/cli/command_daemon.py#L126)):*
> ```Python
> 
>         http_handler = SimpleHTTPServer.SimpleHTTPRequestHandler
>         http_handler.do_GET = get_handler
> ```

Can you also add a /health handler ?
It should return
- 'OK' (200) is both threads are running
- 'Failure (reason)' (503) is one of the thread seems down.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/195#-:-KXkykNgeQ9kx4Tu83Lg:bfo0f0z)*

**Comment by erebe** [comment]
Already on it

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[biggraphite/cli/command_daemon.py, line 126 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/195#-KXkz-LYPnOHS18CGWbP:-KXl-ZtTFP3rOTpSNzUd:b32wtd) ([raw file](https://github.com/criteo/biggraphite/blob/c703fd992cf441abe36e05feb60ec8e43085e3b6/biggraphite/cli/command_daemon.py#L126)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary><blockquote>

Can you also add a /health handler ?
It should return
- 'OK' (200) is both threads are running
- 'Failure (reason)' (503) is one of the thread seems down.
</blockquote></details>

ok

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/195#-:-KXl-ccAX2RbSa0yjRC0:b6iywqn)*

**Comment by iksaif** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[tests/test_bgutil.py, line 24 at r2](https://reviewable.io:443/reviews/criteo/biggraphite/195#-KXlIbrNbZ57Ii7ZJ_EE:-KXlIbrNbZ57Ii7ZJ_EF:b-n82c1s) ([raw file](https://github.com/criteo/biggraphite/blob/2f8ee8a6bab710e59b864747cc1acf2f20eef441/tests/test_bgutil.py#L24)):*
> ```Python
> 
> from biggraphite.cli import bgutil
> from biggraphite.cli import command_daemon
> ```

usually commands are tested in separate test files (see the other test_command_*)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/195)*

**Comment by iksaif** [comment]
:lgtm_strong: , but you'll need to rebase and wait for travis to complete :)

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/195#-:-KXoP84WhTGQs_q2eR2B:b-d8t6ie)*

**Pull request merged**
