### PR TITLE
Cleanup documentation

### PR DESCRIPTION
**Pull request by dpanth3r**
- Make it clearer by reformulating vague parts
- Make bash commands copy-pastable (drop the prefixing currency units)
- Make the style consistent

---
This change is [Reviewable](https://reviewable.io/reviews/criteo/biggraphite/101)

### CODE REVIEW

**Comment by iksaif** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[CASSANDRA_DESIGN.md, line 56 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/101#-KQZmS_QidqmFN5wYb3K:-KQZmS_QidqmFN5wYb3L:b-vcl138) ([raw file](https://github.com/criteo/biggraphite/blob/90de181f73ab3804495b416f85e1df16475d4812/CASSANDRA_DESIGN.md#L56)):*
> ```Markdown
> 
> A metric's metadata contains:
> - UUID
> ```

We actually don't have the UUID yet .. we really should though. It would save some space.

---

*[CASSANDRA_DESIGN.md, line 56 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/101#-KQZmEGe_T_djDPUv7sZ:-KQZmEGe_T_djDPUv7s_:bh4z5qj) ([raw file](https://github.com/criteo/biggraphite/blob/90de181f73ab3804495b416f85e1df16475d4812/CASSANDRA_DESIGN.md#L56)):*
> ```Markdown
> 
> A metric's metadata contains:
> - UUID
> ```

the metric metadata currently doesn't contain a UUID ... we should implement that thoug

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/101)*

**Comment by dpanth3r** [comment]
Lol.

**Comment by iksaif** [comment]
:lgtm:

---

Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/101#-:-KQbDkaRHTPxTA9_fY9L:bnfp4nl)*

**Comment by iksaif** [comment]
:lgtm_strong: 

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/101#-:-KQbL6o03ZQcZ1PkfNRX:b-uwkowd)*

**Comment by iksaif** [comment]
please rebase

**Comment by iksaif** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[CASSANDRA_DESIGN.md, line 56 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/101#-KQZmEGe_T_djDPUv7sZ:-KREb4EVuh4T2s6VjNr6:be9knz) ([raw file](https://github.com/criteo/biggraphite/blob/90de181f73ab3804495b416f85e1df16475d4812/CASSANDRA_DESIGN.md#L56)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> the metric metadata currently doesn't contain a UUID ... we should implement that thoug
</details>
now it does

---

*[CASSANDRA_DESIGN.md, line 56 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/101#-KQZmS_QidqmFN5wYb3K:-KREb5a5toXHG1nz5qjV:bqo1l9q) ([raw file](https://github.com/criteo/biggraphite/blob/90de181f73ab3804495b416f85e1df16475d4812/CASSANDRA_DESIGN.md#L56)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> We actually don't have the UUID yet .. we really should though. It would save some space.
</details>
now we do

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/101)*

**Comment by iksaif** [comment]
merged it :)

**Pull request closed without merging**
