### PR TITLE
Touch metrics in Cassandra backend on timestamp cache update.

### PR DESCRIPTION
**Pull request by rveznaver**
Touching the metric in the backend metadata table will enable us to clean expired metrics based on ```WRITETIME (config)``` where config is the metric metadata. This avoids changing the data structure since, unlike lmdb, the write timestamp is already present for a given value.

---
This change is [Reviewable](https://reviewable.io/reviews/criteo/biggraphite/170)

### CODE REVIEW

**Comment by dpanth3r** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[biggraphite/drivers/memory.py, line 126 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/170#-KVaGONWVT45Du4bLgmJ:-KVaGONWVT45Du4bLgmK:bwz2o0e) ([raw file](https://github.com/criteo/biggraphite/blob/b699548b24eafddf993bf0157096ec22ef7a83b3/biggraphite/drivers/memory.py#L126)):*
> ```Python
>             self._directory_names.add(".".join(path))
> 
>     # TODO: implement touch metric for memory driver
> ```

Is that TODO left here by design? :-)
In case it is, can you leave your name close to it, so that we know who to ping for eventual details?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/170)*

**Comment by dpanth3r** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/170)*

**Comment by dpanth3r** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[biggraphite/drivers/cassandra.py, line 551 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/170#-KVaH2xK_2pWnG7JSmha:-KVaH2xK_2pWnG7JSmhb:b-jqrgj6) ([raw file](https://github.com/criteo/biggraphite/blob/b699548b24eafddf993bf0157096ec22ef7a83b3/biggraphite/drivers/cassandra.py#L551)):*
> ```Python
>         )
>         self.__touch_metrics_statement = self.__session.prepare(
>             "INSERT INTO \"%s\".metrics (name, config) VALUES (?, ?);"
> ```

Additionally, I am not sure that overwriting the configuration is the least-overhead method.
Did you have time for benchmarks/stress-testing in the end?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/170)*

**Comment by rveznaver** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[biggraphite/drivers/cassandra.py, line 551 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/170#-KVaH2xK_2pWnG7JSmha:-KVdOXtQ0hFCQMie0JiY:b-9deeqd) ([raw file](https://github.com/criteo/biggraphite/blob/b699548b24eafddf993bf0157096ec22ef7a83b3/biggraphite/drivers/cassandra.py#L551)):*
<details><summary><i>Previously, dpanth3r (Dan Forest) wrote…</i></summary>
> Additionally, I am not sure that overwriting the configuration is the least-overhead method.
> Did you have time for benchmarks/stress-testing in the end?
</details>
This seemed less intrusive than adding a timestamp field and overwriting that. In both case we end up overwriting a field, so might as well not change the schema and use the timestamp that gets written anyway.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/170)*

**Comment by rveznaver** [comment]
Please do not merge this. We have to add a column as the function writetime() may not be used in a where clause.

**Comment by iksaif** [comment]
Add bgutil clean ?

---

Review status: 1 of 12 files reviewed at latest revision, 5 unresolved discussions.

---

*[biggraphite/accessor.py, line 620 at r3](https://reviewable.io:443/reviews/criteo/biggraphite/170#-KW28Go8QR18WGLuWTvo:-KW28Go8QR18WGLuWTvp:bkdczpc) ([raw file](https://github.com/criteo/biggraphite/blob/35d93311c5ea8cb5192df9152b2b65554fbf0d38/biggraphite/accessor.py#L620)):*
> ```Python
> 
>     @abc.abstractmethod
>     def touch_metric(self, metric):
> ```

Can we have update_metric(self, metric, metadata) instead ?
On top of updating the timestamp it will allow us to refresh potentially changed metadata.

---

*[biggraphite/drivers/cassandra.py, line 988 at r3](https://reviewable.io:443/reviews/criteo/biggraphite/170#-KW28sgRSaNeSp9rEO2a:-KW28sgRSaNeSp9rEO2b:b-cxac0j) ([raw file](https://github.com/criteo/biggraphite/blob/35d93311c5ea8cb5192df9152b2b65554fbf0d38/biggraphite/drivers/cassandra.py#L988)):*
> ```Python
>                 )
> 
>     def clean(self, cutoff, batch_size=10000):
> ```

maybe add ways to shard the cleanups ? Were you able to benchmark it in preprod ?

---

*[biggraphite/drivers/cassandra.py, line 989 at r3](https://reviewable.io:443/reviews/criteo/biggraphite/170#-KW28jJAIzTeL1Tqtd8L:-KW28jJAIzTeL1Tqtd8M:b-fyu6ys) ([raw file](https://github.com/criteo/biggraphite/blob/35d93311c5ea8cb5192df9152b2b65554fbf0d38/biggraphite/drivers/cassandra.py#L989)):*
> ```Python
> 
>     def clean(self, cutoff, batch_size=10000):
>         """See bg_accessor.Accessor."""
> ```

please describe the arguments in the docstring

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/170#-:-KW2973pJo75eIZWf9kv:b75ngur)*

**Comment by rveznaver** [comment]
Review status: 1 of 12 files reviewed at latest revision, 5 unresolved discussions.

---

*[biggraphite/accessor.py, line 620 at r3](https://reviewable.io:443/reviews/criteo/biggraphite/170#-KW28Go8QR18WGLuWTvo:-KW2Wcm82cKYy_S5nre1:b4l35db) ([raw file](https://github.com/criteo/biggraphite/blob/35d93311c5ea8cb5192df9152b2b65554fbf0d38/biggraphite/accessor.py#L620)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> Can we have update_metric(self, metric, metadata) instead ?
> On top of updating the timestamp it will allow us to refresh potentially changed metadata.
</details>
We could, but would rather if we pushed this before deciding to piggyback for the metadata change.

---

*[biggraphite/drivers/cassandra.py, line 988 at r3](https://reviewable.io:443/reviews/criteo/biggraphite/170#-KW28sgRSaNeSp9rEO2a:-KW2VpwIkLCqYaXOuK5h:butq47c) ([raw file](https://github.com/criteo/biggraphite/blob/35d93311c5ea8cb5192df9152b2b65554fbf0d38/biggraphite/drivers/cassandra.py#L988)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> maybe add ways to shard the cleanups ? Were you able to benchmark it in preprod ?
</details>
Didn't see the point in adding sharding without parallelism.
Waiting for this PR for the benchmark (so we can have the timestamp column).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/170)*

**Comment by iksaif** [comment]
Review status: 1 of 12 files reviewed at latest revision, 6 unresolved discussions.

---

*[biggraphite/drivers/cassandra.py, line 199 at r3](https://reviewable.io:443/reviews/criteo/biggraphite/170#-KW2X7s5x-9GciO0_rVW:-KW2X7s5x-9GciO0_rVX:bo6n8fx) ([raw file](https://github.com/criteo/biggraphite/blob/35d93311c5ea8cb5192df9152b2b65554fbf0d38/biggraphite/drivers/cassandra.py#L199)):*
> ```Python
>     "  id uuid,"
>     "  config map<text, text>,"
>     "  timestamp timestamp,"
> ```

please name this field with a more informative name. Could be something like 'wtime', 'mtime', 'updated_on', etc..

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/170)*

**Comment by rveznaver** [comment]
Review status: 1 of 12 files reviewed at latest revision, 6 unresolved discussions.

---

*[biggraphite/drivers/memory.py, line 126 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/170#-KVaGONWVT45Du4bLgmJ:-KW2ttWUVxq3qGznINM3:b-896fix) ([raw file](https://github.com/criteo/biggraphite/blob/b699548b24eafddf993bf0157096ec22ef7a83b3/biggraphite/drivers/memory.py#L126)):*
<details><summary><i>Previously, dpanth3r (Dan Forest) wrote…</i></summary>
> Is that TODO left here by design? :-)
> In case it is, can you leave your name close to it, so that we know who to ping for eventual details?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/170)*

**Comment by iksaif** [comment]
Reviewed 10 of 11 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/170)*

**Comment by iksaif** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/170#-:-KW3czPCoY2hRzQXxiy-:bnfp4nl)*

**Comment by rveznaver** [comment]
Added bgutil clean backend option.

---

Review status: 11 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[biggraphite/drivers/cassandra.py, line 199 at r3](https://reviewable.io:443/reviews/criteo/biggraphite/170#-KW2X7s5x-9GciO0_rVW:-KW3mMftDb-2Wigl-qYd:b-896fix) ([raw file](https://github.com/criteo/biggraphite/blob/35d93311c5ea8cb5192df9152b2b65554fbf0d38/biggraphite/drivers/cassandra.py#L199)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> please name this field with a more informative name. Could be something like 'wtime', 'mtime', 'updated_on', etc..
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/170#-:-KW3mShO1sYn8OxjQP-C:b-pukk9q)*

**Comment by iksaif** [comment]
Review status: 9 of 13 files reviewed at latest revision, 6 unresolved discussions.

---

*[biggraphite/cli/command_clean.py, line 32 at r5](https://reviewable.io:443/reviews/criteo/biggraphite/170#-KW6wXULxKDdq5nuPyil:-KW6wXULxKDdq5nuPyim:b-v779wp) ([raw file](https://github.com/criteo/biggraphite/blob/9c12209eadcd6f48887c94f4a938eeb1a54573bd/biggraphite/cli/command_clean.py#L32)):*
> ```Python
>     def add_arguments(self, parser):
>         """Add custom arguments."""
>         parser.add_argument(
> ```

I think you could just call "cache_from_settings()" or something, like done in bgutil repair (I think)

---

*[biggraphite/cli/command_clean.py, line 37 at r5](https://reviewable.io:443/reviews/criteo/biggraphite/170#-KW6wJVshAvptE_I539r:-KW6wJVshAvptE_I539s:b-dqb0jf) ([raw file](https://github.com/criteo/biggraphite/blob/9c12209eadcd6f48887c94f4a938eeb1a54573bd/biggraphite/cli/command_clean.py#L37)):*
> ```Python
>             action='store_true'
>         )
>         parser.add_argument(
> ```

There is already an argument for that (see utils.py or --help)

---

*[biggraphite/cli/command_clean.py, line 71 at r5](https://reviewable.io:443/reviews/criteo/biggraphite/170#-KW6wFnVSNzTN71HD_IB:-KW6wFnWPpx50UWL3eAo:b-7ivfo9) ([raw file](https://github.com/criteo/biggraphite/blob/9c12209eadcd6f48887c94f4a938eeb1a54573bd/biggraphite/cli/command_clean.py#L71)):*
> ```Python
>                 cache = metadata_cache.DiskCache(accessor, opts.storage_dir)
>                 cache.open()
>                 cache.clean()
> ```

Add cutoff to cache.clean() ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/170)*

**Comment by rveznaver** [comment]
Review status: 9 of 13 files reviewed at latest revision, 6 unresolved discussions.

---

*[biggraphite/cli/command_clean.py, line 32 at r5](https://reviewable.io:443/reviews/criteo/biggraphite/170#-KW6wXULxKDdq5nuPyil:-KW8xG20ZI7Q9uEFJJn6:b1ai11b) ([raw file](https://github.com/criteo/biggraphite/blob/9c12209eadcd6f48887c94f4a938eeb1a54573bd/biggraphite/cli/command_clean.py#L32)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> I think you could just call "cache_from_settings()" or something, like done in bgutil repair (I think)
</details>
The purpose of these arguments is to selectively enable cache/backend cleaning. Have renamed them to be clearer.

---

*[biggraphite/cli/command_clean.py, line 71 at r5](https://reviewable.io:443/reviews/criteo/biggraphite/170#-KW6wFnVSNzTN71HD_IB:-KW8xNt_rPMeXBd9leEA:b-qu6n94) ([raw file](https://github.com/criteo/biggraphite/blob/9c12209eadcd6f48887c94f4a938eeb1a54573bd/biggraphite/cli/command_clean.py#L71)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> Add cutoff to cache.clean() ?
</details>
Good point. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/170)*

**Comment by iksaif** [comment]
Looks like it doesn't work well, see my offline comment on tombstones.

---

Review status: 9 of 13 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/170#-:-KWCNPu2aMKmdlqcUo-j:b-3ia08y)*

**Comment by iksaif** [comment]
Review status: 9 of 13 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[biggraphite/cli/command_clean.py, line 37 at r5](https://reviewable.io:443/reviews/criteo/biggraphite/170#-KW6wJVshAvptE_I539r:-KWbVl0TDWoe8-YDYQuP:b-m2ikdm) ([raw file](https://github.com/criteo/biggraphite/blob/9c12209eadcd6f48887c94f4a938eeb1a54573bd/biggraphite/cli/command_clean.py#L37)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> There is already an argument for that (see utils.py or --help)
</details>
ping ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/170)*

**Comment by iksaif** [comment]
Still something for --clean-backend. We will probably want to disable that by default though to avoid too many tombstones until we tweak all that correctly.

---

Review status: 9 of 13 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/170#-:-KWbVrdIW-7z19WijMYw:b-vb1mj4)*

**Comment by rveznaver** [comment]
Improved and superseded by #185

**Comment by iksaif** [comment]
Thanks for the initial code ! it made Romain's life way easier :)
Closing this MR for now

**Pull request closed without merging**
