### PR TITLE
Add support for directories

### PR DESCRIPTION
**Pull request by unbrice**
This change is [Reviewable](https://reviewable.io/reviews/criteo/biggraphite/5)

### CODE REVIEW

**Comment by iksaif** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[biggraphite/accessor.py, line 86 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/5#-KGwT7vcyWvLMtB-Hv3R:-KGwT7vd-OKeSgK_hozr:56392466) ([raw file](https://github.com/criteo/biggraphite/blob/eb0943412638cc69c238f6949d9059d09842479f/biggraphite/accessor.py#L86)):*
Since cassandra is sparse what is the rationale for having two tables when this could be one table with a flag ? (it's basically a dentry..)
On top of that the same table could have been used for directory metadata (probably with another flag to select stuff faster)

---

*[biggraphite/accessor.py, line 88 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/5#-KGwU7LguXFBxyHjeK6-:-KGwU7LguXFBxyHjeK60:2064482339) ([raw file](https://github.com/criteo/biggraphite/blob/eb0943412638cc69c238f6949d9059d09842479f/biggraphite/accessor.py#L88)):*
it's used to implement the 'metric' API in graphite

---

*[biggraphite/accessor.py, line 89 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/5#-KGwUGHU92p6VWhETlRH:-KGwUGHU92p6VWhETlRI:-1166197276) ([raw file](https://github.com/criteo/biggraphite/blob/eb0943412638cc69c238f6949d9059d09842479f/biggraphite/accessor.py#L89)):*
please add comments regarding when directories are created and deleted.

---

*[biggraphite/accessor.py, line 389 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/5#-KGwThsSczZmcucoKY2n:-KGwThsTe6Xn5iyPNRFu:1919206701) ([raw file](https://github.com/criteo/biggraphite/blob/eb0943412638cc69c238f6949d9059d09842479f/biggraphite/accessor.py#L389)):*
Why is this in 'update_metric' ? Should it be in a create function instead ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/5)*

**Comment by iksaif** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[biggraphite/accessor.py, line 213 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/5#-KHQ41SeRMabmPvlQv3X:-KHQ41SeRMabmPvlQv3Y:570510139) ([raw file](https://github.com/criteo/biggraphite/blob/eb0943412638cc69c238f6949d9059d09842479f/biggraphite/accessor.py#L213)):*
> ```Python
>     _MAX_QUERY_RANGE_MS = 365 * 24 * _ROW_SIZE_MS
> 
>     MAX_METRIC_PER_GLOB = 1000
> ```

This seems very very low, please add a TODO to increase that. Maybe make it a parameter.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/5)*

**Comment by unbrice** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[biggraphite/accessor.py, line 86 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/5#-KGwT7vcyWvLMtB-Hv3R:-KGwfKt5Di32Wb7PRoV8:-691663959) ([raw file](https://github.com/criteo/biggraphite/blob/eb0943412638cc69c238f6949d9059d09842479f/biggraphite/accessor.py#L86)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> Since cassandra is sparse what is the rationale for having two tables when this could be one table with a flag ? (it's basically a dentry..)
> On top of that the same table could have been used for directory metadata (probably with another flag to select stuff faster)</details>
Pros of different tables:
- I expect them to end up with increasingly different metadata (quotas on directories and whisper-header-like on metrics) and the semantic of an entry will become complex
- I suspect that implementing quota or cleaning of empty directories will be easier if we can iterate on directories without filtering all metrics

Pros of one table:
- We get batch transactions to update metadata at the same time as parent entries
- We could not need an additional parameter for functions that use fields presents in both metrics and directories (but I expect they will diverge later to make the return type not depend on the argument)
- We could still build a materialized view of directories only to get performance benefits above

None of the points above is a strong decision factor, but merging things later is generally easier than untangling them so I would rather to keep them separate for now.

---

*[biggraphite/accessor.py, line 88 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/5#-KGwU7LguXFBxyHjeK6-:-KGwmSxyp4tRcz4WJ6gS:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/eb0943412638cc69c238f6949d9059d09842479f/biggraphite/accessor.py#L88)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> it's used to implement the 'metric' API in graphite</details>
Done.

---

*[biggraphite/accessor.py, line 89 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/5#-KGwUGHU92p6VWhETlRH:-KHQLZQ_qj_GSsVTSO6o:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/eb0943412638cc69c238f6949d9059d09842479f/biggraphite/accessor.py#L89)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> please add comments regarding when directories are created and deleted.</details>
Done.

---

*[biggraphite/accessor.py, line 213 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/5#-KHQ41SeRMabmPvlQv3X:-KHQMTagrXzh6f_gshgh:-928195180) ([raw file](https://github.com/criteo/biggraphite/blob/eb0943412638cc69c238f6949d9059d09842479f/biggraphite/accessor.py#L213)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> This seems very very low, please add a TODO to increase that. Maybe make it a parameter.</details>
Done (TODO)

---

*[biggraphite/accessor.py, line 389 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/5#-KGwThsSczZmcucoKY2n:-KGwmsjRHPwQe_DZD19F:-1051204397) ([raw file](https://github.com/criteo/biggraphite/blob/eb0943412638cc69c238f6949d9059d09842479f/biggraphite/accessor.py#L389)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> Why is this in 'update_metric' ? Should it be in a create function instead ?</details>
Right, renamed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/5)*

**Comment by iksaif** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[biggraphite/accessor.py, line 86 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/5#-KGwT7vcyWvLMtB-Hv3R:-KHQ_ihPgK613xAuBjWS:795033144) ([raw file](https://github.com/criteo/biggraphite/blob/eb0943412638cc69c238f6949d9059d09842479f/biggraphite/accessor.py#L86)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> Pros of different tables:
> - I expect them to end up with increasingly different metadata (quotas on directories and whisper-header-like on metrics) and the semantic of an entry will become complex
> - I suspect that implementing quota or cleaning of empty directories will be easier if we can iterate on directories without filtering all metrics
> 
> Pros of one table:
> - We get batch transactions to update metadata at the same time as parent entries
> - We could not need an additional parameter for functions that use fields presents in both metrics and directories (but I expect they will diverge later to make the return type not depend on the argument)
> - We could still build a materialized view of directories only to get performance benefits above
> 
> None of the points above is a strong decision factor, but merging things later is generally easier than untangling them so I would rather to keep them separate for now.</details>
Ok, please add that as a comment in the code :)

Keep in mind that:
* for things such as retentions or quota or ACLs you'll probably need a different table because we will want to quickly load all the quotas  in memory
* cleaning of empty directories will be tricky if the 'value' doesn't contain something that easily gives the number of children (or list of children). Thus the analogy with dentries (that exist for both files and directories)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/5)*

**Comment by unbrice** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[biggraphite/accessor.py, line 86 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/5#-KGwT7vcyWvLMtB-Hv3R:-KHU0NTDXSYh5yYLxKPf:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/eb0943412638cc69c238f6949d9059d09842479f/biggraphite/accessor.py#L86)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> Ok, please add that as a comment in the code :)
> 
> Keep in mind that:
> * for things such as retentions or quota or ACLs you'll probably need a different table because we will want to quickly load all the quotas  in memory
> * cleaning of empty directories will be tricky if the 'value' doesn't contain something that easily gives the number of children (or list of children). Thus the analogy with dentries (that exist for both files and directories)
> 
> 
> </details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/5)*

**Comment by iksaif** [comment]
:lgtm:

<details><summary><i>Previously, coveralls wrote…</i></summary>
> 
> [Coverage Status](https://coveralls.io/builds/6121829)
> 
> Coverage increased (+1.5%) to 63.939% when pulling **4ce200ca319816730cc424988dc09b572423a1ed on unbrice:directories** into **d826670ec4fe0998de3ff7e2334225759f048426 on criteo:master**.
> </details>


---

Reviewed 1 of 1 files at r3.
Review status: 1 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/5#-:-KHU4gUGBgOZtOprNswn:1417088721)*

**Comment by unbrice** [comment]
Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/5)*

**Pull request merged**
