### PR TITLE
Add test_clusters_diff.py

### PR DESCRIPTION
**Pull request by Thib17**
This change is [Reviewable](https://reviewable.io/reviews/criteo/biggraphite/40)

### CODE REVIEW

**Comment by iksaif** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[README.md, line 49 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/40#-KM-YciTqX0hyNiLpYih:-KM-YciTqX0hyNiLpYii:423524707) ([raw file](https://github.com/criteo/biggraphite/blob/a37be3c659faee7422768839e6a8941b5efb8e28/README.md#L49)):*
> ```Markdown
> $ tox
> ```
> You can set /tmp as tmpfs to make tests run faster.
> ```

Cassandra tests generate a lot of I/O, make sure you /tmp is mounted as tmpfs.

---

*[tests/test_clusters_diff.py, line 20 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/40#-KM-YoVyXXn3mTZMCZbG:-KM-YoVyXXn3mTZMCZbH:1988668335) ([raw file](https://github.com/criteo/biggraphite/blob/a37be3c659faee7422768839e6a8941b5efb8e28/tests/test_clusters_diff.py#L20)):*
> ```Python
>         """Should correctly create an http request."""
>         request = clusters_diff.Request('http://fakeurl.com', 'auth_key', 5.0)
>         assert request._request.get_method() == 'GET'
> ```

I think you're supposed to use self.assertEquals() (see https://docs.python.org/2.7/library/unittest.html).
This will produce nicer outputs when it fails.

---

*[tests/test_clusters_diff.py, line 166 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/40#-KM-Z4oRvU0sVn457Kmg:-KM-Z4oRvU0sVn457Kmh:1709065994) ([raw file](https://github.com/criteo/biggraphite/blob/a37be3c659faee7422768839e6a8941b5efb8e28/tests/test_clusters_diff.py#L166)):*
> ```Python
>             assert predicted_dt_2.__dict__ in formated_diffable_targets
> 
>         # with error
> ```

split this in a different test method :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/40)*

**Comment by Thib17** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[README.md, line 49 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/40#-KM-YciTqX0hyNiLpYih:-KM-j_1AgfULFGcu37QQ:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/a37be3c659faee7422768839e6a8941b5efb8e28/README.md#L49)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> Cassandra tests generate a lot of I/O, make sure you /tmp is mounted as tmpfs.
</details>
Done.

---

*[tests/test_clusters_diff.py, line 20 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/40#-KM-YoVyXXn3mTZMCZbG:-KM-jaF7XyLEOBzgaviO:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/a37be3c659faee7422768839e6a8941b5efb8e28/tests/test_clusters_diff.py#L20)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> I think you're supposed to use self.assertEquals() (see https://docs.python.org/2.7/library/unittest.html).
> This will produce nicer outputs when it fails.
</details>
Done.

---

*[tests/test_clusters_diff.py, line 166 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/40#-KM-Z4oRvU0sVn457Kmg:-KM-mHyPC7J9APwe5Vz8:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/a37be3c659faee7422768839e6a8941b5efb8e28/tests/test_clusters_diff.py#L166)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> split this in a different test method :)
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/40)*

**Comment by iksaif** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/40#-:-KM-nbhuJXvpp1Qwfp2F:1417088721)*

**Comment by iksaif** [comment]
Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/40)*

**Comment by iksaif** [comment]
:lgtm_cancel:  wait for some reasons the tests are failing

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/40#-:-KM10WUrW-yXMrNcAfDP:-1096897883)*

**Comment by iksaif** [comment]
https://github.com/criteo/biggraphite/pull/41 will make that easier :)

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/40#-:-KM19Tzu14uSgulDOsEk:-1633266707)*

**Comment by unbrice** [comment]
Reviewed 1 of 5 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[tests/test_clusters_diff.py, line 25 \[r3\]](https://reviewable.io:443/reviews/criteo/biggraphite/40#-KN1oy1GvhQgqFJEc119:-KN1oy1GvhQgqFJEc11A:374752242) ([raw file](https://github.com/criteo/biggraphite/blob/46cad708c8efbcb7e79c5ad02872708c636b6570/tests/test_clusters_diff.py#L25)):*
> ```Python
>     def test_parse_request_result(self):
>         """Should correctly parse a jsonObject into a list of DiffableTarget."""
>         raw_data = ("""[{"target": "target_1", "datapoints": [[0.1, 10], [0.2, 20]]}, """ +
> ```

Nit: rather than bundling a big string and doing escapes, I suggest
data = { "target": "target_1", ...}
data_json = json.json.dumps([data])

---

*[tests/test_clusters_diff.py, line 36 \[r3\]](https://reviewable.io:443/reviews/criteo/biggraphite/40#-KN1pmZ9McGcqwSHN8w-:-KN1pmZAyy6jxiWpfLZN:1053353350) ([raw file](https://github.com/criteo/biggraphite/blob/46cad708c8efbcb7e79c5ad02872708c636b6570/tests/test_clusters_diff.py#L36)):*
> ```Python
>                           diffable_target_1.__dict__)
>         self.assertEquals(request._parse_request_result(raw_data)[1].__dict__,
>                           diffable_target_2.__dict__)
> ```

__dict__ is a bit magic and will break if a protected attribute is added for whatever reason, or if the object gets slots, or...
I suggest comparing the attributes you care about.

---

*[tests/test_clusters_diff.py, line 109 \[r3\]](https://reviewable.io:443/reviews/criteo/biggraphite/40#-KN1tqQRzlG69x16dDuY:-KN1tqQRzlG69x16dDuZ:244660831) ([raw file](https://github.com/criteo/biggraphite/blob/46cad708c8efbcb7e79c5ad02872708c636b6570/tests/test_clusters_diff.py#L109)):*
> ```Python
>     def test_read_queries(self):
>         """Sould correctly read inputs."""
>         tmpFile = tempfile.NamedTemporaryFile()
> ```

no camelCase please, also you should close the file (`with tempfile... as tmp_file`)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/40)*

**Comment by Thib17** [comment]
Review status: 1 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[tests/test_clusters_diff.py, line 25 \[r3\]](https://reviewable.io:443/reviews/criteo/biggraphite/40#-KN1oy1GvhQgqFJEc119:-KNCYVZbp5npAFFJFhUr:-1110805660) ([raw file](https://github.com/criteo/biggraphite/blob/46cad708c8efbcb7e79c5ad02872708c636b6570/tests/test_clusters_diff.py#L25)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> Nit: rather than bundling a big string and doing escapes, I suggest
> data = { "target": "target_1", ...}
> data_json = json.json.dumps([data])
> 
> 
</details>
I think that we need a string because it's the fake response body. The script we want to test will later parse it.

---

*[tests/test_clusters_diff.py, line 36 \[r3\]](https://reviewable.io:443/reviews/criteo/biggraphite/40#-KN1pmZ9McGcqwSHN8w-:-KNCezsHDGUVE4GpdWX5:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/46cad708c8efbcb7e79c5ad02872708c636b6570/tests/test_clusters_diff.py#L36)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> __dict__ is a bit magic and will break if a protected attribute is added for whatever reason, or if the object gets slots, or...
> I suggest comparing the attributes you care about.
</details>
Done.

---

*[tests/test_clusters_diff.py, line 109 \[r3\]](https://reviewable.io:443/reviews/criteo/biggraphite/40#-KN1tqQRzlG69x16dDuY:-KNCYn3mX9nhqbqkDize:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/46cad708c8efbcb7e79c5ad02872708c636b6570/tests/test_clusters_diff.py#L109)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> no camelCase please, also you should close the file (`with tempfile... as tmp_file`)
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/40)*

**Comment by unbrice** [comment]
Reviewed 1 of 5 files at r4.
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[CONTRIBUTING.md, line 68 \[r4\]](https://reviewable.io:443/reviews/criteo/biggraphite/40#-KNCoZvO4it-3pb69TE6:-KNCoZvO4it-3pb69TE7:1270229192) ([raw file](https://github.com/criteo/biggraphite/blob/5624566d79d68bc2cde7af13bcfb0efd3c741d62/CONTRIBUTING.md#L68)):*
> ```Markdown
>     tox
> ```
> Cassandra tests generate a lot of I/O, make sure you /tmp is mounted as tmpfs.
> ```

without "you"

---

*[tests/test_clusters_diff.py, line 25 \[r3\]](https://reviewable.io:443/reviews/criteo/biggraphite/40#-KN1oy1GvhQgqFJEc119:-KNCodxs1ywvkt4A40X3:2108474626) ([raw file](https://github.com/criteo/biggraphite/blob/46cad708c8efbcb7e79c5ad02872708c636b6570/tests/test_clusters_diff.py#L25)):*
<details><summary><i>Previously, Thib17 wrote…</i></summary>
> I think that we need a string because it's the fake response body. The script we want to test will later parse it.
</details>
dumps returns a string, it would be the same only more legible

---

*[tests/test_clusters_diff.py, line 109 \[r3\]](https://reviewable.io:443/reviews/criteo/biggraphite/40#-KN1tqQRzlG69x16dDuY:-KNConouknnJrH80g1f6:2128842825) ([raw file](https://github.com/criteo/biggraphite/blob/46cad708c8efbcb7e79c5ad02872708c636b6570/tests/test_clusters_diff.py#L109)):*
<details><summary><i>Previously, Thib17 wrote…</i></summary>
> Done.
</details>
nope :-P  what you do is to open a second handle to the same file and then close it. What I suggestd is
```python
with tempfile... as tmp_file:
  tmp_file.write(inputs)
  tmp_file.flush()
  queries = _read_queries(tmp_file.name)
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/40)*

**Comment by unbrice** [comment]
Reviewed 2 of 5 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/40)*

**Comment by Thib17** [comment]
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[CONTRIBUTING.md, line 68 \[r4\]](https://reviewable.io:443/reviews/criteo/biggraphite/40#-KNCoZvO4it-3pb69TE6:-KNCr9oc1mITN__sxBD2:-1127790570) ([raw file](https://github.com/criteo/biggraphite/blob/5624566d79d68bc2cde7af13bcfb0efd3c741d62/CONTRIBUTING.md#L68)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> without "you"
</details>
I didn't see that an other line about /tmp mounted as tmpfs was already written. So I just edited the line 58 to explain why.

---

*[tests/test_clusters_diff.py, line 25 \[r3\]](https://reviewable.io:443/reviews/criteo/biggraphite/40#-KN1oy1GvhQgqFJEc119:-KNCskxSb1C442wcltAu:-1277240967) ([raw file](https://github.com/criteo/biggraphite/blob/46cad708c8efbcb7e79c5ad02872708c636b6570/tests/test_clusters_diff.py#L25)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> dumps returns a string, it would be the same only more legible
</details>
Ok. Done.

---

*[tests/test_clusters_diff.py, line 109 \[r3\]](https://reviewable.io:443/reviews/criteo/biggraphite/40#-KN1tqQRzlG69x16dDuY:-KNCtqod5JfT0hDcKndd:435511225) ([raw file](https://github.com/criteo/biggraphite/blob/46cad708c8efbcb7e79c5ad02872708c636b6570/tests/test_clusters_diff.py#L109)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> nope :-P  what you do is to open a second handle to the same file and then close it. What I suggestd is
> ```python
> with tempfile... as tmp_file:
>   tmp_file.write(inputs)
>   tmp_file.flush()
>   queries = _read_queries(tmp_file.name)
> ```
</details>
Yes, sorry. I forgot to apply the second part of your comment. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/40)*

**Comment by unbrice** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/40)*

**Comment by unbrice** [comment]
Reviewed 1 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/40)*

**Comment by unbrice** [comment]
Reviewed 1 of 2 files at r7, 1 of 1 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/40)*

**Comment by iksaif** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/40#-:-KNX3QUw_3q3zTasG05Q:1417088721)*

**Comment by iksaif** [comment]
Reviewed 1 of 5 files at r4, 1 of 2 files at r5, 1 of 2 files at r7, 1 of 1 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/40)*

**Pull request merged**
