### PR TITLE
Further query optimization for Cassandra

### PR DESCRIPTION
**Pull request by dpanth3r**
- Query cleanup
    - Support for braces (generate queries using possible values)
    - Quick cleanup/refactoring

---
This change is [Reviewable](https://reviewable.io/reviews/criteo/biggraphite/183)

### CODE REVIEW

**Comment by iksaif** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[biggraphite/glob_utils.py, line 422 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/183#-KWqTc2rsGfObR9EFgpK:-KWqTc2rsGfObR9EFgpL:b-wzpuyh) ([raw file](https://github.com/criteo/biggraphite/blob/910e46d75e822eac5c093600a5740e2a56941ed4/biggraphite/glob_utils.py#L422)):*
> ```Python
> 
>         i = 0
>         n = len(self._glob)
> ```

It's probably worth it to libify that at some point, it's crazy that there isn't something like that already. I wonder if it would have been possible to piggy back on fnmatch.translate()

---

*[biggraphite/drivers/cassandra.py, line 62 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/183#-KWqURVkAFioKqeDVVVY:-KWqURVkAFioKqeDVVVZ:b6huztp) ([raw file](https://github.com/criteo/biggraphite/blob/910e46d75e822eac5c093600a5740e2a56941ed4/biggraphite/drivers/cassandra.py#L62)):*
> ```Python
> DEFAULT_TRACE = False
> DEFAULT_BULKIMPORT = False
> DEFAULT_MAX_QUERIES_PER_PATTERN = 32
> ```

Isn't that pretty low if we expand by default ?

---

*[biggraphite/drivers/cassandra.py, line 842 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/183#-KWqUm9oGSCsb7O9jBiQ:-KWqUm9oGSCsb7O9jBiR:b-ovn941) ([raw file](https://github.com/criteo/biggraphite/blob/910e46d75e822eac5c093600a5740e2a56941ed4/biggraphite/drivers/cassandra.py#L842)):*
> ```Python
>         metric_names = []
>         try:
>             for query in queries:
> ```

we probably want an "execute_concurrent" here (carefully limiting the amount of queries)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/183)*

**Comment by iksaif** [comment]
Looks good, I'm starting to think that we should split this file in two, (cassandra_metadata.py and cassandra_data.py) at some point.
Thanks !

---

Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/183#-:-KWqUvZ2US5dMg3067DK:bprczf3)*

**Comment by dpanth3r** [comment]
Thanks. I will fix the styling issues, then we should be happy with #169 for the moment :D

**Comment by dpanth3r** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[biggraphite/glob_utils.py, line 422 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/183#-KWqTc2rsGfObR9EFgpK:-KWsMv2dT2cnrGH28OVL:b-3egb7q) ([raw file](https://github.com/criteo/biggraphite/blob/910e46d75e822eac5c093600a5740e2a56941ed4/biggraphite/glob_utils.py#L422)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> It's probably worth it to libify that at some point, it's crazy that there isn't something like that already. I wonder if it would have been possible to piggy back on fnmatch.translate()
</details>
I do not really get what you mean here. fnmatch.translate() only generates regexes, it does not parse the pattern into an abstract representation. If you look at the glob to regex function in this file you will actually see a modified version of the original fnmatch.translate :-)

---

*[biggraphite/drivers/cassandra.py, line 62 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/183#-KWqURVkAFioKqeDVVVY:-KWsNgErt1qkwhXevVFB:b1db7kq) ([raw file](https://github.com/criteo/biggraphite/blob/910e46d75e822eac5c093600a5740e2a56941ed4/biggraphite/drivers/cassandra.py#L62)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> Isn't that pretty low if we expand by default ?
</details>
My code is able to reduce the number of combinations generated to avoid generating too many requests; so I kept the previous value as a reasonable one. But if feel comfortable with a larger default count (64?) for max queries, I will go ahead and bump this value!

---

*[biggraphite/drivers/cassandra.py, line 842 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/183#-KWqUm9oGSCsb7O9jBiQ:-KWsOGvamBurlrigA6BZ:b81ysfc) ([raw file](https://github.com/criteo/biggraphite/blob/910e46d75e822eac5c093600a5740e2a56941ed4/biggraphite/drivers/cassandra.py#L842)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> we probably want an "execute_concurrent" here (carefully limiting the amount of queries)
</details>
The limitation is why I have not been using concurrent for now. We could maybe run sequential batches of 2-5 concurrent requests? If we agree on that, I will implement it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/183)*

**Comment by iksaif** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[biggraphite/drivers/cassandra.py, line 62 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/183#-KWqURVkAFioKqeDVVVY:-KWwe5rNTL1n8qC_KcHT:bupzhu4) ([raw file](https://github.com/criteo/biggraphite/blob/910e46d75e822eac5c093600a5740e2a56941ed4/biggraphite/drivers/cassandra.py#L62)):*
<details><summary><i>Previously, dpanth3r (Dan Forest) wrote…</i></summary>
> My code is able to reduce the number of combinations generated to avoid generating too many requests; so I kept the previous value as a reasonable one. But if feel comfortable with a larger default count (64?) for max queries, I will go ahead and bump this value!
</details>
It's unclear to me what queries will be generated exactly for typical queries, so it's hard to have a good idea of what is a good number of maximum queries. I guess we need to do some tests to tweak that later.

---

*[biggraphite/drivers/cassandra.py, line 842 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/183#-KWqUm9oGSCsb7O9jBiQ:-KWwd_wU-xMINlNiakgM:b-36lehs) ([raw file](https://github.com/criteo/biggraphite/blob/910e46d75e822eac5c093600a5740e2a56941ed4/biggraphite/drivers/cassandra.py#L842)):*
<details><summary><i>Previously, dpanth3r (Dan Forest) wrote…</i></summary>
> The limitation is why I have not been using concurrent for now. We could maybe run sequential batches of 2-5 concurrent requests? If we agree on that, I will implement it.
</details>
execute_concurrent can take the number of concurrent queries to run in parallel as a parameter. I'd limit that to 6 or less.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/183)*

**Comment by iksaif** [comment]
:lgtm_strong:  

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/183#-:-KWwel9y5dqG79DNEgtn:b-yncq5v)*

**Comment by iksaif** [comment]
Found a bug:

$ bgutil --loglevel=DEBUG list 'a.{par,am5}.test.{cassandra,memcached}.*.*'
2016-11-20 12:38:05,290 [DEBUG] biggraphite.drivers.cassandra: SELECT name FROM "biggraphite_metadata"."directories" WHERE component_0 = 'a' AND component_1 = 'am5' AND component_2 = 'test' AND component_3 = 'cassandra' AND component_6 = '__END__' LIMIT 5001 ALLOW FILTERING;
2016-11-20 12:38:07,176 [DEBUG] biggraphite.drivers.cassandra: SELECT name FROM "biggraphite_metadata"."directories" WHERE component_0 = 'a' AND component_1 = 'am5' AND component_2 = 'test' AND component_3 = 'memcached' AND component_6 = '__END__' LIMIT 5001 ALLOW FILTERING;
2016-11-20 12:38:08,226 [DEBUG] biggraphite.drivers.cassandra: SELECT name FROM "biggraphite_metadata"."directories" WHERE component_0 = 'a' AND component_1 = 'par' AND component_2 = 'test' AND component_3 = 'cassandra' AND component_6 = '__END__' LIMIT 5001 ALLOW FILTERING;
2016-11-20 12:38:08,254 [DEBUG] biggraphite.drivers.cassandra: SELECT name FROM "biggraphite_metadata"."directories" WHERE component_0 = 'a' AND component_1 = 'par' AND component_2 = 'test' AND component_3 = 'memcached' AND component_6 = '__END__' LIMIT 5001 ALLOW FILTERING;
2016-11-20 12:38:08,282 [DEBUG] biggraphite.drivers.cassandra: SELECT name FROM "biggraphite_metadata"."metrics" WHERE component_0 = 'a' AND component_1 = 'am5' AND component_2 = 'test' AND component_3 = 'cassandra' AND component_6 = '__END__' LIMIT 5001 ALLOW FILTERING;
2016-11-20 12:38:08,325 [DEBUG] biggraphite.drivers.cassandra: SELECT name FROM "biggraphite_metadata"."metrics" WHERE component_0 = 'a' AND component_1 = 'am5' AND component_2 = 'test' AND component_3 = 'memcached' AND component_6 = '__END__' LIMIT 5001 ALLOW FILTERING;
2016-11-20 12:38:08,368 [DEBUG] biggraphite.drivers.cassandra: SELECT name FROM "biggraphite_metadata"."metrics" WHERE component_0 = 'a' AND component_1 = 'par' AND component_2 = 'test' AND component_3 = 'cassandra' AND component_6 = '__END__' LIMIT 5001 ALLOW FILTERING;
2016-11-20 12:38:08,403 [DEBUG] biggraphite.drivers.cassandra: SELECT name FROM "biggraphite_metadata"."metrics" WHERE component_0 = 'a' AND component_1 = 'par' AND component_2 = 'test' AND component_3 = 'memcached' AND component_6 = '__END__' LIMIT 5001 ALLOW FILTERING;
2016-11-20 12:38:08,426 [DEBUG] biggraphite.drivers._delayed_writer: rebuilt the queues: 0 metrics, 0 per second

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/183#-:-KX0X0mqI9pkig9INdLA:b-ewe5dp)*

**Comment by iksaif** [comment]
forget that, not a bug, just not super efficient, but not a regression

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/183#-:-KX1SLTNi5OPqqO6O66n:b-283biq)*

**Comment by dpanth3r** [comment]
I am adding concurrent request execution to the code, and then we should be on our way to the merge :-)

**Pull request merged**
