### PR TITLE
Support multiple replicated writers

### PR DESCRIPTION
**Pull request by iksaif**
This change is [Reviewable](https://reviewable.io/reviews/criteo/biggraphite/232)

### CODE REVIEW

**Comment by Thib17** [comment]
Reviewed 11 of 13 files at r1.
Review status: 10 of 12 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[biggraphite/accessor.py, line 917 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/232#-KbAp0rEiVoBt0FgE1Wg:-KbAp0rEiVoBt0FgE1Wh:beyvewh) ([raw file](https://github.com/criteo/biggraphite/blob/b5b2a323c70c4f4d4fa1c6f2a42a507679fbb78c/biggraphite/accessor.py#L917)):*
> ```Python
>         # rather wait until we have found values fitting in the next period.
>         ret = (None, None)
>         count = 0
> ```

Is it always 0 ? I don't see where 'count' is updated

---

*[biggraphite/accessor.py, line 960 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/232#-KbAneA8htVkcLvhWeLX:-KbAneA9Z4lQbo3-GqbV:b3hhvjs) ([raw file](https://github.com/criteo/biggraphite/blob/b5b2a323c70c4f4d4fa1c6f2a42a507679fbb78c/biggraphite/accessor.py#L960)):*
> ```Python
> 
>                 # Find the replica id from the shard id.
>                 replica = (shard & SHARD_REPLICA_MASK) >> SHARD_REPLICA_SHIFT
> ```

Maybe you should use unpack_shard ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/232)*

**Comment by iksaif** [comment]
Review status: 8 of 12 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[biggraphite/accessor.py, line 917 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/232#-KbAp0rEiVoBt0FgE1Wg:-KbB-dqcMn4qIgx7MO-1:b-7ql1td) ([raw file](https://github.com/criteo/biggraphite/blob/b5b2a323c70c4f4d4fa1c6f2a42a507679fbb78c/biggraphite/accessor.py#L917)):*
<details><summary><i>Previously, Thib17 (Thibault Chataigner) wrote…</i></summary><blockquote>

Is it always 0 ? I don't see where 'count' is updated
</blockquote></details>

fixed

---

*[biggraphite/accessor.py, line 960 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/232#-KbAneA8htVkcLvhWeLX:-KbB-euB2QoZkJT-g3-E:b-w0sriu) ([raw file](https://github.com/criteo/biggraphite/blob/b5b2a323c70c4f4d4fa1c6f2a42a507679fbb78c/biggraphite/accessor.py#L960)):*
<details><summary><i>Previously, Thib17 (Thibault Chataigner) wrote…</i></summary><blockquote>

Maybe you should use unpack_shard ?
</blockquote></details>

could, but it's faster this way

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/232)*

**Comment by erebe** [comment]
Reviewed 11 of 13 files at r1, 2 of 2 files at r2.
Review status: 9 of 12 files reviewed at latest revision, 5 unresolved discussions.

---

*[benchmarks/accessor_bench.py, line 17 at r2](https://reviewable.io:443/reviews/criteo/biggraphite/232#-KbB9HIxtcc0gbVT23wQ:-KbB9HIxtcc0gbVT23wR:becjbpp) ([raw file](https://github.com/criteo/biggraphite/blob/b40f079cdd7b7085ccf4da21aad499a3f28d46e3/benchmarks/accessor_bench.py#L17)):*
> ```Python
>     ITERATIONS = 10
> else:
>     BASE_CLASS = bg_test_utils.TestCaseWithFakeAccessor
> ```

Is it worth it to bench against the fake Accessor ?
At least you should print a message to say which one we are using to avoid any mistake

---

*[biggraphite/accessor.py, line 49 at r2](https://reviewable.io:443/reviews/criteo/biggraphite/232#-KbB8X3koZPlyq2g4NSc:-KbB8X3koZPlyq2g4NSd:b-7ctl07) ([raw file](https://github.com/criteo/biggraphite/blob/b40f079cdd7b7085ccf4da21aad499a3f28d46e3/biggraphite/accessor.py#L49)):*
> ```Python
> # Number of bits allocated to dinstinguish replicas in the shard
> # id. The default is 2 which means that you can have up to 3 replicas
> # writting a the same time to your database.
> ```

Can you explain in the comment the reason of why this is needed

---

*[biggraphite/plugins/graphite.py, line 153 at r2](https://reviewable.io:443/reviews/criteo/biggraphite/232#-KbBAi7Wx2kSY2OoWcG4:-KbBAi7Wx2kSY2OoWcG5:b6kxuhl) ([raw file](https://github.com/criteo/biggraphite/blob/b40f079cdd7b7085ccf4da21aad499a3f28d46e3/biggraphite/plugins/graphite.py#L153)):*
> ```Python
>         self._django_cache = None
>         self._cache_timeout = None
>         self._lock = threading.RLock()
> ```

Why a reentrant lock ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/232)*

**Comment by iksaif** [comment]
LGTY?

---

Review status: 7 of 13 files reviewed at latest revision, 5 unresolved discussions.

---

*[benchmarks/accessor_bench.py, line 17 at r2](https://reviewable.io:443/reviews/criteo/biggraphite/232#-KbB9HIxtcc0gbVT23wQ:-KbBDTuVbjcyA1V8qlMw:b5p26lc) ([raw file](https://github.com/criteo/biggraphite/blob/b40f079cdd7b7085ccf4da21aad499a3f28d46e3/benchmarks/accessor_bench.py#L17)):*
<details><summary><i>Previously, erebe (Erèbe - Romain Gerard) wrote…</i></summary><blockquote>

Is it worth it to bench against the fake Accessor ?
At least you should print a message to say which one we are using to avoid any mistake
</blockquote></details>

Yes, when you want to bench the python code and not the database :) Added a log

---

*[biggraphite/accessor.py, line 49 at r2](https://reviewable.io:443/reviews/criteo/biggraphite/232#-KbB8X3koZPlyq2g4NSc:-KbBE8ZXBLJtrLL6NoHY:b-896fix) ([raw file](https://github.com/criteo/biggraphite/blob/b40f079cdd7b7085ccf4da21aad499a3f28d46e3/biggraphite/accessor.py#L49)):*
<details><summary><i>Previously, erebe (Erèbe - Romain Gerard) wrote…</i></summary><blockquote>

Can you explain in the comment the reason of why this is needed
</blockquote></details>

Done.

---

*[biggraphite/plugins/graphite.py, line 153 at r2](https://reviewable.io:443/reviews/criteo/biggraphite/232#-KbBAi7Wx2kSY2OoWcG4:-KbBEA161l-FIwCos7OP:b-896fix) ([raw file](https://github.com/criteo/biggraphite/blob/b40f079cdd7b7085ccf4da21aad499a3f28d46e3/biggraphite/plugins/graphite.py#L153)):*
<details><summary><i>Previously, erebe (Erèbe - Romain Gerard) wrote…</i></summary><blockquote>

Why a reentrant lock ?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/232#-:-KbF7cjkXu_6yiLkOcQA:b-85i5t2)*

**Comment by erebe** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/232#-:-KbFNbQ7EbxKmA2OoL0M:bnfp4nl)*

**Pull request merged**
