### PR TITLE
Separate Cassandra from accessor

### PR DESCRIPTION
**Pull request by unbrice**
This change is [Reviewable](https://reviewable.io/reviews/criteo/biggraphite/36)

### CODE REVIEW

**Comment by natbraun** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---

*[biggraphite/accessor.py, line 16 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/36#-KKiCjw2Y98SVdv9vVuc:-KKiCjw33o0yhQ5FRxtZ:-1764706046) ([raw file](https://github.com/criteo/biggraphite/blob/3e0d2eca659aa6078568d5223b635fc8f861325e/biggraphite/accessor.py#L16)):*
> ```Python
> # limitations under the License.
> 
> """Abstracts interface implementing by the different datastores."""
> ```

implemented?

---

*[biggraphite/accessor.py, line 60 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/36#-KKiD9gK__eout3DY0WI:-KKiD9gL2VazmMlmrVd1:-1742237621) ([raw file](https://github.com/criteo/biggraphite/blob/3e0d2eca659aa6078568d5223b635fc8f861325e/biggraphite/accessor.py#L60)):*
> ```Python
> def round_down(rounded, devider):
>     """Round down an integer to a multiple of devider."""
>     return int(rounded) // devider * devider
> ```

divider?

---

*[biggraphite/accessor.py, line 253 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/36#-KKiEwH7pJI12-xIukoV:-KKiEwH7pJI12-xIukoW:1634303125) ([raw file](https://github.com/criteo/biggraphite/blob/3e0d2eca659aa6078568d5223b635fc8f861325e/biggraphite/accessor.py#L253)):*
> ```Python
>         """Fetch points from time_start included to time_end excluded.
> 
>         connect() must have previously been called.
> ```

Two remarks: 
- I think you are changing the semantic here: previously, connect did not need to have been called
- In insert_points, connect is not assumed to have been called, so the two methods are not uniform

---

*[biggraphite/accessor.py, line 266 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/36#-KKiFUTQv9qf0ncCvQwO:-KKiFUTQv9qf0ncCvQwP:808780079) ([raw file](https://github.com/criteo/biggraphite/blob/3e0d2eca659aa6078568d5223b635fc8f861325e/biggraphite/accessor.py#L266)):*
> ```Python
>         Yields:
>           (timestamp, value) where timestamp indicates the value is about the
>           range from timestamp included to timestamp+resolution excluded
> ```

I don't understand this sentence

---

*[biggraphite/graphite_utils.py, line 20 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/36#-KKiFqH7Y2pZnModW3B1:-KKiFqH7Y2pZnModW3B2:-259781966) ([raw file](https://github.com/criteo/biggraphite/blob/3e0d2eca659aa6078568d5223b635fc8f861325e/biggraphite/graphite_utils.py#L20)):*
> ```Python
> from os import path as os_path
> import re
> ```

This whole file should be probably be renamed cassandra_utils

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/36)*

**Comment by unbrice** [comment]
Review status: 7 of 11 files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---

*[biggraphite/accessor.py, line 16 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/36#-KKiCjw2Y98SVdv9vVuc:-KKiJq49zHTHlmlf6xqG:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/3e0d2eca659aa6078568d5223b635fc8f861325e/biggraphite/accessor.py#L16)):*
<details><summary><i>Previously, natbraun (Nathaniel Braun) wrote…</i></summary>
> implemented?
</details>
Done.

---

*[biggraphite/accessor.py, line 60 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/36#-KKiD9gK__eout3DY0WI:-KKiJphHwX-AIFgv0xvP:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/3e0d2eca659aa6078568d5223b635fc8f861325e/biggraphite/accessor.py#L60)):*
<details><summary><i>Previously, natbraun (Nathaniel Braun) wrote…</i></summary>
> divider?
</details>
Done.

---

*[biggraphite/accessor.py, line 253 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/36#-KKiEwH7pJI12-xIukoV:-KKiLW4-HU4WYVDzU4QI:-1756895247) ([raw file](https://github.com/criteo/biggraphite/blob/3e0d2eca659aa6078568d5223b635fc8f861325e/biggraphite/accessor.py#L253)):*
<details><summary><i>Previously, natbraun (Nathaniel Braun) wrote…</i></summary>
> Two remarks: 
> - I think you are changing the semantic here: previously, connect did not need to have been called
> - In insert_points, connect is not assumed to have been called, so the two methods are not uniform
</details>
On the first point, actually the previous code already stated that "connect() must have previously been called."

Though it was (and is) the only function to explicitly state that, all functions need that a connection is already established except noted otherwise. I made that explicit in the class doc and removed the fetch_point specific mention.

---

*[biggraphite/accessor.py, line 266 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/36#-KKiFUTQv9qf0ncCvQwO:-KKiKgRT5GpDFD1X07TX:676965300) ([raw file](https://github.com/criteo/biggraphite/blob/3e0d2eca659aa6078568d5223b635fc8f861325e/biggraphite/accessor.py#L266)):*
<details><summary><i>Previously, natbraun (Nathaniel Braun) wrote…</i></summary>
> I don't understand this sentence
</details>
PTAL

---

*[biggraphite/graphite_utils.py, line 20 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/36#-KKiFqH7Y2pZnModW3B1:-KKiKs7DtxQ_eC3fIY2L:-1429055815) ([raw file](https://github.com/criteo/biggraphite/blob/3e0d2eca659aa6078568d5223b635fc8f861325e/biggraphite/graphite_utils.py#L20)):*
<details><summary><i>Previously, natbraun (Nathaniel Braun) wrote…</i></summary>
> This whole file should be probably be renamed cassandra_utils
</details>
Currently that's what it is but I like the fact that accessor_from_settings will provide a place where to do a `if USE_RIAK: accessor=...` (or whichever backend) so I would like to keep the name unchanged in prevision of future work.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/36)*

**Comment by natbraun** [comment]
Reviewed 5 of 5 files at r2.
Review status: 11 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/36)*

**Comment by natbraun** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/36)*

**Comment by natbraun** [comment]
Reviewed 7 of 7 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/36)*

**Pull request merged**
