### PR TITLE
drivers: add in-memory driver

### PR DESCRIPTION
**Pull request by iksaif**
- Create an in-memory driver from FakeAccessor.
- Change settings to be able to support multiple drivers.
- Update documentation.

---
This change is [Reviewable](https://reviewable.io/reviews/criteo/biggraphite/78)

### CODE REVIEW

**Comment by iksaif** [comment]
Sorry for the somewhat long PR. It was written offline and is pretty hard to split.

**Comment by wdauchy** [comment]
Review status: 0 of 14 files reviewed at latest revision, 5 unresolved discussions.

---

*[CONFIGURATION.md, line 10 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/78#-KPUI2ZQLPxwHxGCuyjb:-KPUI2ZQLPxwHxGCuyjc:b-4z81hk) ([raw file](https://github.com/criteo/biggraphite/blob/ba011bf628f6769d4ae28c9dcead5f6619f3fcc6/CONFIGURATION.md#L10)):*
> produciton
typo

---

*[CONFIGURATION.md, line 25 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/78#-KPULf1c9cjNSyQFBT_N:-KPULf1c9cjNSyQFBT_O:b-7lpefo) ([raw file](https://github.com/criteo/biggraphite/blob/ba011bf628f6769d4ae28c9dcead5f6619f3fcc6/CONFIGURATION.md#L25)):*
> debubging
typo

---

*[biggraphite/utils.py, line 55 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/78#-KPUMdvo-_d4ZF8kYU_b:-KPUMdvo-_d4ZF8kYU_c:bmlr4vr) ([raw file](https://github.com/criteo/biggraphite/blob/ba011bf628f6769d4ae28c9dcead5f6619f3fcc6/biggraphite/utils.py#L55)):*
> ```Python
>     except (TypeError, KeyError):
>         try:
>             res = getattr(settings, name)
> ```

you may avoid the second try/except by putting a default value in getattr, eg (settings, name, default)
I also would have directly put the getattr in the first place but I am maybe missing a case here.

---

*[biggraphite/utils.py, line 60 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/78#-KPUO4tm4rdip4OH-yFH:-KPUO4tnOvp0sr1CGBvQ:b-1uz4os) ([raw file](https://github.com/criteo/biggraphite/blob/ba011bf628f6769d4ae28c9dcead5f6619f3fcc6/biggraphite/utils.py#L60)):*
> ```Python
>     # Fallback to env.
>     if res is None and name in os.environ:
>         res = os.environ[name]
> ```

I would have put a getattr here instead of the name ins os.environ test

---

*[biggraphite/drivers/memory.py, line 94 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/78#-KPUPkt3IbW04MaDHAN6:-KPUPkt3IbW04MaDHAN7:bni0ce8) ([raw file](https://github.com/criteo/biggraphite/blob/ba011bf628f6769d4ae28c9dcead5f6619f3fcc6/biggraphite/drivers/memory.py#L94)):*
> ```Python
>         dots_count = glob.count(".")
>         glob_re = re.compile(fnmatch.translate(glob))
>         for name in names:
> ```

we may use list comprehensions here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/78)*

**Comment by iksaif** [comment]
Review status: 0 of 14 files reviewed at latest revision, 5 unresolved discussions.

---

*[CONFIGURATION.md, line 10 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/78#-KPUI2ZQLPxwHxGCuyjb:-KPkzXDbIE01YROFCzNk:b-896fix) ([raw file](https://github.com/criteo/biggraphite/blob/ba011bf628f6769d4ae28c9dcead5f6619f3fcc6/CONFIGURATION.md#L10)):*
<details><summary><i>Previously, wdauchy (William Dauchy) wrote…</i></summary>
> > produciton
> typo
</details>
Done.

---

*[CONFIGURATION.md, line 25 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/78#-KPULf1c9cjNSyQFBT_N:-KPkzaLJsnJcN4nqH1wR:b-896fix) ([raw file](https://github.com/criteo/biggraphite/blob/ba011bf628f6769d4ae28c9dcead5f6619f3fcc6/CONFIGURATION.md#L25)):*
<details><summary><i>Previously, wdauchy (William Dauchy) wrote…</i></summary>
> > debubging
> typo
</details>
Done.

---

*[biggraphite/utils.py, line 55 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/78#-KPUMdvo-_d4ZF8kYU_b:-KPl-BlAymmEB6qoBuME:b1r5xy1) ([raw file](https://github.com/criteo/biggraphite/blob/ba011bf628f6769d4ae28c9dcead5f6619f3fcc6/biggraphite/utils.py#L55)):*
<details><summary><i>Previously, wdauchy (William Dauchy) wrote…</i></summary>
> you may avoid the second try/except by putting a default value in getattr, eg (settings, name, default)
> I also would have directly put the getattr in the first place but I am maybe missing a case here.
</details>
it would not have the same behavior. We try to use it as a dict first, then as an object. And I can't use .get(key, default) because I'm not sure all indexable objects have this method.

---

*[biggraphite/utils.py, line 60 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/78#-KPUO4tm4rdip4OH-yFH:-KPl-p8Pu4J7XYdzeGia:b-896fix) ([raw file](https://github.com/criteo/biggraphite/blob/ba011bf628f6769d4ae28c9dcead5f6619f3fcc6/biggraphite/utils.py#L60)):*
<details><summary><i>Previously, wdauchy (William Dauchy) wrote…</i></summary>
> I would have put a getattr here instead of the name ins os.environ test
</details>
Done.

---

*[biggraphite/drivers/memory.py, line 94 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/78#-KPUPkt3IbW04MaDHAN6:-KPl00qY73bFJRZls2-n:b-896fix) ([raw file](https://github.com/criteo/biggraphite/blob/ba011bf628f6769d4ae28c9dcead5f6619f3fcc6/biggraphite/drivers/memory.py#L94)):*
<details><summary><i>Previously, wdauchy (William Dauchy) wrote…</i></summary>
> we may use list comprehensions here
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/78)*

**Comment by wdauchy** [comment]
:lgtm:

---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/78#-:-KPl8nl4eIYxIknC4t30:bnfp4nl)*

**Comment by wdauchy** [comment]
:strong_lgtm:

**Comment by wdauchy** [comment]
:lgtm_strong: 

---

Review status: 11 of 14 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/78#-:-KPlJkpyJ5wgjHG_VE2e:b-uwkowd)*

**Pull request merged**
