### PR TITLE
Cleanup metadata First try 

### PR DESCRIPTION
**Pull request by erebe**
Leave your comment after the bip

*bip*

---
This change is [Reviewable](https://reviewable.io/reviews/criteo/biggraphite/185)

### CODE REVIEW

**Comment by iksaif** [comment]
Also check "bgutil clean" that should be updated to call your method

---

Review status: 0 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[biggraphite/accessor.py, line 784 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/185#-KX6Vy-hYtzQoDn0yDW4:-KX6Vy-hYtzQoDn0yDW5:b-no1z91) ([raw file](https://github.com/criteo/biggraphite/blob/b453824387f48cd8c4fc081df1b9e4172afd5d09/biggraphite/accessor.py#L784)):*
> ```Python
> 
>     @abc.abstractmethod
>     def update_metric_modification_time(self, metric_name):
> ```

maybe "touch_metric()" ?

---

*[biggraphite/accessor.py, line 789 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/185#-KX6Vs9Upf3W0vO3TQv6:-KX6Vs9Upf3W0vO3TQv7:b37lzmp) ([raw file](https://github.com/criteo/biggraphite/blob/b453824387f48cd8c4fc081df1b9e4172afd5d09/biggraphite/accessor.py#L789)):*
> ```Python
> 
>     @abc.abstractmethod
>     def delete_expired_metrics(self, cutoff=None):
> ```

This was called "clean()" in the cache.

---

*[biggraphite/metadata_cache.py, line 365 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/185#-KX6WKAOAKAUpcopoMAs:-KX6WKAOAKAUpcopoMAt:bh8l18s) ([raw file](https://github.com/criteo/biggraphite/blob/b453824387f48cd8c4fc081df1b9e4172afd5d09/biggraphite/metadata_cache.py#L365)):*
> ```Python
>         # update timestamp if expired
>         if self.__expired_timestamp(timestamp):
>             self._accessor.update_metric_modification_time(metric_name)
> ```

I think this should be called in metric_get() when the timestamp in the database is too far away (get_metric() will be called regularly because old metrics are removed from the cache)

---

*[biggraphite/drivers/cassandra.py, line 198 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/185#-KX6WfIAAhHT5PKhdZHS:-KX6WfIAAhHT5PKhdZHT:bq663qn) ([raw file](https://github.com/criteo/biggraphite/blob/b453824387f48cd8c4fc081df1b9e4172afd5d09/biggraphite/drivers/cassandra.py#L198)):*
> ```Python
> 
> _METADATA_CREATION_CQL_METRICS_MODIFICATION_TIME = str(
>     "CREATE TABLE IF NOT EXISTS \"%(keyspace)s\".metrics_modification_time ("
> ```

Do we need to create a table just for metrics_modification_time or should we just create metrics_metadata to also store id and config ? Should this be done later ?

---

*[biggraphite/drivers/cassandra.py, line 1191 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/185#-KX6X0o3H4TcD8Sby0u3:-KX6X0o3H4TcD8Sby0u4:b-ssy40k) ([raw file](https://github.com/criteo/biggraphite/blob/b453824387f48cd8c4fc081df1b9e4172afd5d09/biggraphite/drivers/cassandra.py#L1191)):*
> ```Python
>         select.consistency_level = cassandra.ConsistencyLevel.LOCAL_QUORUM
>         select.retry_policy = cassandra.policies.DowngradingConsistencyRetryPolicy
>         select.request_timeout = 120
> ```

Did you try to run that on a large table ? I suspect that this approach won't work and that you'll need to do something like repairs() (more small queries). Maybe we can do that in a second time.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/185#-:-KX6XOCLDkNyKzmCTXut:bd50cqv)*

**Comment by erebe** [comment]
yep, I am already working on it

---

Review status: 0 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[biggraphite/accessor.py, line 784 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/185#-KX6Vy-hYtzQoDn0yDW4:-KX6_YGzNvYnWWgPM-ls:bo8pbrz) ([raw file](https://github.com/criteo/biggraphite/blob/b453824387f48cd8c4fc081df1b9e4172afd5d09/biggraphite/accessor.py#L784)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> maybe "touch_metric()" ?
</details>
ok , will change

---

*[biggraphite/accessor.py, line 789 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/185#-KX6Vs9Upf3W0vO3TQv6:-KX6_Z_H8s25jB6-d1_h:bo8pbrz) ([raw file](https://github.com/criteo/biggraphite/blob/b453824387f48cd8c4fc081df1b9e4172afd5d09/biggraphite/accessor.py#L789)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> This was called "clean()" in the cache.
</details>
ok , will change

---

*[biggraphite/metadata_cache.py, line 365 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/185#-KX6WKAOAKAUpcopoMAs:-KX6_xznGrX4BN2h-nCv:b6nvmow) ([raw file](https://github.com/criteo/biggraphite/blob/b453824387f48cd8c4fc081df1b9e4172afd5d09/biggraphite/metadata_cache.py#L365)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> I think this should be called in metric_get() when the timestamp in the database is too far away (get_metric() will be called regularly because old metrics are removed from the cache)
</details>
Not sure about what do you call "metric_get()".
I don't find any trace of it in the codebase, is it different than get_metric ?

---

*[biggraphite/drivers/cassandra.py, line 198 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/185#-KX6WfIAAhHT5PKhdZHS:-KX6aqZcHWEKdI6SF4Ca:b-cz6dfw) ([raw file](https://github.com/criteo/biggraphite/blob/b453824387f48cd8c4fc081df1b9e4172afd5d09/biggraphite/drivers/cassandra.py#L198)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> Do we need to create a table just for metrics_modification_time or should we just create metrics_metadata to also store id and config ? Should this be done later ?
</details>
As I discover the codebase, I am not quite sure about the access pattern. So for now, I prefer to let it alone in its own table and merge it later if it is overkill.  

---

*[biggraphite/drivers/cassandra.py, line 1191 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/185#-KX6X0o3H4TcD8Sby0u3:-KX6bHYw7avv1ZZsjoLT:brhwadx) ([raw file](https://github.com/criteo/biggraphite/blob/b453824387f48cd8c4fc081df1b9e4172afd5d09/biggraphite/drivers/cassandra.py#L1191)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> Did you try to run that on a large table ? I suspect that this approach won't work and that you'll need to do something like repairs() (more small queries). Maybe we can do that in a second time.
</details>
Not yet for the dry run, I wanted to get your feed back first.
But I would prefer to test the delete before going to prod.

Just for my knowledge how much "big" is for you  as I have no idea of the expected workload ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/185#-:-KX6cpZ_ujdcojZivUqG:b-4fa75h)*

**Comment by iksaif** [comment]
Review status: 0 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[biggraphite/metadata_cache.py, line 365 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/185#-KX6WKAOAKAUpcopoMAs:-KX6gMZY2Zz-BvniZjgQ:bys6dtf) ([raw file](https://github.com/criteo/biggraphite/blob/b453824387f48cd8c4fc081df1b9e4172afd5d09/biggraphite/metadata_cache.py#L365)):*
<details><summary><i>Previously, erebe (Erèbe - Romain Gerard) wrote…</i></summary>
> Not sure about what do you call "metric_get()".
> I don't find any trace of it in the codebase, is it different than get_metric ?
</details>
I meant `get_metric()`

---

*[biggraphite/drivers/cassandra.py, line 198 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/185#-KX6WfIAAhHT5PKhdZHS:-KX6gR2AzlbolueRetmf:b-507qx0) ([raw file](https://github.com/criteo/biggraphite/blob/b453824387f48cd8c4fc081df1b9e4172afd5d09/biggraphite/drivers/cassandra.py#L198)):*
<details><summary><i>Previously, erebe (Erèbe - Romain Gerard) wrote…</i></summary>
> As I discover the codebase, I am not quite sure about the access pattern. So for now, I prefer to let it alone in its own table and merge it later if it is overkill.  
</details>
The thing is that if we are going to move out the rest later, it's better if we don't create a useless temporary intermediate table.
The access pattern is currently:
- glob_metrics(glob): returns metric names matching this glob
- get_metric(metric): returns metric metadata for this metric name

The metric metadata is usually cached by the client so we don't need to make glob_metrics() return the metadata.

---

*[biggraphite/drivers/cassandra.py, line 1191 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/185#-KX6X0o3H4TcD8Sby0u3:-KX6gtZzPEMsKeii6Icp:btb17py) ([raw file](https://github.com/criteo/biggraphite/blob/b453824387f48cd8c4fc081df1b9e4172afd5d09/biggraphite/drivers/cassandra.py#L1191)):*
<details><summary><i>Previously, erebe (Erèbe - Romain Gerard) wrote…</i></summary>
> Not yet for the dry run, I wanted to get your feed back first.
> But I would prefer to test the delete before going to prod.
> 
> Just for my knowledge how much "big" is for you  as I have no idea of the expected workload ?
</details>
See cstars04 in prod and preprod to get some numbers. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/185)*

**Comment by iksaif** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[biggraphite/drivers/cassandra.py, line 198 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/185#-KX6WfIAAhHT5PKhdZHS:-KXB0jyiY6GlMRmyv6N3:b32wtd) ([raw file](https://github.com/criteo/biggraphite/blob/b453824387f48cd8c4fc081df1b9e4172afd5d09/biggraphite/drivers/cassandra.py#L198)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> The thing is that if we are going to move out the rest later, it's better if we don't create a useless temporary intermediate table.
> The access pattern is currently:
> - glob_metrics(glob): returns metric names matching this glob
> - get_metric(metric): returns metric metadata for this metric name
> 
> The metric metadata is usually cached by the client so we don't need to make glob_metrics() return the metadata.
</details>
ok

---

*[biggraphite/drivers/cassandra.py, line 1191 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/185#-KX6X0o3H4TcD8Sby0u3:-KXB1Cme4MT7tzyAMELF:b32wtd) ([raw file](https://github.com/criteo/biggraphite/blob/b453824387f48cd8c4fc081df1b9e4172afd5d09/biggraphite/drivers/cassandra.py#L1191)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> See cstars04 in prod and preprod to get some numbers. 
</details>
ok

---

*[biggraphite/drivers/cassandra.py, line 197 at r2](https://reviewable.io:443/reviews/criteo/biggraphite/185#-KXB1GW0nz01cNkfXGTY:-KXB1GW0nz01cNkfXGTZ:b-f8vnto) ([raw file](https://github.com/criteo/biggraphite/blob/d4d7173d4c5c4916c8de7450b005ac0df7ec50fc/biggraphite/drivers/cassandra.py#L197)):*
> ```Python
> )
> 
> _METADATA_TOUCH_TTL_SEC = 1 * 60 * 60
> ```

We probably want that to be a few days by default. I'd put 3 days.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/185)*

**Comment by iksaif** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[biggraphite/drivers/cassandra.py, line 1164 at r2](https://reviewable.io:443/reviews/criteo/biggraphite/185#-KXB7-42HVbcf3m5nlpJ:-KXB7-42HVbcf3m5nlpK:b-1ev6rx) ([raw file](https://github.com/criteo/biggraphite/blob/d4d7173d4c5c4916c8de7450b005ac0df7ec50fc/biggraphite/drivers/cassandra.py#L1164)):*
> ```Python
> 
>         tables = self.__cluster.metadata.keyspaces[self.keyspace_metadata].tables
>         if 'metrics' in tables and 'directories' in tables:
> ```

check if metrics_metadata exists also here ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/185)*

**Comment by iksaif** [comment]
Looks mostly good, it seems like you'll need to rebase :)

---

Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[biggraphite/cli/command_clean.py, line 61 at r3](https://reviewable.io:443/reviews/criteo/biggraphite/185#-KXBp0QqcBKFwn5dqpqM:-KXBp0QqcBKFwn5dqpqN:bmxtzmj) ([raw file](https://github.com/criteo/biggraphite/blob/cedfc592fca05cba4c61e8e6fe1bce378d77ee94/biggraphite/cli/command_clean.py#L61)):*
> ```Python
>         See command.BaseCommand
>         """
>         with accessor as bg_acc:
> ```

why do we want a "with" here ? it moves all the code to the right :/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/185#-:-KXBpj9wxNgINi9bcngH:b-qslhkb)*

**Comment by erebe** [comment]
yep, going to merge

---

Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[biggraphite/metadata_cache.py, line 364 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/185#-KXA3vQFcKbqyhOkhfH-:-KXA3vQFcKbqyhOkhfH0:bprvb83) ([raw file](https://github.com/criteo/biggraphite/blob/2592488b75bf2059838b16e8c387604a827ae77a/biggraphite/metadata_cache.py#L364)):*
>         if self.__expired_timestamp(timestamp):
>       

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/185#-:-KXBrkGdy9r0XtMjkhNg:bokt2i4)*

**Comment by iksaif** [comment]
:lgtm_strong: 

---

Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/185#-:-KXBzMY2pVyo4z43_DgT:b-uwkowd)*

**Pull request merged**
