### PR TITLE
bgutil: add ways to shard repairs

### PR DESCRIPTION
**Pull request by iksaif**
See #60.

---
This change is [Reviewable](https://reviewable.io/reviews/criteo/biggraphite/119)

### CODE REVIEW

**Comment by iksaif** [comment]
@natbraun 

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/119#-:-KRZts9hq4165p-_gsEa:bwix4nw)*

**Comment by natbraun** [comment]
Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[biggraphite/accessor.py, line 726 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/119#-KRh6baAANcnwCq6CjNf:-KRh6baAANcnwCq6CjNg:b-xn8q6p) ([raw file](https://github.com/criteo/biggraphite/blob/12a32da1ce2ad303207d1bcdfdad421aba42ce56/biggraphite/accessor.py#L726)):*
> ```Python
>         Args:
>           start_key: string, start at key >= start_key.
>           end_key: string, stop at key == end_key.
> ```

Question: shouldn't this be the standard left-inclusive, right-exclusive semantics?

---

*[biggraphite/metadata_cache.py, line 236 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/119#-KRh6lExDdSahApypAzM:-KRh6lExDdSahApypAzN:bnj7hl0) ([raw file](https://github.com/criteo/biggraphite/blob/12a32da1ce2ad303207d1bcdfdad421aba42ce56/biggraphite/metadata_cache.py#L236)):*
> ```Python
>         Args:
>           start_key: string, start at key >= start_key.
>           end_key: string, stop at key == end_key.
> ```

same as above

---

*[biggraphite/metadata_cache.py, line 249 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/119#-KRh6qV5l6A3E0L9mTeG:-KRh6qV5l6A3E0L9mTeH:bnj7hl0) ([raw file](https://github.com/criteo/biggraphite/blob/12a32da1ce2ad303207d1bcdfdad421aba42ce56/biggraphite/metadata_cache.py#L249)):*
> ```Python
>                 print (key, value)
>                 i += 1
>                 if end_key is not None and key > end_key:
> ```

same as above

---

*[biggraphite/drivers/cassandra.py, line 651 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/119#-KRh7HdPb0a2BY2dkN98:-KRh7HdPb0a2BY2dkN99:b-si4kog) ([raw file](https://github.com/criteo/biggraphite/blob/12a32da1ce2ad303207d1bcdfdad421aba42ce56/biggraphite/drivers/cassandra.py#L651)):*
> ```Python
>             result = self.__session.execute(statement, args)
> 
>             if not len(result.current_rows):
> ```

len == 0 seems better, I think

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/119)*

**Comment by iksaif** [comment]
Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[biggraphite/accessor.py, line 726 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/119#-KRh6baAANcnwCq6CjNf:-KRhAHx6UujZTXsg7hq2:bb7f2mf) ([raw file](https://github.com/criteo/biggraphite/blob/12a32da1ce2ad303207d1bcdfdad421aba42ce56/biggraphite/accessor.py#L726)):*
<details><summary><i>Previously, natbraun (Nathaniel Braun) wrote…</i></summary>
> Question: shouldn't this be the standard left-inclusive, right-exclusive semantics?
</details>
done

---

*[biggraphite/metadata_cache.py, line 236 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/119#-KRh6lExDdSahApypAzM:-KRhAx9G471MKN9ok5G5:b-896fix) ([raw file](https://github.com/criteo/biggraphite/blob/12a32da1ce2ad303207d1bcdfdad421aba42ce56/biggraphite/metadata_cache.py#L236)):*
<details><summary><i>Previously, natbraun (Nathaniel Braun) wrote…</i></summary>
> same as above
</details>
Done.

---

*[biggraphite/metadata_cache.py, line 249 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/119#-KRh6qV5l6A3E0L9mTeG:-KRhAxX2DYZSEcb9kRtO:b-896fix) ([raw file](https://github.com/criteo/biggraphite/blob/12a32da1ce2ad303207d1bcdfdad421aba42ce56/biggraphite/metadata_cache.py#L249)):*
<details><summary><i>Previously, natbraun (Nathaniel Braun) wrote…</i></summary>
> same as above
</details>
Done.

---

*[biggraphite/drivers/cassandra.py, line 651 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/119#-KRh7HdPb0a2BY2dkN98:-KRhB1-hRE6cZJ2hFn5O:b-896fix) ([raw file](https://github.com/criteo/biggraphite/blob/12a32da1ce2ad303207d1bcdfdad421aba42ce56/biggraphite/drivers/cassandra.py#L651)):*
<details><summary><i>Previously, natbraun (Nathaniel Braun) wrote…</i></summary>
> len == 0 seems better, I think
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/119)*

**Comment by natbraun** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[biggraphite/metadata_cache.py, line 247 at r2](https://reviewable.io:443/reviews/criteo/biggraphite/119#-KRhDfZIZYo1EEqzojfn:-KRhDfZIZYo1EEqzojfo:b-a7jo2c) ([raw file](https://github.com/criteo/biggraphite/blob/56e25052c966c396bf6993268b7df8a0d89cbe10/biggraphite/metadata_cache.py#L247)):*
> ```Python
>                     return
>             for key, value in cursor:
>                 print (key, value)
> ```

Do we need this print here? If yes, I suggest making it more explicit, like print('Key => value: %s => %s" % (key, value))

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/119)*

**Comment by iksaif** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[biggraphite/metadata_cache.py, line 247 at r2](https://reviewable.io:443/reviews/criteo/biggraphite/119#-KRhDfZIZYo1EEqzojfn:-KRhNL-tR4O_obZlFRve:b-896fix) ([raw file](https://github.com/criteo/biggraphite/blob/56e25052c966c396bf6993268b7df8a0d89cbe10/biggraphite/metadata_cache.py#L247)):*
<details><summary><i>Previously, natbraun (Nathaniel Braun) wrote…</i></summary>
> Do we need this print here? If yes, I suggest making it more explicit, like print('Key => value: %s => %s" % (key, value))
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/119)*

**Comment by natbraun** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[biggraphite/accessor.py, line 714 at r3](https://reviewable.io:443/reviews/criteo/biggraphite/119#-KRiEdH0XJXJUt32lfCc:-KRiEdH0XJXJUt32lfCd:b-x80d8d) ([raw file](https://github.com/criteo/biggraphite/blob/dc5a3afd1f2447dc680c4d0221018c375c2dcde7/biggraphite/accessor.py#L714)):*
>     

---

*[biggraphite/accessor.py, line 721 at r3](https://reviewable.io:443/reviews/criteo/biggraphite/119#-KRiETgFdLdJDzPjbVla:-KRiETgFdLdJDzPjbVlb:b9b9uw5) ([raw file](https://github.com/criteo/biggraphite/blob/dc5a3afd1f2447dc680c4d0221018c375c2dcde7/biggraphite/accessor.py#L721)):*
> ```Python
>         During the repair the keyspace is split in nshards and
>         this function will only take car of 1/n th of the data
>         as specified by shard. This allows the caller to parallelize
> ```

take care

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/119)*

**Comment by natbraun** [comment]
:lgtm_strong:  after my comment is fixed

---

Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/119#-:-KRiEuJSJ0vypCK6Sol2:bk28y1u)*

**Pull request merged**
