### PR TITLE
Support for TTLs

### PR DESCRIPTION
**Pull request by unbrice**
This change is [Reviewable](https://reviewable.io/reviews/criteo/biggraphite/58)

### CODE REVIEW

**Comment by unbrice** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[biggraphite/drivers/cassandra.py, line 427 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/58#-KNbanPoyjHI56J8H1iJ:-KNbanPp_OwV5g5k4n2I:1184896412) ([raw file](https://github.com/criteo/biggraphite/blob/372e1c8c6163d150f9c9d5b3c7370a16fb2aa15b/biggraphite/drivers/cassandra.py#L427)):*
> ```Python
>                 count_down.on_cassandra_result(None)
>                 continue
>             else:
> ```

Discard raw and use #59  instead

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/58)*

**Comment by unbrice** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[biggraphite/drivers/cassandra.py, line 427 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/58#-KNbanPoyjHI56J8H1iJ:-KNc5m3Y4J-3Qzlm3cQl:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/372e1c8c6163d150f9c9d5b3c7370a16fb2aa15b/biggraphite/drivers/cassandra.py#L427)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> Discard raw and use #59  instead
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/58)*

**Comment by unbrice** [comment]
+@iksaif +@natbraun 

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/58#-:-KNc5qlOFzozhNBZ5-yS:1157692033)*

**Comment by natbraun** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[biggraphite/accessor.py, line 285 \[r5\]](https://reviewable.io:443/reviews/criteo/biggraphite/58#-KNcCooKKHlLuA2tmt8X:-KNcCooKKHlLuA2tmt8Y:-1694559970) ([raw file](https://github.com/criteo/biggraphite/blob/568c03ad88d8e3b68804f6c4685365fe658c0fce/biggraphite/accessor.py#L285)):*
> ```Python
>     @property
>     def precision_ms(self):
>         """The duration of this stage in microseconds."""
> ```

We're mixing precision and duration. Let's try to unite them.

---

*[biggraphite/drivers/cassandra.py, line 115 \[r5\]](https://reviewable.io:443/reviews/criteo/biggraphite/58#-KNcDKDG5ruqKxZLNzwu:-KNcDKDG5ruqKxZLNzwv:-282460860) ([raw file](https://github.com/criteo/biggraphite/blob/568c03ad88d8e3b68804f6c4685365fe658c0fce/biggraphite/drivers/cassandra.py#L115)):*
> ```Python
> 
> class _DataTablesManager(object):
> ```

Please add missing doc string for this class.

---

*[biggraphite/drivers/cassandra.py, line 423 \[r5\]](https://reviewable.io:443/reviews/criteo/biggraphite/58#-KNcDbWC2eNP2sBOWIDb:-KNcDbWC2eNP2sBOWIDc:317030890) ([raw file](https://github.com/criteo/biggraphite/blob/568c03ad88d8e3b68804f6c4685365fe658c0fce/biggraphite/drivers/cassandra.py#L423)):*
> ```Python
> 
>         for timestamp, value, count, stage in downsampled:
>             timestamp_ms = int(timestamp) * 1000
> ```

I think the int conversion is redundant here, because we deal with int everywhere now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/58)*

**Comment by natbraun** [comment]
Reviewed 2 of 2 files at r3, 2 of 2 files at r4, 1 of 2 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/58)*

**Comment by unbrice** [comment]
Review status: 4 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[biggraphite/accessor.py, line 285 \[r5\]](https://reviewable.io:443/reviews/criteo/biggraphite/58#-KNcCooKKHlLuA2tmt8X:-KNf5zO5SDhnmr3eC4fO:167974704) ([raw file](https://github.com/criteo/biggraphite/blob/568c03ad88d8e3b68804f6c4685365fe658c0fce/biggraphite/accessor.py#L285)):*
<details><summary><i>Previously, natbraun (Nathaniel Braun) wrote…</i></summary>
> We're mixing precision and duration. Let's try to unite them.
</details>
Indeed precision, duration, step and epoch are confusing. Do you have something in mind?

---

*[biggraphite/drivers/cassandra.py, line 115 \[r5\]](https://reviewable.io:443/reviews/criteo/biggraphite/58#-KNcDKDG5ruqKxZLNzwu:-KNfEefP7Hca4swqR1dC:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/568c03ad88d8e3b68804f6c4685365fe658c0fce/biggraphite/drivers/cassandra.py#L115)):*
<details><summary><i>Previously, natbraun (Nathaniel Braun) wrote…</i></summary>
> Please add missing doc string for this class.
</details>
Done.

---

*[biggraphite/drivers/cassandra.py, line 423 \[r5\]](https://reviewable.io:443/reviews/criteo/biggraphite/58#-KNcDbWC2eNP2sBOWIDb:-KNfEoNW91R5TU5AeCkV:-34519903) ([raw file](https://github.com/criteo/biggraphite/blob/568c03ad88d8e3b68804f6c4685365fe658c0fce/biggraphite/drivers/cassandra.py#L423)):*
<details><summary><i>Previously, natbraun (Nathaniel Braun) wrote…</i></summary>
> I think the int conversion is redundant here, because we deal with int everywhere now.
</details>
This is not specified in downsampler's API. Also timestamps are often floats in Python so I like making the type explicit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/58)*

**Comment by iksaif** [comment]
Review status: 4 of 5 files reviewed at latest revision, 7 unresolved discussions.

---

*[biggraphite/drivers/cassandra.py, line 101 \[r5\]](https://reviewable.io:443/reviews/criteo/biggraphite/58#-KNfAdc6wL9fM3ohTK-J:-KNfAdc712FbgL1oZH0O:911568685) ([raw file](https://github.com/criteo/biggraphite/blob/568c03ad88d8e3b68804f6c4685365fe658c0fce/biggraphite/drivers/cassandra.py#L101)):*
> ```Python
>     ")"
>     "  WITH CLUSTERING ORDER BY (time_offset_ms DESC)"
>     "  AND default_time_to_live = %(default_time_to_live)d"
> ```

please add comments explaining which values will be used and why

---

*[biggraphite/drivers/cassandra.py, line 104 \[r5\]](https://reviewable.io:443/reviews/criteo/biggraphite/58#-KNfC7kw02a4nPWbDEVd:-KNfC7kxh8gNk3puNi_p:-793900979) ([raw file](https://github.com/criteo/biggraphite/blob/568c03ad88d8e3b68804f6c4685365fe658c0fce/biggraphite/drivers/cassandra.py#L104)):*
> ```Python
>     "  AND compaction = {"
>     "    'timestamp_resolution': 'MICROSECONDS',"
>     "    'base_time_seconds': '%(base_time_seconds)d',"
> ```

I think you forgot max_window_size_seconds here

---

*[biggraphite/drivers/cassandra.py, line 117 \[r5\]](https://reviewable.io:443/reviews/criteo/biggraphite/58#-KNfAb0P7TRH7r7aSUip:-KNfAb0P7TRH7r7aSUiq:-161312317) ([raw file](https://github.com/criteo/biggraphite/blob/568c03ad88d8e3b68804f6c4685365fe658c0fce/biggraphite/drivers/cassandra.py#L117)):*
> _OUT_OF_ORDER_S = 3600
why  3600 ?

---

*[biggraphite/drivers/cassandra.py, line 129 \[r5\]](https://reviewable.io:443/reviews/criteo/biggraphite/58#-KNfCAaaob-KtzWeC9y4:-KNfCAaaob-KtzWeC9y5:785366012) ([raw file](https://github.com/criteo/biggraphite/blob/568c03ad88d8e3b68804f6c4685365fe658c0fce/biggraphite/drivers/cassandra.py#L129)):*
> ```Python
>             "default_time_to_live": stage.duration + self._OUT_OF_ORDER_S,
>             "max_window_size_seconds": self._OUT_OF_ORDER_S,
>             "base_time_seconds": self._OUT_OF_ORDER_S,
> ```

(this should be documented in the code and in the .md file): why _OUT_OF_ORDER_S ?
why not 
```
# This first window: A.K.A what we usually want to read. At least OUT_OF_ORDER_S but up to a few steps.
base_time_seconds = max(self._OUT_OF_ORDER_S, stage.step * 16)
# The other windows are base_time_seconds * min_threshold (4) size. This can limit the size of other windows.
max_window_size_seconds = ?? # Why would we want to limit it ?
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/58)*

**Comment by natbraun** [comment]
*[biggraphite/drivers/cassandra.py, line 423 \[r5\]](https://reviewable.io:443/reviews/criteo/biggraphite/58#-KNcDbWC2eNP2sBOWIDb:-KNfTVKkJDXJtQA0ePwp:298657166) ([raw file](https://github.com/criteo/biggraphite/blob/568c03ad88d8e3b68804f6c4685365fe658c0fce/biggraphite/drivers/cassandra.py#L423)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> This is not specified in downsampler's API. Also timestamps are often floats in Python so I like making the type explicit.
</details>
We can specify if you want. It really deals with integers only.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/58)*

**Comment by natbraun** [comment]
Review status: 4 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

*[biggraphite/accessor.py, line 285 \[r5\]](https://reviewable.io:443/reviews/criteo/biggraphite/58#-KNcCooKKHlLuA2tmt8X:-KNfSLMSmtNYRfg7mDp3:-443055904) ([raw file](https://github.com/criteo/biggraphite/blob/568c03ad88d8e3b68804f6c4685365fe658c0fce/biggraphite/accessor.py#L285)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> Indeed precision, duration, step and epoch are confusing. Do you have something in mind?
</details>
Let's stick with precision and epoch - does that suit you?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/58)*

**Comment by unbrice** [comment]
Review status: 4 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

*[biggraphite/accessor.py, line 285 \[r5\]](https://reviewable.io:443/reviews/criteo/biggraphite/58#-KNcCooKKHlLuA2tmt8X:-KNfv06YcRmEocsB8DSV:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/568c03ad88d8e3b68804f6c4685365fe658c0fce/biggraphite/accessor.py#L285)):*
<details><summary><i>Previously, natbraun (Nathaniel Braun) wrote…</i></summary>
> Let's stick with precision and epoch - does that suit you?
</details>
Done.

---

*[biggraphite/drivers/cassandra.py, line 101 \[r5\]](https://reviewable.io:443/reviews/criteo/biggraphite/58#-KNfAdc6wL9fM3ohTK-J:-KNfv1EuVHj0Sf5Alcrc:-237216968) ([raw file](https://github.com/criteo/biggraphite/blob/568c03ad88d8e3b68804f6c4685365fe658c0fce/biggraphite/drivers/cassandra.py#L101)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> please add comments explaining which values will be used and why
</details>
Done, and that gave me a chance to fix meaningless values, PTAL

---

*[biggraphite/drivers/cassandra.py, line 104 \[r5\]](https://reviewable.io:443/reviews/criteo/biggraphite/58#-KNfC7kw02a4nPWbDEVd:-KNfv4sCaragCPyHWfhr:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/568c03ad88d8e3b68804f6c4685365fe658c0fce/biggraphite/drivers/cassandra.py#L104)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> I think you forgot max_window_size_seconds here
</details>
Done.

---

*[biggraphite/drivers/cassandra.py, line 117 \[r5\]](https://reviewable.io:443/reviews/criteo/biggraphite/58#-KNfAb0P7TRH7r7aSUip:-KNfLNkeaLtZIBlmdIeP:-464203785) ([raw file](https://github.com/criteo/biggraphite/blob/568c03ad88d8e3b68804f6c4685365fe658c0fce/biggraphite/drivers/cassandra.py#L117)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> > _OUT_OF_ORDER_S = 3600
> why  3600 ?
</details>
Order of magnitude above clock skew and network delays, reduced to 900 because that's enough.

---

*[biggraphite/drivers/cassandra.py, line 129 \[r5\]](https://reviewable.io:443/reviews/criteo/biggraphite/58#-KNfCAaaob-KtzWeC9y4:-KNfuniunonhzEdKYqO1:20567299) ([raw file](https://github.com/criteo/biggraphite/blob/568c03ad88d8e3b68804f6c4685365fe658c0fce/biggraphite/drivers/cassandra.py#L129)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> (this should be documented in the code and in the .md file): why _OUT_OF_ORDER_S ?
> why not 
> ```
> # This first window: A.K.A what we usually want to read. At least OUT_OF_ORDER_S but up to a few steps.
> base_time_seconds = max(self._OUT_OF_ORDER_S, stage.step * 16)
> # The other windows are base_time_seconds * min_threshold (4) size. This can limit the size of other windows.
> max_window_size_seconds = ?? # Why would we want to limit it ?
> ```
</details>
Indeed, done, PTAL

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/58)*

**Comment by natbraun** [comment]
Reviewed 1 of 1 files at r6.
Review status: 4 of 5 files reviewed at latest revision, 7 unresolved discussions.

---

*[biggraphite/accessor.py, line 285 \[r5\]](https://reviewable.io:443/reviews/criteo/biggraphite/58#-KNfvXL0Z3hUwY9lg5Om:-KNfvXL1yR_2Jys1xfsk:-721097321) ([raw file](https://github.com/criteo/biggraphite/blob/568c03ad88d8e3b68804f6c4685365fe658c0fce/biggraphite/accessor.py#L285)):*
> ```Python
>     @property
>     def precision_ms(self):
>         """The duration of this stage in microseconds."""
> ```

This is milliseconds, no?
Moreover, I think you still have duration in some places :(

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/58)*

**Comment by unbrice** [comment]
Review status: 3 of 5 files reviewed at latest revision, 7 unresolved discussions.

---

*[biggraphite/accessor.py, line 285 \[r5\]](https://reviewable.io:443/reviews/criteo/biggraphite/58#-KNfvXL0Z3hUwY9lg5Om:-KNfxZPadO4nmbjLf2D4:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/568c03ad88d8e3b68804f6c4685365fe658c0fce/biggraphite/accessor.py#L285)):*
<details><summary><i>Previously, natbraun (Nathaniel Braun) wrote…</i></summary>
> This is milliseconds, no?
> Moreover, I think you still have duration in some places :(
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/58)*

**Comment by natbraun** [comment]
Reviewed 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/58)*

**Comment by natbraun** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/58#-:-KNgC-l8qyuHckAHucke:1417088721)*

**Comment by unbrice** [comment]
-@iksaif 

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/58#-:-KNgJ7CyWX9e1TCeKdQx:780244527)*

**Comment by iksaif** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[biggraphite/drivers/cassandra.py, line 140 \[r7\]](https://reviewable.io:443/reviews/criteo/biggraphite/58#-KNkpuyhP2N5SWXeC5Qg:-KNkpuyhP2N5SWXeC5Qh:-1596566641) ([raw file](https://github.com/criteo/biggraphite/blob/8b222a09a4181161e8edd0b72e12873d4f5a6e90/biggraphite/drivers/cassandra.py#L140)):*
> ```Python
> 
>         # Time it takes to receive a step
>         arrival_time = stage.precision + self._OUT_OF_ORDER_S
> ```

Please put OUT_OF_ORDER up in the module and describe what it controls.

---

*[biggraphite/drivers/cassandra.py, line 145 \[r7\]](https://reviewable.io:443/reviews/criteo/biggraphite/58#-KNkf4DlBbFCKKcrX5Sb:-KNkf4DlBbFCKKcrX5Sc:-1114828805) ([raw file](https://github.com/criteo/biggraphite/blob/8b222a09a4181161e8edd0b72e12873d4f5a6e90/biggraphite/drivers/cassandra.py#L145)):*
> ```Python
>         # Generally, we expect to use the last 16 points. As min_threshold==4, and 4*4=16,
>         # data are compacted twice.
>         read_time = stage.precision * 16
> ```

we usually read around 200 steps per graph (default in grafana)

EXPECTED_POINTS_PER_READ = 200 up there (and explain how changing it will affect the system)

---

*[biggraphite/drivers/cassandra.py, line 147 \[r7\]](https://reviewable.io:443/reviews/criteo/biggraphite/58#-KNkosbYI57IJl30Bmyv:-KNkfNHjdb718GDiXwod:-797881151) ([raw file](https://github.com/criteo/biggraphite/blob/8b222a09a4181161e8edd0b72e12873d4f5a6e90/biggraphite/drivers/cassandra.py#L147)):*
> ```Python
>         read_time = stage.precision * 16
>         # No point compacting data expiring today
>         read_time = min(read_time, time_to_live - self._SECONDS_PER_DAY)
> ```

put self._SECONDS_PER_DAY in a constant up there, and explain how changing it will affect the system.

---

*[biggraphite/drivers/cassandra.py, line 158 \[r7\]](https://reviewable.io:443/reviews/criteo/biggraphite/58#-KNkpiZVmG4NFK2ub5TV:-KNkpiZVmG4NFK2ub5TW:-136744561) ([raw file](https://github.com/criteo/biggraphite/blob/8b222a09a4181161e8edd0b72e12873d4f5a6e90/biggraphite/drivers/cassandra.py#L158)):*
> ```Python
>             # When we start compacting
>             "base_time_seconds": arrival_time,
>             # Max time span that we put together in one sstable.
> ```

Please change the wording. Even if it's likely to be that, this isn't guarantee. The only one is that cassandra will stop touching these (which is fine because there should be nothing to change anymore)

---

*[biggraphite/drivers/cassandra.py, line 161 \[r7\]](https://reviewable.io:443/reviews/criteo/biggraphite/58#-KNklGlXAl3yHwZyZE4I:-KNklGlXAl3yHwZyZE4J:-320073822) ([raw file](https://github.com/criteo/biggraphite/blob/8b222a09a4181161e8edd0b72e12873d4f5a6e90/biggraphite/drivers/cassandra.py#L161)):*
> ```Python
>             #  - If too small: Reads need to touch many sstables
>             #  - If too big: We pay compaction overhead for data that are never accessed anymore
>             "max_sstable_age_days": read_time_days,
> ```

Add https://labs.spotify.com/2014/12/18/date-tiered-compaction/

See 
- memtable_flush_period_in_ms (+memtable size threshold)
- crc_check_chance
- compression

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/58)*

**Comment by unbrice** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[biggraphite/drivers/cassandra.py, line 147 \[r7\]](https://reviewable.io:443/reviews/criteo/biggraphite/58#-KNkosbYI57IJl30Bmyv:-KNlHU-6EPZSmGa1v5VU:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/8b222a09a4181161e8edd0b72e12873d4f5a6e90/biggraphite/drivers/cassandra.py#L147)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> put self._SECONDS_PER_DAY in a constant up there, and explain how changing it will affect the system.
</details>
Done.

---

*[biggraphite/drivers/cassandra.py, line 158 \[r7\]](https://reviewable.io:443/reviews/criteo/biggraphite/58#-KNkpiZVmG4NFK2ub5TV:-KNlHTkAmfwU7_WhhVZq:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/8b222a09a4181161e8edd0b72e12873d4f5a6e90/biggraphite/drivers/cassandra.py#L158)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> Please change the wording. Even if it's likely to be that, this isn't guarantee. The only one is that cassandra will stop touching these (which is fine because there should be nothing to change anymore)
</details>
Done.

---

*[biggraphite/drivers/cassandra.py, line 161 \[r7\]](https://reviewable.io:443/reviews/criteo/biggraphite/58#-KNklGlXAl3yHwZyZE4I:-KNlISWAtS5GTuJX6dhL:475667425) ([raw file](https://github.com/criteo/biggraphite/blob/8b222a09a4181161e8edd0b72e12873d4f5a6e90/biggraphite/drivers/cassandra.py#L161)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> Add https://labs.spotify.com/2014/12/18/date-tiered-compaction/
> 
> See 
> - memtable_flush_period_in_ms (+memtable size threshold)
> - crc_check_chance
> - compression
</details>
As compression/CRC did not show up in thread analysis I didn't add them.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/58)*

**Pull request merged**
