### PR TITLE
Implement aggregation mechanism

### PR DESCRIPTION
**Pull request by natbraun**
This change is [Reviewable](https://reviewable.io/reviews/criteo/biggraphite/47)

### CODE REVIEW

**Comment by iksaif** [comment]
Review status: 0 of 2 files reviewed at latest revision, 12 unresolved discussions.

---

*[biggraphite/drivers/aggregator.py, line 21 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/47#-KMUdnSOtgNBBZ7yVOCy:-KMUdnSOtgNBBZ7yVOCz:481073474) ([raw file](https://github.com/criteo/biggraphite/blob/e9edc9d318fcf65fc067660afce002d90fa276d7/biggraphite/drivers/aggregator.py#L21)):*
> ```Python
> 
> 
> class StageAggregator(object):
> ```

StageCounter ? StageAggregate ? 

---

*[biggraphite/drivers/aggregator.py, line 42 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/47#-KMUe8IsoFYWhRzgkXIr:-KMUe8IsoFYWhRzgkXIs:-477109954) ([raw file](https://github.com/criteo/biggraphite/blob/e9edc9d318fcf65fc067660afce002d90fa276d7/biggraphite/drivers/aggregator.py#L42)):*
> ```Python
>         self._aggregator = aggregator
>         self._epoch = None
>         self._count = 0
> ```

make count and value public ?

---

*[biggraphite/drivers/aggregator.py, line 45 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/47#-KMUeCVI4QuXXQk4Jrrb:-KMUeCVI4QuXXQk4Jrrc:-843272391) ([raw file](https://github.com/criteo/biggraphite/blob/e9edc9d318fcf65fc067660afce002d90fa276d7/biggraphite/drivers/aggregator.py#L45)):*
> ```Python
>         self._value = None
> 
>     def compute_aggregate(self, points):
> ```

'_aggregate' is redundant here. Juste compute() / update() ?

---

*[biggraphite/drivers/aggregator.py, line 53 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/47#-KMUeJmBFuERg8ifsgiY:-KMUeJmBFuERg8ifsgiZ:1881751638) ([raw file](https://github.com/criteo/biggraphite/blob/e9edc9d318fcf65fc067660afce002d90fa276d7/biggraphite/drivers/aggregator.py#L53)):*
> ```Python
> 
>         Returns:
>           Array of (timestamp, count, value).
> ```

Iterable of ( ...

---

*[biggraphite/drivers/aggregator.py, line 61 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/47#-KMUeOECMJEkCu6I8Pdr:-KMUeOECMJEkCu6I8Pds:1297225035) ([raw file](https://github.com/criteo/biggraphite/blob/e9edc9d318fcf65fc067660afce002d90fa276d7/biggraphite/drivers/aggregator.py#L61)):*
> ```Python
>         for (timestamp, value) in points:
>             epoch = timestamp // self.precision
>             res_epoch = res[-1][0]
> ```

[-1][0] is hard to read. Can use use a temporary variable to help the reader understand what happens here ?

---

*[biggraphite/drivers/aggregator.py, line 62 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/47#-KMUeZCUzJm1Tk7uSsXz:-KMUeZCUzJm1Tk7uSsY-:270994291) ([raw file](https://github.com/criteo/biggraphite/blob/e9edc9d318fcf65fc067660afce002d90fa276d7/biggraphite/drivers/aggregator.py#L62)):*
> ```Python
>             epoch = timestamp // self.precision
>             res_epoch = res[-1][0]
>             if res_epoch is None:
> ```

please add a comment here explaining why

---

*[biggraphite/drivers/aggregator.py, line 67 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/47#-KMUeaZP31D-_mqxkbMO:-KMUeaZP31D-_mqxkbMP:807658989) ([raw file](https://github.com/criteo/biggraphite/blob/e9edc9d318fcf65fc067660afce002d90fa276d7/biggraphite/drivers/aggregator.py#L67)):*
> ```Python
>                 res.append((epoch, 1, value))
>             else:
>                 values = [res[-1][2], value]
> ```

same, [-1][2] is hard to understand

---

*[biggraphite/drivers/aggregator.py, line 87 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/47#-KMUeeqHWM_w8jlQbUki:-KMUeeqHWM_w8jlQbUkj:1423733334) ([raw file](https://github.com/criteo/biggraphite/blob/e9edc9d318fcf65fc067660afce002d90fa276d7/biggraphite/drivers/aggregator.py#L87)):*
> ```Python
>             self._epoch = res[-1][0] // self.precision
>             self._count = res[-1][1]
>             self._value = res[-1][2]
> ```

same here for [-1][2]

---

*[biggraphite/drivers/aggregator.py, line 95 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/47#-KMUeie1T94v7AV5oj4-:-KMUeie1T94v7AV5oj40:-1808556950) ([raw file](https://github.com/criteo/biggraphite/blob/e9edc9d318fcf65fc067660afce002d90fa276d7/biggraphite/drivers/aggregator.py#L95)):*
> ```Python
> 
>     __slots__ = (
>         "_stage_aggregators",
> ```

"_stages" ?

---

*[biggraphite/drivers/aggregator.py, line 117 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/47#-KMUennPGjgqel46Johy:-KMUennPGjgqel46Johz:-92693776) ([raw file](https://github.com/criteo/biggraphite/blob/e9edc9d318fcf65fc067660afce002d90fa276d7/biggraphite/drivers/aggregator.py#L117)):*
> ```Python
>           Array of arrays of (timestamp, value).
>         """
>         return [[(p[0], p[2]) for p in s.compute_aggregate(points)]
> ```

I'm not sure what p[2] is here

---

*[biggraphite/drivers/aggregator.py, line 120 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/47#-KMUeqGy8oL7TDbhEt5s:-KMUeqGy8oL7TDbhEt5t:1497378902) ([raw file](https://github.com/criteo/biggraphite/blob/e9edc9d318fcf65fc067660afce002d90fa276d7/biggraphite/drivers/aggregator.py#L120)):*
> ```Python
>                 for s in self._stage_aggregators]
> 
>     def update_aggregates(self, points):
> ```

_aggregates is kind of redundante here (because  it's the name of the object)

---

*[tests/test_aggregator.py, line 97 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/47#-KMUeznfrLZKdx66CstL:-KMUeznfrLZKdx66CstM:-1416880654) ([raw file](https://github.com/criteo/biggraphite/blob/e9edc9d318fcf65fc067660afce002d90fa276d7/tests/test_aggregator.py#L97)):*
> ```Python
>     def setUp(self):
>         aggregator = bg_accessor.Aggregator.average
>         retention_string = "10*%ds:25*%ds" % (self.PRECISION, self.PRECISION ** 2)
> ```

test with 3 stages ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/47)*

**Comment by natbraun** [comment]
Review status: 0 of 2 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[biggraphite/drivers/aggregator.py, line 21 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/47#-KMUdnSOtgNBBZ7yVOCy:-KMUgIVKF_Rkvj8Un2Gn:-1471245307) ([raw file](https://github.com/criteo/biggraphite/blob/e9edc9d318fcf65fc067660afce002d90fa276d7/biggraphite/drivers/aggregator.py#L21)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> StageCounter ? StageAggregate ? 
</details>
StageAggregate seems best

---

*[biggraphite/drivers/aggregator.py, line 42 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/47#-KMUe8IsoFYWhRzgkXIr:-KMUgV3ejvJrlhKQhE2M:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/e9edc9d318fcf65fc067660afce002d90fa276d7/biggraphite/drivers/aggregator.py#L42)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> make count and value public ?
</details>
Done.

---

*[biggraphite/drivers/aggregator.py, line 45 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/47#-KMUeCVI4QuXXQk4Jrrb:-KMUgl0JVT5_fC7365Lh:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/e9edc9d318fcf65fc067660afce002d90fa276d7/biggraphite/drivers/aggregator.py#L45)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> '_aggregate' is redundant here. Juste compute() / update() ?
</details>
Done.

---

*[biggraphite/drivers/aggregator.py, line 53 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/47#-KMUeJmBFuERg8ifsgiY:-KMUgo1p5ZR9qQn3fIic:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/e9edc9d318fcf65fc067660afce002d90fa276d7/biggraphite/drivers/aggregator.py#L53)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> Iterable of ( ...
</details>
Done.

---

*[biggraphite/drivers/aggregator.py, line 61 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/47#-KMUeOECMJEkCu6I8Pdr:-KMUhvu4znUN0OseFacE:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/e9edc9d318fcf65fc067660afce002d90fa276d7/biggraphite/drivers/aggregator.py#L61)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> [-1][0] is hard to read. Can use use a temporary variable to help the reader understand what happens here ?
</details>
Done.

---

*[biggraphite/drivers/aggregator.py, line 62 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/47#-KMUeZCUzJm1Tk7uSsXz:-KMUhkjbj_l6LW3di5gE:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/e9edc9d318fcf65fc067660afce002d90fa276d7/biggraphite/drivers/aggregator.py#L62)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> please add a comment here explaining why
</details>
Done.

---

*[biggraphite/drivers/aggregator.py, line 67 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/47#-KMUeaZP31D-_mqxkbMO:-KMUhwvjNoVt4qICmms5:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/e9edc9d318fcf65fc067660afce002d90fa276d7/biggraphite/drivers/aggregator.py#L67)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> same, [-1][2] is hard to understand
</details>
Done.

---

*[biggraphite/drivers/aggregator.py, line 87 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/47#-KMUeeqHWM_w8jlQbUki:-KMUhxhaeDPclWw9_dJF:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/e9edc9d318fcf65fc067660afce002d90fa276d7/biggraphite/drivers/aggregator.py#L87)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> same here for [-1][2]
</details>
Done.

---

*[biggraphite/drivers/aggregator.py, line 95 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/47#-KMUeie1T94v7AV5oj4-:-KMUinE0JOY1gUpQizgx:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/e9edc9d318fcf65fc067660afce002d90fa276d7/biggraphite/drivers/aggregator.py#L95)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> "_stages" ?
</details>
Done.

---

*[biggraphite/drivers/aggregator.py, line 117 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/47#-KMUennPGjgqel46Johy:-KMUjAYU6dUtnz9uV48v:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/e9edc9d318fcf65fc067660afce002d90fa276d7/biggraphite/drivers/aggregator.py#L117)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> I'm not sure what p[2] is here
</details>
Done.

---

*[biggraphite/drivers/aggregator.py, line 120 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/47#-KMUeqGy8oL7TDbhEt5s:-KMUj9wBjFDHMwHuQtE5:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/e9edc9d318fcf65fc067660afce002d90fa276d7/biggraphite/drivers/aggregator.py#L120)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> _aggregates is kind of redundante here (because  it's the name of the object)
</details>
Done.

---

*[tests/test_aggregator.py, line 97 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/47#-KMUeznfrLZKdx66CstL:-KMUmH1WGtTo7zPT3brz:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/e9edc9d318fcf65fc067660afce002d90fa276d7/tests/test_aggregator.py#L97)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> test with 3 stages ?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/47)*

**Comment by iksaif** [comment]
@thib17  for additional readability review

---

Reviewed 2 of 4 files at r2.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[biggraphite/drivers/aggregate.py, line 63 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/47#-KMUnQWFBLL2ESvA2TvQ:-KMUnQWFBLL2ESvA2TvR:-871803367) ([raw file](https://github.com/criteo/biggraphite/blob/03e13e36f7ffa4d58812d0f667f9b5b8530b9146/biggraphite/drivers/aggregate.py#L63)):*
> ```Python
>             epoch = timestamp // self.precision
>             last_res = res[-1]
>             res_epoch = last_res[0]
> ```

I think the readability of this section could be improved but I'm not sure how exactly ... adding Thinault for additional review

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/47#-:-KMUnICSCEB6wbteamRx:1245148632)*

**Comment by Thib17** [comment]
Reviewed 2 of 4 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[biggraphite/accessor.py, line 197 \[r3\]](https://reviewable.io:443/reviews/criteo/biggraphite/47#-KMVkm2TgVf2CO3KWGra:-KMVkm2UedN5L3_Rgc8V:362001968) ([raw file](https://github.com/criteo/biggraphite/blob/50b770f7f89e071e4153a87ec68de2f333b4076a/biggraphite/accessor.py#L197)):*
> ```Python
>             if math.isnan(v):
>                 continue
>             total += v * c
> ```

I think that it could be wrong : I believe that the average aggregation (and therefore the sum) should not use the counts to avoid a period of time that gathers more frequent measures to have a bigger weight for average aggregation. For example, if an hour has an aggregated value of 100 for 10 points, and the next hour has an aggregated value of 1 for only 1 point, then I believe that the aggregated average of the both hours should be 50,5 (not 91 like with this change). But I can have misunderstood how this method is used.

---

*[biggraphite/drivers/aggregate.py, line 63 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/47#-KMUnQWFBLL2ESvA2TvQ:-KMVjZWufBAYPYtlEseu:-29201568) ([raw file](https://github.com/criteo/biggraphite/blob/03e13e36f7ffa4d58812d0f667f9b5b8530b9146/biggraphite/drivers/aggregate.py#L63)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> I think the readability of this section could be improved but I'm not sure how exactly ... adding Thinault for additional review
</details>
I think that renaming res variable could be a good start.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/47)*

**Comment by natbraun** [comment]
*[biggraphite/accessor.py, line 197 \[r3\]](https://reviewable.io:443/reviews/criteo/biggraphite/47#-KMVkm2TgVf2CO3KWGra:-KMW8E8ABDT6l_yx0rvM:-1602057089) ([raw file](https://github.com/criteo/biggraphite/blob/50b770f7f89e071e4153a87ec68de2f333b4076a/biggraphite/accessor.py#L197)):*
<details><summary><i>Previously, Thib17 wrote…</i></summary>
> I think that it could be wrong : I believe that the average aggregation (and therefore the sum) should not use the counts to avoid a period of time that gathers more frequent measures to have a bigger weight for average aggregation. For example, if an hour has an aggregated value of 100 for 10 points, and the next hour has an aggregated value of 1 for only 1 point, then I believe that the aggregated average of the both hours should be 50,5 (not 91 like with this change). But I can have misunderstood how this method is used.
</details>
This is complex. I think this method itself is misleading, because what's inside values can be either average or sum.
So, this mechanism has to be specific to each aggregator - no "one size fits all" __sum_and_count function

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/47)*

**Comment by iksaif** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[biggraphite/accessor.py, line 112 \[r3\]](https://reviewable.io:443/reviews/criteo/biggraphite/47#-KMYSWIAPsOeSVotqiza:-KMYSWIAPsOeSVotqizb:-549071899) ([raw file](https://github.com/criteo/biggraphite/blob/50b770f7f89e071e4153a87ec68de2f333b4076a/biggraphite/accessor.py#L112)):*
> ```Python
>         return self._merge(old, old_weight, fresh)
> 
>     def _merge_average(self, old, old_weight, fresh):
> ```

This is probably what you want to use, but this should be fixed to take values and sums.

---

*[biggraphite/accessor.py, line 197 \[r3\]](https://reviewable.io:443/reviews/criteo/biggraphite/47#-KMVkm2TgVf2CO3KWGra:-KMYO2vLqqu1QSbHdPjX:-1002379926) ([raw file](https://github.com/criteo/biggraphite/blob/50b770f7f89e071e4153a87ec68de2f333b4076a/biggraphite/accessor.py#L197)):*
<details><summary><i>Previously, natbraun (Nathaniel Braun) wrote…</i></summary>
> This is complex. I think this method itself is misleading, because what's inside values can be either average or sum.
> So, this mechanism has to be specific to each aggregator - no "one size fits all" __sum_and_count function
</details>
I really don't get why you're doing this change. This method is supposed to take sums only, when do we feed it averages ?

---

*[biggraphite/drivers/aggregate.py, line 67 \[r3\]](https://reviewable.io:443/reviews/criteo/biggraphite/47#-KMYQg-0oL85X1g40ktx:-KMYQg-1gtuxfVasrfi8:-807853423) ([raw file](https://github.com/criteo/biggraphite/blob/50b770f7f89e071e4153a87ec68de2f333b4076a/biggraphite/drivers/aggregate.py#L67)):*
> ```Python
>                 # no prior state => take first point
>                 res[0] = (epoch, 1, value)
>             elif res_epoch == epoch:
> ```

Shouldn't we group the points by epoch and call downsample only once ?

---

*[biggraphite/drivers/aggregate.py, line 71 \[r3\]](https://reviewable.io:443/reviews/criteo/biggraphite/47#-KMYSil8PTN-LnHJ7hXH:-KMYSil8PTN-LnHJ7hXI:-1603221476) ([raw file](https://github.com/criteo/biggraphite/blob/50b770f7f89e071e4153a87ec68de2f333b4076a/biggraphite/drivers/aggregate.py#L71)):*
> ```Python
>                 values = [last_res_point[2], value]
>                 counts = [last_res_point[1], 1]
>                 aggregated_value = self._aggregator.downsample(values, counts)
> ```

What you want here is to merge aggregated values. 'downsample' will get you the final value to give to the end user (=average). I think merge is what you want.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/47)*

**Pull request closed without merging**
