### PR TITLE
Remove empty dir: first batch

### PR DESCRIPTION
**Pull request by erebe**
The code look like almost like the repair, So maybe putting it also in the repair ?

---
This change is [Reviewable](https://reviewable.io/reviews/criteo/biggraphite/206)

### CODE REVIEW

**Comment by iksaif** [comment]
Review status: 0 of 1 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[biggraphite/drivers/cassandra.py, line 1276 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/206#-KYSbB8LJehnP0oq_bKD:-KYSbB8LJehnP0oq_bKE:bo1whb8) ([raw file](https://github.com/criteo/biggraphite/blob/4cee4c693fe04308804cede786e6f51761bb9eab/biggraphite/drivers/cassandra.py#L1276)):*
> ```Python
>                 callback_on_progress(token - start_token, stop_token - start_token)
> 
>     def _remove_empty_dir(self, start_key=None, end_key=None, shard=0, nshards=1, callback_on_progress=None):
> ```

clean() and repair() are getting pretty big, maybe we should split them up in cassandra_<someting> ?  Up to you.

---

*[biggraphite/drivers/cassandra.py, line 1276 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/206#-KYSbRdC4Ftft8H62FAS:-KYSbRdC4Ftft8H62FAT:b-bvqry3) ([raw file](https://github.com/criteo/biggraphite/blob/4cee4c693fe04308804cede786e6f51761bb9eab/biggraphite/drivers/cassandra.py#L1276)):*
> ```Python
>                 callback_on_progress(token - start_token, stop_token - start_token)
> 
>     def _remove_empty_dir(self, start_key=None, end_key=None, shard=0, nshards=1, callback_on_progress=None):
> ```

This should probably be part of clean() (and maybe change clean() to have a on_progress, etc..)

---

*[biggraphite/drivers/cassandra.py, line 1286 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/206#-KYSbbWASyB7-e9ilfBm:-KYSbbWASyB7-e9ilfBn:b-lrp4pe) ([raw file](https://github.com/criteo/biggraphite/blob/4cee4c693fe04308804cede786e6f51761bb9eab/biggraphite/drivers/cassandra.py#L1286)):*
> ```Python
>         partitioner = self.__cluster.metadata.partitioner
>         if partitioner != "org.apache.cassandra.dht.Murmur3Partitioner":
>             log.warn("Partitioner '%s' not supported for repairs" % partitioner)
> ```

cleans ?

---

*[biggraphite/drivers/cassandra.py, line 1292 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/206#-KYSbdFGBlxjgsaIAVij:-KYSbdFGBlxjgsaIAVik:b-jvamc4) ([raw file](https://github.com/criteo/biggraphite/blob/4cee4c693fe04308804cede786e6f51761bb9eab/biggraphite/drivers/cassandra.py#L1292)):*
> ```Python
>         stop_token = murmur3.INT64_MAX if not end_key else int(end_key)
>         batch_size = 1000
>         max_concurrent_reqs = 1000
> ```

maybe make those configurable for both repair and clean (see how it's done at the top of the file)

---

*[biggraphite/drivers/cassandra.py, line 1298 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/206#-KYSbo7P1gkgXQ63TwQH:-KYSbo7P1gkgXQ63TwQI:b-s3iag4) ([raw file](https://github.com/criteo/biggraphite/blob/4cee4c693fe04308804cede786e6f51761bb9eab/biggraphite/drivers/cassandra.py#L1298)):*
> ```Python
>             my_tokens = tokens / nshards
>             start_token += my_tokens * shard
>             stop_token = start_token + my_tokens
> ```

I'm sure there is a way to factorize all this start_token/stop_token thing in a function for both repair and clean

---

*[biggraphite/drivers/cassandra.py, line 1311 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/206#-KYSc3gB0lNm1DkTcCI6:-KYSc3gB0lNm1DkTcCI7:bo90jgd) ([raw file](https://github.com/criteo/biggraphite/blob/4cee4c693fe04308804cede786e6f51761bb9eab/biggraphite/drivers/cassandra.py#L1311)):*
> ```Python
>                                                      % self.keyspace_metadata)
>         # force read repair to occur in cassandra
>         has_metric_query.consistency_level = cassandra.ConsistencyLevel.LOCAL_QUORUM
> ```

Maybe create _META_BACKGROUND_CONSISTENCY  for background operations ?

---

*[biggraphite/drivers/cassandra.py, line 1313 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/206#-KYSc8INBZ0to4r7n3T5:-KYSc8INBZ0to4r7n3T6:b-sznoym) ([raw file](https://github.com/criteo/biggraphite/blob/4cee4c693fe04308804cede786e6f51761bb9eab/biggraphite/drivers/cassandra.py#L1313)):*
> ```Python
>         has_metric_query.consistency_level = cassandra.ConsistencyLevel.LOCAL_QUORUM
>         has_metric_query.retry_policy = cassandra.policies.DowngradingConsistencyRetryPolicy
>         has_metric_query.request_timeout = 60
> ```

Same here, please put this timeout in a constant at the top of the file, since it's used multiple times.

---

*[biggraphite/drivers/cassandra.py, line 1326 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/206#-KYShH7h5gEBRdFob0MS:-KYShH7h5gEBRdFob0MT:b-7jih9m) ([raw file](https://github.com/criteo/biggraphite/blob/4cee4c693fe04308804cede786e6f51761bb9eab/biggraphite/drivers/cassandra.py#L1326)):*
> ```Python
>                 name, next_token = row
>                 if name:
>                     yield has_metric_query, (name + DIRECTORY_SEPARATOR + "%",)
> ```

discussing that offline, we need to discuss if we want LIKE or = on both tables or components.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/206)*

**Comment by iksaif** [comment]
Could you mark the previous comments that have been addressed as such ?

---

Review status: 0 of 5 files reviewed at latest revision, 9 unresolved discussions.

---

*[biggraphite/cli/command_clean.py, line 50 at r4](https://reviewable.io:443/reviews/criteo/biggraphite/206#-KZVEuanabSPSYRYuHEz:-KZVEuanabSPSYRYuHF-:b-7h97ni) ([raw file](https://github.com/criteo/biggraphite/blob/2ee638f9f451c0a2b3627fdb1bd608bc7a6109a9/biggraphite/cli/command_clean.py#L50)):*
> ```Python
>         #     help="Show no output unless there are problems."
>         # )
>         parser.add_argument(
> ```

why ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/206#-:-KZVFI0h9nSWUc3z2Gu5:b-snlvta)*

**Comment by erebe** [comment]
Review status: 0 of 6 files reviewed at latest revision, 9 unresolved discussions.

---

*[biggraphite/cli/command_clean.py, line 50 at r4](https://reviewable.io:443/reviews/criteo/biggraphite/206#-KZVEuanabSPSYRYuHEz:-KZWQPfTblDqBiMX8qAz:brjz11y) ([raw file](https://github.com/criteo/biggraphite/blob/2ee638f9f451c0a2b3627fdb1bd608bc7a6109a9/biggraphite/cli/command_clean.py#L50)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary><blockquote>

why ?
</blockquote></details>

was a temporary work around because bgutil daemon try to add both clean and repair arguments, which result in a clash when duplicate

---

*[biggraphite/drivers/cassandra.py, line 1276 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/206#-KYSbB8LJehnP0oq_bKD:-KZWQhl3TqxdPW0VV7Gg:bb7f2mf) ([raw file](https://github.com/criteo/biggraphite/blob/4cee4c693fe04308804cede786e6f51761bb9eab/biggraphite/drivers/cassandra.py#L1276)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary><blockquote>

clean() and repair() are getting pretty big, maybe we should split them up in cassandra_<someting> ?  Up to you.
</blockquote></details>

done

---

*[biggraphite/drivers/cassandra.py, line 1276 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/206#-KYSbRdC4Ftft8H62FAS:-KZWQk3kBZBt-sbL3M5v:bb7f2mf) ([raw file](https://github.com/criteo/biggraphite/blob/4cee4c693fe04308804cede786e6f51761bb9eab/biggraphite/drivers/cassandra.py#L1276)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary><blockquote>

This should probably be part of clean() (and maybe change clean() to have a on_progress, etc..)
</blockquote></details>

done

---

*[biggraphite/drivers/cassandra.py, line 1286 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/206#-KYSbbWASyB7-e9ilfBm:-KZWQlph3F7_7V-HI_W6:bb7f2mf) ([raw file](https://github.com/criteo/biggraphite/blob/4cee4c693fe04308804cede786e6f51761bb9eab/biggraphite/drivers/cassandra.py#L1286)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary><blockquote>

cleans ?
</blockquote></details>

done

---

*[biggraphite/drivers/cassandra.py, line 1298 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/206#-KYSbo7P1gkgXQ63TwQH:-KZWQrNKGwNVgDkZiL-F:bb7f2mf) ([raw file](https://github.com/criteo/biggraphite/blob/4cee4c693fe04308804cede786e6f51761bb9eab/biggraphite/drivers/cassandra.py#L1298)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary><blockquote>

I'm sure there is a way to factorize all this start_token/stop_token thing in a function for both repair and clean
</blockquote></details>

done

---

*[biggraphite/drivers/cassandra.py, line 1311 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/206#-KYSc3gB0lNm1DkTcCI6:-KZWQszo9iemj8kiaioM:bb7f2mf) ([raw file](https://github.com/criteo/biggraphite/blob/4cee4c693fe04308804cede786e6f51761bb9eab/biggraphite/drivers/cassandra.py#L1311)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary><blockquote>

Maybe create _META_BACKGROUND_CONSISTENCY  for background operations ?
</blockquote></details>

done

---

*[biggraphite/drivers/cassandra.py, line 1313 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/206#-KYSc8INBZ0to4r7n3T5:-KZWQut1rkmh-I_I_tBP:b-uum18o) ([raw file](https://github.com/criteo/biggraphite/blob/4cee4c693fe04308804cede786e6f51761bb9eab/biggraphite/drivers/cassandra.py#L1313)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary><blockquote>

Same here, please put this timeout in a constant at the top of the file, since it's used multiple times.
</blockquote></details>

done and factorised within _prepare_background...

---

*[biggraphite/drivers/cassandra.py, line 1326 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/206#-KYShH7h5gEBRdFob0MS:-KZWR0UH2GkdNESNL04-:b-k4z1wq) ([raw file](https://github.com/criteo/biggraphite/blob/4cee4c693fe04308804cede786e6f51761bb9eab/biggraphite/drivers/cassandra.py#L1326)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary><blockquote>

discussing that offline, we need to discuss if we want LIKE or = on both tables or components.
</blockquote></details>

as discussed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/206)*

**Comment by iksaif** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/206#-:-KZgy2wy52ADzAWN9jOW:bnfp4nl)*

**Pull request merged**
