### PR TITLE
README.md: add mailing list

### PR DESCRIPTION
**Pull request by iksaif**
This change is [Reviewable](https://reviewable.io/reviews/criteo/biggraphite/28)

### CODE REVIEW

**Comment by unbrice** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 23 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/28#-KJGKUc3L9d8580TWCwr:-KJGKUc3L9d8580TWCws:-139762550) ([raw file](https://github.com/criteo/biggraphite/blob/55f862a2545920afadb6cf0b703853a8bceec016/README.md#L23)):*
> ```Markdown
> Contact
> =======
> ```

+gitter?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/28)*

**Comment by unbrice** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/28)*

**Comment by unbrice** [comment]
:lgtm:

<details><summary><i>Previously, coveralls wrote…</i></summary>
> 
> [Coverage Status](https://coveralls.io/builds/6430004)
> 
> Coverage remained the same at 93.366% when pulling **55f862a2545920afadb6cf0b703853a8bceec016 on iksaif-patch-1** into **fd9a6708a65139432c8fae3dfc7dfa9d1fadcffa on master**.
> 
</details>


---

Review status: all files reviewed at latest revision, all discussions resolved.

---

*[README.md, line 23 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/28#-KJGKUc3L9d8580TWCwr:-KJKWnW1_21fHCq5FPtE:160374738) ([raw file](https://github.com/criteo/biggraphite/blob/55f862a2545920afadb6cf0b703853a8bceec016/README.md#L23)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> +gitter?
</details>
FAR

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/28#-:-KJKWmc_VoMy4u5msP_P:1417088721)*

**Comment by iksaif** [comment]
can I get another LGTM ? :P

<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> :lgtm:
</details>


---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/28#-:-KJKX_51aM4t6NXDUjIc:2057200144)*

**Pull request merged**
