### PR TITLE
Repair improvements

### PR DESCRIPTION
**Pull request by erebe**
This change is [Reviewable](https://reviewable.io/reviews/criteo/biggraphite/199)

### CODE REVIEW

**Comment by iksaif** [comment]
Review status: 0 of 2 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[biggraphite/cli/command_repair.py, line 72 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/199#-KY-YlONW0INHBkXwC8M:-KY-YlOOJ6JiN7z3VNAJ:b-73f1wr) ([raw file](https://github.com/criteo/biggraphite/blob/fc8c039bdd00768ef327c8b38b68e132197a3f14/biggraphite/cli/command_repair.py#L72)):*
> ```Python
>             logging.warning('Skipping disk cache repair because storage_dir is empty')
> 
>         accessor.repair(shard=opts.shard, nshards=opts.nshards,
> ```

hey, why ? I want to keep these options (to be able to shard if needed, and to resume)

---

*[biggraphite/drivers/cassandra.py, line 1199 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/199#-KY-Z-cb-ghT7TAv4-jZ:-KY-Z-cb-ghT7TAv4-j_:bf9lhvl) ([raw file](https://github.com/criteo/biggraphite/blob/d664d59d14c0ab910bedb47f3aa1ae3c42529176/biggraphite/drivers/cassandra.py#L1199)):*
> ```Python
> 
>     def repair(self, batch_size=1000, max_concurrent_reqs=1000, start_at_percent=0,
>                callback_on_repair=None):
> ```

batch_size and max_concurrent_reqs should probably be options of the accessor.
Remember that the options of repair() should be the same of the memory accessor and for the base accessor()

---

*[biggraphite/drivers/cassandra.py, line 1199 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/199#-KY-_KDDMDRxx3Y4TbBU:-KY-_KDDMDRxx3Y4TbBV:b632zto) ([raw file](https://github.com/criteo/biggraphite/blob/d664d59d14c0ab910bedb47f3aa1ae3c42529176/biggraphite/drivers/cassandra.py#L1199)):*
> ```Python
> 
>     def repair(self, batch_size=1000, max_concurrent_reqs=1000, start_at_percent=0,
>                callback_on_repair=None):
> ```

just rename callback_on_repair -> on_progress, and call it even when you don't repair anything

---

*[biggraphite/drivers/cassandra.py, line 1218 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/199#-KY-ZIeOOp4bKxOFgaXs:-KY-ZIeOOp4bKxOFgaXt:bfgte5d) ([raw file](https://github.com/criteo/biggraphite/blob/d664d59d14c0ab910bedb47f3aa1ae3c42529176/biggraphite/drivers/cassandra.py#L1218)):*
> ```Python
>                                            " WHERE token(name) > ? LIMIT %d;"
>                                            % (self.keyspace_metadata, batch_size))
>         dir_query.consistency_level = cassandra.ConsistencyLevel.QUORUM
> ```

maybe LOCAL_QUORUM, and worst case we start one repair by datacenter

---

*[biggraphite/drivers/cassandra.py, line 1226 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/199#-KY-ZMgyXk-F2EYRkk1v:-KY-ZMgyXk-F2EYRkk1w:bhkmlzs) ([raw file](https://github.com/criteo/biggraphite/blob/d664d59d14c0ab910bedb47f3aa1ae3c42529176/biggraphite/drivers/cassandra.py#L1226)):*
> ```Python
>                                                      % self.keyspace_metadata)
>         # force read repair to occur in cassandra
>         has_directory_query.consistency_level = cassandra.ConsistencyLevel.QUORUM
> ```

LOCAL_QUORUM

---

*[biggraphite/drivers/cassandra.py, line 1242 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/199#-KY-ZY8B_-sedxQupqSo:-KY-ZY8B_-sedxQupqSp:behbuut) ([raw file](https://github.com/criteo/biggraphite/blob/d664d59d14c0ab910bedb47f3aa1ae3c42529176/biggraphite/drivers/cassandra.py#L1242)):*
> ```Python
>                 parent_dir = name.rpartition(".")[0]
>                 if parent_dir:
>                     check_parent_dir_queries.append((has_directory_query, (parent_dir,)))
> ```

If execute_concurrent() can take a generator in parameter, could this be a generator instead of using a temporary list ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/199)*

**Comment by erebe** [comment]
Review status: 0 of 2 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[biggraphite/cli/command_repair.py, line 72 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/199#-KY-YlONW0INHBkXwC8M:-KY8k0o97Y-uMgJlK672:bbi6ndk) ([raw file](https://github.com/criteo/biggraphite/blob/fc8c039bdd00768ef327c8b38b68e132197a3f14/biggraphite/cli/command_repair.py#L72)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary><blockquote>

hey, why ? I want to keep these options (to be able to shard if needed, and to resume)
</blockquote></details>

My bad, forgot to commit everything ...

---

*[biggraphite/drivers/cassandra.py, line 1199 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/199#-KY-Z-cb-ghT7TAv4-jZ:-KY8kC005fyrcfGPVpLH:bbi6ndk) ([raw file](https://github.com/criteo/biggraphite/blob/d664d59d14c0ab910bedb47f3aa1ae3c42529176/biggraphite/drivers/cassandra.py#L1199)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary><blockquote>

batch_size and max_concurrent_reqs should probably be options of the accessor.
Remember that the options of repair() should be the same of the memory accessor and for the base accessor()

</blockquote></details>

My bad, forgot to commit everything ...

---

*[biggraphite/drivers/cassandra.py, line 1199 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/199#-KY-_KDDMDRxx3Y4TbBU:-KY8kGhV6X6oflF2MNwn:b32wtd) ([raw file](https://github.com/criteo/biggraphite/blob/d664d59d14c0ab910bedb47f3aa1ae3c42529176/biggraphite/drivers/cassandra.py#L1199)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary><blockquote>

just rename callback_on_repair -> on_progress, and call it even when you don't repair anything
</blockquote></details>

ok

---

*[biggraphite/drivers/cassandra.py, line 1218 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/199#-KY-ZIeOOp4bKxOFgaXs:-KY8kCpk5yNu4EOKYJzz:b32wtd) ([raw file](https://github.com/criteo/biggraphite/blob/d664d59d14c0ab910bedb47f3aa1ae3c42529176/biggraphite/drivers/cassandra.py#L1218)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary><blockquote>

maybe LOCAL_QUORUM, and worst case we start one repair by datacenter
</blockquote></details>

ok

---

*[biggraphite/drivers/cassandra.py, line 1226 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/199#-KY-ZMgyXk-F2EYRkk1v:-KY8kDZKDIDtDgZ1t8vT:b32wtd) ([raw file](https://github.com/criteo/biggraphite/blob/d664d59d14c0ab910bedb47f3aa1ae3c42529176/biggraphite/drivers/cassandra.py#L1226)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary><blockquote>

LOCAL_QUORUM
</blockquote></details>

ok

---

*[biggraphite/drivers/cassandra.py, line 1242 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/199#-KY-ZY8B_-sedxQupqSo:-KY8kPeaBgxOfooDzxj7:bp4juzl) ([raw file](https://github.com/criteo/biggraphite/blob/d664d59d14c0ab910bedb47f3aa1ae3c42529176/biggraphite/drivers/cassandra.py#L1242)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary><blockquote>

If execute_concurrent() can take a generator in parameter, could this be a generator instead of using a temporary list ?
</blockquote></details>

Yes we can... oops wrong year, but as the number of items is already capped due to the select it does not provide any extra safety/value.
I was finishing to split the functon friday to make it great again, so I can add some yield.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/199)*

**Comment by iksaif** [comment]
Review status: 0 of 2 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[biggraphite/drivers/cassandra.py, line 1242 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/199#-KY-ZY8B_-sedxQupqSo:-KYA__Lwk6QVs5WX9m9j:b-3jno4w) ([raw file](https://github.com/criteo/biggraphite/blob/d664d59d14c0ab910bedb47f3aa1ae3c42529176/biggraphite/drivers/cassandra.py#L1242)):*
<details><summary><i>Previously, erebe (Erèbe - Romain Gerard) wrote…</i></summary><blockquote>

Yes we can... oops wrong year, but as the number of items is already capped due to the select it does not provide any extra safety/value.
I was finishing to split the functon friday to make it great again, so I can add some yield.
</blockquote></details>

We can discuss on monday morning what this should roughly look like :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/199)*

**Comment by iksaif** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[biggraphite/drivers/cassandra.py, line 1199 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/199#-KY-Z-cb-ghT7TAv4-jZ:-KYEJnnvc-oJ_XZkq8Ra:b-aqzoa9) ([raw file](https://github.com/criteo/biggraphite/blob/d664d59d14c0ab910bedb47f3aa1ae3c42529176/biggraphite/drivers/cassandra.py#L1199)):*
<details><summary><i>Previously, erebe (Erèbe - Romain Gerard) wrote…</i></summary><blockquote>

My bad, forgot to commit everything ...
</blockquote></details>

can you add this "on_progress" to the other accessors (memory, base accessor ?)

---

*[biggraphite/drivers/cassandra.py, line 1269 at r2](https://reviewable.io:443/reviews/criteo/biggraphite/199#-KYELBIuUZW5r1ItbUl7:-KYELBIuUZW5r1ItbUl8:b-uehjph) ([raw file](https://github.com/criteo/biggraphite/blob/5670e824f44fe9bef05356da2cfd3f62043ee07b/biggraphite/drivers/cassandra.py#L1269)):*
> ```Python
>             progress = 100 - ((stop_token - token) * 100 / (stop_token - start_token))
> 
>             parent_dirs = c_concurrent.execute_concurrent(self.__session,
> ```

self.execute_concurrent (to have the logs and traces if we need to).

---

*[biggraphite/drivers/cassandra.py, line 1275 at r2](https://reviewable.io:443/reviews/criteo/biggraphite/199#-KYELJqCLrq2REkxSqOh:-KYELJqCLrq2REkxSqOi:b-2guby3) ([raw file](https://github.com/criteo/biggraphite/blob/5670e824f44fe9bef05356da2cfd3f62043ee07b/biggraphite/drivers/cassandra.py#L1275)):*
> ```Python
>                                                           results_generator=True)
> 
>             c_concurrent.execute_concurrent(self.__session,
> ```

same here

---

*[biggraphite/drivers/cassandra.py, line 1280 at r2](https://reviewable.io:443/reviews/criteo/biggraphite/199#-KYELRdMtt1XafxYDhgA:-KYELRdMtt1XafxYDhgB:bhktrjv) ([raw file](https://github.com/criteo/biggraphite/blob/5670e824f44fe9bef05356da2cfd3f62043ee07b/biggraphite/drivers/cassandra.py#L1280)):*
> ```Python
>                                             raise_on_first_error=False)
>             if callback_on_progress:
>                 callback_on_progress(progress, result[0][1], result[-1][1])
> ```


 callback_on_progress(progress, token, stop_token)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/199)*

**Comment by erebe** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[biggraphite/drivers/cassandra.py, line 1199 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/199#-KY-Z-cb-ghT7TAv4-jZ:-KYEMoSHMQ5F5Ebrxuhz:b32wn8) ([raw file](https://github.com/criteo/biggraphite/blob/d664d59d14c0ab910bedb47f3aa1ae3c42529176/biggraphite/drivers/cassandra.py#L1199)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary><blockquote>

can you add this "on_progress" to the other accessors (memory, base accessor ?)
</blockquote></details>

k

---

*[biggraphite/drivers/cassandra.py, line 1269 at r2](https://reviewable.io:443/reviews/criteo/biggraphite/199#-KYELBIuUZW5r1ItbUl7:-KYEMqhCdubL33y8xSPw:b3ksm) ([raw file](https://github.com/criteo/biggraphite/blob/5670e824f44fe9bef05356da2cfd3f62043ee07b/biggraphite/drivers/cassandra.py#L1269)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary><blockquote>

self.execute_concurrent (to have the logs and traces if we need to).
</blockquote></details>

k

---

*[biggraphite/drivers/cassandra.py, line 1275 at r2](https://reviewable.io:443/reviews/criteo/biggraphite/199#-KYELJqCLrq2REkxSqOh:-KYEMrVwKgCb5kPgpvQI:b3ksm) ([raw file](https://github.com/criteo/biggraphite/blob/5670e824f44fe9bef05356da2cfd3f62043ee07b/biggraphite/drivers/cassandra.py#L1275)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary><blockquote>

same here
</blockquote></details>

k

---

*[biggraphite/drivers/cassandra.py, line 1280 at r2](https://reviewable.io:443/reviews/criteo/biggraphite/199#-KYELRdMtt1XafxYDhgA:-KYEMsWpnzVckaAMcnIn:b3ksm) ([raw file](https://github.com/criteo/biggraphite/blob/5670e824f44fe9bef05356da2cfd3f62043ee07b/biggraphite/drivers/cassandra.py#L1280)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary><blockquote>

 callback_on_progress(progress, token, stop_token)
</blockquote></details>

k

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/199)*

**Comment by iksaif** [comment]
Review status: 0 of 4 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[biggraphite/accessor.py, line 769 at r3](https://reviewable.io:443/reviews/criteo/biggraphite/199#-KYEW7GSEnlpwwTaq8t8:-KYEW7GT_8W-dM4JbjtT:bv7hjpi) ([raw file](https://github.com/criteo/biggraphite/blob/2aa5268a36c0acd60b1dd9e54f07ecd0100eda86/biggraphite/accessor.py#L769)):*
> ```Python
>           shard: int, shard to repair.
>           nshards: int, number of shards.
>           callback_on_progress: Take 3 parameters, progress (None for now),
> ```

callback_on_progress was supposed to take "done, total" (integers)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/199)*

**Comment by iksaif** [comment]
:lgtm_strong: 

---

Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/199#-:-KYEfftD7Ai3O-iWoPcW:b-uwkowd)*

**Pull request merged**
