### PR TITLE
graphite: support asynchronous reads

### PR DESCRIPTION
**Pull request by iksaif**
This change is [Reviewable](https://reviewable.io/reviews/criteo/biggraphite/32)

### CODE REVIEW

**Comment by iksaif** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[biggraphite/accessor.py, line 551 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/32#-KJaQTLUTVihjNNNKQuO:-KJaQTLUTVihjNNNKQuP:-274708331) ([raw file](https://github.com/criteo/biggraphite/blob/1e12b60a28902744c467356e9207028ff775d6ce/biggraphite/accessor.py#L551)):*
> ```Python
>     # TODO: Remove aggregator_func and perform aggregation server-side.
>     def fetch_points(self, metric_name, time_start, time_end, step,
>                      aggregator_func=None, _fake_query_results=None):
> ```

Create _PointFetcher here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/32)*

**Comment by unbrice** [comment]
Reviewed 4 of 8 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 19 unresolved discussions.

---

*[README.md, line 19 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/32#-KJaWmU9e2GNvWb4e3Nz:-KJaWmU9e2GNvWb4e3O-:1175715946) ([raw file](https://github.com/criteo/biggraphite/blob/1e12b60a28902744c467356e9207028ff775d6ce/README.md#L19)):*
> ```Markdown
> -----------
> 
>     $ virtualenv bg
> ```

nit: please make this a code block so that PRETTY COLORS

---

*[README.md, line 44 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/32#-KJaSmQgzNm9WQmZ8yCO:-KJaSmQgzNm9WQmZ8yCP:188150444) ([raw file](https://github.com/criteo/biggraphite/blob/1e12b60a28902744c467356e9207028ff775d6ce/README.md#L44)):*
> ```Markdown
> 
> 
> or simply
> ```

experts can use unittest.discover but require setting up a working environment:

---

*[README.md, line 52 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/32#-KJaTZwGfexP8Z2olR5w:-KJaTZwGfexP8Z2olR5x:1814797317) ([raw file](https://github.com/criteo/biggraphite/blob/1e12b60a28902744c467356e9207028ff775d6ce/README.md#L52)):*
> ```Markdown
> 
> Here is how to run a test instance of Graphite Web reading metrics
> from Cassandra:
> ```

It will require having a valid virtual environement, like one tox creates in .tox/pypy-coverage or the one described above

---

*[README.md, line 54 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/32#-KJaU2TsR2d65Y-D9ryg:-KJaU2TsR2d65Y-D9ryh:162214812) ([raw file](https://github.com/criteo/biggraphite/blob/1e12b60a28902744c467356e9207028ff775d6ce/README.md#L54)):*
> ```Markdown
> from Cassandra:
> 
>     $ export PYTHONPATH=$(pwd)
> ```

PYTHONPATH is depracted and doesn't work eg if system uses python 3 and venv python2
```bash
export VIRTUAL_ENV=$PWD/.tox/pypy-coverage or bg described above
source $VENV/bin/activate
```

---

*[README.md, line 59 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/32#-KJaTAe2zd1GvsGJCTGX:-KJaTAe2zd1GvsGJCTGY:873480475) ([raw file](https://github.com/criteo/biggraphite/blob/1e12b60a28902744c467356e9207028ff775d6ce/README.md#L59)):*
> ```Markdown
>     $ django-admin migrate --run-syncdb
> 
> Edit bg/lib/python2.7/site-packages/graphite/local_settings.py and put
> ```

VENV/...

---

*[README.md, line 64 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/32#-KJaT337xVisDp-fxnSq:-KJaT337xVisDp-fxnSr:435230810) ([raw file](https://github.com/criteo/biggraphite/blob/1e12b60a28902744c467356e9207028ff775d6ce/README.md#L64)):*
> ```Markdown
>     LOG_DIR = '/tmp'
>     STORAGE_DIR = '/tmp'
>     STORAGE_FINDERS = ['graphite.finders.standard.StandardFinder', 'biggraphite.plugins.graphite.Finder']
> ```

debug is probably easier without the standard finder

---

*[README.md, line 67 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/32#-KJaT8-GZtaAOE7Hrf5Z:-KJaT8-GZtaAOE7Hrf5_:-1353857457) ([raw file](https://github.com/criteo/biggraphite/blob/1e12b60a28902744c467356e9207028ff775d6ce/README.md#L67)):*
> ```Markdown
>     BG_KEYSPACE = 'biggraphite'
>     BG_CONTACT_POINTS = '<MY_CASSANDRA_NODES>'
>     WEBAPP_DIR = "bg/webapp/"
> ```

nit: quote, VENV/webapp

---

*[README.md, line 72 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/32#-KJaTTzLN9P3mGwAolFF:-KJaTTzLN9P3mGwAolFG:-2017452578) ([raw file](https://github.com/criteo/biggraphite/blob/1e12b60a28902744c467356e9207028ff775d6ce/README.md#L72)):*
> ```Markdown
> Start Graphite Web
> 
>     $ run-graphite-devel-server.py bg
> ```

YOUR_VENV

---

*[biggraphite/accessor.py, line 599 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/32#-KJaUPFZs29knHiNTXw7:-KJaUPFZs29knHiNTXw8:44036306) ([raw file](https://github.com/criteo/biggraphite/blob/1e12b60a28902744c467356e9207028ff775d6ce/biggraphite/accessor.py#L599)):*
> ```Python
>         current_timestamp_ms = None
> 
>         def run_aggregation():
> ```

note: when you do the split this can go in a separate method and current_points... can be turned in attribute

---

*[biggraphite/accessor.py, line 629 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/32#-KJaDDBw00nGQTlnoQPV:-KJaDDBw00nGQTlnoQPW:-1959415002) ([raw file](https://github.com/criteo/biggraphite/blob/1e12b60a28902744c467356e9207028ff775d6ce/biggraphite/accessor.py#L629)):*
> ```Python
> 
>                 if current_timestamp_ms != timestamp_ms:
>                     ts, point = run_aggregation()
> ```

nit: I would make run_aggregation() return None if there are no point so that you avoid packing/unpacking

---

*[biggraphite/test_utils.py, line 71 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/32#-KJaS8VgepfY4aQmBnWt:-KJaS8VgepfY4aQmBnWu:-1995642378) ([raw file](https://github.com/criteo/biggraphite/blob/1e12b60a28902744c467356e9207028ff775d6ce/biggraphite/test_utils.py#L71)):*
> ```Python
>     prepare_graphite_imports()
> 
>     # Point the the correct settings
> ```

s/correct settings/settings graphite provides (or whichever property that they have that makes them correct)/

---

*[biggraphite/test_utils.py, line 72 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/32#-KJaRmSexSk7KV-fIWpX:-KJaRmSexSk7KV-fIWpY:-1238027213) ([raw file](https://github.com/criteo/biggraphite/blob/1e12b60a28902744c467356e9207028ff775d6ce/biggraphite/test_utils.py#L72)):*
> ```Python
> 
>     # Point the the correct settings
>     os.environ['DJANGO_SETTINGS_MODULE'] = 'graphite.settings'
> ```

I suggest calling settings.configure rather than setting an env variable (less magic IMHO)
https://docs.djangoproject.com/en/1.9/topics/settings/#either-configure-or-django-settings-module-is-required

---

*[biggraphite/test_utils.py, line 75 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/32#-KJaSOidVkuc0I3IrlMN:-KJaSOidVkuc0I3IrlMO:1374484736) ([raw file](https://github.com/criteo/biggraphite/blob/1e12b60a28902744c467356e9207028ff775d6ce/biggraphite/test_utils.py#L75)):*
> ```Python
> 
>     # Redirect logs somewhere writable
>     from django.conf import settings
> ```

if you get rid of os.environ you should be able to do these imports normally

---

*[biggraphite/plugins/graphite.py, line 23 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/32#-KJaRSvAb3NkjtImKd-A:-KJaRSvAb3NkjtImKd-B:-489082774) ([raw file](https://github.com/criteo/biggraphite/blob/1e12b60a28902744c467356e9207028ff775d6ce/biggraphite/plugins/graphite.py#L23)):*
> ```Python
> from graphite import node
> from graphite.readers import FetchInProgress
> ```

please only import module (from graphite import readers)

---

*[tests/test_accessor.py, line 96 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/32#-KJaV5BDnNMG14ddgYnh:-KJaV5BDnNMG14ddgYni:-556147041) ([raw file](https://github.com/criteo/biggraphite/blob/1e12b60a28902744c467356e9207028ff775d6ce/tests/test_accessor.py#L96)):*
> ```Python
>     def fetch(self, metric, start, end, step=1):
>         """Helper to fetch points as a list."""
>         ret = self.accessor.fetch_points(metric, start, end, step)
> ```

*args, **kwargs

---

*[tests/test_accessor.py, line 97 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/32#-KJaVYOZ3qavw3zp_vh8:-KJaVYOaCFsnQh5v33-a:-1765297033) ([raw file](https://github.com/criteo/biggraphite/blob/1e12b60a28902744c467356e9207028ff775d6ce/tests/test_accessor.py#L97)):*
> ```Python
>         """Helper to fetch points as a list."""
>         ret = self.accessor.fetch_points(metric, start, end, step)
>         self.assertTrue(isinstance(ret, types.GeneratorType))
> ```

hasattr(ret, "__next_") so that it works even with generator class, or isinstance( collections.Iterator)

---

*[tests/test_graphite.py, line 28 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/32#-KJaVwa8ovVsK5mET1US:-KJaVwa8ovVsK5mET1UT:481954959) ([raw file](https://github.com/criteo/biggraphite/blob/1e12b60a28902744c467356e9207028ff775d6ce/tests/test_graphite.py#L28)):*
> ```Python
> 
> from biggraphite.plugins import graphite as bg_graphite  # noqa
> from graphite.readers import FetchInProgress  # noqa
> ```

please only import modules

---

*[tests/test_graphite.py, line 77 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/32#-KJaUcYRLXqid7_pPA0_:-KJaUcYRLXqid7_pPA0a:1755641290) ([raw file](https://github.com/criteo/biggraphite/blob/1e12b60a28902744c467356e9207028ff775d6ce/tests/test_graphite.py#L77)):*
> ```Python
>         self.reader = bg_graphite.Reader(self.accessor, self.metadata_cache, _METRIC_NAME)
> 
>     def fetch(self, start_time=0, end_time=0, now=0):
> ```

fetch(self, *args,**kwargs):
  result = self.reader.fetch(*args, **kwargs)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/32)*

**Comment by unbrice** [comment]
Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 20 unresolved discussions.

---

*[README.md, line 19 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/32#-KJaWmU9e2GNvWb4e3Nz:-KJkwv8RptLlz4MJhqXf:159401445) ([raw file](https://github.com/criteo/biggraphite/blob/1e12b60a28902744c467356e9207028ff775d6ce/README.md#L19)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> nit: please make this a code block so that PRETTY COLORS
</details>
``` bash is even prettier ;-) same for python later on

---

*[tests/test_accessor.py, line 97 \[r3\]](https://reviewable.io:443/reviews/criteo/biggraphite/32#-KJkxVKz9axEn-9WrAuc:-KJkxVKz9axEn-9WrAud:887774011) ([raw file](https://github.com/criteo/biggraphite/blob/5615c6af733f99ee15f816ecfb06b74a51c35b2e/tests/test_accessor.py#L97)):*
> ```Python
>         """Helper to fetch points as a list."""
>         ret = self.accessor.fetch_points(*args, **kwargs)
>         self.assertTrue(hasattr(ret, '__next__'))
> ```

nit: single quote :-p

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/32)*
<!-- Sent from Reviewable.io -->

**Comment by iksaif** [comment]
Review status: 5 of 8 files reviewed at latest revision, 20 unresolved discussions.

---

*[README.md, line 44 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/32#-KJaSmQgzNm9WQmZ8yCO:-KJdger5AzKVkRJZ-lhZ:1514063469) ([raw file](https://github.com/criteo/biggraphite/blob/1e12b60a28902744c467356e9207028ff775d6ce/README.md#L44)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> experts can use unittest.discover but require setting up a working environment:
</details>
changed the text

---

*[README.md, line 52 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/32#-KJaTZwGfexP8Z2olR5w:-KJdh2wjLaWpkKgQYlTH:-933951169) ([raw file](https://github.com/criteo/biggraphite/blob/1e12b60a28902744c467356e9207028ff775d6ce/README.md#L52)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> It will require having a valid virtual environement, like one tox creates in .tox/pypy-coverage or the one described above
</details>
added text to say that we assume we have a working dev env

---

*[README.md, line 54 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/32#-KJaU2TsR2d65Y-D9ryg:-KJdi5CnUIyYLI00pf2P:1483377069) ([raw file](https://github.com/criteo/biggraphite/blob/1e12b60a28902744c467356e9207028ff775d6ce/README.md#L54)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> PYTHONPATH is depracted and doesn't work eg if system uses python 3 and venv python2
> ```bash
> export VIRTUAL_ENV=$PWD/.tox/pypy-coverage or bg described above
> source $VENV/bin/activate
> ```
</details>
This was to be able to import biggraphite without installing it in the venv.
I'll replace this with `pip install -e .`

---

*[README.md, line 59 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/32#-KJaTAe2zd1GvsGJCTGX:-KJdlIG63cNva--_0CUO:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/1e12b60a28902744c467356e9207028ff775d6ce/README.md#L59)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> VENV/...
</details>
Done.

---

*[README.md, line 64 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/32#-KJaT337xVisDp-fxnSq:-KJdlH78jNHZEUdZ8Hro:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/1e12b60a28902744c467356e9207028ff775d6ce/README.md#L64)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> debug is probably easier without the standard finder
</details>
Done.

---

*[README.md, line 67 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/32#-KJaT8-GZtaAOE7Hrf5Z:-KJdlGnLIOYr4mp3UEpO:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/1e12b60a28902744c467356e9207028ff775d6ce/README.md#L67)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> nit: quote, VENV/webapp
</details>
Done.

---

*[README.md, line 72 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/32#-KJaTTzLN9P3mGwAolFF:-KJdlIo3ATtXQ6Hk7G-p:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/1e12b60a28902744c467356e9207028ff775d6ce/README.md#L72)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> YOUR_VENV
</details>
Done.

---

*[biggraphite/test_utils.py, line 71 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/32#-KJaS8VgepfY4aQmBnWt:-KJoTDvfA8Vyag4Qb7GQ:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/1e12b60a28902744c467356e9207028ff775d6ce/biggraphite/test_utils.py#L71)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> s/correct settings/settings graphite provides (or whichever property that they have that makes them correct)/
</details>
Done.

---

*[biggraphite/test_utils.py, line 72 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/32#-KJaRmSexSk7KV-fIWpX:-KJdjRTiRQmrxekt7spO:781137573) ([raw file](https://github.com/criteo/biggraphite/blob/1e12b60a28902744c467356e9207028ff775d6ce/biggraphite/test_utils.py#L72)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> I suggest calling settings.configure rather than setting an env variable (less magic IMHO)
> https://docs.djangoproject.com/en/1.9/topics/settings/#either-configure-or-django-settings-module-is-required
</details>
Setting DJANGO_SETTINGS_MODULE is really the idiomatic to do that thing in django.

configure() is something different, it replaces the default settings (usually django.global_settings) with something else but that works only if this something else has *all* the settings set to something.

I tried with the graphite settings, and basic things like LOGGING_CONFIG are missing .. I don't think it's worth it to dig further.

---

*[biggraphite/plugins/graphite.py, line 23 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/32#-KJaRSvAb3NkjtImKd-A:-KJoTG6e0eAKt-TYosCF:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/1e12b60a28902744c467356e9207028ff775d6ce/biggraphite/plugins/graphite.py#L23)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> please only import module (from graphite import readers)
</details>
Done.

---

*[tests/test_accessor.py, line 96 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/32#-KJaV5BDnNMG14ddgYnh:-KJdnI4ZawSw28ZGh3gr:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/1e12b60a28902744c467356e9207028ff775d6ce/tests/test_accessor.py#L96)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> *args, **kwargs
</details>
Done.

---

*[tests/test_accessor.py, line 97 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/32#-KJaVYOZ3qavw3zp_vh8:-KJdnHqGmK1EcGFcuZmf:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/1e12b60a28902744c467356e9207028ff775d6ce/tests/test_accessor.py#L97)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> hasattr(ret, "__next_") so that it works even with generator class, or isinstance( collections.Iterator)
</details>
Done.

---

*[tests/test_graphite.py, line 28 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/32#-KJaVwa8ovVsK5mET1US:-KJdnQexBuas_ltsDtKl:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/1e12b60a28902744c467356e9207028ff775d6ce/tests/test_graphite.py#L28)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> please only import modules
</details>
Done.

---

*[tests/test_graphite.py, line 77 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/32#-KJaUcYRLXqid7_pPA0_:-KJdn_1hIOU5mgIZjkH3:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/1e12b60a28902744c467356e9207028ff775d6ce/tests/test_graphite.py#L77)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> fetch(self, *args,**kwargs):
>   result = self.reader.fetch(*args, **kwargs)
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/32)*

**Comment by iksaif** [comment]
Review status: 5 of 8 files reviewed at latest revision, 20 unresolved discussions.

---

*[biggraphite/accessor.py, line 599 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/32#-KJaUPFZs29knHiNTXw7:-KJtnDUt731pHFpkn-Gr:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/1e12b60a28902744c467356e9207028ff775d6ce/biggraphite/accessor.py#L599)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> note: when you do the split this can go in a separate method and current_points... can be turned in attribute
</details>
Done.

---

*[tests/test_accessor.py, line 97 \[r3\]](https://reviewable.io:443/reviews/criteo/biggraphite/32#-KJkxVKz9axEn-9WrAuc:-KJtnFgsE_y1SKwloMvo:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/5615c6af733f99ee15f816ecfb06b74a51c35b2e/tests/test_accessor.py#L97)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> nit: single quote :-p
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/32)*

**Comment by iksaif** [comment]
Please take another look.

<details><summary><i>Previously, coveralls wrote…</i></summary>
> 
> [Coverage Status](https://coveralls.io/builds/6453208)
> 
> Coverage increased (+0.4%) to 93.228% when pulling **1e12b60a28902744c467356e9207028ff775d6ce on iksaif:master** into **a71d8fcd34a282c1d76decf7c0b2092b3b2b38b2 on criteo:master**.
> 
</details>


---

Review status: 5 of 8 files reviewed at latest revision, 20 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/32#-:-KJtnHi-KudaAdHafwmU:117034154)*

**Comment by iksaif** [comment]
rebased

<details><summary><i>Previously, coveralls wrote…</i></summary>
> 
> [Coverage Status](https://coveralls.io/builds/6543801)
> 
> Coverage increased (+0.5%) to 93.344% when pulling **fa472b8a5385b86c5358956340e0bd7c08e1ef07 on iksaif:master** into **a71d8fcd34a282c1d76decf7c0b2092b3b2b38b2 on criteo:master**.
> 
</details>


---

Review status: 1 of 8 files reviewed at latest revision, 20 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/32#-:-KJusp_XH49wOvLeE4hQ:-1064904517)*

**Comment by unbrice** [comment]
:lgtm:

<details><summary><i>Previously, coveralls wrote…</i></summary>
> 
> [Coverage Status](https://coveralls.io/builds/6547794)
> 
> Coverage increased (+0.2%) to 93.495% when pulling **8758c32c75fa95cffa41b7709fb91a04dc4e5481 on iksaif:master** into **77795dff9e5d5082930ad61754c5549eaae5c304 on criteo:master**.
> 
</details>


---

Reviewed 1 of 3 files at r4, 6 of 6 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/32#-:-KJvaX4vZumVZInoj2S-:1417088721)*

**Pull request merged**
