### PR TITLE
plugins/carbon: implement setMetadata/getMetadata(#88)

### PR DESCRIPTION
**Pull request by Thib17**
This change is [Reviewable](https://reviewable.io/reviews/criteo/biggraphite/177)

### CODE REVIEW

**Comment by iksaif** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[biggraphite/plugins/carbon.py, line 132 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/177#-KWcSJ_etaImamJgOee_:-KWcSJ_etaImamJgOeea:b-k18qwe) ([raw file](https://github.com/criteo/biggraphite/blob/b539e674e8327b4d14cc4ac566f8ef778814bd1e/biggraphite/plugins/carbon.py#L132)):*
> ```Python
>             if not metadata:
>                 raise ValueError("%s: No such metric" % metric_name)
> ```

you probably want to call something like accessor.update_metric(metric_name, metadata) here :)
(note: the function doesn't exist, yet)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/177)*

**Comment by Thib17** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[biggraphite/plugins/carbon.py, line 132 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/177#-KWcSJ_etaImamJgOee_:-KWi7-ErfGDo90fvuv_8:b-896fix) ([raw file](https://github.com/criteo/biggraphite/blob/b539e674e8327b4d14cc4ac566f8ef778814bd1e/biggraphite/plugins/carbon.py#L132)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> you probably want to call something like accessor.update_metric(metric_name, metadata) here :)
> (note: the function doesn't exist, yet)
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/177)*

**Comment by iksaif** [comment]
:lgtm_strong:  (once tested)

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/177#-:-KWm4r81-eFjOcajJKof:b-jbs9cc)*

**Comment by Thib17** [comment]
Tested in local cassandra !

**Pull request merged**
