### PR TITLE
downsampling: add a stupid downsampler and fix average aggregation

### PR DESCRIPTION
**Pull request by iksaif**
- Add a test downsampler that generates per-minute averages
- Make sure that we could read and aggregate averages

---
This change is [Reviewable](https://reviewable.io/reviews/criteo/biggraphite/46)

### CODE REVIEW

**Comment by natbraun** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[biggraphite/accessor.py, line 195 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/46#-KMTSnJTl2UD_kGs2BlR:-KMTSnJTl2UD_kGs2BlS:-316811969) ([raw file](https://github.com/criteo/biggraphite/blob/4a84041738168c646817323cf37fbfff5d20c48f/biggraphite/accessor.py#L195)):*
> ```Python
>         count = 0
>         for v, c in itertools.izip(values, counts): # FIXME(now): counts izip
>             if math.isnan(v):
> ```

Please remove comments

---

*[biggraphite/accessor.py, line 639 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/46#-KMTShqgszJHhW87mc8p:-KMTShqhUMCE_96u9GK9:111376128) ([raw file](https://github.com/criteo/biggraphite/blob/4a84041738168c646817323cf37fbfff5d20c48f/biggraphite/accessor.py#L639)):*
> ```Python
> 
>         self.current_values = array.array("d")
>         self.current_counts = array.array("d")
> ```

this should be an array of ints

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/46)*

**Comment by natbraun** [comment]
Reviewed 1 of 5 files at r1.
Review status: 1 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/46)*

**Comment by natbraun** [comment]
Review status: 1 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[biggraphite/accessor.py, line 81 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/46#-KMU5WkMmGIk4m8YWyzS:-KMU5WkMmGIk4m8YWyzT:1008875656) ([raw file](https://github.com/criteo/biggraphite/blob/4a84041738168c646817323cf37fbfff5d20c48f/biggraphite/accessor.py#L81)):*
> ```Python
>     minimum = "min"
>     maximum = "max"
>     total = "sum"
> ```

I think 'total' is error prone, and should be renamed simply to 'sum' (see below)

---

*[biggraphite/accessor.py, line 124 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/46#-KMU5dozSgCkC-F2aQAD:-KMU5dozSgCkC-F2aQAE:1008875656) ([raw file](https://github.com/criteo/biggraphite/blob/4a84041738168c646817323cf37fbfff5d20c48f/biggraphite/accessor.py#L124)):*
> ```Python
>         return min(old, fresh)
> 
>     def _merge_total(self, old, old_weight, fresh):
> ```

I think 'total' is error prone, and should be renamed simply to 'sum' (see below)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/46)*

**Comment by natbraun** [comment]
Review status: 1 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[biggraphite/accessor.py, line 124 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/46#-KMU5j-2NrJv162Rm7Hs:-KMU5j-2NrJv162Rm7Ht:977571484) ([raw file](https://github.com/criteo/biggraphite/blob/4a84041738168c646817323cf37fbfff5d20c48f/biggraphite/accessor.py#L124)):*
> ```Python
>         return min(old, fresh)
> 
>     def _merge_total(self, old, old_weight, fresh):
> ```

I think 'total' is error prone, and should be renamed simply to 'sum' (see above)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/46)*

**Comment by iksaif** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[biggraphite/accessor.py, line 81 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/46#-KMU5WkMmGIk4m8YWyzS:-KMUQcxtyq37GX4_oq9U:-389021598) ([raw file](https://github.com/criteo/biggraphite/blob/4a84041738168c646817323cf37fbfff5d20c48f/biggraphite/accessor.py#L81)):*
<details><summary><i>Previously, natbraun (Nathaniel Braun) wrote…</i></summary>
> I think 'total' is error prone, and should be renamed simply to 'sum' (see below)
</details>
Probably, but it's not directly related to my change so let's do that in another review.

---

*[biggraphite/accessor.py, line 124 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/46#-KMU5j-2NrJv162Rm7Hs:-KMUQolkCxYJw9RjuDYl:678021867) ([raw file](https://github.com/criteo/biggraphite/blob/4a84041738168c646817323cf37fbfff5d20c48f/biggraphite/accessor.py#L124)):*
<details><summary><i>Previously, natbraun (Nathaniel Braun) wrote…</i></summary>
> I think 'total' is error prone, and should be renamed simply to 'sum' (see above)
</details>
same

---

*[biggraphite/accessor.py, line 195 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/46#-KMTSnJTl2UD_kGs2BlR:-KMUTMmnMaWnXyVlHMEd:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/4a84041738168c646817323cf37fbfff5d20c48f/biggraphite/accessor.py#L195)):*
<details><summary><i>Previously, natbraun (Nathaniel Braun) wrote…</i></summary>
> Please remove comments
</details>
Done.

---

*[biggraphite/accessor.py, line 639 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/46#-KMTShqgszJHhW87mc8p:-KMUTgReg6j6n9ZUsQPD:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/4a84041738168c646817323cf37fbfff5d20c48f/biggraphite/accessor.py#L639)):*
<details><summary><i>Previously, natbraun (Nathaniel Braun) wrote…</i></summary>
> this should be an array of ints
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/46)*

**Comment by natbraun** [comment]
Reviewed 3 of 5 files at r1, 1 of 2 files at r2.
Review status: 4 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/46)*

**Comment by natbraun** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/46)*

**Comment by natbraun** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/46#-:-KMUVb4CnxSxhoERrI_w:1417088721)*

**Comment by iksaif** [comment]
fixed travis

---

Review status: 3 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/46#-:-KMUZoVO9ThswoO051zi:-1992479922)*

**Comment by natbraun** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/46#-:-KMUbjfV9UY8wQfukhBm:1417088721)*

**Pull request merged**
