### PR TITLE
Performance: Skip metric index if no glob

### PR DESCRIPTION
**Pull request by unbrice**
Speeds up check for metric existence by the carbon plugin.

---
This change is [Reviewable](https://reviewable.io/reviews/criteo/biggraphite/74)

### CODE REVIEW

**Comment by unbrice** [comment]
+@wdauchy please have a look, could be a good opportunity to dive in the project ( -@natbraun  to balance)

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/74#-:-KO7S83KTC6S0EurN3bs:1470574850)*

**Comment by wdauchy** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[biggraphite/drivers/cassandra.py, line 449 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/74#-KOPdfNzfscyJLJn0R6z:-KOPdfO-t5754NBI1I44:b-1zopt7) ([raw file](https://github.com/criteo/biggraphite/blob/22b56f7011c36c6077826ca896ac042087fc2721/biggraphite/drivers/cassandra.py#L449)):*
> ```Python
>         }
>         try:
>             metrics_names = [r[0] for r in self.__session.execute(query)]
> ```

is it really needed here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/74)*

**Comment by unbrice** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[biggraphite/drivers/cassandra.py, line 449 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/74#-KOPdfNzfscyJLJn0R6z:-KOQ43jxK_R95kVt27k9:b-ydqbwh) ([raw file](https://github.com/criteo/biggraphite/blob/22b56f7011c36c6077826ca896ac042087fc2721/biggraphite/drivers/cassandra.py#L449)):*
<details><summary><i>Previously, wdauchy (William Dauchy) wrote…</i></summary>
> is it really needed here?
</details>
you mean replacing `.name` with `[0]` ? No it's needed, I can do it in another change if you want, but it'd be a one line change...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/74)*

**Comment by unbrice** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[biggraphite/drivers/cassandra.py, line 449 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/74#-KOPdfNzfscyJLJn0R6z:-KOQ4OwzoeaLx0sSfv9v:bbxa0j) ([raw file](https://github.com/criteo/biggraphite/blob/22b56f7011c36c6077826ca896ac042087fc2721/biggraphite/drivers/cassandra.py#L449)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> you mean replacing `.name` with `[0]` ? No it's needed, I can do it in another change if you want, but it'd be a one line change...
</details>
I meant: it's *not* needed, only a small refactoring on the way

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/74)*

**Comment by wdauchy** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/74#-:-KOQ6ZS03Vl7-L8C-X8d:bnfp4nl)*

**Pull request merged**
