### PR TITLE
Add bgutil repair and repair() functions

### PR DESCRIPTION
**Pull request by iksaif**
Currently very slow, probably even too slow to be usable
on an actual setup. We need a way to parallelize that.

Also make some changes in create() and exists(): exists() will
check if the parent directory exists too, this allows fsck
to ignore metrics and run only on directories.

---
This change is [Reviewable](https://reviewable.io/reviews/criteo/biggraphite/99)

### CODE REVIEW

**Comment by Thib17** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[biggraphite/cli/command_repair.py, line 34 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/99#-KQPKxGu2AiF29YiNgsg:-KQPKxGvT67hUguWLfU9:b35i500) ([raw file](https://github.com/criteo/biggraphite/blob/6aecee1107baf0b5196e23814dc1d6af372bed75/biggraphite/cli/command_repair.py#L34)):*
> ```Python
>         accessor.connect()
> 
>         storage_path = "/home/cchary/dev/graphite/biggraphite/"
> ```

Is it normal that your name is hardcoded in the path ?

---

*[biggraphite/drivers/cassandra.py, line 420 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/99#-KQPP41TS-QEbCWxrZhC:-KQPP41TS-QEbCWxrZhD:bd4ubd4) ([raw file](https://github.com/criteo/biggraphite/blob/6aecee1107baf0b5196e23814dc1d6af372bed75/biggraphite/drivers/cassandra.py#L420)):*
> encoded_metric_name

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/99)*

**Comment by iksaif** [comment]
Review status: 7 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[biggraphite/cli/command_repair.py, line 34 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/99#-KQPKxGu2AiF29YiNgsg:-KQPsUSqqicapcDiHKzL:b-vy9x58) ([raw file](https://github.com/criteo/biggraphite/blob/6aecee1107baf0b5196e23814dc1d6af372bed75/biggraphite/cli/command_repair.py#L34)):*
<details><summary><i>Previously, Thib17 wrote…</i></summary>
> Is it normal that your name is hardcoded in the path ?
</details>
oops. Fixed.

---

*[biggraphite/drivers/cassandra.py, line 420 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/99#-KQPP41TS-QEbCWxrZhC:-KQPsgLLlJ21U2fURPBG:b-896fix) ([raw file](https://github.com/criteo/biggraphite/blob/6aecee1107baf0b5196e23814dc1d6af372bed75/biggraphite/drivers/cassandra.py#L420)):*
<details><summary><i>Previously, Thib17 wrote…</i></summary>
> > encoded_metric_name
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/99)*

**Comment by Thib17** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/99#-:-KQQK9BFvd85BzWjjWgi:bnfp4nl)*

**Comment by Thib17** [comment]
:strong_lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/99#-:-KQQXc_WBRLE5Y3RGbpx:bf9clrn)*

**Comment by Thib17** [comment]
:lgtm_strong:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/99#-:-KQQZ5Kn4TrbAAw8NwrT:b-jbsf8z)*

**Pull request merged**
