### PR TITLE
Fix several bugs in BigGraphite

### PR DESCRIPTION
**Pull request by natbraun**
This change is [Reviewable](https://reviewable.io/reviews/criteo/biggraphite/50)

### CODE REVIEW

**Comment by unbrice** [comment]
Reviewed 1 of 1 files at r1, 2 of 3 files at r2, 2 of 2 files at r3, 1 of 2 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/50)*

**Comment by iksaif** [comment]
Reviewed 1 of 1 files at r1, 1 of 4 files at r6.
Review status: 5 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[biggraphite/plugins/carbon.py, line 66 \[r6\]](https://reviewable.io:443/reviews/criteo/biggraphite/50#-KN64NUc9BzsNIjtsB_o:-KN64NUeoADXeWkBxeI5:-414713076) ([raw file](https://github.com/criteo/biggraphite/blob/54d093ad78728f31edcf72925312a0fe9f2d520f/biggraphite/plugins/carbon.py#L66)):*
> ```Python
>     def write(self, metric_name, datapoints):
>         metric = self._cache.get_metric(metric_name=metric_name)
>         datapoints = [(int(timestamp), value) for timestamp, value in datapoints]
> ```

please add a comment explaining why we need to do that

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/50)*

**Comment by iksaif** [comment]
:lgtm_strong: 

---

Reviewed 1 of 3 files at r2, 3 of 4 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/50#-:-KN64g-c3miIf2a9zyaw:-1868698381)*

**Comment by natbraun** [comment]
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[biggraphite/plugins/carbon.py, line 66 \[r6\]](https://reviewable.io:443/reviews/criteo/biggraphite/50#-KN64NUc9BzsNIjtsB_o:-KN6FAaIvGIcnvqYE7tA:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/54d093ad78728f31edcf72925312a0fe9f2d520f/biggraphite/plugins/carbon.py#L66)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> please add a comment explaining why we need to do that
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/50)*

**Comment by iksaif** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/50)*

**Comment by iksaif** [comment]
Reviewed 1 of 3 files at r2, 1 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/50)*

**Pull request merged**
