### PR TITLE
Add proper Finder implementation

### PR DESCRIPTION
**Pull request by natbraun**
This change is [Reviewable](https://reviewable.io/reviews/criteo/biggraphite/13)

### CODE REVIEW

**Comment by unbrice** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[biggraphite/graphite_utils.py, line 49 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/13#-KIE5j6UuEclJsp4W8R5:-KIE3l7WkRCxIEM-Qpsl:-1478098551) ([raw file](https://github.com/criteo/biggraphite/blob/c2aca6489df81a6392d693fde881156d0bd6b294/biggraphite/graphite_utils.py#L49)):*
> ```Python
> 
> 
> def glob_metrics_directories(accessor, graphite_glob):
> ```

I suggest glob() as a name

---

*[biggraphite/graphite_utils.py, line 50 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/13#-KIE3rvvq2AZJl890tc7:-KIE3rvvq2AZJl890tc8:968740608) ([raw file](https://github.com/criteo/biggraphite/blob/c2aca6489df81a6392d693fde881156d0bd6b294/biggraphite/graphite_utils.py#L50)):*
> ```Python
> 
> def glob_metrics_directories(accessor, graphite_glob):
>     """Get Cassandra metrics matching a Graphite glob.
> ```

metrics and directories

---

*[biggraphite/plugins/graphite.py, line 140 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/13#-KIE43lWyI7ctK5D-iGf:-KIE43lWyI7ctK5D-iGg:-622111975) ([raw file](https://github.com/criteo/biggraphite/blob/c2aca6489df81a6392d693fde881156d0bd6b294/biggraphite/plugins/graphite.py#L140)):*
> ```Python
>         """
> 
>         if accessor is None:
> ```

according to pep-8 you should use the fact that none is false (if accessor:)

---

*[biggraphite/plugins/graphite.py, line 168 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/13#-KIE4j-oqYOnUFIa7CQ8:-KIE4j-oqYOnUFIa7CQ9:-805731823) ([raw file](https://github.com/criteo/biggraphite/blob/c2aca6489df81a6392d693fde881156d0bd6b294/biggraphite/plugins/graphite.py#L168)):*
> ```Python
>         """Find nodes matching a query."""
>         # TODO: handle directories constructor argument/property
>         (metrics, directories) = graphite_utils.glob_metrics_directories(self._accessor, query.pattern)
> ```

no need for parenthesis on the left side

---

*[tests/test_graphite.py, line 21 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/13#-KIE4sHXMz32gzKpXppV:-KIE4sHXMz32gzKpXppW:-1605545085) ([raw file](https://github.com/criteo/biggraphite/blob/c2aca6489df81a6392d693fde881156d0bd6b294/tests/test_graphite.py#L21)):*
> ```Python
> import unittest
> 
> #from graphite import storage
> ```

you left a comment here

---

*[tests/test_graphite.py, line 100 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/13#-KIE5-__aR-OO6yBYUna:-KIE5-__aR-OO6yBYUnb:-1855241695) ([raw file](https://github.com/criteo/biggraphite/blob/c2aca6489df81a6392d693fde881156d0bd6b294/tests/test_graphite.py#L100)):*
> ```Python
> 
> 
> class FakeFindQuery(object):
> ```

missing doctstring saying why we can't use graphite's query

---

*[tests/test_graphite.py, line 120 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/13#-KIE5DWEn-6ES1PRvbTj:-KIE5DWEn-6ES1PRvbTk:1713804701) ([raw file](https://github.com/criteo/biggraphite/blob/c2aca6489df81a6392d693fde881156d0bd6b294/tests/test_graphite.py#L120)):*
> ```Python
>         nodes = list(self.find_nodes("a"))
>         self.assertEquals(len(nodes), 2)
>         self.assertEquals(sum(n.is_leaf and n.path == "a" for n in nodes), 1)
> ```

I suggest you define a assertMatch(glob, branches, leaves) and call it instead of copying and pasting code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/13)*

**Comment by iksaif** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[biggraphite/plugins/graphite.py, line 147 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/13#-KIOq79UfLrR2bXAyFks:-KIOq79UfLrR2bXAyFkt:-1478684687) ([raw file](https://github.com/criteo/biggraphite/blob/c2aca6489df81a6392d693fde881156d0bd6b294/biggraphite/plugins/graphite.py#L147)):*
> ```Python
>         self._accessor.connect()
> 
>     def _get_accessor_from_django(self):
> ```

This should probably be in some kind of shared function as Reader and Database will need it too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/13)*

**Comment by unbrice** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[biggraphite/plugins/graphite.py, line 147 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/13#-KIOq79UfLrR2bXAyFks:-KIRrJ1CR6mESHcVL42T:-1682085492) ([raw file](https://github.com/criteo/biggraphite/blob/c2aca6489df81a6392d693fde881156d0bd6b294/biggraphite/plugins/graphite.py#L147)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> This should probably be in some kind of shared function as Reader and Database will need it too.
</details>
Indeed we could factor this with https://github.com/criteo/biggraphite/blob/master/biggraphite/plugins/carbon.py#L47 ,
I propose putting that factored code in graphite_utils.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/13)*

**Comment by natbraun** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[biggraphite/graphite_utils.py, line 49 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/13#-KIE5j6UuEclJsp4W8R5:-KIRtdGTq4yYmwq6C5_K:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/c2aca6489df81a6392d693fde881156d0bd6b294/biggraphite/graphite_utils.py#L49)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> I suggest glob() as a name
</details>
Done.

---

*[biggraphite/graphite_utils.py, line 50 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/13#-KIE3rvvq2AZJl890tc7:-KIRtvp5Bi8QYraZaNBS:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/c2aca6489df81a6392d693fde881156d0bd6b294/biggraphite/graphite_utils.py#L50)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> metrics and directories
</details>
Done.

---

*[biggraphite/plugins/graphite.py, line 140 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/13#-KIE43lWyI7ctK5D-iGf:-KIRuinj621ovgkIVg_B:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/c2aca6489df81a6392d693fde881156d0bd6b294/biggraphite/plugins/graphite.py#L140)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> according to pep-8 you should use the fact that none is false (if accessor:)
</details>
Done.

---

*[biggraphite/plugins/graphite.py, line 147 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/13#-KIOq79UfLrR2bXAyFks:-KIRxRwpA9PGZvwC-IZj:1357026200) ([raw file](https://github.com/criteo/biggraphite/blob/c2aca6489df81a6392d693fde881156d0bd6b294/biggraphite/plugins/graphite.py#L147)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> Indeed we could factor this with https://github.com/criteo/biggraphite/blob/master/biggraphite/plugins/carbon.py#L47 ,
> I propose putting that factored code in graphite_utils.
</details>
Done.te

---

*[biggraphite/plugins/graphite.py, line 168 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/13#-KIE4j-oqYOnUFIa7CQ8:-KIRu81I2fuyweL0-Tao:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/c2aca6489df81a6392d693fde881156d0bd6b294/biggraphite/plugins/graphite.py#L168)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> no need for parenthesis on the left side
</details>
Done.

---

*[tests/test_graphite.py, line 21 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/13#-KIE4sHXMz32gzKpXppV:-KIRxagmNnRoxP8aaZGi:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/c2aca6489df81a6392d693fde881156d0bd6b294/tests/test_graphite.py#L21)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> you left a comment here
</details>
Done.

---

*[tests/test_graphite.py, line 100 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/13#-KIE5-__aR-OO6yBYUna:-KIRxxJGh7UCbZx5jorW:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/c2aca6489df81a6392d693fde881156d0bd6b294/tests/test_graphite.py#L100)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> missing doctstring saying why we can't use graphite's query
</details>
Done.

---

*[tests/test_graphite.py, line 120 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/13#-KIE5DWEn-6ES1PRvbTj:-KIS01SUbGVwgIkNxPGx:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/c2aca6489df81a6392d693fde881156d0bd6b294/tests/test_graphite.py#L120)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> I suggest you define a assertMatch(glob, branches, leaves) and call it instead of copying and pasting code.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/13)*

**Comment by unbrice** [comment]
Reviewed 1 of 5 files at r2, 1 of 1 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[biggraphite/graphite_utils.py, line 15 \[r4\]](https://reviewable.io:443/reviews/criteo/biggraphite/13#-KISXCRSO5y44cW5oHIa:-KISXCRSO5y44cW5oHIb:-1209651136) ([raw file](https://github.com/criteo/biggraphite/blob/21a537f3db8c1d2ac2b8a95063fe32f25c002ef3/biggraphite/graphite_utils.py#L15)):*
> ```Python
> 
> def accessor_from_settings(settings):
>     """Get accessor from configuration."""
> ```

Please add a description of settings (either a carbon_conf.Settings or a django-like setting)

---

*[biggraphite/plugins/carbon.py, line 52 \[r4\]](https://reviewable.io:443/reviews/criteo/biggraphite/13#-KISZ5TtcncW6if_X4lj:-KISZ5TtcncW6if_X4lk:-423232214) ([raw file](https://github.com/criteo/biggraphite/blob/21a537f3db8c1d2ac2b8a95063fe32f25c002ef3/biggraphite/plugins/carbon.py#L52)):*
> ```Python
>             self._accessor.connect()
>         except graphite_utils.ConfigException as e:
>             raise carbon_exceptions.CarbonConfigException(str(e))
> ```

no need for str

---

*[tests/test_graphite.py, line 125 \[r4\]](https://reviewable.io:443/reviews/criteo/biggraphite/13#-KISZMJfsxQgEJWgJ4ay:-KISZMJfsxQgEJWgJ4az:-277003713) ([raw file](https://github.com/criteo/biggraphite/blob/21a537f3db8c1d2ac2b8a95063fe32f25c002ef3/tests/test_graphite.py#L125)):*
> ```Python
>         found_leaves = [node.path for node in found if node.is_leaf]
>         self.assertEquals(sorted(found_branches), sorted(branches))
>         self.assertEquals(sorted(found_leaves), sorted(leaves))
> ```

assertItemsEqual

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/13)*

**Comment by natbraun** [comment]
Review status: 1 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[biggraphite/graphite_utils.py, line 15 \[r4\]](https://reviewable.io:443/reviews/criteo/biggraphite/13#-KISXCRSO5y44cW5oHIa:-KIS_RKrfETcveE43F5t:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/21a537f3db8c1d2ac2b8a95063fe32f25c002ef3/biggraphite/graphite_utils.py#L15)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> Please add a description of settings (either a carbon_conf.Settings or a django-like setting)
</details>
Done.

---

*[biggraphite/plugins/carbon.py, line 52 \[r4\]](https://reviewable.io:443/reviews/criteo/biggraphite/13#-KISZ5TtcncW6if_X4lj:-KIS_22wg8DyhiTC46AC:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/21a537f3db8c1d2ac2b8a95063fe32f25c002ef3/biggraphite/plugins/carbon.py#L52)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> no need for str
</details>
Done.

---

*[tests/test_graphite.py, line 125 \[r4\]](https://reviewable.io:443/reviews/criteo/biggraphite/13#-KISZMJfsxQgEJWgJ4ay:-KISZo7zMTJtlY5BF7OU:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/21a537f3db8c1d2ac2b8a95063fe32f25c002ef3/tests/test_graphite.py#L125)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> assertItemsEqual
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/13)*

**Comment by unbrice** [comment]
Reviewed 4 of 5 files at r5.
Review status: 5 of 6 files reviewed at latest revision, 6 unresolved discussions.

---

*[tests/test_graphite.py, line 125 \[r4\]](https://reviewable.io:443/reviews/criteo/biggraphite/13#-KISZMJfsxQgEJWgJ4ay:-KIT5yqWIgyCrMMhUplC:774973290) ([raw file](https://github.com/criteo/biggraphite/blob/21a537f3db8c1d2ac2b8a95063fe32f25c002ef3/tests/test_graphite.py#L125)):*
<details><summary><i>Previously, natbraun (Nathaniel Braun) wrote…</i></summary>
> Done.
</details>
No need for sorted.

---

*[tests/test_graphite_utils.py, line 44 \[r5\]](https://reviewable.io:443/reviews/criteo/biggraphite/13#-KIT68eL_lzRcD5ziLTs:-KIT68eL_lzRcD5ziLTt:-156019328) ([raw file](https://github.com/criteo/biggraphite/blob/83db43a70a1706a830299b1e08eb94e1beacce35/tests/test_graphite_utils.py#L44)):*
> ```Python
>         import types
>         lacks_contact_points = types.ModuleType("lacks_contact_points")
>         setattr(lacks_contact_points, "BG_KEYSPACE", "keyspace")
> ```

lacks_contact_points.BG_KEYSPACE =

---

*[tests/test_graphite_utils.py, line 47 \[r5\]](https://reviewable.io:443/reviews/criteo/biggraphite/13#-KIT6AGN7Uqup46k7ldI:-KIT6AGN7Uqup46k7ldJ:719140283) ([raw file](https://github.com/criteo/biggraphite/blob/83db43a70a1706a830299b1e08eb94e1beacce35/tests/test_graphite_utils.py#L47)):*
> ```Python
> 
>         lacks_keyspace = types.ModuleType("lacks_keyspace")
>         setattr(lacks_keyspace, "BG_CONTACT_POINTS", "localhost")
> ```

lacks_contact_points.BG_CONTACT_POINTS =

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/13)*

**Comment by unbrice** [comment]
Reviewed 1 of 5 files at r5.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/13)*

**Comment by natbraun** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[tests/test_graphite.py, line 125 \[r4\]](https://reviewable.io:443/reviews/criteo/biggraphite/13#-KISZMJfsxQgEJWgJ4ay:-KIT6kSg8oAar-winETh:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/21a537f3db8c1d2ac2b8a95063fe32f25c002ef3/tests/test_graphite.py#L125)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> No need for sorted.
</details>
Done.

---

*[tests/test_graphite_utils.py, line 44 \[r5\]](https://reviewable.io:443/reviews/criteo/biggraphite/13#-KIT68eL_lzRcD5ziLTs:-KIT6ksAp0P4ZO-2JUh9:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/83db43a70a1706a830299b1e08eb94e1beacce35/tests/test_graphite_utils.py#L44)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> lacks_contact_points.BG_KEYSPACE =
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/13)*

**Comment by unbrice** [comment]
:lgtm_strong: 

<details><summary><i>Previously, coveralls wrote…</i></summary>
> 
> [Coverage Status](https://coveralls.io/builds/6291643)
> 
> Coverage increased (+3.9%) to 77.113% when pulling **83db43a70a1706a830299b1e08eb94e1beacce35 on natbraun:master** into **7b585fee7b050da5c1a84b9261334482fd5d2700 on criteo:master**.
> 
</details>


---

Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/13#-:-KITFQJoqauDH-UxZKzm:-1868698381)*

**Comment by natbraun** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[biggraphite/plugins/graphite.py, line 147 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/13#-KIOq79UfLrR2bXAyFks:-KITFm9zWFvT3aquCM3v:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/c2aca6489df81a6392d693fde881156d0bd6b294/biggraphite/plugins/graphite.py#L147)):*
<details><summary><i>Previously, natbraun (Nathaniel Braun) wrote…</i></summary>
> Done.te
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/13)*

**Comment by natbraun** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/test_graphite_utils.py, line 47 \[r5\]](https://reviewable.io:443/reviews/criteo/biggraphite/13#-KIT6AGN7Uqup46k7ldI:-KITFo944Qj9IJBUjf_W:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/83db43a70a1706a830299b1e08eb94e1beacce35/tests/test_graphite_utils.py#L47)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> lacks_contact_points.BG_CONTACT_POINTS =
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/13)*

**Comment by natbraun** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[biggraphite/plugins/graphite.py, line 147 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/13#-KIOq79UfLrR2bXAyFks:-KITFqDcq-jFezB0P52V:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/c2aca6489df81a6392d693fde881156d0bd6b294/biggraphite/plugins/graphite.py#L147)):*
<details><summary><i>Previously, natbraun (Nathaniel Braun) wrote…</i></summary>
> Done.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/13)*

**Comment by iksaif** [comment]
:lgtm:

<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> :lgtm_strong: 
</details>


---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/13#-:-KITIJ9fYSED5TzZpd1q:1417088721)*

**Pull request merged**
