### PR TITLE
Plugin carbon

### PR DESCRIPTION
**Pull request by unbrice**
This change is [Reviewable](https://reviewable.io/reviews/criteo/biggraphite/6)

### CODE REVIEW

**Comment by iksaif** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[biggraphite/plugins/carbon.py, line 19 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/6#-KHQ4amqfZj2da-9n3Uu:-KHQ4amqfZj2da-9n3Uv:-1753631646) ([raw file](https://github.com/criteo/biggraphite/blob/a6f735cdf3724ec18e0a0138e632fee597ec5d69/biggraphite/plugins/carbon.py#L19)):*
> ```Python
> 
> try:
>     from carbon import database
> ```

can you add a comment explaining why you do that ?

---

*[biggraphite/plugins/carbon.py, line 70 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/6#-KHQ4w9s_8hz-NXx66of:-KHQ4w9s_8hz-NXx66og:1240342761) ([raw file](https://github.com/criteo/biggraphite/blob/a6f735cdf3724ec18e0a0138e632fee597ec5d69/biggraphite/plugins/carbon.py#L70)):*
> ```Python
>     def exists(self, metric):
>         # If exists returns "False" then "create" will be called.
>         # New metrics are also throttled by some settings.
> ```

Add a TODO to add some kind of cache here ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/6)*

**Comment by unbrice** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[biggraphite/plugins/carbon.py, line 19 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/6#-KHQ4amqfZj2da-9n3Uu:-KHQ_9V-sOjGv5zNg-dI:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/a6f735cdf3724ec18e0a0138e632fee597ec5d69/biggraphite/plugins/carbon.py#L19)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> can you add a comment explaining why you do that ?</details>
Done.

---

*[biggraphite/plugins/carbon.py, line 70 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/6#-KHQ4w9s_8hz-NXx66of:-KHQ_YQb4cP3aZKznVz1:-480077860) ([raw file](https://github.com/criteo/biggraphite/blob/a6f735cdf3724ec18e0a0138e632fee597ec5d69/biggraphite/plugins/carbon.py#L70)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> Add a TODO to add some kind of cache here ?</details>
Indeed. I added it at the module level. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/6)*

**Comment by iksaif** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[biggraphite/plugins/carbon.py, line 21 \[r4\]](https://reviewable.io:443/reviews/criteo/biggraphite/6#-KHQblUXfvqjdgJZQdCM:-KHQblUXfvqjdgJZQdCN:528839939) ([raw file](https://github.com/criteo/biggraphite/blob/4d0e6f982262987edcaef50ee469012b07d70b91/biggraphite/plugins/carbon.py#L21)):*
> ```Python
>     # Version 0.9.15 (the one from PIP) does not have the "database" module.
>     # Since the TimeSeriesDatabase class there has no behaviour appart from
>     # registering instances, we can use "object" in this case.
> ```

If that's the only reason can't we put a more recent version in requirements.txt  (you can put git or http urls) ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/6)*

**Comment by unbrice** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[biggraphite/plugins/carbon.py, line 21 \[r4\]](https://reviewable.io:443/reviews/criteo/biggraphite/6#-KHQblUXfvqjdgJZQdCM:-KHTw_R7zY-NzqyY7eHb:532360478) ([raw file](https://github.com/criteo/biggraphite/blob/4d0e6f982262987edcaef50ee469012b07d70b91/biggraphite/plugins/carbon.py#L21)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> If that's the only reason can't we put a more recent version in requirements.txt  (you can put git or http urls) ?</details>
There is no published version with this feature :-( I added the URL and commit for people to roll their own.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/6)*

**Comment by unbrice** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[biggraphite/plugins/carbon.py, line 21 \[r4\]](https://reviewable.io:443/reviews/criteo/biggraphite/6#-KHQblUXfvqjdgJZQdCM:-KHUB-slJgjfmYuCkuW3:-798573478) ([raw file](https://github.com/criteo/biggraphite/blob/4d0e6f982262987edcaef50ee469012b07d70b91/biggraphite/plugins/carbon.py#L21)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> There is no published version with this feature :-( I added the URL and commit for people to roll their own.</details>
Added a TODO to update requirements.txt

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/6)*

**Comment by iksaif** [comment]
:lgtm:

<details><summary><i>Previously, coveralls wrote…</i></summary>
> 
> [Coverage Status](https://coveralls.io/builds/6132763)
> 
> Coverage increased (+8.6%) to 71.021% when pulling **bd0b74e5c30fc35a96bfb177fee9f806c163f323 on unbrice:plugin_carbon** into **d826670ec4fe0998de3ff7e2334225759f048426 on criteo:master**.
> </details>


---

Reviewed 1 of 1 files at r7.
Review status: 1 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/6#-:-KHUEJdLCu-1CHkIOy9P:1417088721)*

**Pull request merged**
