### PR TITLE
Adjust the row width to the stage

### PR DESCRIPTION
**Pull request by unbrice**
This causes all previous writes to be ignored.

---
This change is [Reviewable](https://reviewable.io/reviews/criteo/biggraphite/75)

### CODE REVIEW

**Comment by unbrice** [comment]
-@iksaif +@natbraun as Iksaif not around 

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/75#-:-KO7S4Bkgxiz5dMGpN-W:1326438874)*

**Comment by unbrice** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[biggraphite/drivers/cassandra.py, line 142 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/75#-KOJxchRHbUluE2DmiYP:-KOJxchRHbUluE2DmiYQ:1843573895) ([raw file](https://github.com/criteo/biggraphite/blob/c6f9da87bb45b094f090a3910d00b1a6ca1c4066/biggraphite/drivers/cassandra.py#L142)):*
> ```Python
>       An integer, the duration in milliseconds.
>     """
>     return stage.precision_ms * _EXPECTED_POINTS_PER_READ
> ```

From @iksaif: Check that this results in an acceptable overhead/row size in bytes

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/75)*

**Comment by iksaif** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[biggraphite/drivers/cassandra.py, line 142 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/75#-KOJxchRHbUluE2DmiYP:-KOKWJI0ZdCE7Ew-X9wP:1742275430) ([raw file](https://github.com/criteo/biggraphite/blob/c6f9da87bb45b094f090a3910d00b1a6ca1c4066/biggraphite/drivers/cassandra.py#L142)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> From @iksaif: Check that this results in an acceptable overhead/row size in bytes
</details>
as discussed offline 2048 points could be a good number for our current numbers. We can make that tweakable later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/75)*

**Comment by iksaif** [comment]
should somebody takeover this PR ?

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/75#-:-KP9ejar50LTPPLhEXqf:b-uecqkg)*

**Comment by iksaif** [comment]
Closed in favor of https://github.com/criteo/biggraphite/pull/80

**Pull request closed without merging**
