### PR TITLE
Accessor uses Metric instead of names

### PR DESCRIPTION
**Pull request by unbrice**
So that downsampling can happen at write and aggregation server-side,
the Accessor needs to have metadata when it reads/writes.

---
This change is [Reviewable](https://reviewable.io/reviews/criteo/biggraphite/34)

### CODE REVIEW

**Comment by iksaif** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[biggraphite/accessor.py, line 188 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/34#-KJg9FQbHSv6EAwAlvZE:-KJg9FQbHSv6EAwAlvZF:1860261182) ([raw file](https://github.com/criteo/biggraphite/blob/5309c963845a90e9ec8fb04b7a77238c7b6b5539/biggraphite/accessor.py#L188)):*
> ```Python
>     """Represents all information about a metric except its name.
> 
>     Not meant to be mutated.
> ```

Is there a magic class somewhere to freeze it ? 

---

*[biggraphite/accessor.py, line 275 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/34#-KJg9dtmlJy3ITYPT5Ht:-KJg9dtmlJy3ITYPT5Hu:-1166915285) ([raw file](https://github.com/criteo/biggraphite/blob/5309c963845a90e9ec8fb04b7a77238c7b6b5539/biggraphite/accessor.py#L275)):*
> ```Python
>     """
> 
>     __slots__ = ("name", "metadata")
> ```

why not a namedtuple or a Bunch ?

---

*[biggraphite/metadata_cache.py, line 124 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/34#-KJgAIhVdbaXCqABTbwQ:-KJgAIhVdbaXCqABTbwR:-350334200) ([raw file](https://github.com/criteo/biggraphite/blob/5309c963845a90e9ec8fb04b7a77238c7b6b5539/biggraphite/metadata_cache.py#L124)):*
> ```Python
>         """
>         self.__accessor.create_metric(metric)
>         self._cache(metric.name, metric.metadata)
> ```

will the cache really use metric.name here or will it index it with a hash ? Should we use a hash ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/34)*

**Comment by unbrice** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[biggraphite/accessor.py, line 188 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/34#-KJg9FQbHSv6EAwAlvZE:-KJjhXBvs9IywsNf7vhb:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/5309c963845a90e9ec8fb04b7a77238c7b6b5539/biggraphite/accessor.py#L188)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> Is there a magic class somewhere to freeze it ? 
</details>
Done.

---

*[biggraphite/accessor.py, line 275 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/34#-KJg9dtmlJy3ITYPT5Ht:-KJktVZltKvS9mq2wW1r:-1990506588) ([raw file](https://github.com/criteo/biggraphite/blob/5309c963845a90e9ec8fb04b7a77238c7b6b5539/biggraphite/accessor.py#L275)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> why not a namedtuple or a Bunch ?
</details>
I don't think it makes sense to do things like metric[0], also it's quite magic already in the way it delegates to metadata ;-)

---

*[biggraphite/metadata_cache.py, line 124 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/34#-KJgAIhVdbaXCqABTbwQ:-KJkts2a9lhhAS4HKWZo:102040159) ([raw file](https://github.com/criteo/biggraphite/blob/5309c963845a90e9ec8fb04b7a77238c7b6b5539/biggraphite/metadata_cache.py#L124)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> will the cache really use metric.name here or will it index it with a hash ? Should we use a hash ?
</details>
it's a b+tree, maybe I didn't understand the question?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/34)*

**Comment by iksaif** [comment]
Review status: 9 of 11 files reviewed at latest revision, 3 unresolved discussions.

---

*[biggraphite/metadata_cache.py, line 124 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/34#-KJgAIhVdbaXCqABTbwQ:-KJkvcfYD6nPX5ECWVQ8:-1015724063) ([raw file](https://github.com/criteo/biggraphite/blob/5309c963845a90e9ec8fb04b7a77238c7b6b5539/biggraphite/metadata_cache.py#L124)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> it's a b+tree, maybe I didn't understand the question?
</details>
forget that. I didn't see the metric.metadata on the right

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/34)*

**Comment by iksaif** [comment]
:lgtm:

<details><summary><i>Previously, coveralls wrote…</i></summary>
> 
> [Coverage Status](https://coveralls.io/builds/6514906)
> 
> Coverage increased (+0.5%) to 93.313% when pulling **2194ded90d380bae4b25500075bd95de61d76541 on unbrice:master** into **a71d8fcd34a282c1d76decf7c0b2092b3b2b38b2 on criteo:master**.
> 
</details>


---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/34#-:-KJupqc9hx_LdoVllGOF:1417088721)*

**Pull request merged**
