### PR TITLE
Transform DRIVERS to a dict

### PR DESCRIPTION
**Pull request by fedj**

### CODE REVIEW

**Comment by Thib17** [comment]
What does it fix ?
Isn't that saffer to keep it in a frozenset ?

**Comment by fedj** [comment]
A dict is (IMO) way easier to understand than a set of pairs (which basically is the same concept). frozenset is immutable yes but after the refactorings of yesterday, it can now be private to this module.

**Comment by Thib17** [comment]
afaik nothing is really private in python. It's more like a writting convention.

**Comment by iksaif** [comment]
Can you rebase and fix the tests ?

**Comment by fedj** [comment]
Actually, the API of dict changed between python 2.7 and 3 so I'll cancel this one

**Pull request closed without merging**
