### PR TITLE
Return stage instead of step in Downsampler

### PR DESCRIPTION
**Pull request by natbraun**
This change is [Reviewable](https://reviewable.io/reviews/criteo/biggraphite/59)

### CODE REVIEW

**Comment by unbrice** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[biggraphite/drivers/_downsampling.py, line 165 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/59#-KNbaxO5LrPKo1T0HwsL:-KNbaxO5LrPKo1T0HwsM:-362093880) ([raw file](https://github.com/criteo/biggraphite/blob/3a29b17f30744ec2dd10730e373d146d1b10ed48/biggraphite/drivers/_downsampling.py#L165)):*
> ```Python
>         """
>         stages = metric_metadata.retention.stages
>         stage_object = stages[stage]
> ```

stage = stages[stage_index]

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/59)*

**Comment by unbrice** [comment]
:lgtm_strong: 

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[biggraphite/drivers/cassandra.py, line 383 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/59#-KNbbpTJKinreCsqT8lg:-KNbbpTJKinreCsqT8lh:-864292129) ([raw file](https://github.com/criteo/biggraphite/blob/3a29b17f30744ec2dd10730e373d146d1b10ed48/biggraphite/drivers/cassandra.py#L383)):*
> ```Python
>         for datapoint in datapoints:
>             if len(datapoint) == 4:
>                 # Aggregated points have the following fields:
> ```

Add TODO : use a namedtupple

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/59#-:-KNbc4w8d9L5OHMZZfWI:-1868698381)*

**Comment by unbrice** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[biggraphite/drivers/cassandra.py, line 390 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/59#-KNbcK4ww_FD_6OVga5g:-KNbcK4ww_FD_6OVga5h:-609251160) ([raw file](https://github.com/criteo/biggraphite/blob/3a29b17f30744ec2dd10730e373d146d1b10ed48/biggraphite/drivers/cassandra.py#L390)):*
> ```Python
>                 timestamp, value, count, stage = datapoint
>                 count = int(count)
>                 time_step_ms = bg_accessor.round_down(timestamp) * 1000
> ```

stage.round_down

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/59)*

**Comment by natbraun** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[biggraphite/drivers/cassandra.py, line 383 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/59#-KNbbpTJKinreCsqT8lg:-KNbdEf7SZJ_VsqBgNdW:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/3a29b17f30744ec2dd10730e373d146d1b10ed48/biggraphite/drivers/cassandra.py#L383)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> Add TODO : use a namedtupple
</details>
Done.

---

*[biggraphite/drivers/cassandra.py, line 390 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/59#-KNbcK4ww_FD_6OVga5g:-KNbdF4GAlFfrFaMpk3A:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/3a29b17f30744ec2dd10730e373d146d1b10ed48/biggraphite/drivers/cassandra.py#L390)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> stage.round_down
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/59)*

**Comment by natbraun** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[biggraphite/drivers/_downsampling.py, line 165 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/59#-KNbaxO5LrPKo1T0HwsL:-KNbeGCQQpQp3kQtlFJW:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/3a29b17f30744ec2dd10730e373d146d1b10ed48/biggraphite/drivers/_downsampling.py#L165)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> stage = stages[stage_index]
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/59)*

**Comment by iksaif** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/59)*

**Comment by iksaif** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/59)*

**Comment by unbrice** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[biggraphite/drivers/cassandra.py, line 390 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/59#-KNbgZ4rQx4vWAQRbFfK:-KNbgZ4rQx4vWAQRbFfL:509149246) ([raw file](https://github.com/criteo/biggraphite/blob/3f2db62018fd6ea3dbdc5dc0d5bf71987bb872a6/biggraphite/drivers/cassandra.py#L390)):*
> ```Python
>                 timestamp, value, count, stage = datapoint
>                 count = int(count)
>                 time_step_ms = stage.round_down(timestamp) * 1000
> ```

time_step_ms = stage.precision * 1000

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/59)*

**Comment by natbraun** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[biggraphite/drivers/cassandra.py, line 390 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/59#-KNbgZ4rQx4vWAQRbFfK:-KNblWgityoq_zQUZCcJ:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/3f2db62018fd6ea3dbdc5dc0d5bf71987bb872a6/biggraphite/drivers/cassandra.py#L390)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> time_step_ms = stage.precision * 1000
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/59)*

**Comment by unbrice** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/59)*

**Comment by unbrice** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/59)*

**Pull request merged**
