### PR TITLE
bg-carbon-cache manipulate sys.path like upstream

### PR DESCRIPTION
**Pull request by unbrice**
This change is [Reviewable](https://reviewable.io/reviews/criteo/biggraphite/17)

### CODE REVIEW

**Comment by unbrice** [comment]
+@iksaif 

<details><summary><i>Previously, coveralls wrote…</i></summary>
> 
> [Coverage Status](https://coveralls.io/builds/6358635)
> 
> Coverage increased (+0.3%) to 77.559% when pulling **d1c92886f6c70778813e9b6800ef223906f5bcac on unbrice:master** into **dee83a2bf6a3d5542e8f8aa1b94230be8a57be9b on criteo:master**.
> 
</details>


---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/17#-:-KIls47-zRI9kc5DhNBh:453489465)*

**Comment by iksaif** [comment]
:lgtm_strong: 

<details><summary><i>Previously, coveralls wrote…</i></summary>
> 
> [Coverage Status](https://coveralls.io/builds/6360065)
> 
> Coverage increased (+0.6%) to 77.866% when pulling **65c337f069da1256ebbeb7b75e62f94e3e1067b5 on unbrice:master** into **dee83a2bf6a3d5542e8f8aa1b94230be8a57be9b on criteo:master**.
> 
</details>


---

Reviewed 1 of 2 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[biggraphite/cli/bg_carbon_cache.py, line 14 \[r5\]](https://reviewable.io:443/reviews/criteo/biggraphite/17#-KImEOwjBNn3IfVdGFmo:-KImEOwjBNn3IfVdGFmp:-1096603563) ([raw file](https://github.com/criteo/biggraphite/blob/fb6cba209d99d5df30349692a15acfa7a4d1f58b/biggraphite/cli/bg_carbon_cache.py#L14)):*
> ```Python
> # See the License for the specific language governing permissions and
> # limitations under the License.
> """Simulates carbon-cache after loading the carbon plugin."""
> ```

Maybe add some lines in the docstring explaining that we need to do that because we don't have https://github.com/graphite-project/carbon/pull/139

---

*[biggraphite/cli/bg_carbon_cache.py, line 23 \[r5\]](https://reviewable.io:443/reviews/criteo/biggraphite/17#-KImBxR0C_lw2RZ3485E:-KImBxR0C_lw2RZ3485F:679945087) ([raw file](https://github.com/criteo/biggraphite/blob/fb6cba209d99d5df30349692a15acfa7a4d1f58b/biggraphite/cli/bg_carbon_cache.py#L23)):*
> ```Python
> 
> def _manipulate_paths_like_upstream(_executable, sys_path):
>     """Replicate the sys.path magic from carbon-cache."""
> ```

I'm not sure I get what this means

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/17#-:-KImEZjA2AX-KnMXIiPM:-1868698381)*

**Comment by unbrice** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[biggraphite/cli/bg_carbon_cache.py, line 14 \[r5\]](https://reviewable.io:443/reviews/criteo/biggraphite/17#-KImEOwjBNn3IfVdGFmo:-KImNHeYpnlNwvyDVOmC:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/fb6cba209d99d5df30349692a15acfa7a4d1f58b/biggraphite/cli/bg_carbon_cache.py#L14)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> Maybe add some lines in the docstring explaining that we need to do that because we don't have https://github.com/graphite-project/carbon/pull/139
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/17)*

**Comment by unbrice** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[biggraphite/cli/bg_carbon_cache.py, line 23 \[r5\]](https://reviewable.io:443/reviews/criteo/biggraphite/17#-KImBxR0C_lw2RZ3485E:-KImNQW4LWJHFhyDQAfP:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/fb6cba209d99d5df30349692a15acfa7a4d1f58b/biggraphite/cli/bg_carbon_cache.py#L23)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> I'm not sure I get what this means
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/17)*

**Pull request merged**
