### PR TITLE
Fix memory leak and bug

### PR DESCRIPTION
**Pull request by unbrice**
- We were limited to 10M of local cache
- LMDB won't accept unicode objects, so encode metric names to
  UTF-8 (probably safer anyway)
- we cache decoded jsons metadata but they included metric names, taking
  quite some memory (while the idea behind caching is that there are few
  retentions policies in use at any given time)

---
This change is [Reviewable](https://reviewable.io/reviews/criteo/biggraphite/25)

### CODE REVIEW

**Comment by natbraun** [comment]
Reviewed 3 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[biggraphite/accessor.py, line 175 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/25#-KJA86rZLYHHz94JRp5q:-KJA86rZLYHHz94JRp5r:122320271) ([raw file](https://github.com/criteo/biggraphite/blob/3f854ccaa3623fe16e543c66ca1169bbddb40aa1/biggraphite/accessor.py#L175)):*
> ```Python
>       name: The metric to encode, must be an instance of basestring.
>         If it is an instance of string, it will be assumed to already have been
>         encoded.
> ```

Please state why you make this check.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/25)*

**Comment by unbrice** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[biggraphite/accessor.py, line 175 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/25#-KJA86rZLYHHz94JRp5q:-KJA8XtzkTucYJkjsgUK:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/3f854ccaa3623fe16e543c66ca1169bbddb40aa1/biggraphite/accessor.py#L175)):*
<details><summary><i>Previously, natbraun (Nathaniel Braun) wrote…</i></summary>
> Please state why you make this check.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/25)*

**Comment by natbraun** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/25)*

**Comment by natbraun** [comment]
:lgtm:

<details><summary><i>Previously, coveralls wrote…</i></summary>
> 
> [Coverage Status](https://coveralls.io/builds/6413581)
> 
> Coverage decreased (-0.3%) to 92.939% when pulling **3f854ccaa3623fe16e543c66ca1169bbddb40aa1 on unbrice:master** into **fc960283fd114e6289b71665e224c71f83cc226a on criteo:master**.
> 
</details>


---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/25#-:-KJA8arn4k61IHO-AsUc:1417088721)*

**Comment by natbraun** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/25)*

**Comment by natbraun** [comment]
:lgtm:

<details><summary><i>Previously, coveralls wrote…</i></summary>
> 
> [Coverage Status](https://coveralls.io/builds/6414084)
> 
> Coverage increased (+0.1%) to 93.312% when pulling **a875218f946e0382a7a02c11703b0ec16964b0ef on unbrice:master** into **fc960283fd114e6289b71665e224c71f83cc226a on criteo:master**.
> 
</details>


---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/25#-:-KJAHaySdwO75UJLch2-:1417088721)*

**Pull request merged**
