### PR TITLE
Improve Downsampler to use actual metric metadata

### PR DESCRIPTION
**Pull request by natbraun**
This change is [Reviewable](https://reviewable.io/reviews/criteo/biggraphite/49)

### CODE REVIEW

**Comment by iksaif** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[biggraphite/drivers/downsampling.py, line 39 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/49#-KMy0rqA-yx-UPUID_Ym:-KMy0rqA-yx-UPUID_Yn:509396468) ([raw file](https://github.com/criteo/biggraphite/blob/cb2392d03111dc5be2a60c7b19bd3feb10fece4a/biggraphite/drivers/downsampling.py#L39)):*
> ```Python
>         results = []
> 
>         # ensure we have the required aggregation mechanism
> ```

please start comments with an uppercase letter and end with a point :)

---

*[biggraphite/drivers/downsampling.py, line 50 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/49#-KMy0kCgro--l68PvsYY:-KMy0kCgro--l68PvsYZ:-1302601411) ([raw file](https://github.com/criteo/biggraphite/blob/cb2392d03111dc5be2a60c7b19bd3feb10fece4a/biggraphite/drivers/downsampling.py#L50)):*
> ```Python
>         for aggregate in aggregates:
>             results.extend(aggregates)
> ```

maybe add a TODO to remove from __metrics if all the points have been removed from the buffer (to purge old metrics).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/49)*

**Comment by natbraun** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[biggraphite/drivers/downsampling.py, line 39 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/49#-KMy0rqA-yx-UPUID_Ym:-KMy1_zrvYClekUc0RcE:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/cb2392d03111dc5be2a60c7b19bd3feb10fece4a/biggraphite/drivers/downsampling.py#L39)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> please start comments with an uppercase letter and end with a point :)
</details>
Done.

---

*[biggraphite/drivers/downsampling.py, line 50 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/49#-KMy0kCgro--l68PvsYY:-KMy1sibGw9w4MMt9Dgc:1706342915) ([raw file](https://github.com/criteo/biggraphite/blob/cb2392d03111dc5be2a60c7b19bd3feb10fece4a/biggraphite/drivers/downsampling.py#L50)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> maybe add a TODO to remove from __metrics if all the points have been removed from the buffer (to purge old metrics).
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/49)*

**Comment by iksaif** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[biggraphite/drivers/downsampling.py, line 41 \[r3\]](https://reviewable.io:443/reviews/criteo/biggraphite/49#-KMySSoKy9VNR0nTtG91:-KMySSoKy9VNR0nTtG92:-210858341) ([raw file](https://github.com/criteo/biggraphite/blob/e8918f853589f8a233e01a9a736701c2c7d68cd7/biggraphite/drivers/downsampling.py#L41)):*
> ```Python
>         # Ensure we have the required aggregation mechanism.
>         if metric.name not in self.__metrics:
>             self.__metrics[metric.name] = MetricAggregates(metric.metadata)
> ```

You're supposed to have a  MetricBuffer first here, and add the points to MetricAggregates only once they expire/are validated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/49)*

**Comment by natbraun** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[biggraphite/drivers/downsampling.py, line 41 \[r3\]](https://reviewable.io:443/reviews/criteo/biggraphite/49#-KMySSoKy9VNR0nTtG91:-KN1dYR2P0JqQZ3VZeYf:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/e8918f853589f8a233e01a9a736701c2c7d68cd7/biggraphite/drivers/downsampling.py#L41)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> You're supposed to have a  MetricBuffer first here, and add the points to MetricAggregates only once they expire/are validated.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/49)*

**Comment by natbraun** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/49)*

**Comment by natbraun** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/49)*

**Comment by unbrice** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[biggraphite/drivers/downsampling.py, line 51 \[r4\]](https://reviewable.io:443/reviews/criteo/biggraphite/49#-KN1uN98I-Ab6pfKiLGA:-KN1uN98I-Ab6pfKiLGB:1805448501) ([raw file](https://github.com/criteo/biggraphite/blob/8a9790b91fec4f762a58b075f836a4968a038842/biggraphite/drivers/downsampling.py#L51)):*
> ```Python
>         """
>         # Sort points by increasing timestamp.
>         sorted_points = sorted(datapoints, key=lambda p: p[0])
> ```

key is not needed here and makes sorting slower (one function call)

---

*[biggraphite/drivers/downsampling.py, line 56 \[r4\]](https://reviewable.io:443/reviews/criteo/biggraphite/49#-KN1ukavJYNZk20yE_CX:-KN1ukavJYNZk20yE_CY:1045857653) ([raw file](https://github.com/criteo/biggraphite/blob/8a9790b91fec4f762a58b075f836a4968a038842/biggraphite/drivers/downsampling.py#L56)):*
> ```Python
>         expired_points = []
>         for timestamp, value in sorted_points:
>             expired_points.extend(self.__buffer.put(timestamp, value))
> ```

Please confirm it is safe to call
d.feed([4200, 0.0])
d.feed([4000, 1.0])
even though 4200 and 4000 will be out of order

---

*[tests/test_drivers_downsampling.py, line 308 \[r4\]](https://reviewable.io:443/reviews/criteo/biggraphite/49#-KN1xkibJ3FZYpph5wr8:-KN1xkic6MTDgGBcNvjr:1922602567) ([raw file](https://github.com/criteo/biggraphite/blob/8a9790b91fec4f762a58b075f836a4968a038842/tests/test_drivers_downsampling.py#L308)):*
> ```Python
>         ]
>         expected_stage_1 = [
>             (0, 26, 3, self.PRECISION ** 2)
> ```

please add a comment: "26 is 9 + 10 +7, sum of stage0 values"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/49)*

**Comment by natbraun** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[biggraphite/drivers/downsampling.py, line 51 \[r4\]](https://reviewable.io:443/reviews/criteo/biggraphite/49#-KN1uN98I-Ab6pfKiLGA:-KN2-jVFOhPgI1Q8dRJT:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/8a9790b91fec4f762a58b075f836a4968a038842/biggraphite/drivers/downsampling.py#L51)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> key is not needed here and makes sorting slower (one function call)
</details>
Done.

---

*[biggraphite/drivers/downsampling.py, line 56 \[r4\]](https://reviewable.io:443/reviews/criteo/biggraphite/49#-KN1ukavJYNZk20yE_CX:-KN21NpCIYaCP9jocFuZ:1557095778) ([raw file](https://github.com/criteo/biggraphite/blob/8a9790b91fec4f762a58b075f836a4968a038842/biggraphite/drivers/downsampling.py#L56)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> Please confirm it is safe to call
> d.feed([4200, 0.0])
> d.feed([4000, 1.0])
> even though 4200 and 4000 will be out of order
</details>
Done in test_out_of_order

---

*[tests/test_drivers_downsampling.py, line 308 \[r4\]](https://reviewable.io:443/reviews/criteo/biggraphite/49#-KN1xkibJ3FZYpph5wr8:-KN202NQTupdQNQBvK0H:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/8a9790b91fec4f762a58b075f836a4968a038842/tests/test_drivers_downsampling.py#L308)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> please add a comment: "26 is 9 + 10 +7, sum of stage0 values"
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/49)*

**Comment by natbraun** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[biggraphite/drivers/downsampling.py, line 41 \[r3\]](https://reviewable.io:443/reviews/criteo/biggraphite/49#-KMySSoKy9VNR0nTtG91:-KN25IiXvYwFMny_Xy3k:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/e8918f853589f8a233e01a9a736701c2c7d68cd7/biggraphite/drivers/downsampling.py#L41)):*
<details><summary><i>Previously, natbraun (Nathaniel Braun) wrote…</i></summary>
> Done.
</details>
Done.

---

*[biggraphite/drivers/downsampling.py, line 51 \[r4\]](https://reviewable.io:443/reviews/criteo/biggraphite/49#-KN1uN98I-Ab6pfKiLGA:-KN25H9gxwxjeIE0VcuA:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/8a9790b91fec4f762a58b075f836a4968a038842/biggraphite/drivers/downsampling.py#L51)):*
<details><summary><i>Previously, natbraun (Nathaniel Braun) wrote…</i></summary>
> Done.
</details>
Done.

---

*[biggraphite/drivers/downsampling.py, line 56 \[r4\]](https://reviewable.io:443/reviews/criteo/biggraphite/49#-KN1ukavJYNZk20yE_CX:-KN25I9XszjASO6M_Rd6:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/8a9790b91fec4f762a58b075f836a4968a038842/biggraphite/drivers/downsampling.py#L56)):*
<details><summary><i>Previously, natbraun (Nathaniel Braun) wrote…</i></summary>
> Done in test_out_of_order
</details>
Done.

---

*[tests/test_drivers_downsampling.py, line 308 \[r4\]](https://reviewable.io:443/reviews/criteo/biggraphite/49#-KN1xkibJ3FZYpph5wr8:-KN25JnEA3LruAOH65aV:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/8a9790b91fec4f762a58b075f836a4968a038842/tests/test_drivers_downsampling.py#L308)):*
<details><summary><i>Previously, natbraun (Nathaniel Braun) wrote…</i></summary>
> Done.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/49)*

**Comment by unbrice** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[biggraphite/drivers/downsampling.py, line 56 \[r4\]](https://reviewable.io:443/reviews/criteo/biggraphite/49#-KN1ukavJYNZk20yE_CX:-KN28gc_V0ryW3L2vyoV:94699103) ([raw file](https://github.com/criteo/biggraphite/blob/8a9790b91fec4f762a58b075f836a4968a038842/biggraphite/drivers/downsampling.py#L56)):*
<details><summary><i>Previously, natbraun (Nathaniel Braun) wrote…</i></summary>
> Done.
</details>
Your test is a test of 
d.feed([(4200, 00), (4000, 1.0)]
I was refering to:
d.feed([(4200, 00)]
d.feed([(4000, 1.0)]

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/49)*

**Comment by natbraun** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[biggraphite/drivers/downsampling.py, line 56 \[r4\]](https://reviewable.io:443/reviews/criteo/biggraphite/49#-KN1ukavJYNZk20yE_CX:-KN2A9tWCQvUjq7ppMEE:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/8a9790b91fec4f762a58b075f836a4968a038842/biggraphite/drivers/downsampling.py#L56)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> Your test is a test of 
> d.feed([(4200, 00), (4000, 1.0)]
> I was refering to:
> d.feed([(4200, 00)]
> d.feed([(4000, 1.0)]
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/49)*

**Comment by unbrice** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/49)*

**Comment by unbrice** [comment]
Reviewed 1 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/49)*

**Pull request merged**
