### PR TITLE
Add a FakeAccessor and TestWithFakeAccessor

### PR DESCRIPTION
**Pull request by unbrice**
It can be used to write unit tests that run much faster than with a
local Cassandra.

---
This change is [Reviewable](https://reviewable.io/reviews/criteo/biggraphite/12)

### CODE REVIEW

**Comment by natbraun** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/12)*

**Comment by natbraun** [comment]
Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[biggraphite/test_utils.py, line 140 \[r3\]](https://reviewable.io:443/reviews/criteo/biggraphite/12#-KICWNRGQHxrhJHuUesk:-KICWNRGQHxrhJHuUesl:1091788320) ([raw file](https://github.com/criteo/biggraphite/blob/945bce5522deba06c9ff9c3f887134491c0a8a16/biggraphite/test_utils.py#L140)):*
> ```Python
>     def __glob_names(names, glob):
>         res = []
>         parts_count = glob.count(".")
> ```

Technically this is not a part count, but a dot count... (parts_count = dot_count _ 1)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/12)*

**Comment by natbraun** [comment]
Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/12)*

**Comment by unbrice** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[biggraphite/test_utils.py, line 140 \[r3\]](https://reviewable.io:443/reviews/criteo/biggraphite/12#-KICWNRGQHxrhJHuUesk:-KICaNF6DI78Gm5Wkq2i:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/945bce5522deba06c9ff9c3f887134491c0a8a16/biggraphite/test_utils.py#L140)):*
<details><summary><i>Previously, natbraun (Nathaniel Braun) wrote…</i></summary>
> Technically this is not a part count, but a dot count... (parts_count = dot_count _ 1)
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/12)*

**Comment by natbraun** [comment]
:lgtm:

<details><summary><i>Previously, coveralls wrote…</i></summary>
> 
> [Coverage Status](https://coveralls.io/builds/6261762)
> 
> Coverage increased (+0.4%) to 73.207% when pulling **945bce5522deba06c9ff9c3f887134491c0a8a16 on unbrice:master** into **0984ba4dbcfdc1661f7e0806dcce97cd02fc59ab on criteo:master**.
> 
</details>


---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/12#-:-KICaloJRDfUXMBVocQV:1417088721)*

**Pull request merged**
