### PR TITLE
Fix carbon plugin "average" aggregation

### PR DESCRIPTION
**Pull request by unbrice**
Spelling "avg" should have been "average"

---
This change is [Reviewable](https://reviewable.io/reviews/criteo/biggraphite/72)

### CODE REVIEW

**Comment by unbrice** [comment]
+@wdauchy please have a look, could be a good opportunity to dive in the project ( -@natbraun  to balance)

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/72#-:-KO7SLu0f1vHWzEll3Re:1470574850)*

**Comment by wdauchy** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/72)*

**Comment by wdauchy** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/72#-:-KOPVC093g8_iSuDAlmb:bnfp4nl)*

**Comment by natbraun** [comment]
Thanks for merging guys!

**Pull request merged**
