### PR TITLE
Fix command line parsing

### PR DESCRIPTION
**Pull request by erebe**
+ Consistent argument parsing and syntax with whatever argument number

---
This change is [Reviewable](https://reviewable.io/reviews/criteo/biggraphite/228)

### CODE REVIEW

**Comment by iksaif** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[biggraphite/drivers/cassandra.py, line 112 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/228#-KabnDaLPEoRLZh5cpVm:-KabnDaLPEoRLZh5cpVn:bmpfu7j) ([raw file](https://github.com/criteo/biggraphite/blob/72d235e34d0821242a9ff5e6b3a9c7c15e72362e/biggraphite/drivers/cassandra.py#L112)):*
> ```Python
>         default=DEFAULT_KEYSPACE)
>     parser.add_argument(
>         "--cassandra_contact_points", metavar="HOST[,HOST,...]",
> ```

maybe add =localhost,localhost to one of the unittests to validate that it works :) 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/228)*

**Comment by iksaif** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/test_command_test.py, line 45 at r2](https://reviewable.io:443/reviews/criteo/biggraphite/228#-KafmMt0ylOAO75DgSB9:-KafmMt0ylOAO75DgSBA:b-ak251m) ([raw file](https://github.com/criteo/biggraphite/blob/6625493d97d3fa6ca9a05cba16ac20e8829ae7e8/tests/test_command_test.py#L45)):*
> ```Python
>                                   "--cassandra_contact_points_metadata=127.0.0.1,192.168.1.1"])
>         settings = bg_utils.settings_from_args(opts)
>         assert isinstance(settings['cassandra_contact_points'], list)
> ```

self.assertIsInstance(a, b)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/228)*

**Comment by erebe** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/test_command_test.py, line 45 at r2](https://reviewable.io:443/reviews/criteo/biggraphite/228#-KafmMt0ylOAO75DgSB9:-KafrgmZUpDKSAOksPZQ:b-896fix) ([raw file](https://github.com/criteo/biggraphite/blob/6625493d97d3fa6ca9a05cba16ac20e8829ae7e8/tests/test_command_test.py#L45)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary><blockquote>

self.assertIsInstance(a, b)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/228)*

**Comment by erebe** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[biggraphite/drivers/cassandra.py, line 112 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/228#-KabnDaLPEoRLZh5cpVm:-Kafrk45JMJ2u8RXFpgX:b-896fix) ([raw file](https://github.com/criteo/biggraphite/blob/72d235e34d0821242a9ff5e6b3a9c7c15e72362e/biggraphite/drivers/cassandra.py#L112)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary><blockquote>

maybe add =localhost,localhost to one of the unittests to validate that it works :) 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/228)*

**Comment by iksaif** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/228#-:-KafxVtaRDCwBzE2E8_T:bnfp4nl)*

**Pull request merged**
