### PR TITLE
Shift offset by two bytes

### PR DESCRIPTION
**Pull request by natbraun**
This change is [Reviewable](https://reviewable.io/reviews/criteo/biggraphite/120)

### CODE REVIEW

**Comment by iksaif** [comment]
Please add a etter  PR description

---

Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[biggraphite/accessor.py, line 743 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/120#-KRZsLRH_dQ7sJoD-LOw:-KRZsLRH_dQ7sJoD-LOx:b9p4kg7) ([raw file](https://github.com/criteo/biggraphite/blob/c2b45156c3f8bfb774fb54ee45705b44c1a79669/biggraphite/accessor.py#L743)):*
> ```Python
>                  stage,
>                  query_results,
>                  offset_bit_shift=0):
> ```

do not pass this as a parameter, this is an implementation detail of the driver. For now just make it so that the PointGroupper received the correct offset in query_results.

---

*[biggraphite/drivers/cassandra.py, line 36 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/120#-KRZs_OCLvKZQBmt0XUu:-KRZs_OCLvKZQBmt0XUv:b-bski9d) ([raw file](https://github.com/criteo/biggraphite/blob/c2b45156c3f8bfb774fb54ee45705b44c1a79669/biggraphite/drivers/cassandra.py#L36)):*
> ```Python
> 
> # the offset is shifted when stored in C*
> _OFFSET_BIT_SHIFT = 16
> ```

Create offset_mangle(), offset_demangle() functions instead in `accessor.py` and allow the driver to override these.

---

*[biggraphite/drivers/cassandra.py, line 75 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/120#-KRZsfLi5fL9Hb4I7c1g:-KRZsfLi5fL9Hb4I7c1h:b8rbhkg) ([raw file](https://github.com/criteo/biggraphite/blob/c2b45156c3f8bfb774fb54ee45705b44c1a79669/biggraphite/drivers/cassandra.py#L75)):*
> ```Python
> # the datatable.
> # We store 1000 seconds per row
> _ROW_SIZE_MS = 1000 * 1000
> ```

No, we do not store 1000 seconds per row.

---

*[biggraphite/drivers/cassandra.py, line 160 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/120#-KRZsoh2BaMEsgR4dtxS:-KRZsoh2BaMEsgR4dtxT:bajthv) ([raw file](https://github.com/criteo/biggraphite/blob/c2b45156c3f8bfb774fb54ee45705b44c1a79669/biggraphite/drivers/cassandra.py#L160)):*
> ```Python
> }
> ```

do not remove this function.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/120#-:-KRZsBEJgrQ9KIWd7Y8h:bsuk9lt)*

**Comment by iksaif** [comment]
Once fixed, please also add tests :)

---

Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/120#-:-KRZuHJY-Uw4A5LXpN0j:b-6xh3dg)*

**Comment by iksaif** [comment]
Review status: 0 of 2 files reviewed at latest revision, 7 unresolved discussions.

---

*[biggraphite/drivers/cassandra.py, line 454 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/120#-KRbrvZjiIg9TyRtL9it:-KRbrvZjiIg9TyRtL9iu:b-85jq1v) ([raw file](https://github.com/criteo/biggraphite/blob/c2b45156c3f8bfb774fb54ee45705b44c1a79669/biggraphite/drivers/cassandra.py#L454)):*
> ```Python
>             concurrency=self.__concurrency,
>             results_generator=True,
>         )
> ```

def extract_results():
  for bla in query_results:
     bla.offset <<= 2
     yield bla
query_results = extract_results()

---

*[biggraphite/drivers/cassandra.py, line 479 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/120#-KRbvtUwgiNalmc0ly0_:-KRbvtUwgiNalmc0ly0a:bb6oi0o) ([raw file](https://github.com/criteo/biggraphite/blob/183f02dc3d5b31b3aab6fe68162b95c30d7e4ab3/biggraphite/drivers/cassandra.py#L479)):*
> ```Python
>         # xrange(a,b) does not contain b, so we use last_row+1
>         for row_start_ms in xrange(first_row, last_row + 1, _row_size_ms(stage)):
>             row_min_offset_ms = -1  # Selects all FIXME
> ```

= 0 

---

*[biggraphite/drivers/cassandra.py, line 480 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/120#-KRbvhcwlf4F5wsTljIa:-KRbvhcxHNf_ha1eC4-7:b-ayzy33) ([raw file](https://github.com/criteo/biggraphite/blob/183f02dc3d5b31b3aab6fe68162b95c30d7e4ab3/biggraphite/drivers/cassandra.py#L480)):*
> ```Python
>         for row_start_ms in xrange(first_row, last_row + 1, _row_size_ms(stage)):
>             row_min_offset_ms = -1  # Selects all FIXME
>             row_max_offset_ms = stage.duration_ms  # Selects all
> ```

stage.step_ms(row_size_ms(stage))

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/120)*

**Comment by iksaif** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[biggraphite/drivers/cassandra.py, line 36 at r2](https://reviewable.io:443/reviews/criteo/biggraphite/120#-KRcgcba9MWPp-h0tXlH:-KRcgcba9MWPp-h0tXlI:buu1x9m) ([raw file](https://github.com/criteo/biggraphite/blob/e43dd964fc19ce736181076b3bab0840969e2f73/biggraphite/drivers/cassandra.py#L36)):*
> ```Python
> 
> # the offset is shifted when stored in C*
> _OFFSET_SHIFT = 16
> ```

Explain why it's fine to use the two higher bytes and why we want to do it. (Because we have less than 50k values, and because we want to use the other bytes to have multiple writers for the same metric and use these bytes for multiplexing)

---

*[biggraphite/drivers/cassandra.py, line 611 at r2](https://reviewable.io:443/reviews/criteo/biggraphite/120#-KRcgX0pPuswnhWtQdbm:-KRcgX0qOWZoONk4v-cI:b-1gd9ff) ([raw file](https://github.com/criteo/biggraphite/blob/e43dd964fc19ce736181076b3bab0840969e2f73/biggraphite/drivers/cassandra.py#L611)):*
> ```Python
>             time_offset_ms = timestamp_ms % _row_size_ms(stage)
>             time_start_ms = timestamp_ms - time_offset_ms
>             # shift offset left (see #116)
> ```

Remove comment here, and explain why we do it near _OFFSET_SHIFT.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/120)*

**Comment by natbraun** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[biggraphite/accessor.py, line 743 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/120#-KRZsLRH_dQ7sJoD-LOw:-KRchyaiKGXadYuCoF7V:b-896fix) ([raw file](https://github.com/criteo/biggraphite/blob/c2b45156c3f8bfb774fb54ee45705b44c1a79669/biggraphite/accessor.py#L743)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> do not pass this as a parameter, this is an implementation detail of the driver. For now just make it so that the PointGroupper received the correct offset in query_results.
</details>
Done.

---

*[biggraphite/drivers/cassandra.py, line 160 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/120#-KRZsoh2BaMEsgR4dtxS:-KRc20pMxWexse8X_lbC:b-896fix) ([raw file](https://github.com/criteo/biggraphite/blob/c2b45156c3f8bfb774fb54ee45705b44c1a79669/biggraphite/drivers/cassandra.py#L160)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> do not remove this function.
</details>
Done.

---

*[biggraphite/drivers/cassandra.py, line 479 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/120#-KRbvtUwgiNalmc0ly0_:-KRc2O97T42TMMn9yA8h:b-896fix) ([raw file](https://github.com/criteo/biggraphite/blob/183f02dc3d5b31b3aab6fe68162b95c30d7e4ab3/biggraphite/drivers/cassandra.py#L479)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> = 0 
</details>
Done.

---

*[biggraphite/drivers/cassandra.py, line 36 at r2](https://reviewable.io:443/reviews/criteo/biggraphite/120#-KRcgcba9MWPp-h0tXlH:-KRchz6ofu-scLsj6Via:b-896fix) ([raw file](https://github.com/criteo/biggraphite/blob/e43dd964fc19ce736181076b3bab0840969e2f73/biggraphite/drivers/cassandra.py#L36)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> Explain why it's fine to use the two higher bytes and why we want to do it. (Because we have less than 50k values, and because we want to use the other bytes to have multiple writers for the same metric and use these bytes for multiplexing)
</details>
Done.

---

*[biggraphite/drivers/cassandra.py, line 611 at r2](https://reviewable.io:443/reviews/criteo/biggraphite/120#-KRcgX0pPuswnhWtQdbm:-KRciEBPy_y0HBSrTThZ:b-896fix) ([raw file](https://github.com/criteo/biggraphite/blob/e43dd964fc19ce736181076b3bab0840969e2f73/biggraphite/drivers/cassandra.py#L611)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> Remove comment here, and explain why we do it near _OFFSET_SHIFT.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/120)*

**Comment by iksaif** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[biggraphite/drivers/cassandra.py, line 35 at r3](https://reviewable.io:443/reviews/criteo/biggraphite/120#-KRcrV6AUejICaCqsJ7j:-KRcrV6AUejICaCqsJ7k:b-1ejock) ([raw file](https://github.com/criteo/biggraphite/blob/1aa7ef0c75bff8dc6fe84f0799f05125f01b39d9/biggraphite/drivers/cassandra.py#L35)):*
> ```Python
> from biggraphite.drivers import _utils
> 
> # The offset is a Cassandra int (4 bytes) and is shifter by two bytes.
> ```

shifted

---

*[biggraphite/drivers/cassandra.py, line 38 at r3](https://reviewable.io:443/reviews/criteo/biggraphite/120#-KRcrZ_wjXEYth8RJW7i:-KRcrZ_wjXEYth8RJW7j:b-q5z8j9) ([raw file](https://github.com/criteo/biggraphite/blob/1aa7ef0c75bff8dc6fe84f0799f05125f01b39d9/biggraphite/drivers/cassandra.py#L38)):*
> ```Python
> # We want to use the lower two bytes to have multiple writers for the same metric,
> # and use these bytes for multiplexing.
> # This is possible because we have less than 50K values.
> ```

50k cells per partition.

---

*[biggraphite/drivers/cassandra.py, line 614 at r3](https://reviewable.io:443/reviews/criteo/biggraphite/120#-KRcrnZyvQ_8Qw-pna1Z:-KRcrnZyvQ_8Qw-pna1_:bteyq8k) ([raw file](https://github.com/criteo/biggraphite/blob/1aa7ef0c75bff8dc6fe84f0799f05125f01b39d9/biggraphite/drivers/cassandra.py#L614)):*
> ```Python
>             time_offset_ms = timestamp_ms % _row_size_ms(stage)
>             time_start_ms = timestamp_ms - time_offset_ms
>             offset = stage.step_ms(time_offset_ms) << _OFFSET_SHIFT
> ```

since you do the reverse in 'prepare_select' I would do that in 'prepare insert'

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/120)*

**Comment by iksaif** [comment]
:lgtm_strong: 

---

Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/120#-:-KRcsYoR6grVqABVFt74:b-uwkowd)*

**Comment by natbraun** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[biggraphite/drivers/cassandra.py, line 35 at r3](https://reviewable.io:443/reviews/criteo/biggraphite/120#-KRcrV6AUejICaCqsJ7j:-KRctrt_Qwt7kYZ9X0W-:b-896fix) ([raw file](https://github.com/criteo/biggraphite/blob/1aa7ef0c75bff8dc6fe84f0799f05125f01b39d9/biggraphite/drivers/cassandra.py#L35)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> shifted
</details>
Done.

---

*[biggraphite/drivers/cassandra.py, line 38 at r3](https://reviewable.io:443/reviews/criteo/biggraphite/120#-KRcrZ_wjXEYth8RJW7i:-KRcts993CviCh5U0YrO:b-896fix) ([raw file](https://github.com/criteo/biggraphite/blob/1aa7ef0c75bff8dc6fe84f0799f05125f01b39d9/biggraphite/drivers/cassandra.py#L38)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> 50k cells per partition.
</details>
Done.

---

*[biggraphite/drivers/cassandra.py, line 614 at r3](https://reviewable.io:443/reviews/criteo/biggraphite/120#-KRcrnZyvQ_8Qw-pna1Z:-KRcttV1ho8eAmyKbNGf:b-896fix) ([raw file](https://github.com/criteo/biggraphite/blob/1aa7ef0c75bff8dc6fe84f0799f05125f01b39d9/biggraphite/drivers/cassandra.py#L614)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> since you do the reverse in 'prepare_select' I would do that in 'prepare insert'
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/120)*

**Pull request merged**
