### PR TITLE
plugins/graphite: support carbon protocol

### PR DESCRIPTION
**Pull request by Thib17**
issue #97

---
This change is [Reviewable](https://reviewable.io/reviews/criteo/biggraphite/246)

### CODE REVIEW

**Comment by iksaif** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[biggraphite/plugins/graphite.py, line 26 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/246#-Kd5e2QPnHEeSjus02b9:-Kd5e2QQ-Jyk9JFAWDO1:b-da9q0l) ([raw file](https://github.com/criteo/biggraphite/blob/09756e0974524cd71571e5ba0bd90e2afe785f60/biggraphite/plugins/graphite.py#L26)):*
> ```Python
> from graphite.logger import log
> from graphite.render import hashing
> from graphite.carbonlink import CarbonLink
> ```

we import only modules:

from graphite import carbonlink

---

*[biggraphite/plugins/graphite.py, line 103 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/246#-Kd5eHzCyzH4she9D_hS:-Kd5eHzDxXtnPkel98Gr:b3ppczg) ([raw file](https://github.com/criteo/biggraphite/blob/09756e0974524cd71571e5ba0bd90e2afe785f60/biggraphite/plugins/graphite.py#L103)):*
> ```Python
>                 self._metric, start_time, end_time, stage)
> 
>         cached_datapoints = []
> ```

Set to None instead

---

*[biggraphite/plugins/graphite.py, line 123 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/246#-Kd5eNI8gy9KNlkmhkWv:-Kd5eNI8gy9KNlkmhkWw:be9avof) ([raw file](https://github.com/criteo/biggraphite/blob/09756e0974524cd71571e5ba0bd90e2afe785f60/biggraphite/plugins/graphite.py#L123)):*
> ```Python
>                 points[index] = point
> 
>             for (timestamp, value) in cached_datapoints:
> ```

can you put that in a separate function ? _merge_cached_points() or similar

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/246)*

**Comment by Thib17** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[biggraphite/plugins/graphite.py, line 26 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/246#-Kd5e2QPnHEeSjus02b9:-Kd63RVxINpSBB_fQ-E-:b-896fix) ([raw file](https://github.com/criteo/biggraphite/blob/09756e0974524cd71571e5ba0bd90e2afe785f60/biggraphite/plugins/graphite.py#L26)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary><blockquote>

we import only modules:

from graphite import carbonlink
</blockquote></details>

Done.

---

*[biggraphite/plugins/graphite.py, line 103 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/246#-Kd5eHzCyzH4she9D_hS:-Kd628kYT1A3x-j0pkDo:b-896fix) ([raw file](https://github.com/criteo/biggraphite/blob/09756e0974524cd71571e5ba0bd90e2afe785f60/biggraphite/plugins/graphite.py#L103)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary><blockquote>

Set to None instead
</blockquote></details>

Done.

---

*[biggraphite/plugins/graphite.py, line 123 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/246#-Kd5eNI8gy9KNlkmhkWv:-Kd623ZFGX_70wMbSsTz:b-896fix) ([raw file](https://github.com/criteo/biggraphite/blob/09756e0974524cd71571e5ba0bd90e2afe785f60/biggraphite/plugins/graphite.py#L123)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary><blockquote>

can you put that in a separate function ? _merge_cached_points() or similar
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/246)*

**Comment by iksaif** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[biggraphite/plugins/graphite.py, line 111 at r2](https://reviewable.io:443/reviews/criteo/biggraphite/246#-Kd6U20UhfZBJsbmWSgm:-Kd6U20UhfZBJsbmWSgn:b-1pbjn) ([raw file](https://github.com/criteo/biggraphite/blob/7b202bd02cc4985f4b3779c4113e6822291588f8/biggraphite/plugins/graphite.py#L111)):*
> ```Python
>             cached_datapoints = []
> 
>         if isinstance(cached_datapoints, dict):
> ```

you can remove that

---

*[biggraphite/plugins/graphite.py, line 123 at r2](https://reviewable.io:443/reviews/criteo/biggraphite/246#-Kd6U5hIH8rUpUJyau1E:-Kd6U5hIH8rUpUJyau1F:b-hnx11o) ([raw file](https://github.com/criteo/biggraphite/blob/7b202bd02cc4985f4b3779c4113e6822291588f8/biggraphite/plugins/graphite.py#L123)):*
> ```Python
>                 points[index] = point
> 
>             points = _merge_cached_points(points)
> ```

if cached_datapoints:
  points =  _merge_cached_points(points)

---

*[biggraphite/plugins/graphite.py, line 136 at r2](https://reviewable.io:443/reviews/criteo/biggraphite/246#-Kd6UCAnxf-rr8wpdma5:-Kd6UCAnxf-rr8wpdma6:b121pko) ([raw file](https://github.com/criteo/biggraphite/blob/7b202bd02cc4985f4b3779c4113e6822291588f8/biggraphite/plugins/graphite.py#L136)):*
> ```Python
>                 return points
> 
>             for (timestamp, value) in cached_datapoints:
> ```

cached_datapoints.items()

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/246)*

**Comment by Thib17** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[biggraphite/plugins/graphite.py, line 111 at r2](https://reviewable.io:443/reviews/criteo/biggraphite/246#-Kd6U20UhfZBJsbmWSgm:-KdAOg2bUKGcPql5JMzp:b-896fix) ([raw file](https://github.com/criteo/biggraphite/blob/7b202bd02cc4985f4b3779c4113e6822291588f8/biggraphite/plugins/graphite.py#L111)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary><blockquote>

you can remove that
</blockquote></details>

Done.

---

*[biggraphite/plugins/graphite.py, line 123 at r2](https://reviewable.io:443/reviews/criteo/biggraphite/246#-Kd6U5hIH8rUpUJyau1E:-KdAFqG1XfqFCY1-Ehpb:b-896fix) ([raw file](https://github.com/criteo/biggraphite/blob/7b202bd02cc4985f4b3779c4113e6822291588f8/biggraphite/plugins/graphite.py#L123)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary><blockquote>

if cached_datapoints:
  points =  _merge_cached_points(points)
</blockquote></details>

Done.

---

*[biggraphite/plugins/graphite.py, line 136 at r2](https://reviewable.io:443/reviews/criteo/biggraphite/246#-Kd6UCAnxf-rr8wpdma5:-KdAFf3MYsGjrKoiivk3:b67upxh) ([raw file](https://github.com/criteo/biggraphite/blob/7b202bd02cc4985f4b3779c4113e6822291588f8/biggraphite/plugins/graphite.py#L136)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary><blockquote>

cached_datapoints.items()
</blockquote></details>

I check and cached_datapoints is a list. I don't know why they could get a dict in graphite.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/246)*

**Comment by iksaif** [comment]
:lgtm_strong: 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/246#-:-KdAQCa0Xb3wbRGNpj-9:b-uwkowd)*

**Pull request merged**
