### PR TITLE
Implement circular buffer for downsampling

### PR DESCRIPTION
**Pull request by natbraun**
This change is [Reviewable](https://reviewable.io/reviews/criteo/biggraphite/44)

### CODE REVIEW

**Comment by iksaif** [comment]
Review status: 0 of 2 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[biggraphite/drivers/_downsampling.py, line 1 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/44#-KM4MAhbYnCi655kA3z-:-KM4MAhcKqCXwY7nY9EU:469321176) ([raw file](https://github.com/criteo/biggraphite/blob/69492419a4a990326d549af97b5725d0dc7f8b8e/biggraphite/drivers/_downsampling.py#L1)):*
> ```Python
> #!/usr/bin/env python
> ```

name this file simply 'downsampling.py'

---

*[biggraphite/drivers/_downsampling.py, line 36 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/44#-KM4MIuEO5kVRpPLcp0k:-KM4MIuEO5kVRpPLcp0l:1938259955) ([raw file](https://github.com/criteo/biggraphite/blob/69492419a4a990326d549af97b5725d0dc7f8b8e/biggraphite/drivers/_downsampling.py#L36)):*
> ```Python
>     )
> 
>     def __init__(self, precision, count):
> ```

can you add default value for count/capacity ?

---

*[biggraphite/drivers/_downsampling.py, line 45 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/44#-KM4Ls42Izf8xepA1TAa:-KM4Ls42Izf8xepA1TAb:2085041224) ([raw file](https://github.com/criteo/biggraphite/blob/69492419a4a990326d549af97b5725d0dc7f8b8e/biggraphite/drivers/_downsampling.py#L45)):*
> ```Python
>         """
>         self.precision = precision
>         self._count = count
> ```

this is more 'capacity' than 'count'

---

*[biggraphite/drivers/_downsampling.py, line 62 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/44#-KM4LSnDwK27emKhfufI:-KM4LSnEYrM2uXXX-jqy:838614671) ([raw file](https://github.com/criteo/biggraphite/blob/69492419a4a990326d549af97b5725d0dc7f8b8e/biggraphite/drivers/_downsampling.py#L62)):*
> ```Python
>         res = []
>         epoch = timestamp // self.precision
>         for t in xrange(self._epoch - (self._count - 1), epoch):
> ```

can you use temporary variables named epoch_start and epoch_end and use that in xrange() ?

---

*[biggraphite/drivers/_downsampling.py, line 82 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/44#-KM4LdjOHosv-Wnz4OTq:-KM4LdjOHosv-Wnz4OTr:-918964232) ([raw file](https://github.com/criteo/biggraphite/blob/69492419a4a990326d549af97b5725d0dc7f8b8e/biggraphite/drivers/_downsampling.py#L82)):*
> ```Python
>             return None
>         epoch = timestamp // self.precision
>         if epoch > self._epoch - self._count and epoch <= self._epoch:
> ```

same here, can you define epoch_start and epoch_end to make it easier to understand :)

---

*[tests/test_drivers_downsampling.py, line 24 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/44#-KM4NgCMvzc1z9bnWUHz:-KM4NgCMvzc1z9bnWUI-:1654937128) ([raw file](https://github.com/criteo/biggraphite/blob/69492419a4a990326d549af97b5725d0dc7f8b8e/tests/test_drivers_downsampling.py#L24)):*
> ```Python
> from biggraphite.drivers import _downsampling as bg_ds
> 
> class TestDownsampling2(unittest.TestCase):
> ```

TestMetricBuffer()

---

*[tests/test_drivers_downsampling.py, line 26 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/44#-KM4NV0A3nmDuPnnMwu6:-KM4NV0A3nmDuPnnMwu7:-2064655001) ([raw file](https://github.com/criteo/biggraphite/blob/69492419a4a990326d549af97b5725d0dc7f8b8e/tests/test_drivers_downsampling.py#L26)):*
> ```Python
> class TestDownsampling2(unittest.TestCase):
>     def setUp(self):
>         self.md = bg_ds.MetricData(60, 10)
> ```

maybe put 60 in PRECISION or something and reuse it where it makes sense 

---

*[tests/test_drivers_downsampling.py, line 28 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/44#-KM4NN1z3EP8VZ7_AUrt:-KM4NN1z3EP8VZ7_AUru:-1884722609) ([raw file](https://github.com/criteo/biggraphite/blob/69492419a4a990326d549af97b5725d0dc7f8b8e/tests/test_drivers_downsampling.py#L28)):*
> ```Python
>         self.md = bg_ds.MetricData(60, 10)
> 
>     def test_put_simple(self):
> ```

can you add a docstring to each test explaining what they tests and some comments in the code explaining why we expect that ?

---

*[tests/test_drivers_downsampling.py, line 32 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/44#-KM4MhQ43YuU6FgKs0it:-KM4MhQ43YuU6FgKs0iu:1802339405) ([raw file](https://github.com/criteo/biggraphite/blob/69492419a4a990326d549af97b5725d0dc7f8b8e/tests/test_drivers_downsampling.py#L32)):*
> ```Python
>         self.assertEqual([], self.md.put(10, 1))
>         self.assertEqual([], self.md.put(59, 2))
>         self.assertEqual(0, self.md._epoch)
> ```

can you add an accessor for epoch  ? (http://www.programiz.com/python-programming/property)

---

*[tests/test_drivers_downsampling.py, line 38 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/44#-KM4Mz0vizoLAyPlhiZJ:-KM4Mz0vizoLAyPlhiZK:-1842002225) ([raw file](https://github.com/criteo/biggraphite/blob/69492419a4a990326d549af97b5725d0dc7f8b8e/tests/test_drivers_downsampling.py#L38)):*
> ```Python
>             self.md.put(i * 60, i * 100)
>             self.assertEqual(i, self.md._epoch)
>         self.assertEqual([i * 100 for i in xrange(0, 10)], self.md._buffer)
> ```

put into 'expected_results' [i * 100 for i in xrange(0, 10)]

---

*[tests/test_drivers_downsampling.py, line 62 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/44#-KM4NiZRBr-ECnKBXswQ:-KM4NiZRBr-ECnKBXswR:2074540889) ([raw file](https://github.com/criteo/biggraphite/blob/69492419a4a990326d549af97b5725d0dc7f8b8e/tests/test_drivers_downsampling.py#L62)):*
> ```Python
>         self.assertEqual([(300, 500)], self.md.pop_expired(6 * 60))
>         self.assertEqual([], self.md.pop_expired(6 * 60))
> ```

please add two tests:

- check that adding one point in the past doesn't do anything
- test that adding one point far in the future removes everything and puts only this point

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/44)*

**Comment by natbraun** [comment]
*[tests/test_drivers_downsampling.py, line 62 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/44#-KM4NiZRBr-ECnKBXswQ:-KM4Qz8CjTHfTXYH0I6o:-1913959996) ([raw file](https://github.com/criteo/biggraphite/blob/69492419a4a990326d549af97b5725d0dc7f8b8e/tests/test_drivers_downsampling.py#L62)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> please add two tests:
> 
> - check that adding one point in the past doesn't do anything
> - test that adding one point far in the future removes everything and puts only this point
> 
</details>
Actually, adding a point in the past can work, if it's not too long before the most recent point.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/44)*

**Comment by iksaif** [comment]
Review status: 0 of 2 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[tests/test_drivers_downsampling.py, line 62 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/44#-KM4NiZRBr-ECnKBXswQ:-KM4ZVcNLRHRlormMJWN:959719133) ([raw file](https://github.com/criteo/biggraphite/blob/69492419a4a990326d549af97b5725d0dc7f8b8e/tests/test_drivers_downsampling.py#L62)):*
<details><summary><i>Previously, natbraun (Nathaniel Braun) wrote…</i></summary>
> Actually, adding a point in the past can work, if it's not too long before the most recent point.
</details>
I meant that, add a point far in the past

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/44)*

**Comment by natbraun** [comment]
Review status: 0 of 2 files reviewed at latest revision, 11 unresolved discussions.

---

*[tests/test_drivers_downsampling.py, line 24 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/44#-KM4NgCMvzc1z9bnWUHz:-KM4TEfVexcPhyISZpYO:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/69492419a4a990326d549af97b5725d0dc7f8b8e/tests/test_drivers_downsampling.py#L24)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> TestMetricBuffer()
</details>
Done.

---

*[tests/test_drivers_downsampling.py, line 26 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/44#-KM4NV0A3nmDuPnnMwu6:-KM4UHq0St4nVKYtl_hZ:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/69492419a4a990326d549af97b5725d0dc7f8b8e/tests/test_drivers_downsampling.py#L26)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> maybe put 60 in PRECISION or something and reuse it where it makes sense 
</details>
Done.

---

*[tests/test_drivers_downsampling.py, line 28 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/44#-KM4NN1z3EP8VZ7_AUrt:-KM4_HMGxDFq69Zo2Tyo:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/69492419a4a990326d549af97b5725d0dc7f8b8e/tests/test_drivers_downsampling.py#L28)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> can you add a docstring to each test explaining what they tests and some comments in the code explaining why we expect that ?
</details>
Done.

---

*[tests/test_drivers_downsampling.py, line 32 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/44#-KM4MhQ43YuU6FgKs0it:-KM4Z8OjTDKd1voyW_uS:-779448248) ([raw file](https://github.com/criteo/biggraphite/blob/69492419a4a990326d549af97b5725d0dc7f8b8e/tests/test_drivers_downsampling.py#L32)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> can you add an accessor for epoch  ? (http://www.programiz.com/python-programming/property)
</details>
This is an implementation details, and IMO is useful only in tests.

---

*[tests/test_drivers_downsampling.py, line 38 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/44#-KM4Mz0vizoLAyPlhiZJ:-KM4QgF3R0p69l45jmrb:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/69492419a4a990326d549af97b5725d0dc7f8b8e/tests/test_drivers_downsampling.py#L38)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> put into 'expected_results' [i * 100 for i in xrange(0, 10)]
</details>
Done.

---

*[tests/test_drivers_downsampling.py, line 62 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/44#-KM4NiZRBr-ECnKBXswQ:-KM4Z78TgN4AfzKRgJnW:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/69492419a4a990326d549af97b5725d0dc7f8b8e/tests/test_drivers_downsampling.py#L62)):*
<details><summary><i>Previously, natbraun (Nathaniel Braun) wrote…</i></summary>
> Actually, adding a point in the past can work, if it's not too long before the most recent point.
</details>
Done.

---

*[biggraphite/drivers/_downsampling.py, line 1 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/44#-KM4MAhbYnCi655kA3z-:-KM4O98u1JoMapUiHIcM:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/69492419a4a990326d549af97b5725d0dc7f8b8e/biggraphite/drivers/_downsampling.py#L1)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> name this file simply 'downsampling.py'
</details>
Done.

---

*[biggraphite/drivers/_downsampling.py, line 36 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/44#-KM4MIuEO5kVRpPLcp0k:-KM4OGtImT5UpTZiIHLZ:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/69492419a4a990326d549af97b5725d0dc7f8b8e/biggraphite/drivers/_downsampling.py#L36)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> can you add default value for count/capacity ?
</details>
Done.

---

*[biggraphite/drivers/_downsampling.py, line 45 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/44#-KM4Ls42Izf8xepA1TAa:-KM4OSPJZHLX0dQ7wkd4:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/69492419a4a990326d549af97b5725d0dc7f8b8e/biggraphite/drivers/_downsampling.py#L45)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> this is more 'capacity' than 'count'
</details>
Done.

---

*[biggraphite/drivers/_downsampling.py, line 62 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/44#-KM4LSnDwK27emKhfufI:-KM4OeGaVLgQBUzZy_bR:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/69492419a4a990326d549af97b5725d0dc7f8b8e/biggraphite/drivers/_downsampling.py#L62)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> can you use temporary variables named epoch_start and epoch_end and use that in xrange() ?
</details>
Done.

---

*[biggraphite/drivers/_downsampling.py, line 82 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/44#-KM4LdjOHosv-Wnz4OTq:-KM4OzOzPvDY8bbVHBI0:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/69492419a4a990326d549af97b5725d0dc7f8b8e/biggraphite/drivers/_downsampling.py#L82)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> same here, can you define epoch_start and epoch_end to make it easier to understand :)
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/44)*

**Comment by natbraun** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/44)*

**Comment by iksaif** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[biggraphite/drivers/downsampling.py, line 102 \[r3\]](https://reviewable.io:443/reviews/criteo/biggraphite/44#-KM4oRqJtqYiQF9DQYyd:-KM4oRqJtqYiQF9DQYye:999444784) ([raw file](https://github.com/criteo/biggraphite/blob/77f4da332cb2a096b549b83aec8963e053d58c48/biggraphite/drivers/downsampling.py#L102)):*
> ```Python
>         if epoch > self._epoch:
>             self._epoch = epoch
>         return expired
> ```

I just realized that to get the second task working you'll also need to have a function that returns the list of 'temporary points' (in order to aggregate them later)

---

*[tests/test_drivers_downsampling.py, line 23 \[r3\]](https://reviewable.io:443/reviews/criteo/biggraphite/44#-KM4ocSCZsHulty8F0p6:-KM4ocSDImbJx4CquC7J:-1357636379) ([raw file](https://github.com/criteo/biggraphite/blob/77f4da332cb2a096b549b83aec8963e053d58c48/tests/test_drivers_downsampling.py#L23)):*
> ```Python
> from biggraphite.drivers import downsampling as bg_ds
> 
> PRECISION = 60
> ```

if you're not going to use these in other tests consider putting that in TestMetricBuffer

class TestMetricBuffer():
   BLA = 1

---

*[tests/test_drivers_downsampling.py, line 49 \[r3\]](https://reviewable.io:443/reviews/criteo/biggraphite/44#-KM4ovY0RkWO3p8CVCTZ:-KM4ovY0RkWO3p8CVCT_:1613936967) ([raw file](https://github.com/criteo/biggraphite/blob/77f4da332cb2a096b549b83aec8963e053d58c48/tests/test_drivers_downsampling.py#L49)):*
> ```Python
>         # this point in the past does not fit in the buffer, so it must be discarded
>         timestamp_past = - 5 * CAPACITY * PRECISION
>         self.assertEqual([], self.mb.put(timestamp_past, -1))
> ```

negative values may not be something really representative. What about setting the epoch to 1245 and inserting something at 30

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/44)*

**Comment by natbraun** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[biggraphite/drivers/downsampling.py, line 102 \[r3\]](https://reviewable.io:443/reviews/criteo/biggraphite/44#-KM4oRqJtqYiQF9DQYyd:-KM4wJ4Az7cRkiJEFR3B:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/77f4da332cb2a096b549b83aec8963e053d58c48/biggraphite/drivers/downsampling.py#L102)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> I just realized that to get the second task working you'll also need to have a function that returns the list of 'temporary points' (in order to aggregate them later)
</details>
Done.

---

*[tests/test_drivers_downsampling.py, line 23 \[r3\]](https://reviewable.io:443/reviews/criteo/biggraphite/44#-KM4ocSCZsHulty8F0p6:-KM4pZfWAI50wAkwI6Vk:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/77f4da332cb2a096b549b83aec8963e053d58c48/tests/test_drivers_downsampling.py#L23)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> if you're not going to use these in other tests consider putting that in TestMetricBuffer
> 
> class TestMetricBuffer():
>    BLA = 1
</details>
Done.

---

*[tests/test_drivers_downsampling.py, line 49 \[r3\]](https://reviewable.io:443/reviews/criteo/biggraphite/44#-KM4ovY0RkWO3p8CVCTZ:-KM4wGS6BukAyipLiiRh:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/77f4da332cb2a096b549b83aec8963e053d58c48/tests/test_drivers_downsampling.py#L49)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> negative values may not be something really representative. What about setting the epoch to 1245 and inserting something at 30
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/44)*

**Comment by iksaif** [comment]
Reviewed 1 of 3 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/44)*

**Comment by iksaif** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/44#-:-KM4xTAjs5Cb8gtTSptZ:1417088721)*

**Comment by natbraun** [comment]
Reviewed 1 of 3 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/44)*

**Comment by natbraun** [comment]
:lgtm: 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/44#-:-KM51yN-duEKeOkRPxTn:980077423)*

**Comment by natbraun** [comment]
Reviewed 1 of 3 files at r3, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/44)*

**Comment by natbraun** [comment]
Reviewed 1 of 3 files at r3, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/44)*

**Comment by natbraun** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/44#-:-KM58ddbHauoz_WWQBjQ:1417088721)*

**Comment by iksaif** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r3, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/44#-:-KM58wDaDC-YsP90PcRH:1417088721)*

**Pull request merged**
