### PR TITLE
Consider retention to check carbon_xfilesfactor

### PR DESCRIPTION
**Pull request by unbrice**
This fixes a bug when the most detailed retention policy is more precise than a second.

---
This change is [Reviewable](https://reviewable.io/reviews/criteo/biggraphite/8)

### CODE REVIEW

**Comment by unbrice** [comment]
+@natbraun 

<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> #### Consider retention to check carbon\_xfilesfactor
> 
> This fixes a bug when the most detailed retention policy is more precise than a second.
> 
> 
> 
</details>


---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/8#-:-KI3RPG5_b3fmBXnKaxQ:-2054479523)*

**Comment by natbraun** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[biggraphite/accessor.py, line 554 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/8#-KI80Qze-nXNwrVQZldf:-KI80Qze-nXNwrVQZldg:-1462714404) ([raw file](https://github.com/criteo/biggraphite/blob/c21b78e59cdbd7c3d10572f841f53e30a2bc10e1/biggraphite/accessor.py#L554)):*
> ```Python
>         def add_current_points_to_res():
>             if current_timestamp_ms is None:
>                 return
> ```

Please add a comment here to explain the `return` statement

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/8)*

**Comment by natbraun** [comment]
Reviewed 2 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/8)*

**Comment by unbrice** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[biggraphite/accessor.py, line 554 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/8#-KI80Qze-nXNwrVQZldf:-KI89-UTx78omRtq_UJx:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/c21b78e59cdbd7c3d10572f841f53e30a2bc10e1/biggraphite/accessor.py#L554)):*
<details><summary><i>Previously, natbraun (Nathaniel Braun) wrote…</i></summary>
> Please add a comment here to explain the `return` statement
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/8)*

**Comment by natbraun** [comment]
:lgtm:

<details><summary><i>Previously, coveralls wrote…</i></summary>
> 
> [Coverage Status](https://coveralls.io/builds/6232791)
> 
> Coverage decreased (-9.1%) to 63.391% when pulling **f1a74058d0dcb7aad63a1b19792f620ff12a91be on unbrice:aggreg** into **b34c3aa6565eca192be112d7d396bebf29978deb on criteo:master**.
> 
</details>


---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/8#-:-KI89ym076_aWLqv7yv7:1417088721)*

**Comment by natbraun** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/8)*

**Pull request merged**
