### PR TITLE
Make tests easier to run

### PR DESCRIPTION
**Pull request by iksaif**
This change is [Reviewable](https://reviewable.io/reviews/criteo/biggraphite/22)

### CODE REVIEW

**Comment by iksaif** [comment]
@unbrice 

<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> #### Make tests easier to run
</details>


---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/22#-:-KIwBzLXoNcG35p-6LxY:740747057)*

**Comment by unbrice** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[README.md, line 23 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/22#-KJ-hVE0zLUeEwQ67j10:-KJ-hVE15dc8LEb2Vh8S:-1272910845) ([raw file](https://github.com/criteo/biggraphite/blob/b62ecaf17470423ceda8416de6eb13312f081159/README.md#L23)):*
> ```Markdown
> Or `nose2`
> 
>     pip install nose2
> ```

If we are to use a framework, did you consider py.test? It has [all the hype](
http://mathieu.agopian.info/presentations/2015_06_djangocon_europe/) and according to a quick Google search is what one should be using these days.

With py.test we could then do [as such](https://pytest.org/latest/goodpractices.html#integrating-with-setuptools-python-setup-py-test-pytest-runner) so that the full instructions read ```python setup.py test``` (no pip install required if you fix the typo in test**s**_require=) and we can switch frameworks at will.

---

*[biggraphite/test_utils.py, line 38 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/22#-KJ-lCuFawcYOiy13a9o:-KJ-lCuFawcYOiy13a9p:1209950674) ([raw file](https://github.com/criteo/biggraphite/blob/b62ecaf17470423ceda8416de6eb13312f081159/biggraphite/test_utils.py#L38)):*
> ```Python
> 
> 
> HAS_CASSANDRA_HOME = os.getenv("CASSANDRA_HOME")
> ```

Nit: if it this is called HAS_ it should be a boolean.

---

*[biggraphite/test_utils.py, line 41 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/22#-KJ-lH3dJ0kpo21zHd5J:-KJ-l0VX-Sige6CFj1Hi:1236410026) ([raw file](https://github.com/criteo/biggraphite/blob/b62ecaf17470423ceda8416de6eb13312f081159/biggraphite/test_utils.py#L41)):*
> ```Python
> 
> if HAS_CASSANDRA_HOME:
>     from testing import cassandra as testing_cassandra
> ```

Since this is in deps, it will be installed, so why not import it unconditionally?

---

*[biggraphite/test_utils.py, line 71 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/22#-KJ-lTQCahJ2S0WMB3t8:-KJ-lTQCahJ2S0WMB3t9:1302673542) ([raw file](https://github.com/criteo/biggraphite/blob/b62ecaf17470423ceda8416de6eb13312f081159/biggraphite/test_utils.py#L71)):*
> ```Python
>             for package_path in sys.path:
>                 if package_path.endswith("site-packages"):
>                     for path in list(to_add):
> ```

no need for list()

---

*[biggraphite/test_utils.py, line 72 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/22#-KJ-m9ne_MH2OqACU4dR:-KJ-m9ne_MH2OqACU4dS:-2138514114) ([raw file](https://github.com/criteo/biggraphite/blob/b62ecaf17470423ceda8416de6eb13312f081159/biggraphite/test_utils.py#L72)):*
> ```Python
>                 if package_path.endswith("site-packages"):
>                     for path in list(to_add):
>                         venv_path = package_path + path
> ```

My understanding is that when this line is interpreted the venv is package_path.
I did some research and it seems that actually a better way to find the currently active venv (what the loop was trying to do before) is:
```python
venv_root = None
if hasattr(sys, "real_prefix") and sys.prefix != sys.real_prefix:
  venv_root = sys.prefix
```
Or maybe I just didn't understand what this aims at achieving.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/22)*

**Comment by unbrice** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[biggraphite/test_utils.py, line 74 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/22#-KJ-nRNw7ps7J7LOt1Zc:-KJ-nRNxjFvuE_F0zEl1:1762960846) ([raw file](https://github.com/criteo/biggraphite/blob/b62ecaf17470423ceda8416de6eb13312f081159/biggraphite/test_utils.py#L74)):*
> ```Python
>                         venv_path = package_path + path
>                         if os.path.isdir(venv_path):
>                             # Replace the path in the list.
> ```

This comment is not most helpful. I think it should be "Remove system-wide install from sys.path", if I got it right. But then I don't see why you do that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/22)*

**Comment by iksaif** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[README.md, line 23 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/22#-KJ-hVE0zLUeEwQ67j10:-KJ-t5QDNFfXhCU6HRaU:-1930235552) ([raw file](https://github.com/criteo/biggraphite/blob/b62ecaf17470423ceda8416de6eb13312f081159/README.md#L23)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> If we are to use a framework, did you consider py.test? It has [all the hype](
> http://mathieu.agopian.info/presentations/2015_06_djangocon_europe/) and according to a quick Google search is what one should be using these days.
> 
> With py.test we could then do [as such](https://pytest.org/latest/goodpractices.html#integrating-with-setuptools-python-setup-py-test-pytest-runner) so that the full instructions read ```python setup.py test``` (no pip install required if you fix the typo in test**s**_require=) and we can switch frameworks at will.
</details>
It wasn't really about using nose2 as a framework but more as a test runner.  I'll just leave the instructions for tox.

---

*[biggraphite/test_utils.py, line 71 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/22#-KJ-lTQCahJ2S0WMB3t8:-KJ-tNdUIi4jky_daI6E:1732898479) ([raw file](https://github.com/criteo/biggraphite/blob/b62ecaf17470423ceda8416de6eb13312f081159/biggraphite/test_utils.py#L71)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> no need for list()
</details>
Even when changing it inside the loop ?

---

*[biggraphite/test_utils.py, line 72 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/22#-KJ-m9ne_MH2OqACU4dR:-KJ-tahT8Y-gFRevz1KT:1672070323) ([raw file](https://github.com/criteo/biggraphite/blob/b62ecaf17470423ceda8416de6eb13312f081159/biggraphite/test_utils.py#L72)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> My understanding is that when this line is interpreted the venv is package_path.
> I did some research and it seems that actually a better way to find the currently active venv (what the loop was trying to do before) is:
> ```python
> venv_root = None
> if hasattr(sys, "real_prefix") and sys.prefix != sys.real_prefix:
>   venv_root = sys.prefix
> ```
> Or maybe I just didn't understand what this aims at achieving.
</details>
I just changed the existing code to handle /opt/graphite/webapp/ on top of /opt/graphite/lib. I assumed that the previous code worked.

---

*[biggraphite/test_utils.py, line 74 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/22#-KJ-nRNw7ps7J7LOt1Zc:-KJ-x4Pp5gwDjFyZgJHO:558877946) ([raw file](https://github.com/criteo/biggraphite/blob/b62ecaf17470423ceda8416de6eb13312f081159/biggraphite/test_utils.py#L74)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> This comment is not most helpful. I think it should be "Remove system-wide install from sys.path", if I got it right. But then I don't see why you do that.
</details>
It's doing exactly the same thing it used to do (except that to_add is a list and not a single variable)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/22)*

**Comment by unbrice** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[README.md, line 23 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/22#-KJ-hVE0zLUeEwQ67j10:-KJ1urcAOvqWW6haEoJK:-682275779) ([raw file](https://github.com/criteo/biggraphite/blob/b62ecaf17470423ceda8416de6eb13312f081159/README.md#L23)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> It wasn't really about using nose2 as a framework but more as a test runner.  I'll just leave the instructions for tox.
</details>
Sounds good to me.

---

*[biggraphite/test_utils.py, line 71 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/22#-KJ-lTQCahJ2S0WMB3t8:-KJ1v22vnyIvZ7yXpRbp:1428688807) ([raw file](https://github.com/criteo/biggraphite/blob/b62ecaf17470423ceda8416de6eb13312f081159/biggraphite/test_utils.py#L71)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> Even when changing it inside the loop ?
</details>
Oh, right... Now I think I understand the code. What you're doing with to_add is way too clever for my little brain though. I  suggest you split it in three steps: 1/ find the venv root 2/ fix to_add, adding venv_root if it contains them 3/ change sys.path and three comments describing each of the three steps.

---

*[biggraphite/test_utils.py, line 72 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/22#-KJ-m9ne_MH2OqACU4dR:-KJ1yOHRq3REfFFW92UQ:-341549254) ([raw file](https://github.com/criteo/biggraphite/blob/b62ecaf17470423ceda8416de6eb13312f081159/biggraphite/test_utils.py#L72)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> I just changed the existing code to handle /opt/graphite/webapp/ on top of /opt/graphite/lib. I assumed that the previous code worked.
</details>
It did work but venv_path is not the path to the venv, rather the path to a "to_add" element. I think using the snippet I suggested would work better as the phase 1 I described above.

---

*[biggraphite/test_utils.py, line 74 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/22#-KJ-nRNw7ps7J7LOt1Zc:-KJ1zcGBXR10b6Ji4JQZ:-1034592509) ([raw file](https://github.com/criteo/biggraphite/blob/b62ecaf17470423ceda8416de6eb13312f081159/biggraphite/test_utils.py#L74)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> It's doing exactly the same thing it used to do (except that to_add is a list and not a single variable)
</details>
I understand now. Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/22)*

**Comment by iksaif** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[biggraphite/test_utils.py, line 41 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/22#-KJ-lH3dJ0kpo21zHd5J:-KJ4w5W5h7bdf5vCe0u8:-710303188) ([raw file](https://github.com/criteo/biggraphite/blob/b62ecaf17470423ceda8416de6eb13312f081159/biggraphite/test_utils.py#L41)):*
> ince this is in deps, it will be installed, so why not import it unconditionally?

Basically because the failure case is different if we want cassandra or if we don't really care (exception in one case, silent in the other)

---

*[biggraphite/test_utils.py, line 71 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/22#-KJ-lTQCahJ2S0WMB3t8:-KJ4x5iy-q4GyMtJ5pmR:-472951203) ([raw file](https://github.com/criteo/biggraphite/blob/b62ecaf17470423ceda8416de6eb13312f081159/biggraphite/test_utils.py#L71)):*
> ink I understand the code. What you're doing with to_add is way too clever for my little brain though. I suggest you split it in three steps: 1/ find the venv root 2/ fix to_add, adding venv_root if it contains them 3/ change sys.path and three comments describing each of the three steps.

That's not what the current code is doing, the current code iterates on anything in sys.path and look for something that contains 'site-packages'. I don't really want to change that since I'm not sure why it was written this way in the first place.

Again, I don't want to change the logic of all this, I just want to add another path. If we want to change the actual logic we can do it in a separate change.

---

*[biggraphite/test_utils.py, line 72 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/22#-KJ-m9ne_MH2OqACU4dR:-KJ4wi3W4qG8FMYC2ab2:689721402) ([raw file](https://github.com/criteo/biggraphite/blob/b62ecaf17470423ceda8416de6eb13312f081159/biggraphite/test_utils.py#L72)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> It did work but venv_path is not the path to the venv, rather the path to a "to_add" element. I think using the snippet I suggested would work better as the phase 1 I described above.
</details>
renamed venv_path to venv_module_path. This used to be 'graphite_path' (while it was really carbon_path)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/22)*

**Comment by unbrice** [comment]
:lgtm:

<details><summary><i>Previously, coveralls wrote…</i></summary>
> 
> [Coverage Status](https://coveralls.io/builds/6396487)
> 
> Coverage remained the same at 93.308% when pulling **55120c377849e7440cc028138c13d4e49cf83ed0 on iksaif:master** into **4b4b353584edf9b3f50369874fdff8eb665d5f00 on criteo:master**.
> 
</details>


---

Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[README.md, line 23 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/22#-KJ-hVE0zLUeEwQ67j10:-KJ54Fq341_y96J2H5C5:676834233) ([raw file](https://github.com/criteo/biggraphite/blob/b62ecaf17470423ceda8416de6eb13312f081159/README.md#L23)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> Sounds good to me.
</details>
LGTM

---

*[biggraphite/test_utils.py, line 38 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/22#-KJ-lCuFawcYOiy13a9o:-KJ54LHjFCj8TOE4Blvv:676834233) ([raw file](https://github.com/criteo/biggraphite/blob/b62ecaf17470423ceda8416de6eb13312f081159/biggraphite/test_utils.py#L38)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> Nit: if it this is called HAS_ it should be a boolean.
</details>
LGTM

---

*[biggraphite/test_utils.py, line 41 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/22#-KJ-lH3dJ0kpo21zHd5J:-KJ54PqutBfK0ju-ebdM:5173665) ([raw file](https://github.com/criteo/biggraphite/blob/b62ecaf17470423ceda8416de6eb13312f081159/biggraphite/test_utils.py#L41)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> > ince this is in deps, it will be installed, so why not import it unconditionally?
> 
> Basically because the failure case is different if we want cassandra or if we don't really care (exception in one case, silent in the other)
</details>
OK

---

*[biggraphite/test_utils.py, line 71 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/22#-KJ-lTQCahJ2S0WMB3t8:-KJ54U2QAQcUs8fSPZO0:5173665) ([raw file](https://github.com/criteo/biggraphite/blob/b62ecaf17470423ceda8416de6eb13312f081159/biggraphite/test_utils.py#L71)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> > ink I understand the code. What you're doing with to_add is way too clever for my little brain though. I suggest you split it in three steps: 1/ find the venv root 2/ fix to_add, adding venv_root if it contains them 3/ change sys.path and three comments describing each of the three steps.
> 
> That's not what the current code is doing, the current code iterates on anything in sys.path and look for something that contains 'site-packages'. I don't really want to change that since I'm not sure why it was written this way in the first place.
> 
> Again, I don't want to change the logic of all this, I just want to add another path. If we want to change the actual logic we can do it in a separate change.
</details>
OK

---

*[biggraphite/test_utils.py, line 72 \[r1\]](https://reviewable.io:443/reviews/criteo/biggraphite/22#-KJ-m9ne_MH2OqACU4dR:-KJ54WTj1Eknb6Hrd2OA:5173665) ([raw file](https://github.com/criteo/biggraphite/blob/b62ecaf17470423ceda8416de6eb13312f081159/biggraphite/test_utils.py#L72)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> renamed venv_path to venv_module_path. This used to be 'graphite_path' (while it was really carbon_path)
</details>
OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/22#-:-KJ54Y5aOcy0mYyLrBj2:1417088721)*

**Pull request merged**
