### PR TITLE
Add statistics on used metrics (#107)

### LINKED ISSUE #107: Add statistics on used metrics
It would be nice to have a 'stats' table that could for example record the 'last_access_time' for a metric. This could have a probability of 10% of being updated and would give us an idea of rarely used metrics.

### PR DESCRIPTION
**Pull request by InformatiQ**
resolves #107 

This change is [Reviewable](https://reviewable.io/reviews/criteo/biggraphite/243)

### CODE REVIEW

**Comment by iksaif** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[CHANGELOG.md, line 33 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/243#-KcS5mP887jqvu3MwzB0:-KcS5mP887jqvu3MwzB1:b-z0fp1w) ([raw file](https://github.com/criteo/biggraphite/blob/8e2f1d9dcb4b6cfedf562699fda29359aeb9a927/CHANGELOG.md#L33)):*
> ```Markdown
> ## [Unreleased]
> ### Added
> - new column (read_on) in metric_metadata for adding statistics on read metrics (#107)
> ```

Please moved "unreleased" above [0.7.0]
Please add instructions to change the existing schema here.

---

*[biggraphite/drivers/cassandra.py, line 100 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/243#-KcS6-yWSpubqbvaayBE:-KcS6-yWSpubqbvaayBF:bgtc27i) ([raw file](https://github.com/criteo/biggraphite/blob/8e2f1d9dcb4b6cfedf562699fda29359aeb9a927/biggraphite/drivers/cassandra.py#L100)):*
> ```Python
> }
> 
> COUNTER = 0
> ```

Can you make that a member of the Cassandra accassor and name it self._read_on_counter
Also add  self._read_on_sampling_rate (a float between 0 and 1)

---

*[biggraphite/drivers/cassandra.py, line 257 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/243#-KcS6IFXluREUznm_rKr:-KcS6IFXluREUznm_rKs:bipv617) ([raw file](https://github.com/criteo/biggraphite/blob/8e2f1d9dcb4b6cfedf562699fda29359aeb9a927/biggraphite/drivers/cassandra.py#L257)):*
> ```Python
>     "  name text,"
>     "  updated_on  timeuuid,"
>     "  read_on  timeuuid,"
> ```

maybe add a counter named read_count here ? ( https://docs.datastax.com/en/cql/3.1/cql/cql_using/use_counter_t.html )

---

*[biggraphite/drivers/cassandra.py, line 1122 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/243#-KcS6RLpekcBN-OOwjKf:-KcS6RLpekcBN-OOwjKg:bkmq5zi) ([raw file](https://github.com/criteo/biggraphite/blob/8e2f1d9dcb4b6cfedf562699fda29359aeb9a927/biggraphite/drivers/cassandra.py#L1122)):*
> ```Python
>             self.__select_metric_metadata_statement, (encoded_metric_name, )))
>         if not result:
>             return None
> ```

move this part in a specific sub-function

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/243)*

**Comment by InformatiQ** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[biggraphite/drivers/cassandra.py, line 100 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/243#-KcS6-yWSpubqbvaayBE:-KcSESqwTk27ARGV2HLJ:b43onl9) ([raw file](https://github.com/criteo/biggraphite/blob/8e2f1d9dcb4b6cfedf562699fda29359aeb9a927/biggraphite/drivers/cassandra.py#L100)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary><blockquote>

Can you make that a member of the Cassandra accassor and name it self._read_on_counter
Also add  self._read_on_sampling_rate (a float between 0 and 1)
</blockquote></details>

not sure what the samplingr_rate is for

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/243)*

**Comment by iksaif** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[biggraphite/drivers/cassandra.py, line 100 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/243#-KcS6-yWSpubqbvaayBE:-KcSITDvufxBvneG7SJx:b48x4i1) ([raw file](https://github.com/criteo/biggraphite/blob/8e2f1d9dcb4b6cfedf562699fda29359aeb9a927/biggraphite/drivers/cassandra.py#L100)):*
<details><summary><i>Previously, InformatiQ (Ramez Hanna) wrote…</i></summary><blockquote>

not sure what the samplingr_rate is for
</blockquote></details>

it's to control the "one out of ten".

0.1 would be 1/10th of the requests, etc..

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/243)*

**Comment by InformatiQ** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[CHANGELOG.md, line 33 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/243#-KcS5mP887jqvu3MwzB0:-KcSIX-XAQLWfv1xTmbu:b-896fix) ([raw file](https://github.com/criteo/biggraphite/blob/8e2f1d9dcb4b6cfedf562699fda29359aeb9a927/CHANGELOG.md#L33)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary><blockquote>

Please moved "unreleased" above [0.7.0]
Please add instructions to change the existing schema here.
</blockquote></details>

Done.

---

*[biggraphite/drivers/cassandra.py, line 1122 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/243#-KcS6RLpekcBN-OOwjKf:-KcSIdaurNgYibAvK-Zf:b-896fix) ([raw file](https://github.com/criteo/biggraphite/blob/8e2f1d9dcb4b6cfedf562699fda29359aeb9a927/biggraphite/drivers/cassandra.py#L1122)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary><blockquote>

move this part in a specific sub-function
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/243)*

**Comment by InformatiQ** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[biggraphite/drivers/cassandra.py, line 100 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/243#-KcS6-yWSpubqbvaayBE:-KcTIfJ7JpR5A0En9k6s:b-896fix) ([raw file](https://github.com/criteo/biggraphite/blob/8e2f1d9dcb4b6cfedf562699fda29359aeb9a927/biggraphite/drivers/cassandra.py#L100)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary><blockquote>

it's to control the "one out of ten".

0.1 would be 1/10th of the requests, etc..
</blockquote></details>

Done.

---

*[biggraphite/drivers/cassandra.py, line 257 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/243#-KcS6IFXluREUznm_rKr:-KcSa5POKxQrQm0vdBq-:b-lt4yl6) ([raw file](https://github.com/criteo/biggraphite/blob/8e2f1d9dcb4b6cfedf562699fda29359aeb9a927/biggraphite/drivers/cassandra.py#L257)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary><blockquote>

maybe add a counter named read_count here ? ( https://docs.datastax.com/en/cql/3.1/cql/cql_using/use_counter_t.html )
</blockquote></details>

I would need a new table for that, as we cannot mix counter and non-counter columns. is it 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/243)*

**Comment by iksaif** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[biggraphite/drivers/cassandra.py, line 100 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/243#-KcS6-yWSpubqbvaayBE:-KcTTA-qXZ9xI4903__5:b7dy8lz) ([raw file](https://github.com/criteo/biggraphite/blob/8e2f1d9dcb4b6cfedf562699fda29359aeb9a927/biggraphite/drivers/cassandra.py#L100)):*
<details><summary><i>Previously, InformatiQ (Ramez Hanna) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Can you still move COUNTER to the cassandra driver ? (self._read_on_counter)

---

*[biggraphite/drivers/cassandra.py, line 257 at r1](https://reviewable.io:443/reviews/criteo/biggraphite/243#-KcS6IFXluREUznm_rKr:-KcTTDxLDEp3dAPKB1iH:b-838wfs) ([raw file](https://github.com/criteo/biggraphite/blob/8e2f1d9dcb4b6cfedf562699fda29359aeb9a927/biggraphite/drivers/cassandra.py#L257)):*
<details><summary><i>Previously, InformatiQ (Ramez Hanna) wrote…</i></summary><blockquote>

I would need a new table for that, as we cannot mix counter and non-counter columns. is it 
</blockquote></details>

Ok !

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/243)*

**Comment by iksaif** [comment]
(also rebase and make sure the tests are passing)

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/243#-:-KcTTKms4oeMFejJmJxR:ba6jt6i)*

**Comment by iksaif** [comment]
:lgtm_strong: 

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/243#-:-KcUAoY7fO21MPYYGWAE:b-uwkowd)*

**Pull request merged**
