### PR TITLE
Add Graphite utility class

### PR DESCRIPTION
**Pull request by natbraun**
Add several Graphite utility free functions:
  * is_graphite_glob
  * graphite_to_cassandra_glob
  * filter_metrics
  * get_graphite_metrics

---
This change is [Reviewable](https://reviewable.io/reviews/criteo/biggraphite/3)

### CODE REVIEW

**Comment by iksaif** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[biggraphite/graphite_utils.py, line 8 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/3#-KGvxJXGLuO9YGPuHGWZ:-KGvxJXHSPaJzCgdyYBH:166875720) ([raw file](https://github.com/criteo/biggraphite/blob/286ce157aad0d88bd2463123599167e7f32ecdbe/biggraphite/graphite_utils.py#L8)):*
please don't mix " and ' in your file, let's go with ' only :)

---

*[biggraphite/graphite_utils.py, line 12 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/3#-KGvxWs7LMULjczPkzls:-KGvxWs7LMULjczPkzlt:-1441500332) ([raw file](https://github.com/criteo/biggraphite/blob/286ce157aad0d88bd2463123599167e7f32ecdbe/biggraphite/graphite_utils.py#L12)):*
a metric /component/  is  (since you split the metric)

---

*[biggraphite/graphite_utils.py, line 29 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/3#-KGvxrMuCK4PJmcnIF2m:-KGvxrMuCK4PJmcnIF2n:417929741) ([raw file](https://github.com/criteo/biggraphite/blob/286ce157aad0d88bd2463123599167e7f32ecdbe/biggraphite/graphite_utils.py#L29)):*
This seems mostly copy pasted from the graphite code, can you add a link to the original file ?

---

*[biggraphite/graphite_utils.py, line 46 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/3#-KGw-cJ06cjTt2Y8cxhG:-KGw-cJ06cjTt2Y8cxhH:-125223836) ([raw file](https://github.com/criteo/biggraphite/blob/286ce157aad0d88bd2463123599167e7f32ecdbe/biggraphite/graphite_utils.py#L46)):*
It's unclear to me how this will be used in the Finder plugin.
Remember that Graphite works this way:
- metrics/?query=criteo.* -> criteo.a, criteo.b, criteo.c
- metrics/?query=criteo.*.* -> criteo.*.foo, criteo.*.bar}    (yep ! even if criteo.a.foo and criteo.b.foo you only get criteo.*.foo)
- metrics/?query=criteo.{storage,foo}.* -> criteo.{storage,foo}.probes

See http://xf.iksaif.net/graphite/bigraphite/finder.py

While this function seems to return anything that matches a full path. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/3)*

**Comment by unbrice** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[biggraphite/graphite_utils.py, line 8 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/3#-KGvzObfMHVk2YG51mCC:-KGvzObfMHVk2YG51mCD:2099083239) ([raw file](https://github.com/criteo/biggraphite/blob/286ce157aad0d88bd2463123599167e7f32ecdbe/biggraphite/graphite_utils.py#L8)):*
I think all functions but the last one should be module private

---

*[biggraphite/graphite_utils.py, line 8 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/3#-KGvxJXGLuO9YGPuHGWZ:-KGw3-6_wLst0HxfEh-N:-280880197) ([raw file](https://github.com/criteo/biggraphite/blob/286ce157aad0d88bd2463123599167e7f32ecdbe/biggraphite/graphite_utils.py#L8)):*
Actually the rest of the code uses " only but I agree on consistency

---

*[biggraphite/graphite_utils.py, line 16 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/3#-KGvzvYms3Qx_QxVEXC6:-KGvzRr8RuQvqGX8E82c:176717936) ([raw file](https://github.com/criteo/biggraphite/blob/286ce157aad0d88bd2463123599167e7f32ecdbe/biggraphite/graphite_utils.py#L16)):*
On terminolgies: accessor.py calls a list of either an exact name without dot or a "*" components, each of the element being a component. So I suggest _graphite_glob_to_acessor_componenents

---

*[biggraphite/graphite_utils.py, line 21 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/3#-KGw-IkbFROXp1fEB38Z:-KGvzT8YS463SZAOAld7:-1335274694) ([raw file](https://github.com/criteo/biggraphite/blob/286ce157aad0d88bd2463123599167e7f32ecdbe/biggraphite/graphite_utils.py#L21)):*
_filter_glob?

---

*[biggraphite/graphite_utils.py, line 25 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/3#-KGw-W8wA1_Fo5oy7JTe:-KGw-W8xtno2fiHf6Ivy:239278291) ([raw file](https://github.com/criteo/biggraphite/blob/286ce157aad0d88bd2463123599167e7f32ecdbe/biggraphite/graphite_utils.py#L25)):*
list of strings, the metrics to match to filter

---

*[biggraphite/graphite_utils.py, line 26 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/3#-KGw-MYRj-TVHZL4I0zq:-KGw-MYRj-TVHZL4I0zr:-1753368251) ([raw file](https://github.com/criteo/biggraphite/blob/286ce157aad0d88bd2463123599167e7f32ecdbe/biggraphite/graphite_utils.py#L26)):*
glob: pattern used to filter, the ones of fnmatch except they allow for one pair of braces

---

*[biggraphite/graphite_utils.py, line 31 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/3#-KGw-iez93TCFgwIMDaI:-KGw-iez93TCFgwIMDaJ:-627574184) ([raw file](https://github.com/criteo/biggraphite/blob/286ce157aad0d88bd2463123599167e7f32ecdbe/biggraphite/graphite_utils.py#L31)):*
brace_close?

---

*[biggraphite/graphite_utils.py, line 46 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/3#-KGw0CIw0g2MivaxF0ty:-KGw0CIw0g2MivaxF0tz:-816597538) ([raw file](https://github.com/criteo/biggraphite/blob/286ce157aad0d88bd2463123599167e7f32ecdbe/biggraphite/graphite_utils.py#L46)):*
glob_metrics?

---

*[biggraphite/graphite_utils.py, line 46 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/3#-KGw-cJ06cjTt2Y8cxhG:-KGw1T_gt0KD7wTUEuWK:393195647) ([raw file](https://github.com/criteo/biggraphite/blob/286ce157aad0d88bd2463123599167e7f32ecdbe/biggraphite/graphite_utils.py#L46)):*
indeed it seems that this doesn't match yet the behavior of the finder

---

*[biggraphite/graphite_utils.py, line 48 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/3#-KGw0N2q2tcc4ciNyAqI:-KGw0N2q2tcc4ciNyAqJ:-1052346647) ([raw file](https://github.com/criteo/biggraphite/blob/286ce157aad0d88bd2463123599167e7f32ecdbe/biggraphite/graphite_utils.py#L48)):*
accessor_components

---

*[tests/test_graphite_utils.py, line 23 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/3#-KGw2LIUO6HZitDE7YCr:-KGw2LIUO6HZitDE7YCs:-1034484441) ([raw file](https://github.com/criteo/biggraphite/blob/286ce157aad0d88bd2463123599167e7f32ecdbe/tests/test_graphite_utils.py#L23)):*
I suggest renaming this TestImplementationDetails and having a TestWithAccessor(test_utils.TestCaseWithAccessor) that performs actual queries, also including the examples Corentin proposed above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/3)*

**Comment by natbraun** [comment]
Review status: 0 of 3 files reviewed at latest revision, 13 unresolved discussions.

---

*[biggraphite/graphite_utils.py, line 8 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/3#-KGvxJXGLuO9YGPuHGWZ:-KGw6qXGyR9qq3XFE0Hl:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/286ce157aad0d88bd2463123599167e7f32ecdbe/biggraphite/graphite_utils.py#L8)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> Actually the rest of the code uses " only but I agree on consistency</details>
Done.

---

*[biggraphite/graphite_utils.py, line 8 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/3#-KGvzObfMHVk2YG51mCC:-KGw84heZYZUSlYV6TNd:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/286ce157aad0d88bd2463123599167e7f32ecdbe/biggraphite/graphite_utils.py#L8)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> I think all functions but the last one should be module private</details>
Done.

---

*[biggraphite/graphite_utils.py, line 12 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/3#-KGvxWs7LMULjczPkzls:-KGw8UM2RxX8SuLcOBXB:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/286ce157aad0d88bd2463123599167e7f32ecdbe/biggraphite/graphite_utils.py#L12)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> a metric /component/  is  (since you split the metric)</details>
Done.

---

*[biggraphite/graphite_utils.py, line 16 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/3#-KGvzvYms3Qx_QxVEXC6:-KGw8mj6555rzg2z6z_j:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/286ce157aad0d88bd2463123599167e7f32ecdbe/biggraphite/graphite_utils.py#L16)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> On terminolgies: accessor.py calls a list of either an exact name without dot or a "*" components, each of the element being a component. So I suggest _graphite_glob_to_acessor_componenents</details>
Done.

---

*[biggraphite/graphite_utils.py, line 21 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/3#-KGw-IkbFROXp1fEB38Z:-KHJkOd_xaYtOZdK5jS9:827754902) ([raw file](https://github.com/criteo/biggraphite/blob/286ce157aad0d88bd2463123599167e7f32ecdbe/biggraphite/graphite_utils.py#L21)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> _filter_glob?</details>
I kept `filter_metrics` because this function really filters full metrics

---

*[biggraphite/graphite_utils.py, line 25 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/3#-KGw-W8wA1_Fo5oy7JTe:-KGwI1hlC3mrtxialLlo:1424561546) ([raw file](https://github.com/criteo/biggraphite/blob/286ce157aad0d88bd2463123599167e7f32ecdbe/biggraphite/graphite_utils.py#L25)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> list of strings, the metrics to match to filter</details>
I used: `entries: list of strings, the accessor elements to match to filter`

---

*[biggraphite/graphite_utils.py, line 26 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/3#-KGw-MYRj-TVHZL4I0zq:-KGwINpNUHLBXgpiB1kl:-1890234928) ([raw file](https://github.com/criteo/biggraphite/blob/286ce157aad0d88bd2463123599167e7f32ecdbe/biggraphite/graphite_utils.py#L26)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> glob: pattern used to filter, the ones of fnmatch except they allow for one pair of braces</details>
I used: `glob: pattern used to filter, like fnmatch with one pair of braces allowed`

---

*[biggraphite/graphite_utils.py, line 29 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/3#-KGvxrMuCK4PJmcnIF2m:-KGw6gbLPH5IpznzfO0i:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/286ce157aad0d88bd2463123599167e7f32ecdbe/biggraphite/graphite_utils.py#L29)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> This seems mostly copy pasted from the graphite code, can you add a link to the original file ?</details>
Done.

---

*[biggraphite/graphite_utils.py, line 31 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/3#-KGw-iez93TCFgwIMDaI:-KGwITKkkl-nw3T8eaa4:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/286ce157aad0d88bd2463123599167e7f32ecdbe/biggraphite/graphite_utils.py#L31)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> brace_close?</details>
Done.

---

*[biggraphite/graphite_utils.py, line 46 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/3#-KGw-cJ06cjTt2Y8cxhG:-KHJlL5lBeTvSBJc6G-o:-701206845) ([raw file](https://github.com/criteo/biggraphite/blob/286ce157aad0d88bd2463123599167e7f32ecdbe/biggraphite/graphite_utils.py#L46)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> indeed it seems that this doesn't match yet the behavior of the finder</details>
This is fixed using the `format_metrics` function

---

*[biggraphite/graphite_utils.py, line 46 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/3#-KGw0CIw0g2MivaxF0ty:-KHJlR_DCPGn6Z5PmuJL:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/286ce157aad0d88bd2463123599167e7f32ecdbe/biggraphite/graphite_utils.py#L46)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> glob_metrics?</details>
Done.

---

*[biggraphite/graphite_utils.py, line 48 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/3#-KGw0N2q2tcc4ciNyAqI:-KHJlUCST2uCUOH-EvP8:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/286ce157aad0d88bd2463123599167e7f32ecdbe/biggraphite/graphite_utils.py#L48)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> accessor_components</details>
Done.

---

*[tests/test_graphite_utils.py, line 23 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/3#-KGw2LIUO6HZitDE7YCr:-KHJt6hpmWiP-8MyiOOy:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/286ce157aad0d88bd2463123599167e7f32ecdbe/tests/test_graphite_utils.py#L23)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> I suggest renaming this TestImplementationDetails and having a TestWithAccessor(test_utils.TestCaseWithAccessor) that performs actual queries, also including the examples Corentin proposed above</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/3)*

**Comment by iksaif** [comment]
Review status: 0 of 3 files reviewed at latest revision, 14 unresolved discussions.

---

*[biggraphite/graphite_utils.py, line 31 \[r4\]](https://reviewable.io:443/reviews/criteo/biggraphite/3#-KHKISQFDlpGfW5-dDyg:-KHKISQG7hcxjDYaqzH7:-1584205772) ([raw file](https://github.com/criteo/biggraphite/blob/ec9a1a73cea84480c874a1a528a7b650e5217b69/biggraphite/graphite_utils.py#L31)):*
> ```Python
>       Formatted metric.
>     """
>     prefix = glob[:glob.rfind(".")+1]
> ```

dirname()

---

*[biggraphite/graphite_utils.py, line 32 \[r4\]](https://reviewable.io:443/reviews/criteo/biggraphite/3#-KHKIU0UUJOfPIRw0BB9:-KHKIU0UUJOfPIRw0BBA:-1486339678) ([raw file](https://github.com/criteo/biggraphite/blob/ec9a1a73cea84480c874a1a528a7b650e5217b69/biggraphite/graphite_utils.py#L32)):*
> ```Python
>     """
>     prefix = glob[:glob.rfind(".")+1]
>     return prefix + metric[metric.rfind(".")+1:]
> ```

basename()

---

*[biggraphite/graphite_utils.py, line 54 \[r4\]](https://reviewable.io:443/reviews/criteo/biggraphite/3#-KHKIZXKuqcbxMadVubB:-KHKIZXLnOdpL7dR4vfC:743767313) ([raw file](https://github.com/criteo/biggraphite/blob/ec9a1a73cea84480c874a1a528a7b650e5217b69/biggraphite/graphite_utils.py#L54)):*
> ```Python
> 
>     for variant in variants:
>         for match in fnmatch.filter(metrics, variant):
> ```

call dirname() once on glob :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/3)*

**Comment by natbraun** [comment]
Review status: 0 of 3 files reviewed at latest revision, 14 unresolved discussions.

---

*[biggraphite/graphite_utils.py, line 31 \[r4\]](https://reviewable.io:443/reviews/criteo/biggraphite/3#-KHKISQFDlpGfW5-dDyg:-KHKPu4EimqqNJ0667SH:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/ec9a1a73cea84480c874a1a528a7b650e5217b69/biggraphite/graphite_utils.py#L31)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> dirname()</details>
Done.

---

*[biggraphite/graphite_utils.py, line 32 \[r4\]](https://reviewable.io:443/reviews/criteo/biggraphite/3#-KHKIU0UUJOfPIRw0BB9:-KHKPtslLXWa9LYL88N2:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/ec9a1a73cea84480c874a1a528a7b650e5217b69/biggraphite/graphite_utils.py#L32)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> basename()</details>
Done.

---

*[biggraphite/graphite_utils.py, line 54 \[r4\]](https://reviewable.io:443/reviews/criteo/biggraphite/3#-KHKIZXKuqcbxMadVubB:-KHKPvTvrsSKj4BP0vso:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/ec9a1a73cea84480c874a1a528a7b650e5217b69/biggraphite/graphite_utils.py#L54)):*
<details><summary><i>Previously, iksaif (Corentin Chary) wrote…</i></summary>
> call dirname() once on glob :)</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/3)*

**Comment by unbrice** [comment]
Review status: 0 of 3 files reviewed at latest revision, 10 unresolved discussions.

---

*[biggraphite/graphite_utils.py, line 8 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/3#-KGvzObfMHVk2YG51mCC:-KHQdwU0gOxjGxCGYx0m:550568433) ([raw file](https://github.com/criteo/biggraphite/blob/286ce157aad0d88bd2463123599167e7f32ecdbe/biggraphite/graphite_utils.py#L8)):*
<details><summary><i>Previously, natbraun (Nathaniel Braun) wrote…</i></summary>
> Done.</details>
Can you make the constant private as well?

---

*[biggraphite/graphite_utils.py, line 31 \[r5\]](https://reviewable.io:443/reviews/criteo/biggraphite/3#-KHQeVJ1mARoBBQeVrUW:-KHQeVJ1mARoBBQeVrUX:472118219) ([raw file](https://github.com/criteo/biggraphite/blob/34548f25fd0f35b02d8bc5a7edac5fb26fcde79e/biggraphite/graphite_utils.py#L31)):*
> ```Python
> 
> 
> def _format_metric(metric, dirname):
> ```

Is this is done by the callee in the end?

---

*[tests/test_graphite_utils.py, line 23 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/3#-KGw2LIUO6HZitDE7YCr:-KHQeJxVgs3_uI5vI9Wc:-1108748448) ([raw file](https://github.com/criteo/biggraphite/blob/286ce157aad0d88bd2463123599167e7f32ecdbe/tests/test_graphite_utils.py#L23)):*
<details><summary><i>Previously, natbraun (Nathaniel Braun) wrote…</i></summary>
> Done.</details>
Can you put both classes in one file?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/3)*

**Comment by unbrice** [comment]
Reviewed 1 of 4 files at r3, 1 of 2 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[tests/test_graphite_utils_internals.py, line 20 \[r5\]](https://reviewable.io:443/reviews/criteo/biggraphite/3#-KHQedFHCjgigKDIYPTh:-KHQedFHCjgigKDIYPTi:-780145481) ([raw file](https://github.com/criteo/biggraphite/blob/34548f25fd0f35b02d8bc5a7edac5fb26fcde79e/tests/test_graphite_utils_internals.py#L20)):*
> ```Python
> import unittest
> 
> from biggraphite import graphite_utils as gu
> ```

It's gu  here and bg_gu in the other file.

---

*[tests/test_graphite_utils_with_accessor.py, line 33 \[r5\]](https://reviewable.io:443/reviews/criteo/biggraphite/3#-KHQf383tBjSEp7FtKRN:-KHQf383tBjSEp7FtKRO:-1427244997) ([raw file](https://github.com/criteo/biggraphite/blob/34548f25fd0f35b02d8bc5a7edac5fb26fcde79e/tests/test_graphite_utils_with_accessor.py#L33)):*
> ```Python
>         self.assertEqual(["a"], bg_gu.glob_metrics(self.accessor, "*"))
>         self.assertEqual(["*.*.c"], bg_gu.glob_metrics(self.accessor, "*.*.c"))
>         self.assertEqual(["a.*.a", "a.*.c", "a.*.d"], bg_gu.glob_metrics(self.accessor, "a.*.*"))
> ```

Rather than test that accessor work, I thik this test should the weirdness of Graphite globs
something like having a.b1.c, a.b2.c, x.y.z and trying *.b{1,2}.* and *.*.c

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/3)*

**Comment by natbraun** [comment]
Review status: 0 of 2 files reviewed at latest revision, 9 unresolved discussions.

---

*[biggraphite/graphite_utils.py, line 8 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/3#-KGvzObfMHVk2YG51mCC:-KI2b3wskKY3C4eAo57M:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/286ce157aad0d88bd2463123599167e7f32ecdbe/biggraphite/graphite_utils.py#L8)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> Can you make the constant private as well?
</details>
Done.

---

*[biggraphite/graphite_utils.py, line 31 \[r5\]](https://reviewable.io:443/reviews/criteo/biggraphite/3#-KHQeVJ1mARoBBQeVrUW:-KI2aEBT6R39RnhI2RVH:-801531568) ([raw file](https://github.com/criteo/biggraphite/blob/34548f25fd0f35b02d8bc5a7edac5fb26fcde79e/biggraphite/graphite_utils.py#L31)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> Is this is done by the callee in the end?
</details>
No, so I just removed it.

---

*[tests/test_graphite_utils.py, line 23 \[r2\]](https://reviewable.io:443/reviews/criteo/biggraphite/3#-KGw2LIUO6HZitDE7YCr:-KI2ao8aS8IT6ihVMHLf:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/286ce157aad0d88bd2463123599167e7f32ecdbe/tests/test_graphite_utils.py#L23)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> Can you put both classes in one file?
</details>
Done.

---

*[tests/test_graphite_utils_internals.py, line 20 \[r5\]](https://reviewable.io:443/reviews/criteo/biggraphite/3#-KHQedFHCjgigKDIYPTh:-KI2aRQcZWR-mDkTSzuP:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/34548f25fd0f35b02d8bc5a7edac5fb26fcde79e/tests/test_graphite_utils_internals.py#L20)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> It's gu  here and bg_gu in the other file.
</details>
Done.

---

*[tests/test_graphite_utils_with_accessor.py, line 33 \[r5\]](https://reviewable.io:443/reviews/criteo/biggraphite/3#-KHQf383tBjSEp7FtKRN:-KI2al2liUzOPoMphaOr:-499146009) ([raw file](https://github.com/criteo/biggraphite/blob/34548f25fd0f35b02d8bc5a7edac5fb26fcde79e/tests/test_graphite_utils_with_accessor.py#L33)):*
<details><summary><i>Previously, unbrice (Brice Arnould) wrote…</i></summary>
> Rather than test that accessor work, I thik this test should the weirdness of Graphite globs
> something like having a.b1.c, a.b2.c, x.y.z and trying *.b{1,2}.* and *.*.c
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/3)*

**Comment by iksaif** [comment]
Reviewed 1 of 1 files at r8.
Review status: 1 of 2 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/3)*

**Comment by iksaif** [comment]
:lgtm:

<details><summary><i>Previously, coveralls wrote…</i></summary>
> 
> [Coverage Status](https://coveralls.io/builds/6229657)
> 
> Coverage increased (+1.5%) to 72.523% when pulling **ab445cfeb7bb8f41427d2d8cab6be0e4c907c5ae on natbraun:master** into **58e2eeed651391d2322338eb3c3b89360dadf20f on criteo:master**.
> 
</details>


---

Review status: 1 of 2 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/biggraphite/3#-:-KI2ti1auiswveYILgF2:1417088721)*

**Pull request merged**
